### ISSUE TITLE
How to send mail to matched username from rule

### ISSUE THREAD

**Issue by tatdatpham** [Yelp/elastalert#1005]
Hi, 
I have rule (type change) to detect user login from new IP. Now i want send mail to that user. How can ?
for example : 
```
filter:
- query:
    query_string:
      query: "type: ssh"
#- term:
#    type: "ssh"
# (Required)
# The alert is use when a match is found
alert_text: |
    New login from {0} for user {1} at {2}
alert_text_args:
  - src_ip
  - username
  - timestamp
alert_text_type: alert_text_only
```
I want to send mail to {username}

Thanks!
