### ISSUE TITLE
What is best rule type in my case?

### ISSUE THREAD

**Issue by tatdatpham** [Yelp/elastalert#1009]
My case : 
I have log collect infomation (username, IP, location, device) ..
I want check when user login from new IP -> Alert ; when user login from new device -> Alert; time period is 3 days. (like warning login in facebook).
My question:
- What rule should I use?
- If i use rule CHANGE. i check data in field change only. If field has new value -> alert ( field {IP} has new IP -> alert. But if i hava two IP - in this case, alert is not good) . But rule CHANGE can be run maximum 10k query only. How can increase ? "use_count_query" dont work in rule CHANGE.

Thanks!
P/s: My EL is not good !

**Comment by Qmando** [comment]
http://elastalert.readthedocs.io/en/latest/ruletypes.html#new-term

```
type: new_term
fields:
 - [username, IP]
 - [username, device]
terms_window_size:
  days: 3
```

This is almost exactly what you want. This will alert on a new combination of (username, ip/device). When elastalert starts, it will look for everything from the last 3 days and consider those "known" values. Once a combination causes an alert, it will not alert again, until elastalert restarts.

Alternative, if you really want 3 day realerting.

```
type: any
query_key: [username, IP, device]
realert:
  days: 3
```

This will alert on everything first, but then will wait for 3 days before alerting on that (username, ip, device) combination again.

**Comment by Qmando** [comment]
Also, the maximum 10k query_hit_size only apply to a single query (Sorry documentation is not clear about this!). Elastalert will make additional queries to get all documents. You should see
"Queried rule ...: 10,000 / 10,000 hits"
"Queried rule ...: 20,000 / 10,000 hits (scrolling)"
"Queried rule ...: 30,000 / 10,000 hits (scrolling)"

**Comment by tatdatpham** [comment]
Thank for suggestion.
Here is my config

```
index: fb-mail*

# (Required, new_term specific)
# Monitor the field ip_address
fields:
 - [user, client_ip]
 - [user, device]

# (Optional, new_term specific)
# This means that we will query 90 days worth of data when ElastAlert starts to find which values of ip_address already exist
# If they existed in the last 90 days, no alerts will be triggered for them when they appear
terms_window_size:
  days: 1

# (Required)
# A list of Elasticsearch filters used for find events
# These filters are joined with AND and nested in a filtered query
# For more info: http://www.elasticsearch.org/guide/en/elasticsearch/reference/current/query-dsl.html
# We are filtering for only "login_event" type documents with username "admin"
filter:
- term:
    _type: "iis-access"
- and:
    - term:
        user: "test"
```
And when i run with this rule, i got warning. Is it problem?

`WARNING:elastalert:No results were found from all sub-aggregations.  This can either indicate that there is no baseline data OR that a non-primitive field was used in a composite key.`
