### ISSUE TITLE
Difference between kibana timezone and elastalert timezone

### ISSUE THREAD

**Issue by RupeshRanjan409** [Yelp/elastalert#1011]
Will my elastalerts trigger alerts for below config, if i have a timezone difference of 5 hours between my kibana UI and my server where i am hosting elastalert?

```
buffer_time:
 hours: 2

timeframe:
  minutes: 15
```
