### ISSUE TITLE
How to call elasticsearch API from elastalert?

### ISSUE THREAD

**Issue by bhaskarv82** [Yelp/elastalert#1033]
This may not be right place to ask this question. But I could not find articles to do so.
I have below packages installed on CentOS.
Elasticsearch
ISO8601 or Unix timestamped data
Python 2.6 or 2.7
pip, see requirements.txt

But, how do I make a call to an elastic search cluster using an API. I have API and a service account to do so.
Here is what, I am looking for.
Which file under elastalert-master/example_rules, should I modify?

I have tried changing config.yaml.example as well but that keeps calling auth py files and errors out.
I know that I don't have to auth anything as I have the API and service account.
I just have to use elastakert as a cron to do so.

Please suggest.

**Comment by bhaskarv82** [comment]
Only problem is that I don't have to install elastic search. I just have to call an API which lets me talk to ELK cluster and run the query for me.
I need the number of files to be updated.

**Comment by prayagupd** [comment]
@bhaskarv82 are you saying you could not connect to elasticsearch from elastalert? 

First thing, after successfully installing elastlaert, add or modify a yaml config which will have elasticsearch config (`es_host` and `es_port`), (lets call it `my-alerts.yaml`)

```yaml
# This is the folder that contains the rule yaml files
# Any .yaml file will be loaded as a rule
rules_folder: /etc/alert_rules/

# ElastAlert will buffer results from the most recent
# period of time, in case some log sources are not in real time
buffer_time:
  minutes: 1

# The Elasticsearch hostname for metadata writeback
# Note that every rule can have its own Elasticsearch host
es_host: 172.21.3.9

# The Elasticsearch port
es_port: 9200

# The AWS region to use. Set this when using AWS-managed elasticsearch
#aws_region: us-west-1

# The AWS profile to use. Use this if you are using an aws-cli profile.
# See http://docs.aws.amazon.com/cli/latest/userguide/cli-chap-getting-started.html
# for details
#profile: test

# Optional URL prefix for Elasticsearch
#es_url_prefix: elasticsearch

# Connect with TLS to Elasticsearch
#use_ssl: True

# Verify TLS certificates
#verify_certs: True

# GET request with body is the default option for Elasticsearch.
# If it fails for some reason, you can pass 'GET', 'POST' or 'source'.
# See http://elasticsearch-py.readthedocs.io/en/master/connection.html?highlight=send_get_body_as#transport
# for details
#es_send_get_body_as: GET

# Option basic-auth username and password for Elasticsearch
#es_username: someusername
#es_password: somepassword

# The index on es_host which is used for metadata storage
# This can be a unmapped index, but it is recommended that you run
# elastalert-create-index to set a mapping
writeback_index: elastalert_status
# writeback_index: alerting_metadata

# If an alert fails for some reason, ElastAlert will retry
# sending the alert until this time period has elapsed
alert_time_limit:
  days: 1
```

Then add a rule whereever you want (example, `/etc/alert_rules`), which knows what `index` of your elasticsearch cluster to `query`.

```yaml
#es_host: localhost
#es_port: 9200
name: My application error alert
type: frequency
index: myapplication-*
num_events: 1
#timeframe:
#    hours: 4
filter:
- query:
   query_string:
      query: "\"ERROR\""
alert:
- "email"
email:
- "prayagupd@prayagupd.com"
```

Then, run elastalert

```bash
/usr/bin/python -m elastalert.elastalert --verbose --config /usr/local/elastalert/my-alerts.yaml
```
