### ISSUE TITLE
[query] query malformed, no start_object after query name

### ISSUE THREAD

**Issue by Puneeth-n** [Yelp/elastalert#1045]
**ES Version**
```
ES 5.1 AWS
```

**Rule**
```
index: logstash-*

name: some_errors

type: any

filter:
    - query:
        - query_string:
            query: "_exists_:$event.supplier"

alert:
    - "email"

email:
    - "foo.bar@baz.com"
```

**Generated ES query**
```
curl -H 'Content-Type: application/json' -XGET 'http://localhost:9200/logstash-*/_search?pretty&_source_include=%40timestamp%2C%2A&ignore_unavailable=true&scroll=30s&size=10000' -d '{
  "query": {
    "bool": {
      "filter": {
        "bool": {
          "must": [
            {
              "range": {
                "@timestamp": {
                  "gt": "2017-04-21T16:07:00.656634Z",
                  "lte": "2017-04-21T16:22:00.656634Z"
                }
              }
            },
            {
              "query": [
                {
                  "query_string": {
                    "query": "_exists_:$event.supplier"
                  }
                }
              ]
            }
          ]
        }
      }
    }
  },
  "sort": [
    {
      "@timestamp": {
        "order": "asc"
      }
    }
  ]
}'
```
