### ISSUE TITLE
Are Max and Min Percentage switched?

### ISSUE THREAD

**Issue by oridayne** [Yelp/elastalert#1098]
Are you sure max_percentage is "If the percentage of matching documents is less than this number, an alert will be triggered."

I have a logs getting GET responses from a website, and there are nothing but 200 response codes.
I set a percentage rule just to test it, and it looks like this:

```
name: Testing Rule Alerting
type: percentage_match

es_host: localhost
es_port: 9200

index: keepalive-*
description: "95% of mongo audit codes per request path should be successful"

# how far it is willing to look back in time for logs
# calculation window
buffer_time:
  hours: 1

# divide our calculation window into 1 hour segments,
# and evaluate percentages by hour
#bucket_interval:
#  minutes: 10

realert:
  hours: 12

# per request path
# use keyword so that the search is optimized
#query_key: doc.requestPath.keyword
doc_type: website_healthcheck


filter:
- term:
   _type: website_healthcheck


match_bucket_filter:
- terms:
    http_poller_metadata.code: [200]

# if percent of documents with bad response codes is greater than 5%, alert
max_percentage: 5

... alerts...other things....

```

I ran the elastalert test rule, and it actually printed "Percent Violation, value: 100 (min:0 max: 5)
Is Max and min percentage switched?
