### ISSUE TITLE
Having one specific field from all the events in the alert_text

### ISSUE THREAD

**Issue by HainanHU** [Yelp/elastalert#1119]
Hi!

I need some help regarding alert_text. Here is my alert configuration:
```
name: Alert
type: frequency
index: logstash-*
num_events: 10
timeframe:
    minutes: 30
query_key: user_id
attach_related: true

filter:
- term:
    tags: "some_term"
alert:
- "email"
- "slack"
email:
- "foo@gmail.com"
slack:
slack_webhook_url:
- "xxxxxxxxx"

alert_text_type: alert_text_only
alert_text: "User {0} perform suspicious command: {1}."
alert_text_args:
  - user_id
  - cmd
```
What I am trying to do, is to list the cmd field from all 10 events in the alert_text so that I can get a summary of all the event. The origin json event is too long that with too many information that are not needed. May I get some suggestions of how to do that?
Many thanks for your help!
