### ISSUE TITLE
Flatline - Alert when nothing is in ES

### ISSUE THREAD

**Issue by windowsansiblernew** [Yelp/elastalert#1137]
I have the below rule for alerting me whenever there is nothing present in ES, but its not doing anything, am i missing something? doc_type is same as _type in ES?
```
name: Count

type: flatline

index: logs*

threshold: 10


timeframe:
  minutes: 30
doc_type: 'logs'

realert:
  minutes: 5

use_count_query: true

filter:
- query:
   query_string:
    query: "data: user1"


alert:
 - email

```
