### ISSUE TITLE
starttime/endtime confusion

### ISSUE THREAD

**Issue by xmackex** [Yelp/elastalert#1161]
Hello, we have ```percentage_match``` rule with next alert text
```
alert_text: "\n
    num_matches: {2}\n
    percentage: {0}\n
    max_percentage: {1}\n
    When: {3} - {4}\n
    "

alert_text_args:
    - percentage
    - max_percentage
    - num_matches
    - starttime
    - endtime
```

Unfortunately in result message I get
```
 num_matches: 1
 percentage: 1.6
 max_percentage: 0.0001
 When: 2017-06-12 12:30:00.295596+00:00 - <MISSING VALUE>
```
But in log I see
```
Ran sys percentage from 2017-06-12 12:27 UTC to 2017-06-12 12:30 UTC: 625 query hits (0 already seen), 1 matches, 2 alerts sent
```

Can you please help me to figure out is it my misconfiguration or some bug?
Note, in message I get endtime in starttime element
