### ISSUE TITLE
finds Hits and Matches but never alerts

### ISSUE THREAD

**Issue by Dmitry1987** [Yelp/elastalert#1175]
I have a weird issue despite setting realert: minutes: 0, the percentage_match rule never triggers alert.

```
INFO:elastalert:Ran Test, find when DEBUG level messages higher than 5% from 2017-06-19 15:00 UTC to 2017-06-20 08:57 UTC: 2349348514 query hits (0 already seen), 31 matches, 0 alerts sent.
```

I tried many combinations, and I know that the data I query should alert.
The rule goes approximately like this:

```
type: percentage_match
realert:
  minutes: 0
description: "Test, find when DEBUG level messages higher than 5%"
buffer_time:
  hours: 6
bucket_interval:
  hours: 3

include: ["environment", "environment_type", "service"]

query_key: environment
min_percentage: 5
doc_type: message

# The wildcard makes sure we don't mix in messages without 'environment' field, like Care Config on ECS
filter:
- term:
    environment_type: "production"

match_bucket_filter:
- term:
    environment_type: "production"
- term:
    level: "DEBUG"
```

the 'realert' should make it send an alert on any match? (the match is when item count in "match_bucket_filter" passed threshold of min/max_percentage from the count in main filter, right?)

**Comment by Qmando** [comment]
Was there anything in the logs after that line? Did it say ``Ignoring match...``?
What is your alerter? Do you have any enhancements? Aggregation set?

**Comment by Dmitry1987** [comment]
Hi @Qmando , sometimes it says "ignoring match for silenced rule" too.  and I deleted the index and used realert: 0, but it seem doesn't affect.   
Now I added few "print" lines there in percentage match rule function to print the values it's working with, and got this:
```
match_bucket_count: 0
other_bucket_count: 2308
query_key: env1
match_bucket_count: 0
other_bucket_count: 7
query_key: env2
match_bucket_count: 622
other_bucket_count: 1053
37.1343283582  match_percentage > max
query_key: env2
match_bucket_count: 624
other_bucket_count: 1058
37.0986920333  match_percentage > max
query_key: env2
match_bucket_count: 2
other_bucket_count: 3
40.0  match_percentage > max
...  etc'   hundreds lines (its a loop through all my environments and it's ok, the query_key in action :) )

INFO:elastalert:Ignoring match for silenced rule Percentage ERROR more than 5%.env1
INFO:elastalert:Ignoring match for silenced rule Percentage ERROR more than 5%.env2
....   for each env name it showed the silenced message
```

but i also had runs with matches like i posted earlier and no 'silenced' info messages after the run.  but in those cases also was "0 alerts".

**Comment by Qmando** [comment]
That may be because you had old silence stashes. Try changing the name of the rule slightly.

**Comment by Dmitry1987** [comment]
this run with the values shown above, as last line showed this
```
INFO:elastalert:Ran Percentage ERROR more than 5% from 2017-06-20 16:00 UTC to 2017-06-20 18:53 UTC: 2324348238 query hits (0 already seen), 59 matches, 0 alerts sent
```

and the rule full version is:
```
import: shared_settings.conf

timestamp_field: timestamp
timestamp_type: custom
timestamp_format: "%Y-%m-%d %H:%M:%S.%f"
generate_kibana_link: false

allow_buffer_time_overlap: true
name: Percentage ERROR more than 5%
type: percentage_match

realert:
  minutes: 1

description: "5% Errors"

buffer_time:
  hours: 1

bucket_interval:
  minutes: 30

include: ["environment", "environment_type", "service"]

query_key: environment

max_percentage: 5

doc_type: message

filter:
- term:
   environment_type: "production"
- term:
   service: "something"

match_bucket_filter:
- term:
    environment_type: "production"
- term:
    service: "something"
- term:
    level: "DEBUG"

```

and in the "shared_config" i have the mails, api keys etc'  like:
```
match_enhancements:
- "alert_enhancement_kibana.KibanaLinkAppender"
realert:
  minutes: 30
alert:
- "victorops"
...
```
The realert added in 'rule'  itself will override the one from included shared configs file right? (it does work with some settings, not sure if realert did)  anyway i tried to set '0' in both files to be sure it's not a silenced timeframe issue.
