### ISSUE TITLE
Elasticsearch version 5.4.1 problem with Elastcsearch-curator 5.1

### ISSUE THREAD

**Issue by yami12376** [Yelp/elastalert#1183]
Hello,

in `/opt/elasticsearch-curator`
i made two files 

curator_action.yml

```

# Remeber, leave a key empty if there is no value.  None will be a string,
# not a Python "NoneType"
#
# Also remember that all examples have 'disable_action' set to True.  If you
# want to use this action as a template, be sure to set this to False after
# copying it.
actions:
  1:
    action: delete_indices
    description: >-
      Delete indices older than 5 days (based on index name), for custom-
      prefixed indices. Ignore the error if the filter does not result in an
      actionable list of indices (ignore_empty_list) and exit cleanly.
    options:
      ignore_empty_list: True
      continue_if_exception: False
      disable_action: False
    filters:
    - filtertype: age
      source: name
      direction: older
      timestring: '%Y.%m.%d'
      unit: days
      unit_count: 1
```

curator_config.yml

```
# Rember, leave a key empty if there is no value.  None will be a string,
# not a Python "NoneType"
client:
  hosts:
    - search1
  port: 9200
  timeout: 30

logging:
  loglevel: INFO

```

When running 

`curator --config /opt/elasticsearch-curator/curator_config.yml /opt/elasticsearch-curator/curator_action.yml
`

I get **error**

```
2017-06-23 14:35:42,568 INFO      Preparing Action ID: 1, "delete_indices"
Unable to create client connection to Elasticsearch.  Error: ConnectionError(<urllib3.connection.HTTPConnection object at 0x7fc7ab891518>: Failed to establish a new connection: [Errno -2] Name or service not known) caused by: NewConnectionError(<urllib3.connection.HTTPConnection object at 0x7fc7ab891518>: Failed to establish a new connection: [Errno -2] Name or service not known)

```

My ElasticSearch is not  running on localhost:9200 but on 10.2.0.164:9200

It is running i can check it by `service elasticsearch  status`

```
elasticsearch.service - Elasticsearch
   Loaded: loaded (/usr/lib/systemd/system/elasticsearch.service; enabled)
   Active: active (running) since czw 2017-06-22 10:45:26 CEST; 1 day 3h ago
     Docs: http://www.elastic.co
 Main PID: 23680 (java)

```

```
curl -XGET '10.2.0.164:9200'
{
  "name" : "xbD5hPX",
  "cluster_name" : "elasticsearch",
  "cluster_uuid" : "th6x6w7sQAyjULThAaIv1Q",
  "version" : {
    "number" : "5.4.1",
    "build_hash" : "2cfe0df",
    "build_date" : "2017-05-29T16:05:51.443Z",
    "build_snapshot" : false,
    "lucene_version" : "6.5.1"
  },
  "tagline" : "You Know, for Search"
}

```

It could be that this part is wrong: 
```
client:
  hosts:
    - search1
```

i'm not sure what to post here
