### ISSUE TITLE
Multiple queries comparison in one rule

### ISSUE THREAD

**Issue by contactcuong** [Yelp/elastalert#1186]
Hi, is it possible to include more than 1 query and doing comparison <count> between queries within a rule and trigger alerts correspondingly.
My expectation looks like as following, thanks for your help.

```
es_host: xxx.xxx.xxx.xxx
es_port: 9200
name: Count_FAILURE
type: spike
index: logstash*%Y.%m.%d*
threshold_cur: 100
timeframe:
  minutes: 15
spike_height: 3
spike_type: "up"
filter:
- query:
    query_string:
       query(A): "foo:bar AND \"request success\""
- query:
    query_string:
       query(B): "foo:bar AND \"response success\""
- query:
    query_string:
       query(C): "foo:bar AND \"response FAILURE\""

alert: 
- command:
    command: if (B) < 0.8* (A) ; then myscript --var <count_of_query(B)>
- command:
    command: if (C) < 0.8* (B) ; then myscript --var <count_of_query(C)>

**Comment by Qmando** [comment]
You can do percentage comparisons using http://elastalert.readthedocs.io/en/latest/ruletypes.html#percentage-match

You can also get more than one query into a single rule:
```
filter:
- query:
    query_string:
       query(A): "foo:bar AND (\"request success\" OR \"response success\" OR \"response FAILURE\")
```

**Comment by contactcuong** [comment]
thanks @Qmando, how can I use count_of_hit/count_of_query result as parameter input of myscript?

**Comment by Qmando** [comment]
Adding ``pipe_match_json: true`` will cause the match object as JSON to be piped to stdin of the command run.

**Comment by contactcuong** [comment]
hi @Qmando I tried with your suggestions `pipe_match_json: true` but it seems not work properly.
Assuming the following scenario for test: saying once alert triggered, it will create a filename `test_<count_of_hit>` (i.e. `test_132` or `test_167`...)

Here is my command
```
es_host: xxx.xxx.xxx.xxx
es_port: 9200
name: TEST
type: spike
index: logstash*2017.06.29*
threshold_cur: 20
timeframe:
  minutes: 5
spike_height: 1.5
spike_type: "up"
filter:
- query:
    query_string:
       query: "foo:bar AND \"request success\""
alert: 
- command:
    command: ["/bin/touch", "test_@"]
pipe_match_json: true
```
Thanks for your help again!
