### ISSUE TITLE
Elastalert sent multiple mail and don't aggregate

### ISSUE THREAD

**Issue by Alexwii** [Yelp/elastalert#1190]
Hello everyone !

I'm not sur it's a bug, but since a recent update of Elastalert aggregation seem doesn't work.

I receive multiple email and not on the same one.

My configuration :
```
#        DATABASE INFORMATION
es_host: '127.0.0.1'
es_port: 9200
index: 'logstash-*'

#        RULES

name: 'Flapping'

type: 'frequency'

num_events: 5

timeframe:
  hours: 1

query_key:
- source
- interface
- cisco_facility

#        AGGREGATION

aggregation:
  minutes: 30

aggregation_key:
- source
- interface
- cisco_facility

summary_table_fields:
- source
- interface
- message

#        FILTER

filter:
- query_string:
    query: 'Super Query of the death''


#        ALERT

alert: email
email:
- 'mail@mycompany.com'
smtp_host: 'smtp.mycompany.com'
from_addr: 'elastalert@mycompany.com'

```
I don't understand where is the problem ... ?

Thank you so much for your answer
