### ISSUE TITLE
Exclude for query

### ISSUE THREAD

**Issue by elbars** [Yelp/elastalert#1196]
Hello, tell me how to create a rule that would correspond to one parameter and exclude the other.
My rule:
``` 
name: Nginx error
type: frequency
index: logstash-*
timestamp_field: "@timestamp"

num_events: 1
timeframe:
  minutes: 1

filter:
- query_string:
    query: "\"[error]\" AND NOT \"LUA DEBUG\""
```
All the same arrive notices in which there is and [error] and LUA DEBUG.
Any idea? Thank you
