### ISSUE TITLE
Avoid num_hits being reset per each timeframe set

### ISSUE THREAD

**Issue by contactcuong** [Yelp/elastalert#1197]
The `num_hits` was being reset for each every `15 mins`, how can I prevent this.
Here is my rule.

```
es_host: xxx.xxx.xxx.xxx
es_port: 9200
name: TEST
type: frequency
index: logstash*2017.07.03*
num_events: 0
# use_count_query: true
# doc_type: mytest_request
timeframe:
  minutes: 15
filter:
- query:
    query_string:
       query: "(dc:dc01 || dc:dc02) && env:prod && host_type:\"company-app\" && \"API\" && \"successful to server\""
alert: 
- command:
    command: ["/usr/bin/myscript", "--host", "myhost", "--key", "mykey", "--value", "%(num_hits)s"]
realert:
  minutes: 1
pipe_match_json: true
```
Following is my data trend
<a href='https://postimg.org/image/jljs848w7/' target='_blank'><img src='https://s7.postimg.org/jljs848w7/image.png' border='0' alt='postimage'/></a>
