### ISSUE TITLE
Not generating alerts with query_key 

### ISSUE THREAD

**Issue by terrapina** [Yelp/elastalert#1198]
I'm new to elastalert and doing some testing before we make the system live. I have a very simple input into elastic that keeps track of the downloads from our fleet of media servers. All i want is to alert when a media serve has seen no downloads for 5 minutes. My json and rule are as follows;
```

{
  "_index": "test_mapping",
  "_type": "mytype",
  "_id": "AV0FWnOK5hCKCXZcg0o0",
  "_version": 1,
  "_score": null,
  "_source": {
    "uid": 1667,
    "@timestamp": "2017-07-02T22:10:00.194Z",
    "device": "SERVERMEDIA021",
    "downloads": 649,
    "@version": "1",
    "timestamp": 1499033382
  },
  "fields": {
    "@timestamp": [
      1499033400194
    ]
  },
  "sort": [
    1499033400194
  ]
}
```

```
es_host: localhost
es_port: 9200
name: Example rule
type: flatline
index: test_mapping-*
query_key: device
threshold: 1
timeframe:
 minutes: 10
alert:
- command
command: ["/bin/test"]
realert:
 hours:	5
```
I have 30+ servers that i monitor, with each server having a different id in the "device" field i thought i would have been able to just use query_key, and this would alert if any of the devices drop out for 5 minutes, but i'm not generating any alerts/matches/hits? The test data is populated correctly and should cause an alert. Have i misunderstood the documentation? I probably have... i'm confused about how to get this to alert. Any help is appreciated! Thank you.
