### ISSUE TITLE
Expect spike rule keeps alert

### ISSUE THREAD

**Issue by contactcuong** [Yelp/elastalert#1208]
I would expect the spike rule keeps alert from 10:30 till 10:45 through still (base on `realert`) , but alert only get trigger at 10:30 once despite of `realert` was being set, how can I achieve the goal?

Here is my rule:
```
es_host: xxx.xxx.xxx.xxx
es_port: 9200
name: HTTP_BAD_CODE_400
type: spike
index: logstash*%Y.%m.%d*
threshold_cur: 500
timeframe:
  minutes: 15
spike_height: 5
spike_type: "up"
filter:
- query:
    query_string:
       query: "(dc:dc01 || dc:dc02) && env:production && http_status:400"
alert: 
- command:
    command: ["/usr/bin/myscript", "--server", "xxx.xxx.xxx.xxx", "--port", "xxx", "--host", "xxx", "--key", "xxx", "--value", "xxx"]
realert:
  minutes: 3
```
Here is my data trend: ![Kibana](https://s4.postimg.org/78o586o4t/github.png)
[https://s4.postimg.org/78o586o4t/github.png](url)
