### ISSUE TITLE
Alert aggregation does not work

### ISSUE THREAD

**Issue by fabMrc** [Yelp/elastalert#1212]
Hi

I configured elastalert for aggregating messages in one alert inside a time window and it continues to raise each alert independantly

My configuration

rule :
```yaml
name: Raise Alert on java Exception
index: filebeat-*
use_local_time: true
timestamp_format: '%Y-%m-%dT%H:%M:%S.%f+02:00'
timestamp_type: custom
timestamp_format_expr: 'ts[:23] + ts[26:]'
type: any
aggregation:
  minutes: 3
filter:
- query:
    wildcard:
      message: "*exception*"
- terms:
    loglevel: ["ERROR", "WARN","FATAL"]
alert:
- "email"
email:
- "toto@foo.com"
```

global config
```yaml
# This is the folder that contains the rule yaml files
# Any .yaml file will be loaded as a rule
rules_folder: /opt/elastalert/rules

# How often ElastAlert will query Elasticsearch
# The unit can be anything from weeks to seconds
run_every:
  minutes: 3

# ElastAlert will buffer results from the most recent
# period of time, in case some log sources are not in real time
buffer_time:
  minutes: 3

# The Elasticsearch hostname for metadata writeback
# Note that every rule can have its own Elasticsearch host
es_host: es.foo.com

# The Elasticsearch port
es_port: 9200

# The index on es_host which is used for metadata storage
# This can be a unmapped index, but it is recommended that you run
# elastalert-create-index to set a mapping
writeback_index: elastalert_status

from_addr: elastalert@monitoring.almerys.com
smtp_host: smtp@foo.com
smtp_port: 25

# If an alert fails for some reason, ElastAlert will retry
# sending the alert until this time period has elapsed
alert_time_limit:
  days: 2
```

each alert is sended. I would like in each 3 minutes period aggregate all alert in one mail notification
