### ISSUE TITLE
Metric Aggregation - Help please

### ISSUE THREAD

**Issue by flippakitten** [Yelp/elastalert#1213]
I am trying to get the average delivery time for email within the last hour, below is the data from Kibana.

When I run the rule, there are no matches, even though it should pretty much always trigger the rule. Any help or guidance would be greatly appreciated.

``` 
 @timestamp                July 11th 2017, 19:29:52.033
t _id                               0_17268518853_0
t _index                         emails-2017.07.11
? _index_time                2017-07-11T17:29:52.053Z
? _queue_time               2017-07-11T17:29:52.033Z
t dsn_action                  relayed
t dsn_status                  2.0.0 (success)
t e_id                             delivery_times
 e_time                          July 11th 2017, 19:29:51.920
t recipient_domain       yahoo.com
# time_wait                   64
```

```
name: Average Times
type: metric_aggregation

es_host: eshost
es_port: 9200
use_ssl: True

use_strftime_index: true
index: emails-%Y.%m.%d

buffer_time:
  hours: 1

metric_agg_key: time_wait
metric_agg_type: avg
#query_key: recipient_domain
doc_type: metrics

max_threshold: 1

filter:
- query:
    query_string:
       query: "e_id: delivery_times AND dsn_action: relayed"

alert:
- "slack"
```

```
INFO:elastalert:Ran Average Times from 2017-07-11 21:04 SAST to 2017-07-11 21:12 SAST: 0 query hits (0 already seen), 0 matches, 0 alerts sent
INFO:elastalert:Sleeping for 41.514278 seconds
INFO:elastalert:Ran Average Times from 2017-07-11 21:04 SAST to 2017-07-11 21:13 SAST: 0 query hits (0 already seen), 0 matches, 0 alerts sent
INFO:elastalert:Sleeping for 45.599063 seconds
```

Thank you
