### ISSUE TITLE
Quick advice on percentage_match rule

### ISSUE THREAD

**Issue by contactcuong** [Yelp/elastalert#1222]
@Qmando I was trying to have an alert triggered on specific query, that said if `http/200 < 95% of http/all` it will be trigger, but it never happens.

Here following is my rule, I set `min_percentage: 99` for testing purpose:
```
es_host: xxx
es_port: 9200

name: EXAMPLE_PERCENTAGE_MATCH
type: percentage_match
index: logstash*2017.07.13*
description: "95% of all http requests should be successful"

filter:
- query:
    query_string:
       query: "(dc:dc01 || dc:dc02) && env:production && !(file:\"/app/logs/haproxy/haproxy.log\" || alive || nginx || status || api:bootstrap) && host_type:\"myapp-app\" && log_type:tomcat_access && http_uri:\"/myapp/api\""

buffer_time:
  minutes: 1

query_key: http_status
doc_type: EXAMPLE_PERCENTAGE_MATCH

match_bucket_filter:
- terms:
    http_status: [200]

min_percentage: 99

alert: 
- command:
    command: ["/usr/bin/myscript"]
realert:
  minutes: 3
```
My data trend: ![screenshot](https://s9.postimg.org/gy4bh8l8v/2017-07-13_130248.png)
