### ISSUE TITLE
New Term ruletype can't recognize old term after restart alert process

### ISSUE THREAD

**Issue by byakuinss** [Yelp/elastalert#1229]
I'm using metricbeat to collect system information of 57 machines. 
If there is any new server start to send message through metricbeat, elastalert should send notification to administrators. 

As far as I know, it should query documents in 7 days (`terms_window_size` setting), if there is any new term appear but not include in the past 7 days, it should send alert message. 

My rule config is working without any error messages, but it send 57 alert message when I restart the alert process or change the rule config everytime. 
Is that normal? Or how could I modify the rule config to avoid the false alert when restart the alert process? 
Any help or guidance would be greatly appreciated!

My rule config:
```
name: Alert New Server
index: metricbeat-*
type: new_term

fields:
  - "beat.hostname"

query_key: beat.hostname
terms_window_size:
  days: 7

realert:
  minutes: 0

filter:
- term:
    metricset.name: "cpu"
- term:
    type: "metricsets"

alert:
- "email"

email:
- "xxx.xxxx@xxx.com"
```
