### ISSUE TITLE
0 match with Flatline

### ISSUE THREAD

**Issue by F1sn1k** [Yelp/elastalert#1231]
I got hits but 0 matches.

The idea is to get an alert if `number of events is less than 5000 (threshold) in last 24 hours`

```
index: "logstash-*"

name: Client - Sending emails amount too low

type: flatline

# (Required)
# PagerDuty settings
pagerduty_client_name: PagerDuty # Pager duty client account name
pagerduty_service_key: pdkey # PagerDuty API Service key

filter:
- query:
    query_string:
      query: "app_name: Micro-Alert-Service AND NOT email_categories: now-tracking AND client_identifier: client"

threshold: 5000

timeframe:
  hours: 24

alert:
  - pagerduty

use_local_time: false
```
and the **config** file:

```rules_folder: example_rules

run_every:
  minutes: 1

buffer_time:
  minutes: 15


es_host: elasticsearch.xxx.com

# The Elasticsearch port
es_port: 9200

writeback_index: status-elastalert

alert_time_limit:
  days: 2
```

And the result is something like this 

> elastalert_status - {'hits': 2876, 'matches': 0 }
