### ISSUE TITLE
datetime parse error

### ISSUE THREAD

**Issue by hongjn** [Yelp/elastalert#1232]
rule:
```
es_host: eshost
es_port: esport
name: Example new term rule
type: new_term
index: myindex
timestamp_field: postDate
fields:
 - "name"
terms_window_size:
  days: 7
filter:
- term:
    _type: "mytype"
alert:
- "command"
command: ["/bin/echo find sth."]
```
postDate: datetype, its format: epoch_millis.
run in docker, build from [elastalert-docker](https://github.com/krizsan/elastalert-docker)

error msg:
```
File "/usr/lib/python2.7/site-packages/elasticsearch-2.4.1-py2.7.egg/elasticsearch/connection/base.py", line 114, in _raise_error
elastalert.util.EAException: Error initializing rule Example new term rule: Error searching for existing terms: RequestError(400, u'search_phase_execution_exception', {u'status': 400, u'error': {u'failed_shards': [{u'node': u'KbQ8A-QIQ2CoBuBQS1YtuQ', u'index': u'citic3', u'reason': {u'caused_by': {u'reason': u'Invalid format: "2017-07-11T12:35:42.225162Z"', u'type': u'illegal_argument_exception'}, u'reason': u'failed to parse date field [2017-07-11T12:35:42.225162Z] with format [epoch_millis]', u'type': u'parse_exception'}, u'shard': 0}], u'root_cause': [{u'reason': u'failed to parse date field [2017-07-11T12:35:42.225162Z] with format [epoch_millis]', u'type': u'parse_exception'}], u'grouped': True, u'reason': u'all shards failed', u'phase': u'query', u'type': u'search_phase_execution_exception'}})

```
