### ISSUE TITLE
HTTP POST Alerter: EAException('Error loading file %s: %s' % (rule_file, e))

### ISSUE THREAD

**Issue by byakuinss** [Yelp/elastalert#1246]
Hi, @Qmando @brianmpollack 
I'm try to send an alert message to Pushover through HTTP POST alerter.
I saw this new alerter for HTTP POST: https://github.com/Yelp/elastalert/pull/1207
So I also upgraded my elastalert from 0.1.16 to 0.1.18. 

My rule config is as below: (according to the [HTTP POST Alerter document](http://elastalert.readthedocs.io/en/stable/ruletypes.html#http-post))

disk_usage.yaml
```
name: test http post
type: any
index: metricbeat-*
doc_type: metricsets
filter:
  - term:
      beat.hostname: "my_host"
  - range:
      system.filesystem.used.pct:
        from: 0.75
        to: 1

alert: post
http_post_url: "https://api.pushover.net/1/messages.json"
#http_post_payload:
http_post_static_payload:
  token: "my_token"
  user: "my_user"
  device: "my_device"
  title: "Elastalert HTTP POST test"
  message: "Elastalert HTTP POST test"
```

The rule config has been tested by elastalert-test-rule, there is no any errors or exceptions.
But when I tried to start the elastalert process, I got an error:
```
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/bigdata/.local/lib/python2.7/site-packages/elastalert/elastalert.py", line 1734, in <module>
    sys.exit(main(sys.argv[1:]))
  File "/home/bigdata/.local/lib/python2.7/site-packages/elastalert/elastalert.py", line 1728, in main
    client = ElastAlerter(args)
  File "/home/bigdata/.local/lib/python2.7/site-packages/elastalert/elastalert.py", line 112, in __init__
    self.conf = load_rules(self.args)
  File "/home/bigdata/.local/lib/python2.7/site-packages/elastalert/config.py", line 453, in load_rules
    raise EAException('Error loading file %s: %s' % (rule_file, e))
elastalert.util.EAException: Error loading file test/disk_usage.yaml: Error initiating alert post: Could not import module post: need more than 1 value to unpack
```

I have no idea what the problem is, could anyone give me some advice? 
Or a HTTP POST alert rule config example? I would really appreciate your help.

**Comment by byakuinss** [comment]
Solved it. 
Wrote a simple Pushover alerter in elastalert_modules references from HTTP POST Alerter.

pushover_alerts.py
```
from elastalert.alerts import Alerter
import httplib
import urllib
from elastalert.util import EAException
from elastalert.util import elastalert_logger
from elastalert.util import lookup_es_key

class PushoverAlerter(Alerter):
    """ Requested elasticsearch indices are sent by HTTP POST to Pushover. Encoded with JSON. """

    def __init__(self, rule):
        super(PushoverAlerter, self).__init__(rule)
        self.post_payload = self.rule.get('pushover_payload', {})
        self.post_static_payload = self.rule.get('pushover_parameter', {})
        self.post_all_values = self.rule.get('pushover_all_values', not self.post_payload)

    def alert(self, matches):
        body = self.create_alert_body(matches)
        title = self.create_title(matches)

        """ Each match will trigger a POST to the specified endpoint(s). """
        for match in matches:
            payload = match if self.post_all_values else {}
            for post_key, es_key in self.post_payload.items():
                payload[post_key] = lookup_es_key(match, es_key)
            headers = {"Content-type": "application/x-www-form-urlencoded"}
            data = self.post_static_payload
            data['message'] = body
            data['title'] = title

            try:
                conn = httplib.HTTPSConnection("api.pushover.net:443")
                conn.request("POST", "/1/messages.json",
                             urllib.urlencode(data), headers)

            except httplib.HTTPException as e:
                raise EAException("Error posting Pushover alert: %s" % e)
            elastalert_logger.info("Pushover alert sent.")

    def get_info(self):
        return {'type': 'http_post'}
```


rule_config
```
name: test
type: any
index: metricbeat-*

filter:
  - term:
      beat.hostname: "testelk"
  - range:
      system.filesystem.used.pct:
        from: 0.1
        to: 1

alert: 
- "elastalert_modules.pushover_alerts.PushoverAlerter"
- "slack"

slack:
slack_webhook_url: "my_slack_url"

pushover_parameter:
  token: "my_token"
  user: "my_user"
  device: "my_device"

alert_subject: "[test] Host {0}:{1} is abnormal at {2} {3}%"
alert_subject_args:
- "beat.hostname"
- name
- "@timestamp"
- "system.filesystem.used.pct"

alert_text: "{0} {1}% {2}"
alert_text_type: alert_text_only
alert_text_args: ["beat.hostname", "system.filesystem.used.pct", "@timestamp"]
```
