### ISSUE TITLE
Flatline rule with dynamic threshold

### ISSUE THREAD

**Issue by DKlinec** [Yelp/elastalert#1254]
Hey everyone,

I would like to create a rule that would throw an error if the today's result count is less than 25% of the average count per day in the past two weeks.
For the lack of a better idea I tried creating a new ruletype that would accept a thresholdQuery value execute it and set the threshold according to it's results, but I struck out... I couldn't get it to work, mostly because I don't know how to execute the thresholdQuery.

From the new rule type (DynamicFlatline):

`def __init__(self, *args):
        super(DynamicFlatlineRule, self).__init__(*args)
        thresholdQuery = self.rules['thresholdQuery']

        self.check_for_match(thresholdQuery)
        self.threshold = (self.occurrences[thresholdQuery].count()) / 14 * 0.75
        
        # Dictionary mapping query keys to the first events
        self.first_event = {}`

The rule yaml:

```
filter:
- query:
    query_string:
      query: "app_name: MAS AND NOT email_categories: CAT1 AND client_identifier: CLN"

thresholdQuery: "app_name: MAS AND NOT email_categories: CAT1 AND client_identifier: CLN AND @timestamp:[now-14d/d TO now]"
threshold: 5000
```

And the error I got was:

`Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/Users/myUser/Projects/CustomElastalert/elastalert/elastalert/elastalert.py", line 1783, in <module>
    sys.exit(main(sys.argv[1:]))
  File "/Users/myUser/Projects/CustomElastalert/elastalert/elastalert/elastalert.py", line 1777, in main
    client = ElastAlerter(args)
  File "/Users/myUser/Projects/CustomElastalert/elastalert/elastalert/elastalert.py", line 123, in __init__
    self.conf = load_rules(self.args)
  File "elastalert/config.py", line 454, in load_rules
    raise EAException('Error loading file %s: %s' % (rule_file, e))
elastalert.util.EAException: Error loading file example_rules/my_rules.yaml: Error initializing rule `

Any ideas on why this is not working?

I realise this might not be the best way to tackle the problem, so if anyone has any other ideas, you are more than welcome to share.
