### ISSUE TITLE
Elastalert starts up and then sleeps 

### ISSUE THREAD

**Issue by zorro1992** [Yelp/elastalert#1256]
Hey I am new to elastalert. I have my error.yaml which when testes rules well and gives me the error list but when I run the command `elastalert --verbose --rule /root/elastalert/rules/error.yaml` I keep on getting the below output.

```
INFO:elastalert:Starting up
INFO:elastalert:Sleeping for 59.991074 seconds
INFO:elastalert:Sleeping for 59.985646 seconds
```
My error.yml file.
```
Could anyone please help me . 

# Alert when the rate of events exceeds a threshold
 
# (Required)
# Rule name, must be unique
name: ERROR Log
 
# (Required)
# Type of alert.
# the frequency rule type alerts when num_events events occur with timeframe time
# type: frequency
type: any
realert: 
  minutes: 0 
# (Required)
# Index to search, wildcard supported
index: logstash-*
#timestamp_field: "#timestamp" 
use_local_time: true
# use_strftime_index: true
 
# (Required, frequency specific)
# Alert when this many documents matching the query occur within a timeframe
num_events: 1
 
# (Required, frequency specific)
# num_events must occur within this amount of time to trigger an alert
timeframe:
    minutes: 15
 
# (Required)
# A list of Elasticsearch filters used for find events
# These filters are joined with AND and nested in a filtered query
# For more info: http://www.elasticsearch.org/guide/en/elasticsearch/reference/current/query-dsl.html
filter:
#- term:
     #message: "thrown"
- query:
    query_string:
        query: "thrown"

alert:
- "slack"
slack:
slack_webhook_url: "xxxxx"
#slack_channel_override: '#dsmonitoring'

#realert:
  #minutes: 0


```

Debug has only the below informations 
```

curl -H 'Content-Type: application/json' -XGET 'http://localhost:9200/elastalert_status/elastalert/_search?pretty&size=1000' -d '{
  "query": {
    "bool": {
      "filter": {
        "range": {
          "alert_time": {
            "from": "2017-07-30T19:24:57.768771Z",
            "to": "2017-08-01T19:24:57.768857Z"
          }
        }
      },
      "must": {
        "query_string": {
          "query": "!_exists_:aggregate_id AND alert_sent:false"
        }
      }
    }
  },
  "sort": {
    "alert_time": {
      "order": "asc"
    }
  }
}'
```

Not sure why this error is . Thanks in advance
