### ISSUE TITLE
Getting MISSING VALUE when using Metric Aggregation rule

### ISSUE THREAD

**Issue by mshkrebtan** [Yelp/elastalert#1260]
I want ElastAlert to send alerts when there is more than _X_% of disk space used on a node. Therefore I am interested in monitoring a specific field's value and I use a _Metric Aggregation_ rule. 

In the alert text I want to see what device is observed and where it is mounted on. Moreover, in the alert text I also want to see a link to the Elasticsearch document to be able to get more details on the issue.

In my rule of type _Metric Aggregation_ I want to put specific fields' values in the alert text. Yet all I get is multiple `<MISSING VALUE>` stubs.

Here is the rule itself:
```yaml
es_host: elasticsearch
es_port: 9200

name: Filesystem Metrics Warning
type: metric_aggregation
index: metrics-system-*

########################### Metric Aggregation Rule ############################
metric_agg_key: system.filesystem.used.pct
metric_agg_type: max
max_threshold: 25

doc_type: metrics-system
query_key:
  - k8_node
  - system.filesystem.free
  - system.filesystem.device_name
  - system.filesystem.mount_point

use_run_every_query_size: true

alert:
 - "debug"
 - "slack"

################################ Slack Alert Options ###########################
alert_subject: "[dev] [{0}] [> 25 of disk space is used]  - <http://kibana.dev/app/kibana#/doc/metrics-system-*/{1}/metrics-system?id={2}|More>"

alert_subject_args:
  - k8_node
  - _index                                                                                                                                                                                              
  - _id 

alert_text_type: alert_text_only

alert_text: "There are only {0} bytes free on device {1} mounted on {2}"

alert_text_args:
  - system.filesystem.free
  - system.filesystem.device_name
  - system.filesystem.mount_point

slack_webhook_url: https://hooks.slack.com/services/...
slack_username_override: ElastAlert

slack_msg_color: warning

############################### Realert Options ################################
realert:
  minutes: 1
```

And here is an example of alerts I get:

```
[dev] [192.168.1.19] [> 25 of disk space is used] - <http://kibana.dev/app/kibana#/doc/metrics-system-*/<MISSING VALUE>/metrics-system?id=<MISSING VALUE>|More>
There are only <MISSING VALUE> bytes free on device <MISSING VALUE> mounted on <MISSING VALUE>
```
How can put the actual fields's values in alert text? I assume it is due to the rule implementation. Please help!
