### ISSUE TITLE
num_hits vs num_matches

### ISSUE THREAD

**Issue by otisonoza** [Yelp/elastalert#1261]
Hi all,

I have `frequency` type rule with `terms` query.

```
use_terms_query: true
query_key: clientIP
```

```
filter:
- query:
    match:
        detail: "some text I match against"
```

In the alert I have these fields:
```
num_hits: 1
num_matches: 1
```

Sometimes with other numbers, but it's always the `num_hits` which is larger.

Could you please explain what `num_hits` and `num_matches` really mean?

Thank you,
Ádám
