### ISSUE TITLE
Alert for time range

### ISSUE THREAD

**Issue by kernelpanicfbsd** [Yelp/elastalert#1265]
Hello, I need to receive alerts only between a certain time range (not date) so if I want to only recieve alerts between 6 in the morning and 6 in the evening would it look something like this?

```
filter:
- range:
    @timestamp:
      from: 06.00.00
      to: 18.00.00
```
