### ISSUE TITLE
what rule should i take?

### ISSUE THREAD

**Issue by xiaoxinba** [Yelp/elastalert#1268]
my scenario:
  in some period:
     host 1：log count--count1;
     host 2 :  log count--count2;
     then count1/count2 <threshold then alert

Any leads would be much appreciate.

**Comment by Qmando** [comment]
You can do percentage based alerts  http://elastalert.readthedocs.io/en/latest/ruletypes.html?highlight=percentage#percentage-match

```
type: percentage_match
doc_type: something
filter:
 - terms:
      hostname:
       - host1
       - host2
match_bucket_filter:
 - term:
      hostname: host2
min_percentage: 50
```

this means "Alert when count(host2) is less than 50% of count(host1 + host2)"
