### ISSUE TITLE
Flatline alerts

### ISSUE THREAD

**Issue by SMAPPER** [Yelp/elastalert#1270]
I am having trouble with getting **Flatline** alerts to work. It seems like I can get it functioning properly using **use_count_query** but then the alerts simply return the number of matches. What I am trying to do is generate an alert any time a system has failed to send logs within a given period.

For example, if I have a Windows box that normally sends 1,000 events in an hour I want to know if it fails to send any events in an hour. I've got mock data in Elasticsearch were I start with events and then shut the log agent off for a few hours and then turn it back on to play with. However, I cannot get ElastAlert with Flatline to alert and notify which Hostname is failing to send logs.

My alert rule is as follows:

```python
name: No logs received

type: flatline

index: lab-bootcamp-day3-*

threshold: 1

timeframe:
  minutes: 30
query_key: "Hostname"
doc_type: 'windows'

realert:
  minutes: 0

use_terms_query: true

filter:
- query:
   query_string:
    query: "*"

alert_text: "Absensce of logs from {0} detected in 30 minutes"
alert_text_args: ["Hostname"]

alert:
- command
command: ["tee", "/tmp/alert_output.log"]
pipe_match_json: true
```

The **Hostname** field is a field in Elasticsearch that exists on every Windows log. Basically, I just want alerts to trigger when no logs are received from a given **Hostname** and for the alert to contain the **Hostname**. Even if this had to be the built-in **host** field that would be fine.

Ideas?

**Comment by SMAPPER** [comment]
By the way, if you can help me out I plan on building some ElastAlert video tutorials to release to the community. You have a solid alerting framework that is my go to for Elastic Stack implementations.

**Comment by Trustys** [comment]
Hello,

When you run your rule, have you a debug message like this ?:

`elastalert_1     | INFO:elastalert:Queried rule ## No logs received from 2017-08-16 12:00 CEST to 2017-08-16 12:01 CEST: 5 buckets
`
Are you sure of your doc_type ?

**Comment by tylerkoldenjtp** [comment]
@SMAPPER Were you able to resolve this issue? I'm experiencing a similar situation where the args are not being recognized.

**Comment by vozura** [comment]
I was able to solve it by using this config:

````
name: No Logs Received from Windows device!

type: flatline

index: logstash-windows-*

threshold: 1

timeframe:
  minutes: 60

query_key: "host.keyword"
doc_type: "windows"

use_terms_query: true

filter:
- query:
    query_string:
      query: "*"

alert_text: "No logs received from {0} in the last 60 minutes"
alert_text_args: ["key"]

alert:
 - "email"
email:
 - "someone@something.com"
````

I initially specified "host" for `query_key` but that gave me the following error:

`ERROR:root:Error running terms query: TransportError(400, u'search_phase_execution_exception', u'Fielddata is disabled on text fields by default. Set fielddata=true on [host] in order to load fielddata in memory by uninverting the inverted index. Note that this can however use significant memory. Alternatively use a keyword field instead.')`

so I changed it to "host.keyword" instead and that worked.

`doc_type` is the value of the "_type" field within Kibana.

For `alert_text_args` you need to specify "key" because that is the field Elastalert stores the value of "host.keyword".

I hope this will help someone as I was looking for a solution for several weeks.

**Comment by Petiois** [comment]
Hi thx for you example.

Is it possible to pass several arguments in ```query_key``` and got them after for build alerting ?
```
type: flatline

threshold: 1
timeframe:
        minutes: 1

query_key: ["user","event_vrf"] # =~ GROUP-BY

#realert:
#        minutes: 60

filter:
        - query:
                query_string:
                        query: 'fcr'

alert:
        - "elastalert_modules.hive_alerter.HiveAlerter"

hive_alert_config:
        title: "AA UCxx Test Compte inactif" ## This will default to {rule[index]_rule[name]} if not provided alert_subject
        type: 'UCxx'
        source: 'AA'
        description: 'Test de compte inactif {match[key]}
'
```

Thx,
