### ISSUE TITLE
Lost data on "summary_table_filed"

### ISSUE THREAD

**Issue by sergii-rolskii** [Yelp/elastalert#1272]
Hi, I have a problem with "summary_table_filed" 

My configuration:

```
name: Flatline DA field action.type:(auth OR provision) equal to zero > 15min  
type: flatline
es_host: elastic
es_port: 9200

index: operations-*

use_count_query: false

timeframe:
  minutes: 3

query_key: action.type

threshold: 100

filter:
- query:
    query_string:
      query: "action.type:(auth provision)"

doc_type: "log"

summary_table_fields: 
 - carrier
 - operator

alert_text_type: exclude_fields 

# (Required)
# The alert is use when a match is found
alert:
- "email"
email: "my@email.com"
```

On the console I see that rules count right:

```
INFO:elastalert:Sent email to ['my@email.com']
INFO:elastalert:Ignoring match for silenced rule Flatline DA field action.type:(auth OR provision) equal to zero > 15min.provision
INFO:elastalert:Ignoring match for silenced rule Flatline DA field action.type:(auth OR provision) equal to zero > 15min.auth
INFO:elastalert:Ran Flatline DA field action.type:(auth OR provision) equal to zero > 15min from 2017-08-06 13:45 EEST to 2017-08-06 13:53 EEST: 228 query hits (195 already seen), 3 matches, 1 alerts sent
INFO:elastalert:Sleeping for 59.667277 seconds
```

but on the email on table "summary_table_filed" data lost or often not displayed:

> Aggregation resulted in the following data for summary_table_fields ==> ['carrier', 'operator', 'count']:
> 
> +--------------+-------------------+-------+
> | carrier        | operator        | count |
> +========+==========+=====+
> | None         | None              | 1       |
> +--------------+-------------------+-------+
> 
> Flatline DA field action.type:(auth OR provision) equal to zero > 15min
> 
> An abnormally low number of events occurred around 2017-08-06 14:03 EEST.
> Between 2017-08-06 14:00 EEST and 2017-08-06 14:03 EEST, there were less than 100 events.
> 

Sometimes the data are present:

> Aggregation resulted in the following data for summary_table_fields ==> ['carrier', 'operator', 'count']:
> 
> +--------------+------------------------+-------+
> | carrier       | operator                | count |
> +========+==============+====+
> | my_carrier_1 | my_operator_1 | 1     |
> +--------------+-------------------------+-------+
> 
> Flatline DA field action.type:(auth OR provision) equal to zero > 15min
> 
> An abnormally low number of events occurred around 2017-08-06 13:49 EEST.
> Between 2017-08-06 13:46 EEST and 2017-08-06 13:49 EEST, there were less than 100 events.
> 

I have 2 different carriers and operator when event's less threshold, I want to see which operator's and carrier has become smaller than threshold(focus on field action.type)
