### ISSUE TITLE
summary_table_fields ignored when aggregation is used

### ISSUE THREAD

**Issue by amraam83** [Yelp/elastalert#1282]
Hi,

I need to have a report printed on my alert for the following rule:
```
name: 'not 200 ok'

type: frequency

num_events: 3

timeframe:
  minutes: 5

use_strftime_index: true
index: logstash-httpd-access-%Y.%m.%d

doc_type: httpd-access

filter:
- term:
    fields.ssl_client_verify.keyword: "SUCCESS"
- term:
    fields.method.keyword: "POST"
- terms:
    fields.url_path.keyword: ["/first/path", "/second/path"]
- terms:
    fields.host_canonical.keyword: ["first_host", "second_host"]
- query:
   query_string:
      query: "NOT fields.http_status:200"

raw_count_keys: False
summary_table_fields:
    - sys.id
    - fields.url_path
    - fields.http_status
```
This works. but if I modify it in the following way (notice the aggregation), the report is not printed on the alarm:
```
name: 'not 200 ok'

type: frequency

num_events: 3

timeframe:
    minutes: 5

use_strftime_index: true
index: logstash-httpd-access-%Y.%m.%d

doc_type: httpd-access

filter:
- term:
    fields.ssl_client_verify.keyword: "SUCCESS"
- term:
    fields.method.keyword: "POST"
- terms:
    fields.url_path.keyword: ["/first/path", "/second/path"]
- terms:
    fields.host_canonical.keyword: ["first_host", "second_host"]
- query:
   query_string:
      query: "NOT fields.http_status:200"

aggregation:
  minutes: 5

raw_count_keys: False
summary_table_fields:
    - sys.id
    - fields.url_path
    - fields.http_status
```
Any suggestions? Bug?
