### ISSUE TITLE
After i use agreation and summary_table_fields config setting, the table is not formated

### ISSUE THREAD

**Issue by qianghaohao** [Yelp/elastalert#1284]
Hello everyone，
    After i use the agreation and summary_table_fields config options，the table is not formated，
the result as following in email：
```
+----------+---------+---------+---------+---------+---------+---------+-------+
|   host   | request | status_ | remote_ | time_lo | num_hit | num_mat | count |
|          |         |  code   |  addr   |   cal   |    s    |  ches   |       |
+==========+=========+=========+=========+=========+=========+=========+=======+
| stcharle | GET /pr | 404     | 66.249. | 14/Aug/ | 14      | 2       | 1     |
| srealest | operty/ |         | 79.48   | 2017:02 |         |         |       |
| atetoday | 1704140 |         |         | :50:47  |         |         |       |
| .chime.m | 9 HTTP/ |         |         | -0700   |         |         |       |
| e        | 1.1     |         |         |         |         |         |       |
+----------+---------+---------+---------+---------+---------+---------+-------+
| www.mill | GET     | 404     | 157.55. | 14/Aug/ | 39      | 5       | 1     |
| erteamre | /real-  |         | 39.240  | 2017:02 |         |         |       |
| altors.c | estate/ |         |         | :51:53  |         |         |       |
| om       | florane |         |         | -0700   |         |         |       |
|          | -garden |         |         |         |         |         |       |
|          | s-sub-i |         |         |         |         |         |       |
|          | nkster_ |         |         |         |         |         |       |
|          | inkster |         |         |         |         |         |       |
|          | / HTTP/ |         |         |         |         |         |       |
|          | 1.1     |         |         |         |         |         |       |
+----------+---------+---------+---------+---------+---------+---------+-------+
| www.mill | GET /si | 404     | 52.32.8 | 14/Aug/ | 39      | 5       | 1     |
| erteamre | testatu |         | 5.119   | 2017:02 |         |         |       |
| altors.c | shidden |         |         | :51:33  |         |         |       |
| om       | .aspx H |         |         | -0700   |         |         |       |
|          | TTP/1.1 |         |         |         |         |         |       |
+----------+---------+---------+---------+---------+---------+---------+-------+
| www.newm | POST    | 404     | 109.92. | 14/Aug/ | 39      | 5       | 1     |
| anhomesa | /wp-log |         | 228.12  | 2017:02 |         |         |       |
| les.com  | in.php  |         |         | :51:37  |         |         |       |
|          | HTTP/1. |         |         | -0700   |         |         |       |
|          | 1       |         |         |         |         |         |       |
+----------+---------+---------+---------+---------+---------+---------+-------+
| www.home | GET /Bi | 404     | 40.77.1 | 14/Aug/ | 14      | 2       | 1     |
| salesins | ngSiteA |         | 81.156  | 2017:02 |         |         |       |
| tcharles | uth.xml |         |         | :51:09  |         |         |       |
| .com     | HTTP/1. |         |         | -0700   |         |         |       |
|          | 1       |         |         |         |         |         |       |
+----------+---------+---------+---------+---------+---------+---------+-------+
| stcharle | GET /pr | 404     | 66.249. | 14/Aug/ | 39      | 5       | 1     |
| srealest | operty/ |         | 79.51   | 2017:02 |         |         |       |
| atetoday | 1705537 |         |         | :52:02  |         |         |       |
| .chime.m | 6 HTTP/ |         |         | -0700   |         |         |       |
| e        | 1.1     |         |         |         |         |         |       |
+----------+---------+---------+---------+---------+---------+---------+-------+
| www.sava | POST /C | 404     | 52.87.7 | 14/Aug/ | 39      | 5       | 1     |
| nnahandb | ontextW |         | 9.151   | 2017:02 |         |         |       |
| eyond.co | ebHook. |         |         | :51:24  |         |         |       |
| m        | ashx HT |         |         | -0700   |         |         |       |
|          | TP/1.1  |         |         |         |         |         |       |
+----------+---------+---------+---------+---------+---------+---------+-------+
```
So, how to get a recortar table? Thanks!

**Comment by qianghaohao** [comment]
I have seen the source code, the table user Texttable. Mybe use PrettyTable is Ok?

**Comment by sathishdsgithub** [comment]
@qianghaohao 

Could you please share the complete yaml rule details ?

**Comment by qianghaohao** [comment]
@sathishdsgithub The following is my full rule file, thanks! 
```
es_host: xxxxxx
es_port: 9200
name: nginx_exception_alert
type: frequency
index: chime*
num_events: 5
timeframe:
  minutes: 5
aggregation:
    minutes: 1
realert:
  minutes: 0
filter:
- term:
    status_code: 404
alert_text_type: exclude_fields
alert_text: |
    5分钟内nginx异常状态码个数超过阀值(>=5),触发报警
    主机: {}
    请求URL: {}
    HTTP状态码: {}
    远程IP地址: {}
    日志时间戳: {}
    总查询次数: {}
    总异常次数: {}
    原始日志信息: {}
alert_text_args:
- host
- request
- status_code
- remote_addr
- time_local
- num_hits
- num_matches
- message
summary_table_fields:
    - host
    - request
    - status_code
    - remote_addr
    - time_local
    - num_hits
    - num_matches
alert:
- "email"
email:
- "xxxxxxxx"
corp_id: "xxxxxxxxx"
secret: "xxxxxxxxxxxxx"
agent_id: 1000003
party_id: 2
user_id: "@all"
log_path: "xxxxx.log"
phone_number:
    - xxxx
```
