### ISSUE TITLE
get no alerts when setting multi values to query_key

### ISSUE THREAD

**Issue by wangxiangyu** [Yelp/elastalert#1300]
I use the frequency rule to do the monitoring.  This is my configuration.
```
type: frequency
num_events: 1
timeframe:
  minutes: 5
filter:
  - query:
      range:
        query_time:
             gte: 0.5
use_terms_query: true
query_key: 
    - beat.hostname
    - port
```
When elastalert was up, No alert was send. I tried to debug, I found the aggs part of query to ES was:
```
    "aggs": {
        "counts": {
            "terms": {
                "field": "beat.hostname,port",
                "size": 50
            }
        }
    }
``` 
As far as I know, `"field": "beat.hostname,port"` is not supported by ES, So the buckets returned are null.

Do I make any mistake?
