### ISSUE TITLE
How can I silence a rule when another has triggered an alert?

### ISSUE THREAD

**Issue by CodingSpiderFox** [Yelp/elastalert#1322]
I have this rule that fires an alert when average CPU load is >= 80% for one minute

```yaml
name: CPU overload
type: metric_aggregation

index: metricbeat-*

buffer_time:
 minutes: 1

metric_agg_key: system.load.norm.1
metric_agg_type: avg
query_key: beat.hostname
doc_type: metricsets


#sync_bucket_interval: true
#allow_buffer_time_overlap: true
#use_run_every_query_size: true

max_threshold: 0.8


import: "/opt/elastalert/rules/jira_settings.txt"

#(Required)
#The alert is use when a match is found
alert:
- "debug"
- "jira"

jira_label: ["cpu_overload"]
jira_priority: 3
```

I have another rule that fires an alert when average CPU load is >= 50% for one minute 

```yaml
name: CPU warning
type: metric_aggregation

index: metricbeat-*

buffer_time:
 minutes: 1

metric_agg_key: system.load.norm.1
metric_agg_type: avg
query_key: beat.hostname
doc_type: metricsets


#sync_bucket_interval: true
#allow_buffer_time_overlap: true
#use_run_every_query_size: true

max_threshold: 0.5


import: "/opt/elastalert/rules/jira_settings.txt"

#(Required)
#The alert is use when a match is found
alert:
- "debug"
- "jira"

jira_label: ["cpu_warning"]
jira_priority: 1
```

When the overload (80%) rule is matched, the 50% rule also generates an alert. How can I prevent the 50% rule to generate an alert when the 80% already generated one (per-hostname basis)?
