### ISSUE TITLE
No query registered for filtered error

### ISSUE THREAD

**Issue by AviralSri** [Yelp/elastalert#1333]
Hi,
My setup:
elastalert->0.0.81
elasticsearch->5.3.1
python->2.7.11

Following is my rule file: 3__app__BLRWFD500316__log_name__eqSecurity__1__30.yaml:
```
realert:
  minutes: 5
from_addr: appmon@capgemini.com
alert_text: "Dear User,\n\t The server BLRWFD500316 is having log_name value as\
  \ Security for the last 30 minutes"
es_host: xx.xx.xxx.xx
index: winlogbeat-*
smtp_host: ismtp.corp.company.com
type: frequency
es_port: 9204
filter:
- query:
  query_string:
   query: "log_name:Security"
- query:
  query_string:
   query: "beat.hostname:DIN16005618"
timeframe:
  minutes: 30
alert: email
name: 3__app__BLRWFD500316__log_name__eqSecurity__1__30.yaml
email: ["aviral.srivastava@company.com"]
num_events: 1
```

I already had setup of elastalert0.0.81 with elasticsearch 2.1.0
We recently deployed elasticsearch 5.3.1. So I did pip uninstall "elasticsearch<3.0.0", then pip install "elasticsearch>=5.0.0"

When testing my config file using
elastalert-test-rule example_rules/3__app__BLRWFD500316__log_name__eqSecurity__1__30.yaml

Successfully loaded 3__app__BLRWFD500316__log_name__eqSecurity__1__30.yaml

INFO:requests.packages.urllib3.connectionpool:Starting new HTTP connection (1):
xx.xx.xxx.xx
WARNING:elasticsearch:GET http://xx.xx.xxx.xx:9204/winlogbeat-*/_search?ignore_u
navailable=true&size=1 [status:400 request:0.069s]
Error running your filter:
RequestError(400, u'parsing_exception', {u'status': 400, u'error': {u'line': 1,
u'root_cause': [{u'reason': u'no [query] registered for [filtered]', u'type': u'
parsing_exception', u'line': 1, u'col': 68}], u'type': u'parsing_exception', u'r
eason': u'no [query] registered for [filtered]', u'col': 68}})
INFO:elastalert:Note: In debug mode, alerts will be logged to console but NOT ac
tually sent. To send them, use --verbose.
INFO:requests.packages.urllib3.connectionpool:Starting new HTTP connection (1):
xx.xx.xxx.xx
WARNING:elasticsearch:GET http://xx.xx.xxx.xx:9204/winlogbeat-*/_search?_source_
include=%40timestamp%2C%2A&ignore_unavailable=true&size=10000 [status:400 reques
t:0.048s]
ERROR:root:Error running query: TransportError(400, u'parsing_exception', u'no [
query] registered for [filtered]')

Would have written the following documents to elastalert_status:

elastalert_error - {'message': "Error running query: TransportError(400, u'parsi
ng_exception', u'no [query] registered for [filtered]')", 'traceback': ['Traceba
ck (most recent call last):', '  File "C:\\Python27\\lib\\site-packages\\elastal
ert-0.0.81-py2.7.egg\\elastalert\\elastalert.py", line 303, in get_hits', "    r
es = self.current_es.search(index=index, size=rule['max_query_size'], body=query
, ignore_unavailable=True, **extra_args)", '  File "C:\\Python27\\lib\\site-pack
ages\\elasticsearch\\client\\utils.py", line 73, in _wrapped', '    return func(
*args, params=params, **kwargs)', '  File "C:\\Python27\\lib\\site-packages\\ela
sticsearch\\client\\__init__.py", line 623, in search', "    doc_type, '_search'
), params=params, body=body)", '  File "C:\\Python27\\lib\\site-packages\\elasti
csearch\\transport.py", line 312, in perform_request', '    status, headers, dat
a = connection.perform_request(method, url, params, body, ignore=ignore, timeout
=timeout)', '  File "C:\\Python27\\lib\\site-packages\\elasticsearch\\connection
\\http_requests.py", line 90, in perform_request', '    self._raise_error(respon
se.status_code, raw_data)', '  File "C:\\Python27\\lib\\site-packages\\elasticse
arch\\connection\\base.py", line 125, in _raise_error', '    raise HTTP_EXCEPTIO
NS.get(status_code, TransportError)(status_code, error_message, additional_info)
', "RequestError: TransportError(400, u'parsing_exception', u'no [query] registe
red for [filtered]')"], 'data': {'rule': '3__app__BLRWFD500316__log_name__eqSecu
rity__1__30.yaml'}}

It appears to be a an error in query syntax. Can somebody help.
