### ISSUE TITLE
Cannot get a metric aggregation to work.

### ISSUE THREAD

**Issue by goveebee** [Yelp/elastalert#1366]
Hi!

I'm trying to create an alert for when the average time for an event step is too high. Here is the Elastic document for one hit:

```
{
  "_index": "monitor",
  "_type": "ActivitySummary",
  "_score": null,
  "_source": {
    "bpmCellName": "bpmCell01",
    "activityType": "userTask",
    "activityName": "Signera",
    "wleName": "Signera (POST)",
    "wleTime": "2017-10-02T14:35:59.028+02:00",
    "taskState": "Completed",
    "kpiData": {
      "Labor Cost.double": "0",
      "Wait Time (Clock).long": 3,
      "Execution Time (Clock).long": 63,
      "Rework.double": "0",
      "Value Add.double": "1",
      "Resource Cost.double": "0",
      "Total Time (Clock).long": 67,
      "Cost.double": "0.00000000"
    },
    "taskStartTime": "2017-10-02T14:34:51.567+02:00",
    "taskClaimedTime": "2017-10-02T14:34:55.233+02:00",
    "taskCompletedTime": "2017-10-02T14:35:59.027+02:00",
    "activityTotalDuration": 67460,
  },
  "fields": {
    "wleTime per day Text": [
      "Mån"
    ],
    "taskCompletedTime": [
      1506947759027
    ],
    "taskStartTime": [
      1506947691567
    ],
    "ActivityTotalDurationSeconds": [
      67
    ],
    "taskClaimedTime": [
      1506947695233
    ],
    "wleTime": [
      1506947759028
    ],
    "wleTime per day": [
      1
    ],
    "wleTime per hour": [
      14
    ]
  }
}
```

Timestamp_field is wleTime, _type is AvtivitySummary, activityName is Signera and the time value is in ActivityTotalDurationSeconds

Here is my rule file:

```
name: Signera Snittid more than 10s
type: metric_aggregation

index: monitor

buffer_time:
  hours: 1

metric_agg_key: ActivityTotalDuration
metric_agg_type: avg
#query_key: beat.hostname
doc_type: ActivitySummary

timestamp_field: "wleTime"
  
bucket_interval:
#  hours: 1
  minutes: 10
  
#sync_bucket_interval: true
#allow_buffer_time_overlap: true
#use_run_every_query_size: true

#min_threshold: 0.1
max_threshold: 1000

filter:
- query:
    query_string:
      query: "activityName: Singera"
```

Here is the output when I test the rule.
```
Successfully loaded Signera Snittid more than 10s

INFO:elastalert:Note: In debug mode, alerts will be logged to console but NOT actually sent.
                To send them but remain verbose, use --verbose instead.

Would have written the following documents to writeback index (default is elastalert_status):

elastalert_status - {'hits': 0, 'matches': 0, '@timestamp': datetime.datetime(2017, 10, 2, 14, 0, 28, 162645, tzinfo=tzutc()), 'rule_name': 'Signera Snittid more than 10s', 'starttime': datetime.datetime(2017, 10, 1, 14, 0, 28, 101609, tzinfo=tzutc()), 'endtime': datetime.datetime(2017, 10, 2, 14, 0, 28, 101609, tzinfo=tzutc()), 'time_taken': 0.053568124771118164}
```
What might be wrong?
