### ISSUE TITLE
The alert_subject is not being used with PagerDuty integration

### ISSUE THREAD

**Issue by tterstep** [Yelp/elastalert#1371]
hi. I am having an issue while trying to move our ElastAlert rules from **Email** integration to **PagerDuty** integration.

An example of the PagerDuty rule I am using is below

```
es_host: 0.0.0.0
es_port: 9200

name: "<rule_name>"
description: <rule description>
use_kibana4_dashboard: <kibana_link>
index: logstash-*
use_local_time: False 

run_every:
  hours: 1
buffer_time:
  hours: 1

type: any

filter:
- query:
    query_string:
      query: '<query_1>'
- query:
    query_string:
      query: '<query_2>'


include:
- <alert_subject_arg_1>
- <alert_subject_arg_2>

alert:
- pagerduty


pagerduty_service_key: "<service_key>"
pagerduty_client_name: "<client_name>"
alert_subject: "PROD REDSHIFT FRESHNESS alert for table"
alert_subject: "alert_subject {0}, {1}"
alert_subject_args:
- <alert_subject_arg_1>
- <alert_subject_arg_2>

realert:
  minutes: 0
```
This does generate the alert and I can see it in PagerDuty, yet the **alert_subject** field is not being used and instead the **rule_name** is being picked up.

Please note that the exact same rule using the Email integration as below

```
es_host: 0.0.0.0
es_port: 9200

name: "<rule_name>"
description: <rule description>
use_kibana4_dashboard: <kibana_link>
index: logstash-*
use_local_time: False 

run_every:
  hours: 1
buffer_time:
  hours: 1

type: any

filter:
- query:
    query_string:
      query: '<query_1>'
- query:
    query_string:
      query: '<query_2>'


include:
- <alert_subject_arg_1>
- <alert_subject_arg_2>

alert:
- email

smtp_host: "<smtp_host>"
smtp_auth_file: "smtp_auth.yaml"
from_addr: "<from_address>"


alert_subject: "PROD REDSHIFT FRESHNESS alert for table"
alert_subject: "alert_subject {0}, {1}"
alert_subject_args:
- <alert_subject_arg_1>
- <alert_subject_arg_2>

realert:
  minutes: 0
```

does function properly and uses the **alert_subject** as expected.

I am currently using ElastAlert **0.0.76**
Is this a known bug with this version?
Any advice on if there is any modification that the PagerDuty rule needs in order to function properly?

Thank you

**Comment by Qmando** [comment]
You'll want to use ``pagerduty_incident_key`` instead of ``alert_subject`` and ``pagerduty_incident_key_args`` instead of ``alert_subject_args``. They should function the same.

Sorry for the inconsistent use of variable names!

Also, you should definitely upgrade as 0.0.76 is pretty old. Though, I don't think pagerduty has changed much, lots of other bugs have been fixed.

**Comment by tterstep** [comment]
hi @Qmando
Thanks for the speedy reply
 
substituted the `alert_subject` and `alert_subject_args` with `pagerduty_incident_key` and `pagerduty_incident_key_args` per your advise and still no change. A single alert is being generated with the `rule_name` as subject. Please see the modified rule below

```
es_host: 0.0.0.0
es_port: 9200

name: "<rule_name>"
description: <rule description>
use_kibana4_dashboard: <kibana_link>
index: logstash-*
use_local_time: False 

run_every:
  hours: 1
buffer_time:
  hours: 1

type: any

filter:
- query:
    query_string:
      query: '<query_1>'
- query:
    query_string:
      query: '<query_2>'


include:
- <alert_subject_arg_1>
- <alert_subject_arg_2>

alert:
- pagerduty


pagerduty_service_key: "<service_key>"
pagerduty_client_name: "<client_name>"
pagerduty_incident_key: "PROD REDSHIFT FRESHNESS alert for table"
alert_subject: "alert_subject {0}, {1}"
alert_subject_args:
- <alert_subject_arg_1>
- <alert_subject_arg_2>

realert:
  minutes: 0
```
