### ISSUE TITLE
Flatline rule gives false negative for 24 hour timeframe

### ISSUE THREAD

**Issue by aurcioli-handy** [Yelp/elastalert#1373]
Flatline rule gives false negative for 24 hour timeframe
----------

#### Summary
We have a `flatline` type rule which is supposed to alert for less than `1` query match in a 24 hour `timeframe`. The rule does not produce a match when a query is not seen for more than 24 hours, and thus does not trigger the alert.

#### Configuration details
Elastalert version: `0.1.18`

Relevant `config.yml` options:
(Hostnames have been altered)
```yaml
rules_folder: /opt/rules
run_every:
  minutes: 1
buffer_time:
  minutes: 15
es_host: es1.example.com
es_port: 9201
use_ssl: True
verify_certs: True
es_send_get_body_as: GET
writeback_index: elastalert_status
notify_email: elastalert@example.com
smtp_host: "smtp.gmail.com"
smtp_port: 587
smtp_auth_file: "/smtp_creds/smtp_auth"
alert_time_limit:
  days: 2
```

#### Rule template
```yaml
name: "48 Hour Reminders Failed to send! (America/New_York)"
es_host: es2.example.com
es_port: 9201
index: fluentd-*
type: flatline
threshold: 1
timeframe:
  minutes: 1445 # 24hours + 5 minutes
filter:
  - query:
      query_string:
        query: "logger: FooLogger AND message.worker: FooWorker AND message.event_name: completed_at AND message.utc_hour: 21"
alert_text: "48 Hour Reminder Failed to send (America/New_York)"
alert_text_type: alert_text_only
alert:
- victorops
realert:
  hours: 24
victorops_api_key: redacted 
victorops_routing_key: application
victorops_message_type: CRITICAL
```

In the last 10 days the event we are querying for in the rule was below the threshold (no documents in ES) on September 26th, and October 3rd (Yesterday). Both times ElastAlert failed to trigger an alert even though `elastalert_status` shows `0 hits`. 

![screen shot 2017-10-04 at 4 54 11 pm](https://user-images.githubusercontent.com/15836389/31199702-3ccca804-a926-11e7-8e97-89b08d143a45.png)

Kibana results for rule query in the last 10 days:

|Time|message.worker|
|----|-------------------| 
|October 2nd 2017, 17:14:25.666|	FooWorker|
|October 1st 2017, 17:14:13.111|	FooWorker|
|September 30th 2017, 17:14:10.554|	FooWorker|
|September 29th 2017, 17:15:05.429|	FooWorker|
|September 28th 2017, 17:14:11.917|	FooWorker|
|September 27th 2017, 17:14:20.885|	FooWorker|
|September 25th 2017, 17:14:16.968|	FooWorker|
|September 24th 2017, 17:14:03.887|	FooWorker|

When querying `elastalert_status` for September 26th there are no documents with a `match` count of 1. (Same story for all dates which should have triggered an alert but did not) Here is a sample around the relevant timeframe:

|Time| 	hits|  	matches|  	rule_name|
|----|------|----------|-------------|  
|September 26th 2017, 17:17:24.350|	0|	0|	48 Hour Reminders Failed to send! (America/New_York)|
|September 26th 2017, 17:16:27.494|	0|	0|	48 Hour Reminders Failed to send! (America/New_York)|
|September 26th 2017, 17:15:24.863|	0|	0|	48 Hour Reminders Failed to send! (America/New_York)|
|September 26th 2017, 17:14:26.126|	0|	0|	48 Hour Reminders Failed to send! (America/New_York)|
|September 26th 2017, 17:13:56.258|	0|	0|	48 Hour Reminders Failed to send! (America/New_York)|

It seems to us that the flatline rule is either malfuctioning or we have done something wrong here. Any ideas would be appreciated. Thankyou.
