### ISSUE TITLE
Cardinality rule type and top_count_keys 

### ISSUE THREAD

**Issue by Trustys** [Yelp/elastalert#1374]
Hello everybody,

I try to use top_count_keys in a cardinality rule type but I can't succeed to make it works : 

```
name: "##PortScan"

index: firewall_*
type: cardinality

query_key: [event_ip,src_ip,dst_port]
cardinality_field: dst_ip
max_cardinality: 25

buffer_time:
    minutes: 5

timeframe:
    minutes: 5

filter:
- query:
    query_string:
        query: 'event_device:Firewall AND dst_port:(1 OR 5 OR 7 OR 18 OR 20 OR 21 OR 22 OR 23)

top_count_number: 10

raw_count_keys: false

include:
  - src_ip
  - source
  - dst_ip
  - dst_port
  - event_ip

top_count_keys: ["dst_ip"]

alert_text_type: exclude_fields
```
Alerts is working but no top_count_keys in alert output:
`dst_ip: No events found.`

I tried with raw_count_keys: false disabled but same issue : 
`dst_ip.raw: No events found.`

Does anybody else has the same issue ?
