### ISSUE TITLE
ES5 NOT/AND issues

### ISSUE THREAD

**Issue by matolivier** [Yelp/elastalert#1375]
Hi,

I'm having an issue running my ES 2.X filters with 5.X.
The old rules were the following:
 ```
filter:
  - term:
    pool: POOL_ES 
  - and:
    - not:
        range:
           client_ip:
                "from" : "10.0.0.0"
                "to" : "10.255.255.255"
    - not:
        term:
           client_ip: "x.x.x.x"
```
I'm aware the terms should be replaced by query_string or wildcard in my case, but I'm unable to adapt the AND/NOT logic.
I always have this kind of error (here is the request in debug mode):

```
"RequestError: TransportError(400, u'parsing_exception', u'[and] query malformed, no start_object after query name')"], 'data': {'query': {'sort': [{'@timestamp': {'order': 'asc'}}], 'query': {'bool': {'filter': {'bool': {'must': [{'range': {'@timestamp': {'gt': '2017-10-06T08:51:25.346421Z', 'lte': '2017-10-06T09:06:25.346421Z'}}}, {'wildcard': {'pool': 'POOL_ES*'}}, {'and': [{'not': {'term': {'client_ip': 'x.x.x.x'}}}]}]}}}}}, 'rule': 'crawlers POOL_ES'}}
````
Someone mentioned the documentation is outdated for ES5 in issue #912 but unfortunately I am not really good at ES queries neither.

**Comment by matolivier** [comment]
I found an answer is the issue #930 

The following filter works:

```
filter:
- bool:
    must:
        - wildcard:
            pool: "POOL_ES*"
        - bool:
            must_not:
                - term:
                    client_ip: "x.x.x.x"
                - range:
                    client_ip:
                        from: "10.0.0.0"
                        to: "10.255.255.255"
```
