### ISSUE TITLE
Show every hit in Email body

### ISSUE THREAD

**Issue by Invictus96** [Yelp/elastalert#1389]
Hello, 
i created a rule any.yml and the result are 3 hits and 3 matches. 
But in the email body there is the content of only one of the three matches. 
How can I change, that in one email the content of every message_field is shown? 

Thanks for your response

**Comment by Invictus96** [comment]
ok, realalert: minutes: 0 fixed it!
But now I got three mails, how can I put the content of those three into one email?

**Comment by Qmando** [comment]
add
```
aggregation:
  minutes: 5
```

which means that after the first alert, all subsequent alerts for the next 5 minutes will be joined into a single email.

**Comment by Invictus96** [comment]
Yes, I tried this yesterday. But than no email is generated. 
Is there somthing wrong with the rule?

```
es_host: localhost
es_port: 9200
name: LoggingLevel
type: any
index: filebeat-*
    
query_key: beat.hostname

filter:
 - query_string:
    query: "message:Error" 
        #OR message:Error"
        #and source:PFAD

alert:
 - "email"

email:
 - "MyEmail"

smtp_host: "192.168.146.3" 

alert_text: |
    timestamp: {0}
    message: {1}
alert_text_args: ["@timestamp", "message"]

alert_text_type: exclude_fields 

realert:
  minutes: 0
  
aggregation:
  minutes: 5
```

Thanks
