### ISSUE TITLE
Allow mapping in config between num_events/threshold and values of query_key

### ISSUE THREAD

**Issue by Qmando** [Yelp/elastalert#14]
It would be nice to be able to map alert thresholds with different values of query_key. This way, one rule can cover multiple things which only differ in a threshold value. An example of what this could look like:

```
type: frequency
query_key: error_type
num_events: 
  timeouterror: 50
  valueerror: 5
  someothererror: 15
  default: 10
```
