### ISSUE TITLE
Composite keys for new_term alert

### ISSUE THREAD

**Issue by skiptomyliu** [Yelp/elastalert#1412]
Hello!  

I am attempting to alert whenever a user has ssh'ed into a host that they've never ssh'ed into before.  I seem to get hits, but never any matches to alert.

```
terms_window_size:
  days: 10

realert:
  minutes: 0

# Monitor for new unique username, @source_host pairs.
fields: [["username", "@source_host"]]

filter:
- query:
    query_string:
        query: "tags:ssh AND _exists_:@source_host AND _exists_:username"
```

I read in the documentation that `fields` can contain a list as an entry.  Am I correct in interpreting the above rule as:  if a new `username` AND `@source_host` pair is found that wasn't seen in the last 10 days, alert?    I seem to get hits, but never any matches to alert even if I set the terms_window_size to something real small like a minute.  

As always, help and guidance is always appreciated!  Love using elastalert.
