### ISSUE TITLE
Ignoring known alerts in future

### ISSUE THREAD

**Issue by slavniyteo** [Yelp/elastalert#1423]
Hi, thank you for awesome tool.

I've searched docs but found nothing. 

When I receive some alert with known error, I want to ignore same errors.

For example, my rule alerts every doc with field `level: WARN`. I receive an alert from service `some-service` with message `Can't do some unnesessary stuff`. And I want to ignore all same alerts but want to receive all other alerts from this service.

Is there any way?

**Comment by muravitskiy** [comment]
According to the [docs](https://elastalert.readthedocs.io/en/latest/ruletypes.html#realert) you can ignore same alerts for some period using `realert` option and combine with `use_terms_query`. ElastAlert will make an aggregation query to get documents matching each unique value of `query_key`( `doc_type` is required).  Note that if your service generates a lot of unique messages you should increase `terms_size ` which defaults to `50`
```yaml
doc_type: logs
use_terms_query: true
query_key: message
filter:
    - term:
        level: "WARN"
    - term:
        service: some-service
realert:
    minutes: 60
```
