### ISSUE TITLE
get no alerts when setting multi values to query_key, while the rule type is Metric Aggregation.

### ISSUE THREAD

**Issue by zxq1002** [Yelp/elastalert#1435]
my configuration is:
```
...
metric_agg_key: EXEC
metric_agg_type: avg
query_key: ["appname.keyword", "ip"]
doc_type: gerrit_sshd_log
  
bucket_interval:
  minutes: 5
  
sync_bucket_interval: true
#allow_buffer_time_overlap: true
#use_run_every_query_size: true

min_threshold: 0
max_threshold: 30000

filter:
- term:
    OPERATION: "git-upload-pack"

# (Required)
# The alert is use when a match is found
alert:
- "email"
...
```

When elastalert is running, no alerts was triggered. 
Do i make any mistake? Or multi query_key does not support metric aggregation rule type.
