### ISSUE TITLE
DEBUG logs caused a lot of alerts?

### ISSUE THREAD

**Issue by quantonganh** [Yelp/elastalert#1437]
We have only one rule like this:

```
# (Required)
# Type of alert.
# the frequency rule type alerts when num_events events occur with timeframe time
type: frequency

# (Required)
# Index to search, wildcard supported
index: filebeat-*

# (Required, frequency specific)
# Alert when this many documents matching the query occur within a timeframe
num_events: 1

# (Required, frequency specific)
# num_events must occur within this amount of time to trigger an alert
timeframe:
  days: 1

# (Required)
# A list of Elasticsearch filters used for find events
# These filters are joined with AND and nested in a filtered query
# For more info: http://www.elasticsearch.org/guide/en/elasticsearch/reference/current/query-dsl.html
filter:
- query:
    query_string:
      query: "log: failed to backup database"
```

Don't know why we got a lot of alerts when starting:

```
Example frequency rule

At least 1 events occurred between 2017-11-28 08:41 UTC and 2017-11-29 08:41 UTC

@timestamp: 2017-11-29T08:41:07.946Z
_id: AWAG7-CYxo-tUa49b7a4
_index: filebeat-2017.11.29
_type: doc
beat: {
   "hostname": "xx", 
   "name": "xx", 
   "version": "5.5.0"
}
input_type: log
log: INFO:elastalert:Queried rule Example frequency rule from 2017-11-29 08:33 UTC to 2017-11-29 08:41 UTC: 57 / 57 hits
num_hits: 64
num_matches: 7
offset: 615687
source: /var/lib/docker/containers/xx/xx-json.log
stream: stdout
time: 2017-11-29T08:41:02.568570966Z
type: log
```

Does it mean that ElastAlert send an alert whenever it found a `num_matches`?
Is there a way to disable this behaviour?
