### ISSUE TITLE
Reproduce a query in elastalert with should/must/must_not

### ISSUE THREAD

**Issue by gpoire** [Yelp/elastalert#1464]
Hello everyone, 
I'm trying to adapt this query in a rules in elastalert but it doesn't really work for the moment

Elasticsearch request : 
GET /_search
{
    "query": {
        "bool" : {
          "should" : [
            {"match_phrase" : { "message" : "one sentence" }},
            {"match_phrase" : { "message" : "another" }}
      ]
    }
}
}

Elastalert rules : 

filter:
  - query:
     bool:
      should:
       match_phrase:
        "message": "one sentence"
       match_phrase:
        "message": "another"

Have someone already solve this kind of problem ? 

Thanks for your help

**Comment by Qmando** [comment]
ElastAlert only does filter based queries, not scored, so ``should`` is not really used.

You probably want something like:
```
filter:
 - query:
      query_string:
        query: "\"one sentence\" OR another"
        default_field: message
```
