### ISSUE TITLE
Aggregation

### ISSUE THREAD

**Issue by zakrush** [Yelp/elastalert#1467]
Good day. 
I don't have any idea how can I solve the problem with alerts. 
My rule is:
```
name: Change files of production

index: wazuh-alerts-*
type: any
realert:
  seconds: 0
alert_time_limit:
  days: 2
aggregation:
  minutes: 3

filter:
- query:
    query_string:
      query: "rule.groups: update_prod AND audit"

include:
  - audit.auid
  - audit.file.name
  - audit.euid

run_enhancements_first: true

alert:
  - slack
alert_subject: ":exclamation: Prod was updated: "
alert_text_type: alert_text_only
alert_text: |
  User with UID *{0}* updated prod as user with UID {1}

alert_text_args:
  - audit.auid
  - audit.euid
slack_webhook_url: "https://hooks.slack.com/services/****"
slack_username_override: "*********"
slack_channel_override: "update_prod"
```
It's alert about changes files into production  backend web-server. At the aggregation time I can get 1 or over 600 mathes and all of them have one `audit.auid` and `audit.euid`. 

How I can sent one alert regardless of the number match? 
I tried do `aggregation_key: audit.auid` but it didn't help me.
