### ISSUE TITLE
multiple queries in a single rule

### ISSUE THREAD

**Issue by tterstep** [Yelp/elastalert#1468]
Can someone please explain me whether the below two are equivalent? I would expect them to be yet I am seeing different results in each case.

RULE 1

```
es_host: host
es_port: port


name: <"name">
description: <"Description>
generate_kibana_link: true
use_kibana4_dashboard: <"kibana_dashboard">
index: <index>
use_local_time: False

run_every:
  hours: 3
buffer_time:
  hours: 3


type: flatline
threshold: 1
timeframe:
 hours: 3


filter:
- query:
    query_string:
      query: 'source:"source" AND NOT message: "message" AND NOT name: "name"'


alert:
- email

email: <"email">
alert_subject: "<subject>"
alert_subject_args:
- key
alert_text_args:
- "kibana_link"

smtp_host: "smtp_host"
smtp_auth_file: "auth_yaml"
from_addr: "from_addr"


realert:
  minutes: 0

query_key: host
```

RULE 2

```
es_host: host
es_port: port


name: <"name">
description: <"Description>
generate_kibana_link: true
use_kibana4_dashboard: <"kibana_dashboard">
index: <index>
use_local_time: False

run_every:
  hours: 3
buffer_time:
  hours: 3


type: flatline
threshold: 1
timeframe:
 hours: 3


filter:
- query:
    query_string:
      query: 'source:"source"'
- query:
    query_string:
      query: 'NOT message: "message"'
- query:
    query_string:
     query: 'NOT name: "name"''


alert:
- email

email: <"email">
alert_subject: "<subject>"
alert_subject_args:
- key
alert_text_args:
- "kibana_link"

smtp_host: "smtp_host"
smtp_auth_file: "auth_yaml"
from_addr: "from_addr"


realert:
  minutes: 0

query_key: host
```
Note for the RULE 1 the 
query contains all 3 query conditions
while  
for RULE 2
the queries are separated
Thanks!
