### ISSUE TITLE
Flatline Rule going off when there is data

### ISSUE THREAD

**Issue by Mokatsu** [Yelp/elastalert#1475]
Hi, I have been having some issue with a flatline rule that I wrote for one of my indexes.
Here is the rule:

````
es_host: $ES_HOST
es_port: $ES_PORT
name: rule_name
type: flatline
index: index_name
timestamp_field: "date_event"
realert:
   hours: 4
threshold: 1
timeframe:
   hours: 8
filter:
   - term:
      _type: "windows_firewall_event"
slack_webhook_url: $SLACK_WEBHOOK_URL
alert:
   - slack
````

But when I check Kibana every time I see data, so then I actually captured the get request as the rule was being run just to see what query the rule actually runs, here is what I found:
````
{"sort": 
  [
    {"date_event": 
    {"order": "asc"}
      }
    ],
    "query": 
    {"bool": 
      {"filter": 
        {"bool": 
        {"must": 
          [
            {"range": 
              {"date_event": 
                {"gt": "2018-01-03T20:11:08.077692Z", "lte": "2018-01-03T20:20:08.894815Z"}
              }
            },
             {"term": 
              {"_type": "windows_firewall_event"}
           }
          ]
        }
      }
    }
   }
}
````

Then I ran that same query for each time stamp the flatline alert on and every time I saw data.

Not sure why the rule is going off when there is data in the index.

Any help would be appreciated.
p.s. - the variables in the rule get changed (with an external script) before the rule is placed into the rules folder
