### ISSUE TITLE
Flatline Rule with query_key

### ISSUE THREAD

**Issue by tterstep** [Yelp/elastalert#1478]
Hi there.

I have this rule that I expect to run every 6 hours, look back 6 hours and to trigger if there are >=0 events. 
This should work separately for each **host** hence the query_key implementation.
Yet I see it triggering even when there are events in Kibana

i.e this in kibana for last 6 hours returns events

```
"host1" AND source:"some source" AND NOT message: "some message" AND NOT name: "some name"
```

**The rule**
```
es_host: es_host
es_port: port


name: name
description: description
use_kibana4_dashboard: kibana_dashboard
index: logstash-*
use_local_time: False

run_every:
  hours: 6
buffer_time:
  hours: 6


type: flatline
threshold: 1
timeframe:
  hours: 6


filter:
- query:
    query_string:
      query: 'source:"some source" AND NOT message: "some message" AND NOT name: "some name"'



alert:
- email


# Email Config
email: email
alert_subject: "subject"
alert_subject_args:
- key


smtp_host: "smtp_host"
smtp_auth_file: "<smtp_auth_file>"
from_addr: "from_addr"


realert:
  minutes: 0

query_key: host
```

Can somebody please advise what am I doing incorrectly here?

Thank you!
Tigran
