### ISSUE TITLE
Issue with Spike alerting

### ISSUE THREAD

**Issue by hsafe** [Yelp/elastalert#1491]
Hi,
I am reltively new to elastalert,and though successfully configured and tested the Frequency alert; have trouble to get my hands around spike. No matter how small I set the values it seems it does not match and get me alerted. Here is the config I am using:
```
name: Company_http_request_spike
type: spike
index: filebeat-*
threshold_ref: 100
timeframe:
  hours: 1
spike_height: 10
spike_type: "up"
aggregation:
  hours: 1
filter:
- range: 
    http_status_code:
      from: 200
      to: 599  
- term:
    beat.hostname: "app-lb1.example.org"

alert:
- slack
slack_webhook_url: https://hooks.slack.com/services/MySecretToken
```
My Interpretation: any http requests regardless of the type if within a time frame of 1 hour multiplied by 10 for the threshold of 100, report me in the slack and aggregate the report for each hour.
Please note that a Frequency alert using the common configs behaves as expected and reports generated in that alert.
