### ISSUE TITLE
query_key ignored when using use_count_query

### ISSUE THREAD

**Issue by alpha-er** [Yelp/elastalert#1510]
I have a spike rule the uses use_count_query and specifies a query_key. My expectation is that the count will be separate for each value of query_key.

spike_rule:
```
index: logstash-*
filter:
  - query:
      query_string:
        query: 'type:"cloudwatch-ecs"'
query_key: "application.name"

type: spike
spike_height: 2
spike_type: up
timeframe:
  hours: 3
threshold_ref: 1
use_count_query: true
doc_type: cloudwatch-ecs
```

sample result from elastalert-test-rule:
```
INFO:elastalert:Alert for ecs_application_log_volume_spike at 2018-01-24T20:43:12.899160Z:
INFO:elastalert:ecs_application_log_volume_spike

An abnormal number (595604) of events occurred around 2018-01-25 09:43 NZDT.
Preceding that time, there were only 295206 events within 3:00:00

@timestamp: 2018-01-24T20:43:12.899160Z
num_hits: 2792161
num_matches: 1
reference_count: 295206
spike_count: 595604
