### ISSUE TITLE
Documentation on printing out custom alert messages

### ISSUE THREAD

**Issue by darrenhaken** [Yelp/elastalert#1523]
I'm trying to create a `frequency` alert that counts and aggregates by a key called `application`.
The goal is to alert when an application appears to be sending a large volume of the event.
We didn't want to use Spike as we'd prefer to work off a threshold at the moment.

When the alert fires I would it to display what application is causing the alert.

Here is the alert:

```
name: too many events per application in the last hour
type: frequency

index: index-*
doc_type: index-event

timeframe:
  hours: 1

realert:
  hours: 1

# Alert when this many documents matching the query occur within a timeframe
num_events: 50000

use_count_query: True
use_terms_query: True
query_key: application

alert:
  - "slack"
```

The alert looks like:
```
too many events per application in the last hour
too many events per application in the last hour

At least 50000 events occurred between xx and xx

@timestamp: 2018-01-30T21:21:39.974040Z
num_hits: xxxxx
num_matches: xxx
```

I'd like the alert to look something like:
```
too many events per application in the last hour
Application {{app_name}} has at least 50000 events occurred between xx and xx

@timestamp: 2018-01-30T21:21:39.974040Z
num_hits: xxxxx
num_matches: xxx
```
