### ISSUE TITLE
Deprecated aggregation order key [_term] used, replaced by [_key]

### ISSUE THREAD

**Issue by Stono** [Yelp/elastalert#1528]
When using a rule such as this:
```
name: application spike in traffic
type: spike

index: metrics20-today
doc_type: metrics20-event

# The spike rule matches when the current window contains spike_height times more
# events than the reference window
spike_height: 3

# The direction of the spike
# 'up' matches only spikes, 'down' matches only troughs
# 'both' matches both spikes and troughs
spike_type: up

realert:
  hours: 3

timeframe:
  hours: 3
filter:
- not:
    term:
      application: "mercury"
use_terms_query: True
query_key: application

alert:
  - "slack"

alert_text: "Application {0} traffic has spiked in the last 3 hours"
alert_text_type: alert_text_only
alert_text_args: ["application"]
```

We get spam warnings in elasticsearch logs like this:
```
Deprecated aggregation order key [_term] used, replaced by [_key]
```

Because of `_term` being deprecated:, see: https://www.elastic.co/guide/en/elasticsearch/reference/current/search-aggregations-bucket-terms-aggregation.html
