### ISSUE TITLE
run_every config seems to be ignored

### ISSUE THREAD

**Issue by isadp** [Yelp/elastalert#1551]
Maybe my config is wrong - I have set run_every to 5 minutes, but elastalert polls the es-Index every minute. 

```
#name: threat by IP
type: frequency
index: threat*
num_events: 3
query_key: "SourceIP"
run_every:
  minutes: 5
timeframe:
  minutes: 5
buffer_time:
  minutes: 5
filter:
- query:
    query_string:
       query: "Action: (block-ip OR reset-both)"
alert: email
email:
 .......
aggregation:
  minutes: 10
realert:
  minutes: 10

```
