### ISSUE TITLE
Elastalert group by client_id

### ISSUE THREAD

**Issue by F1sn1k** [Yelp/elastalert#1567]
Hello. Is there a way I can get separate results for different clients with one query

```
query: 'event: "alert_sent"`
```
and I like to group by `client_id`

The desired result I want for example:
```
Client A: 530 hits
Client B: 435 hits
Client C: 3545 hits
```

Using `query_key: client_id` I get a result with list of clients but all have same result for example:

```
Client A: 100 hits
Client B: 100 hits
Client C: 100 hits
```
------
 Here is sample of my rule:

```
index: "mya_output_eb-*"
name: Total alert for clients
timestamp_field: timestamp

alert_text: "There were {0} notifications for {1}."
alert_text_args: ["num_hits", "client_id"]
alert_text_type: alert_text_only

type: flatline
threshold: 10
timeframe:
  hours: 24
 
filter:
- query:
    query_string:
      query: 'event: "alert_sent"'

query_key: client_id

alert:
  - slack
slack_webhook_url: https://hooks.slack.com/services/xxx/xxx/xxx
```

Should I use `aggregation with aggregation keys`? or other configuration ?
