### ISSUE TITLE
Multiple windows event id based correlation rule

### ISSUE THREAD

**Issue by suchandbabu** [Yelp/elastalert#1606]
Hi,

Can you please help me to write a correlation rule which querying multiple windows event ids.

I have given below the logic.

[(4618 AND 6273) AND (4907 OR 4660 OR 4670) AND (4964 OR 4767 )]

**Comment by suchandbabu** [comment]
@Qmando 
Requesting your help to solve the above mentioned issue.

**Comment by Qmando** [comment]
This is not really supported very well out of the box. One thing you could do is use cardinality rule.
Let's say the field you are looking at is called "code".

```
type: cardinality
filter:
 - terms:
      code: [4618, 6273]
cardinality_field: code
max_cardinality: 1
timeframe:
  hours: 1
```

This will alert if there is at least one of each 4618 and 6273 in an hour. However, you would need to make a new alert for every combination.
