### ISSUE TITLE
how to alert only after a certain number of minutes

### ISSUE THREAD

**Issue by ashokbellur** [Yelp/elastalert#1659]
Hello, I have this rule that alerts immediately based on the query_string

I want the alert to go out say after 5 min. How would i do that? I am using pagerduty and want to wait for a few minutes before alerting oncall.

```
name: Service Reporting Down 3min
type: any
index: filebeat-%Y.%m.%d
use_strftime_index: true

doc_type: application
realert:
  minutes: 3

filter:
  - query:
      query_string:
        query: '+service_name:"myservice" +message:"* is now down*"'

alert_subject: "SERVICE DOWN: reporting service down in the {0} environment on {1}"
alert_subject_args:
  - environment
  - beat.hostname

alert_text_type: alert_text_only
alert_text: |
   is reporting a service is down in {1} on {2}
  ```
  {0}
  ```
alert_text_args:
  - message
  - environment
  - beat.hostname
```
Thanks!.
