### ISSUE TITLE
Adding filter option to NewTermsRule

### ISSUE THREAD

**Issue by stevegszabo** [Yelp/elastalert#1663]
NewTermsRule doesn't seem to support a filter option at the rule level so we added:

```
filter:
- terms:
    oiqenv: ["prd", "poc"]
- match_phrase:
    oiqstatus: ERROR
```

NewTermsRule.get_all_terms:

```
for field in self.fields:
            if 'filter' in self.rules:
                for item in self.rules['filter']:
                    query_template['filter']['bool']['must'].append(item)
```
