### ISSUE TITLE
elastalert test rule failing with parsing exceptions

### ISSUE THREAD

**Issue by chakrapani123** [Yelp/elastalert#1664]
WARNING:elasticsearch:GET http://11.11.11.111:9200/syslog24514-%25%7B%2BYYYY.MM.dd%7D/_search?ignore_unavailable=true&size=1 [status:400 request:0.027s]
Error running your filter:
RequestError(400, u'parsing_exception', {u'status': 400, u'error': {u'line': 1, u'root_cause': [{u'reason': u'no [query] registered for [filtered]', u'type': u'parsing_exception', u'line': 1, u'col': 62}], u'type': u'parsing_exception', u'reason': u'no [query] registered for [filtered]', u'col': 62}})

rule.yml: 
```
es_host: 11.12.13.145
es_port: 9200
name: error_count
type: frequency
index: syslog24514-%{+YYYY.MM.dd}
num_events: 1
timeframe:
    hours: 4
filter:
- query:
      query_string:
        query: "event_name: GetJob"
alert:
- "slack"
slack:
slack_webhook_url: "https://hooks.slack.com/services/XXXXX"
```
I have it on centos 7.3 Elastalert version : 0.1.29 & ES cluster : 6.2
