### ISSUE TITLE
HTTP POST Alert - it is not possible to combine some Key Values from ElasticSearch into one Payload Key

### ISSUE THREAD

**Issue by olisolis** [Yelp/elastalert#1688]
Hier is my HTTP POST Alert rule:

```
es_host: xxx
es_port: 9200
name: Test POST rule
type: any
index: logstash-*
realert:
  minutes: 0
filter:
- match:
    level: "ERROR"
alert: post
http_post_url: "xxx"
http_post_payload:
  comment: message
http_post_static_payload:
  ...
```

The Problem is, that it seems not possible to enter more then one Key Value for "comment" in "http_post_payload".

I would expect something like that:

```
...
http_post_payload:
  comment: message + ", " + id + ", " + timestamp
...
```

Thank you for your suggestions!
