### ISSUE TITLE
[BUG] Issue with rules config

### ISSUE THREAD

**Issue by regardfs** [Yelp/elastalert#1690]
Here is my rules config:
```
name: LOG ERROR WATCH
type: any
index: logstash-*
num_events: 5

timeframe:
  hours: 1

filter:
- query:
    query_string:
      query: "message: *ERROR*"

```

When start, it reports error as below:
```
elastalert    | 2018-05-09 04:13:39,409 DEBG 'elastalert' stderr output:
elastalert    |   File "/usr/local/bin/elastalert", line 11, in <module>
elastalert    |     load_entry_point('elastalert==0.1.30', 'console_scripts', 'elastalert')()
elastalert    |   File "/usr/local/lib/python2.7/site-packages/elastalert-0.1.30-py2.7.egg/elastalert/elastalert.py", line 1858, in main
elastalert    |     client = ElastAlerter(args)
elastalert    |   File "/usr/local/lib/python2.7/site-packages/elastalert-0.1.30-py2.7.egg/elastalert/elastalert.py", line 130, in __init__
elastalert    |     self.conf = load_rules(self.args)
elastalert    |   File "/usr/local/lib/python2.7/site-packages/elastalert-0.1.30-py2.7.egg/elastalert/config.py", line 484, in load_rules
elastalert    |     raise EAException('Error loading file %s: %s' % (rule_file, e))
elastalert    | elastalert.util.EAException: Error loading file /opt/rules/log_error_watch.yml: Invalid Rule file: /opt/rules/log_error_watch.yml
elastalert    | 'index' is a required property
```

It suggested that I do not have keyword of index ,but indeed, I sure have it in my config file, So anyone could help me about this?
