### ISSUE TITLE
Trouble with more complex filter rules either not alerting or alerting too easily

### ISSUE THREAD

**Issue by NekoKetsueki** [Yelp/elastalert#1699]
I have been trying to fix this issue for a long time now without success.

I am using:
- ELK v6.2.2
- Various beats v6.1.3+
- Elastalert v0.1.29 (According to changelog) pulled from GIT on 12/03/18

Basically I want an alert when:
> if host = host1 OR host2 then
> if balanced.backend = (NOSRV OR timeout) OR if msgnum = DOWN
> AND NOT connected to port80

I have tried quite a few different methods to achieve this.

My best method so far:
```
 filter:
   - query_string: 
       query: "host: ip-XXX-XX-XX-1 OR host: ip-XXX-XX-XX-2"
   - query_string: 
        query: "balanced.backend: NOSRV OR balanced.backend: timeout OR msgnums: DOWN NOT connected.to: prt80"
```
This does alert but it ignores the first query and alerts on the second - ie. if the IP is not one of the two listed it will still alert.

I recently had a revelation that maybe because I'm using queries it might be picking up a section, eg. "ip-" from the first query and then just alerting on that, so I tried with terms (and the minimum_should_match) and with escape characters to specify the IP but the alerts didn't trigger at all.
```
filter:
   - terms:
        host: ["ip-XXX-XX-XX-1", "ip-XXX-XX-XX-2"]
   - terms:
        balanced.backend: ["<NOSRV>", "timeout,"]
   - term:
        msgnums: "DOWN"
   - query_string: 
        query: "NOT connected.to: prt80"
```
(I did also try with escaping the gth, lth and comma symbols.)

I then tried in one long query string but got no alerts:
```
filter:
   - query_string: 
        query: "host: \"ip-XXX-XX-XX-1\" OR host: \"ip-XXX-XX-XX-2\" AND balanced.backend: NOSRV OR balanced.backend: timeout OR msgnums: DOWN NOT connected.to: prt80"
```

I did also try to follow the docs themselves on the alert system but found that the nested and/or/not methods seem to have been deprecated in Elastic 6+
```
filter:
- or:
    - query_string: 
        query: "host: ip-XXX-XX-XX-1 OR host: ip-XXX-XX-XX-2"
    - and:
       - query_string: 
            query: "balanced.backend: NOSRV OR balanced.backend: timeout OR msgnums: DOWN"
        - not:
           - query_string: 
              query: "connected.to: prt80"
```

I have also tried to use the new Elastic queries such as the match/multi_match but could not get them working through the elastalert rule system.

Any advice would be greatly appreciated!

- NekoKetsueki.

**Comment by Qmando** [comment]
You were very close in the first one. Try
```
 filter:
   - query_string: 
       query: "host: \"ip-XXX-XX-XX-1\" OR host: \"ip-XXX-XX-XX-2\""
   - query_string: 
        query: "balanced.backend: NOSRV OR balanced.backend: timeout OR msgnums: DOWN NOT connected.to: prt80"
```

You need the quotes in query_string because without them, it treats each "token" as separate queries joined by ORs. IE, ``host: ip-10-20-30-40`` actually means "any document where host contains either "ip" or "10" or "20" etc.

The filter with ``terms`` didn't match anything because for term/terms, it checks for exact matches with the analyzed tokens. "ip-XX-YY" gets split up into 3 terms, "ip", "xx", "yy", so the full string will never work in term(s) query.
