### ISSUE TITLE
metric_aggregation

### ISSUE THREAD

**Issue by Invictus96** [Yelp/elastalert#1700]
Hi members,

this is my metric_aggregation.yml

```
es_host: elasticsearch-coordinating
es_port: 9200
index: metricbeat-*
type: metric_aggregation
name: Out_of_Memory

buffer_time:
  minutes: 15

metric_agg_key: docker.memory.usage.pct
metric_agg_type: max
query_key: beat.hostname
doc_type: metricsets

max_threshold: 0.1

filter:
 - terms:
      docker.container.name.keyword: ["dockerelk_elasticsearch_1", "dockerelk_elasticsearch_2", "dockerelk_elasticsearch_3"]

alert:
 - "email"

email:
 - "MyEmail@myemail.com"

smtp_host: "IP"

alert_text: |
    Memory: {0}
    Der ELK-Stack laeuft out of Memory, please scale!
alert_text_args: ["docker.memory.usage.pct"]

alert_text_type: exclude_fields
```

I dont now how to configure that: 
From each container, the sum of the maximum docker.memory.usage.pct is generated

And an email will be send if this Total sum of max docker.memory is over 70 (0,7)%
