### ISSUE TITLE
Event ID 4625 - Failed Logins

### ISSUE THREAD

**Issue by mathurin68** [Yelp/elastalert#1708]
I think I have this pretty close but I'm missing something I'm looking for  -  more than 6 failed logins on the same computer within 10 minutes.   

```
es_host: localhost
es_port: 9200
name: word_failed
index: winlogbeat-*
# Alert when login failures occur for a single user
filter:
  - query:
        query_string:
            query: "event_id: 4625"
type: frequency
num_events: 6
timeframe:
    minutes: 10
query_key: "computer_name"
include: ["computer_name", "event_data.TargetUserName", "@timestamp"]

```

when I test the rule with elastalert-test-rule I get a massive number for the last day.  BUT it doesn't change if I change the query_key, num_events, or timeframe I can't change those numbers.  

What am I doing wrong?  

Thanks!!
