### ISSUE TITLE
Elastalert - multiple query for one field in the same index

### ISSUE THREAD

**Issue by breetty** [Yelp/elastalert#1711]
Hi,

We have configured elastalert as a service and we need to query the same field in the same index for multiple queries. We have tried with two different cases like below:

Case 1:
======
rule1.yaml
----------
```
filter:
- query:
    query_string:
      query: "field: value1 text"
```
rule2.yaml
----------
```
filter:
- query:
    query_string:
      query: "field: value2 text"
```
Case 2:
====
rule3.yaml
-----------
```
filter:
- query:
    query_string:
      query: "field: value1 text OR \"value2 text\""
```
Issue 1: The problem with Case 1 rule is we are getting alert triggered for both rules with some random message. We are not getting the exact log message in the alert.
Issue 2: The problem with Case 2 rule is we are getting alert triggered correctly when we input the logs but again  with some random message. We are not getting the exact log message in the alert.
Issue 3: Elastalert is scanning the full index from beginning and re-triggering all the alerts again.

Please let us know if you can throw some insight into this or How we can query same field for different queries?

Thanks and Regards,
Breetty
