### ISSUE TITLE
Insert fields from the index we're scanning

### ISSUE THREAD

**Issue by KevinTrejo11** [Yelp/elastalert#1714]
This is my rule:

```
_host: [HOST]
es_port: [PORT]
name: Happy alert
type: any
index: happy-index-*
filter:
   query:
      query_string:
        query: "happy_field.now: /.*word.*/"
```

All the matches from elastalert are written in the "elastalert_status" index 

Now:
My happy-index-* has a field call "name" 
Is it a way to add that field's value into another field in the "elastalert_status" index?
Do I have to modify the mapping?

Can I manipulate that value within the rule?
So I can have something like this:
`name: value_from_happy-index-*`

I want to do this so the elastalert_status index'd have a filed like this:
`new_field: value_from_happy-index-*`

Thanks! 😄
