### ISSUE TITLE
how to use filter in alert_text_args

### ISSUE THREAD

**Issue by mikeweiwei** [Yelp/elastalert#1734]
for example ：
```
    name: admin_test1111
    type: frequency
    owner: admin
    description: 2018-06-11 16:38:53
    index: logstash-*
    num_events: 1
    is_enabled: true
    timeframe:
      minutes: 60
    filter:
    - query:
        query_string:
          query: 'kubernetes.labels.name: hello'
    - query:
        query_string:
          query: 'kubernetes.namespace_name: admin'
    - query:
        wildcard:
          log: '*Listening*'
    alert:
    - email
    smtp_host: smtp.exmail.qq.com
    smtp_port: 465
    smtp_ssl: true
    from_addr: 
    smtp_auth_file: /opt/config/email_config.yaml
    email:
    alert_text_args:
    - name
    - kubernetes.labels.name
    - filter
    - num_hits
```
**question**：if i want user “the filter query wildcard log” in alert_text_args ，

alert_text_args:
    - filter[2].query.wildcard.log ??????????

**Comment by Qmando** [comment]
This is not supported right now. You'll have to either duplicate the text in the alert definition or, if you want it slightly more standardized, you could perhaps use YAML anchors.

**Comment by mikeweiwei** [comment]
For the above configuration, can you give an example？

**Comment by Qmando** [comment]
It's a bit convoluted, but this would let you have only a single place where a query is defined.
```
filter:
 - query:
        query_string:
          query: &query1 'kubernetes.labels.name: hello'
query1: *query1
alert_text: "You queried for {}"
alert_text_args: [query1]
```
