### ISSUE TITLE
Issue with Frequency Alter (Most likely User Error)

### ISSUE THREAD

**Issue by runtman** [Yelp/elastalert#1740]
Hello, I am trying to alert when our syslog index reaches 1000 documents from a single host in a single hour: 

This is my alert:

```
# Check a single host for over 1000 syslog messages in an hour
name: Spamming Syslog Messages (1 Hour) - Warning
filter:
  - term:
      source: /var/log/syslog
type: frequency
num_events: 1000
timeframe:
  hours: 1
query_key: beat.hostname

# (Required)
# Index to search, wildcard supported
index: system-logs-*

terms_window_size:
  days: 1

# (Required)
# The alert is use when a match is found
alert:
- "email"
- "slack"

# Alert Content Settings
alert_text: "We have detected a host spamming to syslog (1000 messages in an hour)\n\n
  Host: {0}\n\n
  Number Of Logs: {1}\n"
alert_text_type: alert_text_only
alert_text_args: ["host", "num_hits"]
include: ["@timestamp", "host", "num_hits"]

# Email Settings
email:
  - "x"
email_reply_to: "alerts"
from_addr: "alerts"

# Slack Settings
slack_webhook_url: "x"
slack_username_override: "Elastic-Search Alerts"
slack_emoji_override: ':spam:'
slack_msg_color: 'warning'
```

If I change this value to `10` for example I should get roughly 50 alerts, but I only get 2-3 and the "number of logs" is not accurate to a search I am running in ElasticSearch so I somewhat feel like it's not matching on hostname.

Here is an example doc:

```
{
  "_index": "system-logs-2018.06.14",
  "_type": "log",
  "_id": "4gGf_WMB5xbo51VQnp0c",
  "_score": 1,
  "_source": {
    "syslog_pid": "1410",
    "syslog_severity_code": 5,
    "offset": 81538,
    "syslog_facility": "user-level",
    "input_type": "log",
    "syslog_facility_code": 1,
    "source": "/var/log/syslog",
    "syslog_program": "postfix/local",
    "message": "Jun 14 09:23:17 x postfix/local[1410]: warning: hash:/etc/aliases: lookup of 'root' failed",
    "type": "log",
    "syslog_message": "warning: hash:/etc/aliases: lookup of 'root' failed",
    "syslog_severity": "notice",
    "tags": [
      "syslog",
      "beats_input_codec_plain_applied"
    ],
    "received_from": "x",
    "@timestamp": "2018-06-14T09:23:17.000Z",
    "syslog_hostname": "x",
    "syslog_timestamp": "Jun 14 09:23:17",
    "received_at": "2018-06-14T09:23:21.240Z",
    "@version": "1",
    "beat": {
      "hostname": "x",
      "name": "x",
      "version": "5.5.0"
    },
    "host": "x",
    "fields": {
      "log_type": "syslog",
      "environment": "x",
      "alert_email": "x",
      "source": "x",
      "environment_type": "production"
    }
  },
  "fields": {
    "@timestamp": [
      "2018-06-14T09:23:17.000Z"
    ]
  }
}
```

Am I making an obvious error here?
