### ISSUE TITLE
Question with query_key

### ISSUE THREAD

**Issue by lanzehao** [Yelp/elastalert#1757]
Hi member, I met a question in using query_key.

An example:
I have two service named `buy apple` and `buy banana`
When any service received more than 20 "400" or "500" errors, I want an alert, then I have:
```
name: sell fruit statuscode error

type: frequency

index: myindex

num_events: 20

timeframe:
  minutes: 5
  
query_key: service

filter:
- range:
    response:
        from: 400
		
alert:
- "email"

email:
- "myemail@email.com"

alert_text_type: alert_text_only

alert_text: |
    service: {}
    time range: {:%Y-%m-%d %H:%M:%S} to {:%Y-%m-%d %H:%M:%S}
    query: {}
    num_events: {}
	event_occured: {}

alert_text_args:
    - service
    - original_starttime
    - endtime
    - filter
    - num_events
    - num_hits/num_match
```

I use `query_key` to get alert independently for 'apple' or 'orange'
I want to get `event_occured` for 'apple' or 'orange' alone, too.
Unfortunately I can only find 2 useful number args in _alerts.rule or _alerts.match: `num_matches` and `num_hits`.

num_hits is the total hits of all querys, including  both `apple` and `banana`, how can I get the hits for 'apple' alone?
