### ISSUE TITLE
Flatline with query_key does not iterate over it

### ISSUE THREAD

**Issue by hugomcfonseca** [Yelp/elastalert#1758]
Hello, I have the following rule to check if two events are being done every day. 
Every time I get an alert, it sends a message to Slack that identifies a given **key_name**. However, I am able to get this value in Slack message (and also in OpsGenie, that is not present in this rule configuration), and it shows me a placeholder **<MISSING_VALUE>** instead. 

I am trying to understand if it is a problem on my rule or it is a bug of flatline with query_key.

```
name: RULE_ID

# Override buffer_time
buffer_time:
    hours: 24

# Uncomment it only after ElastAlert supports multi run_every by rule
# Follow up https://github.com/Yelp/elastalert/pull/1298
# run_every:
#     hours: 24

# Ignore repeated for a given amount of time (by query_key unique value)
realert:
    hours: 12

# ES index to get data from
index: logstash-%Y.%m.%d-cron-live
use_strftime_index: True

# Configuration of alert type
type: flatline

# Alert when this many documents are not matched
threshold: 2

# Time period which must contain a given number of matched documents
timeframe:
    hours: 24

use_count_query: false

# Evaluates threshold limit to each combination of these fields
query_key:
    - key_name

# Limit values to the documents returned by filter
filter:
- term:
    source: "logfile.log"
- terms:
    message: ["starting", "ending"]

# List and configurations of each alert output
alert:
- "slack":
    slack_webhook_url: <WEBHOOK_URL>
    slack_username_override: 'Elastic Alerts'
    slack_channel_override: '#tests'
    slack_msg_color: warning
alert_text: |
    I got the following key: {0}
alert_text_args:
    - key_name
alert_text_type: exclude_fields
```
