### ISSUE TITLE
Rule only work manually

### ISSUE THREAD

**Issue by w0rk3r** [Yelp/elastalert#1759]
Hey, i'm having some issues with this specific rule, that is only sending alerts when i do it manually with elastalert-test-rule --alert, i have already tried realert: 0 , change the timeframe, etc..
```
es_host:` 10.1.0.101
es_port: 9200
name: Globalprotect Brute-force
type: frequency
index: agility-*
num_events: 1
timeframe:
  minutes: 5
filter:
- query:
    query_string:
      query: "Reason:\"User is not in allowlist\""

alert_text: "Alert: Multiple auth fails from the user {0}, coming from the IP {1}, with the following reason {2}"
alert_text_type: alert_text_only
alert_text_args: ["data.dstusr","data.srcip","Reason"]

alert:
- "telegram"

telegram_bot_token: 564447464:AAHuyefvrfytveryuyf3sE0JYr7iGPmixJFPws

telegram_room_id: "@example1234"
```
![image](https://user-images.githubusercontent.com/26856693/41727258-477f7f2e-754a-11e8-9da5-a4e12944ea5f.png)
![image](https://user-images.githubusercontent.com/26856693/41727348-84954772-754a-11e8-85da-a12946d0ee00.png)
