### ISSUE TITLE
Difference between num_hits and num_matches

### ISSUE THREAD

**Issue by Amruth007** [Yelp/elastalert#1765]
Hi,

I am using,
```
type: frequency
num_events: 20
filter:
- query:
    query_string:
         query: 'some query'
```

When the alert is triggered I could see 
```
num_hits: 0
num_matches: 1
```
I am confused with num_hits and num_matches. If there are 0 hits how can there be 1 match?
