### ISSUE TITLE
Threshold rule false positive

### ISSUE THREAD

**Issue by ManofWax** [Yelp/elastalert#1768]
Hello I've implemented the following rule to monitor for no data on a specific index:

```
name: No data on index streamparse
type: flatline
index: streamparse-*
threshold: 1
timeframe:
    minutes: 60
realert:
    hours: 3
use_count_query: true
doc_type: "doc"
alert:
- "stomp"
stomp_hostname: rabbitmq
stomp_hostport: 61613
stomp_login: "guest"
stomp_password: "guest"
```
I got a lot of false positives, for example I got the following alert:
```
An abnormally low number of events occurred around 2018-06-27 11:41 UTC. Between 2018-06-27 10:41 UTC and 2018-06-27 11:41 UTC, there were less than 1 events. @timestamp: 2018-06-27T11:41:17.716208Z count: 0 key: all num_hits: 0 num_matches: 4
```
And then I query elasticsearch manually:

```
GET streamparse-2018.06/_count
{
    "query": {
        "range" : {
            "@timestamp" : {
                "gte": "2018-06-27T10:41:17.716208Z",
                "lte": "2018-06-27T11:41:17.716208Z"
            }
        }
    }
}
```

And I got the following result:

```
{
  "count": 372,
  "_shards": {
    "total": 1,
    "successful": 1,
    "skipped": 0,
    "failed": 0
  }
}
```

This happens a couple of time a day. Is there something wrong on my elastalert alert?
