### ISSUE TITLE
Basic New_Term Rule for newb

### ISSUE THREAD

**Issue by senatorhotchkiss** [Yelp/elastalert#1770]
Trying to accomplish a very simple task. Show SHA256 checksum value of executed files, which has not been seen before. 

But I am flooded with alerts by already existing SHA256 values. It's not working as expected.
What am I doing wrong?

```
name: New Process Detected
type: new_term
index: "*:logstash-*"
fields:
 - "sha256"
terms_window_size:
  days: 90
filter:
- term:
    event_type: "sysmon"
alert:
#- "debug"
- "email"
# Email options
alert_subject: "New Process Found!"
email:
- "someguy@domain.com"
smtp_host: "myserver"
smtp_port: 25
from_addr: "elastalert@domain.com"
```
