### ISSUE TITLE
Poor documentation for multiple alerters

### ISSUE THREAD

**Issue by laalot** [Yelp/elastalert#1779]
This may fall under the remit of my lacking yaml knowledge but, I had a bit of trouble getting a single rule to fire alerts down multiple channels.

I eventually worked out the syntax had to be as follows;
```
alert:
- alerttype:
    alerttypeparam: {{ param }}
- alerttype:
    alerttypeparam: {{ param }}
```
Again - this may just be an issue revolving around my limited knowledge of yaml, but I think the docs could benefit from detailing a case such as this.
