### ISSUE TITLE
What is the best : regexp our wildcard+or

### ISSUE THREAD

**Issue by CdeNag** [Yelp/elastalert#1781]
Hello

I am a new Elastalert user.
What is the most performant request : one regexp or 2 wildcards wih or: ?
```
name: Mon1
type: any
index: Idx1
filter:
- query:
    query_string:
       query: "syslog_message: alarm AND syslog_message: error"
- regexp:
       syslog_message.keyword: ".*ALARM.*(CRITICAL|SEVER).*"
```

```
name: Mon1
type: any
index: Idx1
filter:
- query:
    query_string:
       query: "syslog_message: alarm AND syslog_message: error"
-or:
    - query:
        wildcard:
            syslog_message.keyword: "*ALARM*CRITICAL*"
    - query:
        wildcard:
            syslog_message.keyword: "*ALARM*SEVER*"
```

**Comment by Qmando** [comment]
If you are worried about performance, i'd probably try avoid a leading wildcard. You might want to try using the string analysis to your advantage:

```
filter:
- query:
    query_string:
      query: "alarm AND error AND (critical OR severe)"
      default_field: syslog_message
```

Back to your original questions though, I have no idea what is more performant, regex or wildcard. I'd guess they have the same underlying implementation.
