### ISSUE TITLE
Combining range and negation in filter

### ISSUE THREAD

**Issue by vanushah** [Yelp/elastalert#1788]
I have simple "any" rule, and I'm trying to combine range and not in filter. Like this:

```
filter:
- query:
    and:
      range:
        timestamp:
          gte: now-1m
      not:
        term:
          http.response.status: 200

```
But I'm getting this error in log of Elastalert
```
ERROR:root:Error running query: TransportError(400, u'parsing_exception', u'no [query] registered for [and]'
```
So I'm guessing: am I doing something wrong or is a bug?

**Comment by Qmando** [comment]
Use
```
filter:
 - not:
      term:
        http.response.status: 200
```
or
```
filter:
 - query_string:
      query: "NOT http.response.status: 200"
```

You shouldn't put timestamp into the filter, elastalert handles that for you.
