### ISSUE TITLE
elastalert sending alert for "info level also"

### ISSUE THREAD

**Issue by samratbe** [Yelp/elastalert#1801]
i have configured elastalert to send alert for log level error. but is sending alert for log level "ERROR" also.

here is my elastalert configuration.

```
es_host: vpc-XXXXXXXXXXXXXXXX.es.amazonaws.com
es_port: 443
name: XXXXXXXXXXXXXXX
type: frequency
index: "XXXXXXXXXXXXXXX"
num_events: 10

timeframe:
    minutes: 5

filter:
- query:
    query_string:
      query: "exception_message: 400 Bad Request"

alert:
- "email"
email: 
 XXXXXXXXXXX
```
