### ISSUE TITLE
How do you make a rule that sends an alert when there is, for example, only 80% disk space left? Low disk space rule 

### ISSUE THREAD

**Issue by rokstar1254** [Yelp/elastalert#1807]

**Comment by Qmando** [comment]
Assuming it's a numeric field called disk_used:
```
name: something
type: any
index: something
filter:
 - range:
      disk_used:
        gt: .8
alert:
 - something
```

**Comment by itsecureadmin** [comment]
I have two rules defined for disk space (and two for inode usage).  Warning on 75-84% and critical on 85%+ - this is the warning rule:

```
filter:
-query
  - query_string:
      query: "type:metricsets AND system.filesystem.used.pct:[0.75 TO 0.84]"

query_delay:
  minutes: 1
query_key: host
```

The critical rule is:

```
filter:
-query
  - query_string:
      query: "type:metricsets AND system.filesystem.used.pct:[0.85 TO 1.0]"

query_delay:
  minutes: 1
query_key: host
```

It's important to use query_key so that each host can be alerted on.

I use query_delay since indexing is delayed on ElasticSearch.

**Comment by pingwang** [comment]
> I have two rules defined for disk space (and two for inode usage). Warning on 75-84% and critical on 85%+ - this is the warning rule:
> 
> ```
> filter:
> -query
>   - query_string:
>       query: "type:metricsets AND system.filesystem.used.pct:[0.75 TO 0.84]"
> 
> query_delay:
>   minutes: 1
> query_key: host
> ```
> The critical rule is:
> 
> ```
> filter:
> -query
>   - query_string:
>       query: "type:metricsets AND system.filesystem.used.pct:[0.85 TO 1.0]"
> 
> query_delay:
>   minutes: 1
> query_key: host
> ```
> It's important to use query_key so that each host can be alerted on.
> 
> I use query_delay since indexing is delayed on ElasticSearch.

do we need to specify index: something?
or query: "type:metricsets AND system.filesystem.used.pct:[0.85 TO 1.0]" is enough?

**Comment by Qmando** [comment]
You *always* need to specify an index. Everything in Elasticsearch has an index.

**Comment by itsecureadmin** [comment]
Yes, a more complete example might be the following, which also includes the index, alert information, and a higher threshold for larger disks:

```
es_host: $es_host

es_port: 80
aws_region: $es_region

name: "$ea_hostname:  CRITICAL : Disk Usage Alert"
index: $es_index

type: any 

realert:
  minutes: 15

filter:
- query:
  - query_string:
      query: "type:metricsets"
- query:
  - query_string:
      query: "(system.filesystem.used.pct:[0.85 TO 1.0] AND system.filesystem.total: <2000000000001) OR (system.filesystem.used.pct:[0.95 TO 1.0] AND system.filesystem.total: >2000000000000)"

query_delay:
  minutes: 1
query_key: host

alert_text_type: alert_text_only
include : ["host","system.filesystem.used.pct","system.filesystem.mount_point"]

alert:
- "slack"
alert_text: "
*Used %*        : {0}\n
*Mount Point*   : {2}\n
*Host*          : {1}\n
*ElastAlert Node*  : $ea_hostname"

alert_text_args: ["system.filesystem.used.pct","host","system.filesystem.mount_point"]

slack_webhook_url: $slack_channel_url
slack_emoji_override: ":heavy_exclamation_mark:"
```
