### ISSUE TITLE
Duplicate Rules alert - when using rules_folder

### ISSUE THREAD

**Issue by billiaz** [Yelp/elastalert#1832]
I am getting this error when I use the rules_folder with only one rule:

```
elastalert-758d66fbc5-lbsgs › elastalert
elastalert-758d66fbc5-lbsgs elastalert Traceback (most recent call last):
elastalert-758d66fbc5-lbsgs elastalert   File "/usr/bin/elastalert", line 11, in <module>
elastalert-758d66fbc5-lbsgs elastalert     load_entry_point('elastalert==0.1.33', 'console_scripts', 'elastalert')()
elastalert-758d66fbc5-lbsgs elastalert   File "/usr/lib/python2.7/site-packages/elastalert/elastalert.py", line 1897, in main
elastalert-758d66fbc5-lbsgs elastalert     client = ElastAlerter(args)
elastalert-758d66fbc5-lbsgs elastalert   File "/usr/lib/python2.7/site-packages/elastalert/elastalert.py", line 130, in __init__
elastalert-758d66fbc5-lbsgs elastalert     self.conf = load_rules(self.args)
elastalert-758d66fbc5-lbsgs elastalert   File "/usr/lib/python2.7/site-packages/elastalert/config.py", line 485, in load_rules
elastalert-758d66fbc5-lbsgs elastalert     raise EAException('Error loading file %s: %s' % (rule_file, e))
elastalert-758d66fbc5-lbsgs elastalert elastalert.util.EAException: Error loading file /etc/elastalert/rules.d/..2018_07_27_19_02_08.758794168/alert1.yaml: Duplicate rule named Login Va

```

My config is:
```
rules_folder: /etc/elastalert/rules.d
run_every:
  minutes: 5

buffer_time:
  minutes: 15
writeback_index: elastalert_status

alert_time_limit:
  days: 2
```
And my rule
```
name: "Login V"
type: any
index: logstash-*
filter:
- term:
    host: "mail.dddd"
    user: "va"
    action: "Login"
alert:
- "email"

alert_text: "User {0} loggedin on {1} using imap at {2{"
alert_text_type: alert_text_only
alert_text_args: ["user", "host", "@timestamp"]

email_from_field: "ElasticAlert"
email_add_domain: "@kub."
pipe_alert_text: true

email:
- "mail"
```
