### ISSUE TITLE
QUESTION: Alerted when a user loggins, even if he does it every 2 minutes.

### ISSUE THREAD

**Issue by billiaz** [Yelp/elastalert#1833]
I have this rule, which is executed only once the moment the alert manager starts.

I want to be able to be alerted for every different user logins with imap (this in the future will be alert me if anybody adds any user to admin group). Now I am testing with it
Is there any way to add at type: any repetition of this or another type can do the trick?

```
name: "Login V"
type: any
index: logstash-*
filter:
- term:
    user: "user@user.com"
- term:
    action: "Login"
alert:
- "email"

alert_text: "User {0} loggedin on {1} using imap at {2}"
alert_text_type: alert_text_only
alert_text_args: ["user", "host", "@timestamp"]
email_from_field: "ElasticAlert"
email_add_domain: "@.net"
pipe_alert_text: true

email:
- "user@email.com"
```
