### ISSUE TITLE
regex with query_string

### ISSUE THREAD

**Issue by dabougie** [Yelp/elastalert#1835]
We're having trouble matching the following rule with a regex.  We're happy to use either a dedicated regexp filter, or embed a regex in a query_string filter.

Here is an example log:
```
{
  "_index": "logstash-2018.07.27",
  "_type": "doc",
  "_id": "Cy9K3WQBxKeqlnIcMZ3S",
  "_version": 1,
  "_score": null,
  "_source": {
    "message": " fence lnx902-p14 success",
    "procid": "32139",
    "@version": "1",
    "severity": "err",
    "type": "rsyslog",
    "@timestamp": "2018-07-27T19:49:44.000Z",
    "facility": "local4",
    "host": "127.0.0.1",
    "sysloghost": "lnx901",
    "programname": "fence_node"
  },
  "fields": {
    "@timestamp": [
      "2018-07-27T19:49:44.000Z"
    ]
  },
  "highlight": {
    "message": [
      "@kibana-highlighted-field@fence@/kibana-highlighted-field@ @kibana-highlighted-field@lnx902@/kibana-highlighted-field@-p14 success"
    ]
  },
  "sort": [
    1532720984000
  ]
}

```

And here is an example of one rule we've tried:
```
name: fence_node 
type: any
index: logstash-*
filter:
- query:
    query_string:
      query: "programname:fence_node AND message:\"/fence.*success/\""
query_key: [message]
realert:
  hours: 1
```

Any suggestions for a correct regex match would be greatly appreciated.
