### ISSUE TITLE
Elastalert for multiple queries

### ISSUE THREAD

**Issue by abdur03** [Yelp/elastalert#1848]
Hi,

Need to configure the elastalert if i found any of the below sentences on my messages from Kibana dashboard

- out of memory
- Writing text to file from position
- rows using load data from jdbc

Please find my elastalert rule which i have configured
```
es_host: localhost
es_port: 9200
name: String - Test
type: frequency
index: filebeat-*
num_events: 50
timeframe:
    minutes: 1
filter:
- query:
    query_string:
      query: "Writing text to file from position OR rows using load data from jdbc OR out of memory"
      default_field: message
```
But for the above rule im getting an alert for all messages

Please do let me know exact rule for the same
