### ISSUE TITLE
Add if statement to rule file

### ISSUE THREAD

**Issue by AxelMonroyX** [Yelp/elastalert#1909]
Is posible to add if statements?

Something similar to this example
```yaml
alert_subject_args:
  - field_name
alert_text_args:
  - field_name

alert_subject: "{{ if {0} }}  This happen {0} {{else}} something happen {{ end }}"
alert_text: "{{ if {0} }}  This happen {0} {{else}} something happen {{ end }}"

```

**Comment by AxelMonroyX** [comment]
Hi @Qmando any idea about this ?

**Comment by Qmando** [comment]
You can set `alert_missing_value` to change the default value, instead of "MISSING VALUE".

Other than that, you'll need to use an enhancement to achieve this. https://elastalert.readthedocs.io/en/latest/recipes/adding_enhancements.html

**Comment by nikhilgangrade** [comment]
@AxelMonroyX did you find any solution for this?

**Comment by AxelMonroyX** [comment]
> @AxelMonroyX did you find any solution for this?

I end up using 3 different files to handle this 
```yaml
# SWITCH CASE


# 1rs case
name: Rule 1 case 1
filter:
- query_string:
     query: "field_name:\"value\" AND field_name_2:\"value2\""

# 2nd case
name: Rule 2 case 2
filter:
- query_string:
     query: "field_name:\"value\" AND field_name_3:\"value3\""

# Default
name: Rule 3 Default
filter:
- query_string:
     query: "field_name:\"value\" AND NOT field_name_2:\"value2\" AND NOT field_name_3:\"value3\""
```
