### ISSUE TITLE
How to resolve 'ERROR:root:Error while running alert email: Error connecting to SMTP host: [Errno 10061] No connection could be made because the target machine actively refused it'?

### ISSUE THREAD

**Issue by venkateshrepal** [Yelp/elastalert#1914]
Hi, 
I am creating an application where I need to send mail for some particular logs.
Here is my rule file: 
```
es_host: localhost
es_port: 9200
name: Log Level Test
type: frequency
index: testindexv4
num_events: 1
timeframe:
   hours: 4
filter:
 - term:
     log_level.keyword: "ERROR"
 - query:
     query_string:
       query: "log_level.keyword: ERROR"
alert:
- "email"
email:
- "testmails8087@gmail.com"

```

Here is the config.yaml

```
rules_folder: myrules
run_every:
  seconds: 2
buffer_time:
  seconds: 10
es_host: localhost
es_port: 9200
writeback_index: elastalert_status
alert_time_limit:
  days: 2
```

Here is smpt_auth.yaml

```
alert:
 - email
email:
 - "testmails8087@gmail.com"
smtp_host: "smtp.gmail.com" 
smtp_port: 587 
smtp_ssl: true
from_addr: "testmails8087@gmail.com"
smtp_auth_file: 'D:\ELK_Info\ElastAlert\elastalert-master\smtp_auth_user.yaml'
```

Here is smtp_auth_user.yaml

```
alert:
 - email
email:
 - "testmails8087@gmail.com"
smtp_host: "smtp.gmail.com" 
smtp_port: 587 
smtp_ssl: true
from_addr: "testmails8087@gmail.com"
smtp_auth_file: 'D:\ELK_Info\ElastAlert\elastalert-master\smtp_auth_user.yaml'
```

When I run this command:
### `python -m elastalert.elastalert --verbose --rule myrules\myrule.yaml
`
I get error as: 
ERROR:root:Error while running alert email: Error connecting to SMTP host: [Errno 10061] No connection could be made because the target machine actively refused it.

I get this error if I disable my symantec protection. If I keep it enable, I get another error as: 

**`ERROR:root:Error while running alert email: Error connecting to SMTP host: [Errno 10013] An attempt was made to access a socket in a way forbidden by its access permissions`**

Any idea on how to resolve the same please?

**Comment by Qmando** [comment]
Sounds like a firewall issue.

**Comment by venkateshrepal** [comment]
@Qmando  
Can you please elaborate more?

**Comment by Qmando** [comment]
I just googled the error. https://stackoverflow.com/a/1082251 looks similar

**Comment by venkateshrepal** [comment]
@Qmando  Yes it gave me a cause of problem, but not the solution. Can you please let me know how we can access port 465 for elastalert for mail alert application?

**Comment by nsano-rururu** [comment]
Launch a web browser on the terminal running ElastAlert, access the Google settings screen, go to the Google account → App that can access the account → Allow less secure apps: Disable → Change to enable. When I specified the Gmail address with from_addr and confirmed the operation, it worked normally.

![1](https://user-images.githubusercontent.com/22293449/99171276-fbc53280-274a-11eb-8380-af4ac6b8f04a.PNG)
![2](https://user-images.githubusercontent.com/22293449/99171279-fe278c80-274a-11eb-9f0f-3914d9f9a93d.PNG)
![キャプチャ](https://user-images.githubusercontent.com/22293449/99171281-0089e680-274b-11eb-99b4-deda85900d82.PNG)

**smtp_port: 587**

```yaml
smtp_host: "smtp.gmail.com" 
smtp_port: 587 
smtp_ssl: false
smtp_auth_file: '/opt/elastalert/smtp/smtp_auth_user.yaml"
```

smtp_auth_user.yaml

```yaml
user: xxx@gmail
password: xxx
```
