### ISSUE TITLE
Referencing to timeframe.minutes in alert_text

### ISSUE THREAD

**Issue by lucasalvarezlacasa** [Yelp/elastalert#1916]
Hello everybody!. Is there a way to print out the timeframe interval (in minutes) in the alert_text section?
This is what I've done:

```
num_events: 1
timeframe:
  minutes: 15
realert:
  minutes: 15

...

alert_text:
 "We found {0} logs classified as '{1}' in the last {2} minutes for this client. 
  Message: {3}"
alert_text_args:
- num_events
- classification
- timeframe
- message
```
However, this prints it in the following format: hh:mm:ss. I would like to get the int value corresponding to the minutes I defined before.

I tried by putting timeframe.minutes in the alert_text_args section but it didn't work.

Any help would be strongly appreciated!. Thank you!.

**Comment by Qmando** [comment]
You need to either 
- Hardcode it
- Add an enhancement, which is way overkill

**Comment by lucasalvarezlacasa** [comment]
What you mean by hardcode it? I'm using "timeframe.minutes" inside of the "alert_text_messages" block but the alarms never gets sent.

**Comment by lucasalvarezlacasa** [comment]
This is what I'm trying:
```
num_events: 1
timeframe:
  minutes: 15
realert:
  minutes: 15

...

alert_text:
 "We found {0} logs classified as '{1}' in the last {2} minutes for this client. 
  Message: {3}"
alert_text_args:
- num_events
- classification
- timeframe.minutes
- message
```
