### ISSUE TITLE
Delay builds up over time due to long queries?

### ISSUE THREAD

**Issue by SpencerMalone** [Yelp/elastalert#1938]
Today I noticed that some of my alerting seemed to be running ~15-20 minutes behind. After digging in, sure enough, my events looked like this:
```
timestamp: October 1st 2018, 23:30:08.243
endtime: October 1st 2018, 23:12:20.534
starttime: September 28th 2018, 23:12:20.534
```
Even for shorter query sizes, and even though the time taken was ~1-2 seconds for these longer rules.

After digging around for a while, I realized that my rules were being delayed by the time taken to run the rules before. We had a harsh spike of lag in the middle of today that caused the following:

Event before the lag spike:
```
timestamp: October 1st 2018, 14:05:05.750
starttime: September 28th 2018, 14:02:20.534
endtime: October 1st 2018, 14:02:20.534
time_taken: 0.801
```

The rule run during:
```
timestamp: October 1st 2018, 14:08:58.099
starttime: September 28th 2018, 14:03:20.534
endtime: October 1st 2018, 14:03:20.534
time_taken: 172.903
```

The rule run after:
```
timestamp: October 1st 2018, 14:09:03.173
starttime: September 28th 2018, 14:04:20.534
endtime: October 1st 2018, 14:04:20.534
time_taken: 1.283
```

So, before the lag spike, there was a delay of 3 minutes
After the rule took 2 minutes to run, from that point on there was a delay of 5 minutes between when the rule was running, and the time period it was querying.

This case was extreme, but over time this is building up on some of our other elastalert instances. What's going on here?

My rule definitions are all aprox the following, with timeframe, buffer_time, realert, and percentage all tweaked for various windows:

```
name: Jenkins 1 hour SLO alert
index: nginx:nginx-*
es_host: <redacted>
es_port: 9200
timeframe:
  hours: 1
buffer_time:
  hours: 1
realert:
  minutes: 10
allow_buffer_time_overlap: true
type: percentage_match
max_percentage: 2.88
filter:
  - query:
      query_string:
        # This should match all requests that you want to filter by
        query: 'vhost:"<vhost redacted for privacy>"'
match_bucket_filter:
  - query_string:
      # This is a subset of the requests that is erroring. We're choosing only to regard 5XXs as errors, not 4XXs
      query: "status_major:5xx"
alert: slack
alert_text_type: "alert_text_only"
# Be sure to update this to match your service!
alert_text: |
  {0:.2f}% of Jenkins requests in the last {1} have error'd. You will burn through your SLO within 4.5 hours.
alert_text_args:
  - "percentage"
  - "timeframe"
slack_username_override: "Jenkins ElastAlert"
slack_webhook_url: <redacted>
slack_msg_color: "warning"
```
