### ISSUE TITLE
Wildcard Windows directories in queries/terms not working

### ISSUE THREAD

**Issue by josephbleroy** [Yelp/elastalert#1960]
I'm working on writing some security specific queries. So far I've been able to get some wildcard queries working properly, such as:

```
# WORKS
# https://raw.githubusercontent.com/Neo23x0/sigma/master/rules/windows/sysmon/sysmon_outlook_shell.yml
filter:
- query:
   query_string:
      query: "(event_data.ParentImage:*OUTLOOK.EXE) AND (event_data.Image:*cmd.exe OR event_data.Image:*powershell.exe OR event_data.Image:*wscript.exe OR event_data.Image:*cscript.exe OR event_data.Image:*sh.exe OR event_data.Image:*bash.exe OR event_data.Image:*schtasks.exe)"
```

But I would like to focus on writing a query that includes Windows directories, using the following logic:

```
- query:
   query_string:
      query: "(event_id:1) AND (event_data.Image:C:\Intel\Logs\* OR event_data.Image:C:\Users\Default\*)"
```

So far nothing is working. This is likely due to my limited experience with Elasticsearch DSL, not ElastAlert itself. 

Any guidance or direction is greatly appreciated!

Thank you.

**Comment by prashanttct07** [comment]
Try match query instead of querystring

**Comment by josephbleroy** [comment]
I wasn't able to get the query syntax working correctly, however I did get it sort of working by using the following syntax:

```
filter:
- term:
      event_id: "1"
- wildcard:
       event_data.Image: '\C:\\Intel\\Logs\\*'
```

However, I'd like to setup multiple wildcards using **OR logic** so that whenever something is executed from any of the directories an alert will be sent:

```
filter:
- term:
      event_id: "1"
- wildcard:
       event_data.Image: '\C:\\Intel\\Logs\\*'
       event_data.Image: '\C:\\Windows\\Fonts\\*'
       event_data.Image: '\C:\\Windows\\Debug\\*'
```

Any ideas?

**Comment by Qmando** [comment]
https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-query-string-query.html

```
filter:
- term:
     event_id: "1"
 - query_string:
      query: "\"C/Intel/Logs\" OR \"C/Windows/Debug\" OR \"C/Windows/Fonts\""
      default_field: event_data.Image
```
