### ISSUE TITLE
Debugging metric aggregation

### ISSUE THREAD

**Issue by Yv-o-rL** [Yelp/elastalert#1974]
Hi!

I've an issue with a `sum` metric aggregation. My goal is to alert when a specific threshold is exceeded over a 24 hour period.

_config.yaml_:
```
run_every:
  minutes: 5
buffer_time:
  minutes: 10
```

_metric_aggregation_test.yaml_:
```
type: metric_aggregation
metric_agg_key: bytes
metric_agg_type: sum
#Alerting treshold set to 100GB
max_threshold: 100000000000
doc_type: doc
buffer_time:
  hours: 24
query_key: "node.keyword"
aggregation:
  schedule: '5 8 * * *'
summary_table_fields: [node.keyword,bytes_sum]
alert_text_type: aggregation_summary_only
```

My issue is that I don't get the same result when I'm checking the aggregation in Kibana.
I'm not entirely sure what's happening when I'm getting these entries in the `elastalert_stderr.log`.

> INFO:elastalert:Metric aggregation test from 2018-10-24 14:55 UTC to 2018-10-25 11:35 UTC: 0 query hits (0 already seen), 0 matches, 0 alerts sent
>INFO:elastalert:Metric aggregation test from 2018-10-24 14:55 UTC to 2018-10-25 11:40 UTC: 0 query hits (0 already seen), 0 matches, 0 alerts sent
>INFO:elastalert:Metric aggregation test from 2018-10-24 14:55 UTC to 2018-10-25 11:45 UTC: 0 query hits (0 already seen), 0 matches, 0 alerts sent
>INFO:elastalert:Metric aggregation test from 2018-10-24 14:55 UTC to 2018-10-25 11:50 UTC: 0 query hits (0 already seen), 0 matches, 0 alerts sent
>INFO:elastalert:Metric aggregation test from 2018-10-24 14:55 UTC to 2018-10-25 11:55 UTC: 0 query hits (0 already seen), 0 matches, 0 alerts sent
>INFO:elastalert:Metric aggregation test from 2018-10-24 14:55 UTC to 2018-10-25 12:00 UTC: 0 query hits (0 already seen), 0 matches, 0 alerts sent

I get about the half of the actual results I should see. Could you please help me how can I check what's happening? I have couple thousand nodes and need to see why there are missing ones.

Thank you!
Yvorl
