### ISSUE TITLE
Emails contain entries not matching the query 

### ISSUE THREAD

**Issue by yxz900** [Yelp/elastalert#1981]
Hi,

I have a frequency rule like the following:

```
type: frequency
index: index-*
use_strftime_index: true
num_events: 10
timeframe:
  minutes: 1
query_key: user
aggregation:
  hours: 1
filter:
- query:
    query_string:
      query: conditions
alert:
- "email"
alert_subject: subject
alert_text_type: aggregation_summary_only
email:
- my_email
summary_table_fields:
    - user
```

I want to receive an email when there are more than 10 events per minute for a "user". I want to receive information of only the "user"s that match the query. However, in the email I received, there are also entries of "user"s for which there are less than 10 events (see below). What am I missing in my configuration here?

Aggregation resulted in the following data for summary_table_fields ==> ['user', 'count']:
```
+----------+-------+
| user | count |
+==========+=======+
| aaa   | 3     |
+----------+-------+
| bbb   | 6     |
+----------+-------+
| ccc   | 4     |
+----------+-------+
| ddd     | 406   |
+----------+-------+
| eee   | 13    |
+----------+-------+
| fff   | 6     |
```
Thanks for your help!
