### ISSUE TITLE
Accessing match data for flatline rules

### ISSUE THREAD

**Issue by alankis** [Yelp/elastalert#1996]
It is possible to get hostname on which event is matched with the flatline rule? The complete rule is bellow. 

```
Name: Spark Master process missing
type: flatline
index: metricbeat-*

filter:
- query:
    query_string:
      query: "beat.hostname: ip-xx-xx-xx-xx.ec2.internal"

- query:
    query_string:
      query: "system.process.name: java"

- query:
    query_string:
      query: "system.process.cmdline: /*java*/"
      analyze_wildcard: true

- query:
    wildcard:
      system.process.cmdline: "/.*org.apache.spark.deploy.master.Master.*/"

threshold: 1
timeframe:
  #minutes: 5
  seconds: 10

doc_type: metricsets

alert:
  - "slack"
new_style_string_format: true
slack:
slack_webhook_url: "https://hooks.slack.com/services/some/radnomhash"
```
The idea is simple. I am aggregating metrics from multiple hosts, so basically Spark master process only exists on a single machine, thus I am using the beat.hostname as the first filter, then check the process name and finally I am checking the part of cmdline which is specific for Spark master process. The rule as it is now is working, but the problem is that I would like to access the actual hostname of triggered alert. Is that possible with Flatline rule type? 

Running Elastalert in debug mode, shows me only below listed fields as available: 

```
@timestamp: 2018-11-12T14:32:25.985728Z
count: 0
key: all
num_hits: 0
num_matches: 1
```
