### ISSUE TITLE
[Question] num_events can elasticsearch filters be used

### ISSUE THREAD

**Issue by runtman** [Yelp/elastalert#2010]
Hey we use a "num_events: 500" variable to try and identify servers that are spamming, so for example:

```
# Check a single host for over 500 syslog messages in an hour
name: Spamming Syslog Messages (1 Hour) - Warning
filter:
  - term:
      source: /var/log/syslog
type: frequency
num_events: 500
timeframe:
  hours: 1
query_key: beat.hostname

# (Required)
# Index to search, wildcard supported
index: system-logs-*

terms_window_size:
  days: 1

# (Required)
# The alert is use when a match is found
alert:
- "email"
- "slack"
```

I was curious if we can use elasticsearch filters for the `num_events`. For example:

    num_events: filter[term][log_threshold]

Something like that?
