### ISSUE TITLE
Range filter on numeric field

### ISSUE THREAD

**Issue by rangolucas** [Yelp/elastalert#2027]
Elastalert not reporting any alerts using the following rule:

```
name: ERROR within logs
type: any
index: customindex
realert:
  minutes: 0
filter:
- range:
    status_code:
      from: 500
      to: 599
```

Strangely, it won't throw any alerts if I use a blacklist rule using status_code as the query key, but it does work with string fields.
