### ISSUE TITLE
Ignoring <MISSING VALUE>

### ISSUE THREAD

**Issue by DpoBoceka** [Yelp/elastalert#2044]
Hi.
Is there any way to not display in outputs the fields that have no value?

**Comment by Qmando** [comment]
Two options:

1. add `alert_missing_value: ""`. This changes it to show an empty space instead of "MISSING VALUE".

2. Add an `_exists_` query to your filter so that the field always exists.
```
filter:
 - query:
      query_string:
        query: "_exists_: fieldname"
```
