### ISSUE TITLE
elasticsearch dns resolving in kubernetes

### ISSUE THREAD

**Issue by ArpadK** [Yelp/elastalert#2057]
I'm trying to run elastalert in kubernetes but for some reason, it won't connect to elasticsearch:
```Container timezone not modified
ntpd: can't set priority: Permission denied
reset adjtime failed: Operation not permitted
creating new /var/db/ntpd.drift
adjtimex failed: Operation not permitted
wget -q -T 3 -O - http://elasticsearch:tcp://10.99.190.160:9200
Waiting for Elasticsearch...
Waiting for Elasticsearch...
Waiting for Elasticsearch...
Waiting for Elasticsearch...
```
It looks like it doesn't resolve the DNS correctly. The elasticsearch pod does run on 10.99.190.160 but a call to http://elasticsearch:tcp://10.99.190.160:9200 will obviously not work. If I do a nslookup inside of the container it gives the right response:
```
/opt/elastalert # nslookup elasticsearch
nslookup: can't resolve '(null)': Name does not resolve

Name:      elasticsearch
Address 1: 10.99.190.160 elasticsearch.default.svc.cluster.local
```
My elasticalert config looks like this:
```
rules_folder: /opt/rules

run_every:
  seconds: 5

buffer_time:
  minutes: 15

es_host: elasticsearch

es_port: 9200

writeback_index: elastalert_status

alert_time_limit:
  days: 2
```
The elasticsearch kubernetes service is difined liked this:
```
apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
  labels:
    app: elasticsearch
spec:
  ports:
  - port: 9200
    protocol: TCP
    name: http
  - port: 9300
    protocol: TCP
    name: transport
  selector:
    app: elasticsearch
```
I have an Heartbeat container running in the same pod as the elasticallert container and that one connects to elasticsearch without any problem. I also tried running the same containers outside of kubernetes in a docker network and then it also works fine. Does anyone have an idea what is going wrong here?
