### ISSUE TITLE
How to get an alarm when the minimun threshold matches for the servers at the same time ?

### ISSUE THREAD

**Issue by amolkekan** [Yelp/elastalert#2059]
@Qmando 
Please have a look in this issue.

Here is my rule, in this we want alert when the usercount is below 200 for both the servers (prod-smartfox-001 and prod-smartfox-002) at the same timestamp.

```
name: SmartFox USER Count
type: metric_aggregation
index: logstash-*

buffer_time:
  minutes: 1

metric_agg_key: usercount
metric_agg_type: min
query_key: beat.hostname.keyword
doc_type: doc

bucket_interval:
  minutes: 1

sync_bucket_interval: true

min_threshold: 200

filter:
- query:
    query_string:
      query: "(beat.hostname: 'prod-smartfox-001') AND (beat.hostname: 'prod-smartfox-002')"

alert:
- "email"

alert_subject: "MPL Alarm: USER COUNT BELOW 200 ON SMARTFOX SERVERS"
alert_subject_args:
- "beat.hostname.keyword"
- "usercount_min"

alert_text: |
        -------------  ALERT -------------
        TITLE: USER COUNT < 200
        API: {0}
        TIMESTAMP: {1}

alert_text_args: ["beat.hostname.keyword", "@timestamp"]
```

But in elastalert-test-rule the output we get in not for the same time stamp, it gives alert at different time stamp for both servers.
