### ISSUE TITLE
0 hits and False Alert With FlatLine

### ISSUE THREAD

**Issue by mukeshchouhan** [Yelp/elastalert#2060]
My index has around 16lacs docs in 30 mins but my flatline rule is sending false alert-
```
name: test_rule
type: flatline

index: test_index

timestamp_field: "timestamp"
timestamp_type: "unix_ms"
#use_term_query: true
#use_count_query: true

timeframe:
  minutes: 30
threshold: 1
  
doc_type: _doc

realert: 
  minutes: 30
    
alert:
- "slack"

slack_webhook_url:
- https://hooks.slack.com/services/xxxxxxxx

```

Alert-

```
An abnormally low number of events occurred around 2019-01-04 13:15 UTC.
Between 2019-01-04 12:45 UTC and 2019-01-04 13:15 UTC, there were less than 1 events.

count: 0
key: all
num_hits: 0
num_matches: 8
timestamp: 2019-01-04T13:15:50.237531Z
```
