### ISSUE TITLE
Alert Generate on file

### ISSUE THREAD

**Issue by ankit22550** [Yelp/elastalert#2074]
Hello Team,

I want to Generate Alert file on a daily basis using a command alert. 

```
name: sshd
type: flatline

es_host: elasticsearch
es_port: 9200

# Option basic-auth username and password for Elasticsearch
es_username: admin
es_password: admin

# Connect with TLS to Elasticsearch
use_ssl: True

index: metricbeat-*
description: "SSH process is not running"

threshold: 5
timeframe:
  minutes: 5

doc_type: metricsets

filter:
- term:
    system.process.name: "sshd"

alert:
- "email"
- "command"

email:
- "ankit2.kumar@orange.com"

command: ["tee", "-a", "/tmp/sshd-$(date '+%d-%m-%Y').log"]
```

unable to create an alert file  please help me to create alert
