### ISSUE TITLE
cardinality rule, return unique value count?

### ISSUE THREAD

**Issue by shortstack** [Yelp/elastalert#2081]
we have the following rule (replaced values with dummy data).

```
type: cardinality
cardinality_field: "unique_field"
min_cardinality: 40
timeframe:
  hours: 1
filter:
- term:
    term: "value"
```

we want to know when the count of "unique_field" drops below 40. i assume that on the backend, it's doing something like this: https://www.elastic.co/guide/en/elasticsearch/guide/current/cardinality.html

question: how do we get the aggregations value that gets returned in that query? 

for example, when we get an alert, it says in the alert that the count dropped below 40. if that value is 36, how do we get the alert to return that 36?

thank you!
