### ISSUE TITLE
Alert based on a single thresold value.

### ISSUE THREAD

**Issue by sachin250191** [Yelp/elastalert#2086]
Hi All,

i want to configure an alert, which should work on current data without comparing with last values.
For Example:-
i want to grep a string , let's say "exception"
than a alert should be sent if i get this word exception comes more than 100 times in current hour.... it should not compare the data from last hours as now it does...

**Comment by Qmando** [comment]
```
type: frequency
num_events: 100
timeframe:
  hours: 1
filter:
 - query_string:
      query: "exception"
```
