### ISSUE TITLE
Alert to multiple sns topics

### ISSUE THREAD

**Issue by FerranMarin** [Yelp/elastalert#2104]
I am trying to set up a rule to publish to multiple sns topics. But I am not getting the configuration right.

I know I have the aws permissions right, because I can publish to any of the two topics, but I cannot do it with both. What I tried so far is:
```
alert:
- "sns"

sns:
sns_topic_arn: ["arn:aws-topic1", "arn:aws-topic2"] `
```
```
alert:
- "sns"
- "sns2"

sns:
sns_topic_arn: "arn:aws-topic1"
sns2:
sns_topic_arn: "arn:aws-topic2"`
```
And many other ways, but none seam to work. Is there anyway to setup what I want without creating multiple rules for the same thing?

**Comment by Salaander** [comment]
[ElastAlert documentation](https://elastalert.readthedocs.io/en/latest/ruletypes.html#sns) does not really mention the ability to specify multiple topics.
If you look at the [code ](https://github.com/Yelp/elastalert/blob/35fb95e228007a2f4f40f8c59717d6682dd9fe3a/elastalert/alerts.py#L932) you can see what you need to check: [boto3 documentation](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/sns.html#SNS.Topic.publish). It's not an option, you need to implement this to the SNS check, but it shouldn't be hard.

**Comment by Qmando** [comment]
You can set up multiple copies of an alerter by inlining the configurations
```
alert:
 - sns:
      sns_topic_arn: "aws-topic1"
 - sns:
       sns_topic_arn: "aws-topic2"
default_sns_settings: xyz
```

**Comment by FerranMarin** [comment]
I am sorry to re-open it, but I am getting this error from the logs:
"mapping values are not allowed in this context"

And my config file looks like:
```
alert:
- sns
    sns_topic_arn: "arn:aws:sns:us-east-1:<numbers>:topic1"
- sns
    sns_topic_arn: "arn:aws:sns:us-east-1:<numbers>:topic2"
```
