### ISSUE TITLE
Test (has hits), actual run (no hits)

### ISSUE THREAD

**Issue by garyluu** [Yelp/elastalert#2108]
I have a flatline rule to check if logs are being received:

```
# Alert when no data has been received for more then 30 seconds.

# Rule name, must be unique
name: No Staging Data

# Type of alert.
type: flatline

# Alert when this many documents matching the query occur within a timeframe
threshold: 1

# num_events must occur within this amount of time to trigger an alert
timeframe:
  minutes: 30
use_count_query: true
realert:
  minutes: 10

exponential_realert:
  hours: 1

doc_type: doc

# Index to search, wildcard supported
index: staging-logstash-%Y.%m*
use_strftime_index: true

alert_subject: "No data on dashboard"

alert_text_type: alert_text_only
alert_text: "The stack receives no data at Staging. It might be down :("

# The alert is use when a match is found
alert:
  - slack
slack_webhook_url: "<MY_SLACK_URL>"
slack_username_override: "ElastAlert"

```
I have something hitting my server (generating a document) every 5 mins.  When I run the test, I correctly see:

```
...
INFO:elastalert:Queried rule No Staging Data from 2019-01-31 19:55 UTC to 2019-01-31 20:00 UTC: 1 hits
INFO:elastalert:Queried rule No Staging Data from 2019-01-31 20:00 UTC to 2019-01-31 20:05 UTC: 1 hits

elastalert_status - {'hits': 325, 'matches': 0, '@timestamp': datetime.datetime(2019, 1, 31, 20, 5, 1, 923921, tzinfo=tzutc()), 'rule_name': 'No Staging Data', 'starttime': datetime.datetime(2019, 1, 30, 20, 5, 0, 610431, tzinfo=tzutc()), 'endtime': datetime.datetime(2019, 1, 31, 20, 5, 0, 610431, tzinfo=tzutc()), 'time_taken': 1.3082690238952637}
``` 

Because there's always logs sent.  

However, having the rule actually running and looking at elastalert_status, it appears to be fine and matches the test, but after many hours later shows a series of 0 hits (and 4 matches) and causes the alert to go out on Slack.  

```
# The elasticsearch hostname for metadata writeback
# Note that every rule can have its own elasticsearch host
es_host: localhost

# The elasticsearch port
es_port: 9200

# This is the folder that contains the rule yaml files
# Any .yaml file will be loaded as a rule
rules_folder: rules

# How often ElastAlert will query elasticsearch
# The unit can be anything from weeks to seconds
run_every:
  minutes: 5

# ElastAlert will buffer results from the most recent
# period of time, in case some log sources are not in real time
buffer_time:
  minutes: 5

# Optional URL prefix for elasticsearch
#es_url_prefix: elasticsearch

# Connect with TLS to elasticsearch
#use_ssl: True

# Verify TLS certificates
#verify_certs: True

# GET request with body is the default option for Elasticsearch.
# If it fails for some reason, you can pass 'GET', 'POST' or 'source'.
# See http://elasticsearch-py.readthedocs.io/en/master/connection.html?highlight=send_get_body_as#transport
# for details
#es_send_get_body_as: GET

# Option basic-auth username and password for elasticsearch
#es_username: someusername
#es_password: somepassword

# The index on es_host which is used for metadata storage
# This can be a unmapped index, but it is recommended that you run
# elastalert-create-index to set a mapping
writeback_index: elastalert

# If an alert fails for some reason, ElastAlert will retry
# sending the alert until this time period has elapsed
alert_time_limit:
  days: 2
```

Any ideas what can cause this?
