### ISSUE TITLE
terms does not support multiple fields

### ISSUE THREAD

**Issue by prandelicious** [Yelp/elastalert#2109]
I'm getting this error message when using multiple fields in `terms`:
```
[terms] query does not support multiple fields
```
Here's my configuration:
```yaml
es_host: 10.9.x.x
es_port: 9200
type: frequency
index: app-stream-*
num_events: 3
timeframe:
    minutes: 30
filter:
- terms:
    request: ["/auth/token"]
    response: ["400"]
alert:
- sns
sns_topic_arn: "arn:aws:sns:us-east-1:xxxxxx:opsgenie"
```

**Comment by prandelicious** [comment]
Thank you! We're using 6.x

**Comment by pdscopes** [comment]
Should thing:

```yaml
filter:
- bool:
    must:
    - terms:
        request: ["/auth/token"]
    - terms:
        response: ["400"]
```
