### ISSUE TITLE
limit_execution new feature : problem with synchronization between main cron and rules specific cron not matching

### ISSUE THREAD

**Issue by damioune123** [Yelp/elastalert#2119]
Hello,
I've encountered a problem with the new limit_execution feature. Let's say the main cron is running every rules every minutes and I have a limit_execution on a specific rule with for example that value : "10 11-17 * * 1-5".
If the cron of the specific rule wakes up at 11:10:02 (because previous rules took sometimes), the rules will be paused until next execution.

The problem is that the code allows only a hardcoded value of 1 second for the margin (see https://github.com/Yelp/elastalert/blob/beta/elastalert/elastalert.py#L1245 ).

I've really needed to handle a greater margin than 1 sec so I forked the project and added a limit_execution_margin env var in config (default to 10s). Let met know if you're interested by a pull request of this feature

**Comment by rabiashaikabdulkader** [comment]
> Hello,
> I've encountered a problem with the new limit_execution feature. Let's say the main cron is running every rules every minutes and I have a limit_execution on a specific rule with for example that value : "10 11-17 * * 1-5".
> If the cron of the specific rule wakes up at 11:10:02 (because previous rules took sometimes), the rules will be paused until next execution without doing anything.

Hi @damioune123  could you please guide me how the alert.yaml file should like ? 

I am unsure on under which hierrachy should we add this attribute limit_execution:

Is it okay if I add the attribute like this : 

```
type: frequency
index: prod-filebeat-k8s-*
timeframe:
  minutes: 0
num_events: 1
limit_execution: "* 02-03 * * *"
filter:
  - term:
      kubernetes.container.name: get-sqs-stats
  - term:
      json.message: "Approximate number of messages on the queue"
  - term:

```
