### ISSUE TITLE
Rule matches num_events to num_hits even if they don't match and triggers alert

### ISSUE THREAD

**Issue by cuhajub** [Yelp/elastalert#2125]
Hi,

I have the following rule which gets triggered even when the num_hits is less than 4 500 000. 
```
name: More than 4 500 000 documents in prod* indices for the last 15 min

type: frequency

index: prod-*-%Y.%m.%d

use_strftime_index: true

use_count_query: true

doc_type: log,logs

num_events: 4500000

timeframe:
  minutes: 15

top_count_keys:
- message

top_count_number: 5

alert:
- slack
<cut>

```

Example of notification with less num_hits:
`More than 4 500 000 documents in prod* indices for the last 15 min
More than 4 500 000 documents in prod* indices for the last 15 min

At least 4500000 events occurred between 2019-02-07 21:27 CET and 2019-02-07 21:42 CET

message.keyword:
No events found.

@timestamp: 2019-02-07T20:42:30.789860Z
num_hits: 1158439
num_matches: 1`

Why is alert being send when the num_hits is clearly less than 4 500 000?

**Comment by artushin** [comment]
Did you ever figure this out? I get something like this with the following config:

```
    name: service-warnings
    realert:
      minutes: 5
    type: frequency
    num_events: 1000
    timeframe:
      minutes: 5
    doc_type: {{ $docType }}
    filter:
    - query_string:
        query: {{ $query }}
    index: {{ $index }}-%Y.%m.%d
    use_strftime_index: true
    use_count_query: true
    top_count_keys: 
     - "message.keyword"
    top_count_number: 100
    query_delay:
      minutes: 1
    alert_text_args: 
    - "num_hits"
    - "@timestamp"
    alert_text: |
      {0} service warnings occurred at {1}
    alert:
    - "email"
```

```
203 client warns occurred

At least 1000 events occurred between 2019-07-20 04:09 UTC and 2019-07-20 04:14 UTC

message.keyword:
message1: 253
message2: 224
message3: 172
...
message29: 1

@timestamp: 2019-07-20T04:14:32.889613Z
num_hits: 203
num_matches: 1
```

I don't understand the the relationship between num_hits and the threshold here.
