### ISSUE TITLE
elastalert-test-rule works, but not elastalert

### ISSUE THREAD

**Issue by danielmanser** [Yelp/elastalert#2140]
Given follwing rule, running it with `elastalert-test-rule sshlogins.yaml` works and triggers an alert, but when run with `elastalert --config sshlogins.yaml`, no alert is being sent:

```yaml
---
rules_folder: rules
run_every:
  minutes: 5
buffer_time:
  minutes: 5
writeback_index: elastalert_status
es_host: localhost
es_port: 9200
use_ssl: False
name: SSH Logins on storage
type: frequency
index: graylog*
num_events: 1
timeframe:
  hours: 1
filter:
- query:
    query_string:
      query: "operation_executable: \"/usr/sbin/sshd\""
- query:
    query_string:
      query: "message: \"CRED_DISP\""
timestamp_field: timestamp
timestamp_type: custom
timestamp_format: "%Y-%m-%d %H:%M:%S.%f"
timestamp_format_expr: 'ts[:23] + ts[26:]'
alert:
- command
command: ["/bin/touch", "/tmp/touchtest.txt"]
```

Output:
```
Would have written the following documents to writeback index (default is elastalert_status):

silence - {'rule_name': 'SSH Logins on storage', '@timestamp': datetime.datetime(2019, 2, 18, 11, 4, 50, 35094, tzinfo=tzutc()), 'exponent': 0, 'until': datetime.datetime(2019, 2, 18, 11, 5, 50, 35084, tzinfo=tzutc())}

elastalert_status - {'hits': 9, 'matches': 9, '@timestamp': datetime.datetime(2019, 2, 18, 11, 4, 50, 38630, tzinfo=tzutc()), 'rule_name': 'SSH Logins on storage', 'starttime': datetime.datetime(2019, 2, 12, 9, 37, 48, 578151, tzinfo=tzutc()), 'endtime': datetime.datetime(2019, 2, 18, 11, 4, 12, 578151, tzinfo=tzutc()), 'time_taken': 37.45062184333801}
```

Running the same config with `elastalert`:

```
root@logs2# elastalert --config sshlogins.yaml --debug
INFO:elastalert:Note: In debug mode, alerts will be logged to console but NOT actually sent.
            To send them but remain verbose, use --verbose instead.
INFO:elastalert:Starting up
INFO:elastalert:Sleeping for 59.993254 seconds
INFO:elastalert:Sleeping for 59.996758 seconds
INFO:elastalert:Sleeping for 59.996711 seconds
INFO:elastalert:Sleeping for 59.997216 seconds
INFO:elastalert:Sleeping for 59.996909 seconds
INFO:elastalert:Sleeping for 59.997018 seconds
```

What am I missing?

**Comment by Qmando** [comment]
The global config file and the rule file are not the same. You need --config to point to elastalert's config (https://github.com/Yelp/elastalert/blob/master/config.yaml.example), not a rule itself. Put sshlogins.yaml into a folder and point `rules_folder` in the config to that.

**Comment by danielmanser** [comment]
Thank you - that helped!

**Comment by kasramtm** [comment]
I have the same issue.
when running elastalert-test-rule --config config.yml rules/test.yml
shows hits and queries to ES and also says which documets would have been writen to elastalert indices
but when running elastalert --config ../config.yaml --rule test.yaml --verbose --es_debug_trace test
i just get
1 rules loaded
INFO:elastalert:Starting up
INFO:elastalert:Disabled rules are: []
INFO:elastalert:Sleeping for 59.99978 seconds
INFO:elastalert:Background configuration change check run at 2020-01-17 19:42 +0330
INFO:elastalert:Background alerts thread 0 pending alerts sent at 2020-01-17 19:42 +0330
INFO:elastalert:Disabled rules are: []
INFO:elastalert:Sleeping for 59.999675 seconds

any idea what's the problem here?

**Comment by amar-shinde** [comment]
Facing the same issue as @kasramtm . Any suggestion to this is appreciated.

**Comment by Qmando** [comment]
If you don't see any logs for your rule, then it hasn't run it. IF you want help, show your config.yaml file, the rules file, and your logs.

**Comment by paarth1995** [comment]
Hello @Qmando .  Thank you for replying back

This is my elastalert config file

```
This is the folder that contains the rule yaml files
# Any .yaml file will be loaded as a rule
rules_folder: awesomeRules

# How often ElastAlert will query Elasticsearch
# The unit can be anything from weeks to seconds
run_every:
  minutes: 1

# ElastAlert will buffer results from the most recent
# period of time, in case some log sources are not in real time
buffer_time:
  minutes: 15

# The Elasticsearch hostname for metadata writeback
# Note that every rule can have its own Elasticsearch host
es_host: localhost

# The Elasticsearch port
es_port: 10222

# The AWS region to use. Set this when using AWS-managed elasticsearch
#aws_region: us-east-1

# The AWS profile to use. Use this if you are using an aws-cli profile.
# See http://docs.aws.amazon.com/cli/latest/userguide/cli-chap-getting-started.html
# for details
#profile: test

# Optional URL prefix for Elasticsearch
#es_url_prefix: elasticsearch

# Connect with TLS to Elasticsearch
#use_ssl: True
```

This is my supervisord.conf file 

```
[unix_http_server]
file=/tmp/supervisor.sock

[supervisord]
logfile=/tmp/supervisord.log
logfile_maxbytes=1MB
logfile_backups=2
loglevel=debug
nodaemon=false
directory=%(here)s



[rpcinterface:supervisor]
supervisor.rpcinterface_factory = supervisor.rpcinterface:make_main_rpcinterface



[supervisorctl]
serverurl=unix:///tmp/supervisor.sock



[program:elastalert]
# running globally
# (alternative) using virtualenv
command=/opt/conda/bin/elastalert --config /home/ubuntu/elastalert/config.yaml --verbose
process_name=elastalert
startretries=10
autorestart=true
startsecs=15
stopsignal=INT
stopasgroup=true
killasgroup=true
stderr_logfile=/var/log/elastalert_stderr.log
stderr_logfile_maxbytes=5MB
"supervisord.conf" 38L, 708C  
```

This is my Rules file:-

```
es_host: localhost
es_port: 112200
name: original rule name
type: frequency
index: logstash-*
num_events: 1
timeframe:
    hours: 4
filter:
- query:
    query_string:
      query: "Please enter phone number."
alert:
- command:
command: ["/home/ubuntu/elastalert/script.sh","%(container_name)s"]
```

And these are my logs:-

```
12,374 INFO daemonizing the supervisord process
2020-08-20 13:33:12,374 INFO set current directory: '/etc'
2020-08-20 13:33:12,376 INFO supervisord started with pid 10584
2020-08-20 13:33:13,380 INFO spawned: 'elastalert' with pid 10627
2020-08-20 13:33:14,549 DEBG 'elastalert' stderr output:
INFO:elastalert:Starting up

2020-08-20 13:33:14,552 DEBG 'elastalert' stderr output:
INFO:elastalert:Disabled rules are: []
INFO:elastalert:Sleeping for 59.999925 seconds

2020-08-20 13:33:28,569 INFO success: elastalert entered RUNNING state, process has stayed up for > than 15 seconds (startsecs)
2020-08-20 13:34:14,557 DEBG 'elastalert' stderr output:
INFO:elastalert:Background configuration change check run at 2020-08-20 13:34 UTC

2020-08-20 13:34:14,562 DEBG 'elastalert' stderr output:
INFO:elastalert:Background alerts thread 0 pending alerts sent at 2020-08-20 13:34 UTC

2020-08-20 13:34:14,604 DEBG 'elastalert' stderr output:
INFO:elastalert:Disabled rules are: []
INFO:elastalert:Sleeping for 59.999797 seconds
```
