### ISSUE TITLE
can not make flatline working

### ISSUE THREAD

**Issue by notmaxx** [Yelp/elastalert#2157]
hi, I am trying to create `flatline` rule to detect absence of log records:
```
name: no log records ttl-reaper
index: my-index-*
type: flatline
timestamp_field: time

timeframe: 
  hours: 1
threshold: 1
use_count_query: true
doc_type: my-index

filter:
- query:
   query_string:
    query: 'worker_type:"ttl-reaper"'

alert_text: no worker logs
alert: slack
slack_webhook_url: https://hooks.slack.com/services/...

realert:
  minutes: 5
```

ElastAlert is running every 5 min. Here is example for ElastAlert output in kibana

Columns are: `time`, `rule_name`, `matches`, `hits`

![image](https://user-images.githubusercontent.com/18590450/53780607-07f75680-3eba-11e9-9d05-737e1c1b945e.png)

I expect I'd receive alert for interval 16:00 - 17:00 when there are 0 records found but I didn't 

Please help me to configure the rule correctly
