### ISSUE TITLE
[Question] What's the purpose of multi query combined together

### ISSUE THREAD

**Issue by regardfs** [Yelp/elastalert#2173]
I saw this example in doc website, so I have a question, does below filter expecting to get request which satisfy all query conditions??
```
filter:
- query:
    query_string:
      query: "username: bob"
- query:
    query_string:
      query: "_type: login_logs"
- query:
    query_string:
      query: "field: value OR otherfield: othervalue"
- query:
    query_string:
       query: "this: that AND these: those"
```
