### ISSUE TITLE
KeyError: 'metric_mysql.status.command.select_avg'

### ISSUE THREAD

**Issue by hurnhu** [Yelp/elastalert#2178]
I am trying to create an alert with elastalert that will send an email when the AVG select count for a mysql server is 0 for the last minute.

I have this as my alert:
```

name: test flat

type: flatline
run_every:
    seconds: 15
relalert:
    minutes: 1
threshold: 1
min_threshold: 1
timeframe:
    minutes: 5
index: metricbeat-*
type: metric_aggregation
metric_agg_key: mysql.status.command.select
metric_agg_type: avg
buffer_time:
  minutes: 1
filter:
- term:
    metricset.name: mysql
- query:
    query_string:
        query: "host.name: client-web-server"   

es_host: elasticsearch

index: metricbeat-*
alert_subject: "test"
alert:
  - email
email:
  - "a@a.com"
email_from_field: "data.user"
email_add_domain: "a@a.com.com"
```
When running this test alert I get the following error KeyError: 'metric_mysql.status.command.select_avg'
