### ISSUE TITLE
email body message encoding Issue

### ISSUE THREAD

**Issue by 2nutz4u** [Yelp/elastalert#2196]
I have an instance of praeco running which utilizes elastialert API. Everything is working properly except the body of the email message, the message is all scrambled.  Below is the output of my sample email and my yml rule file. I reached out for help with the praceo community but they suggested to submit issue here.   According to them " Praeco just generates the rule .yaml files, but doesn't really control the sending of the email to you. This might have something to do with unicode/utf-8/character encoding in elastalert codebase" 
Thank you in advance.
![image](https://user-images.githubusercontent.com/30449004/55684469-688e0f00-5910-11e9-9805-4a95c6a8dd07.png)

```
__praeco_query_builder: >-
  {"query":{"logicalOperator":"any","children":[{"type":"query-builder-rule","query":{"rule":"event_id","selectedOperator":"contains","selectedOperand":"event_id","val$
alert:
  - email
alert_subject: |
  Account Locked Out
alert_subject_args: []
alert_text: |-
  {0}
  {1}
alert_text_args:
  - event_data.TargetUserName
  - message
alert_text_type: alert_text_only
doc_type: doc
email:
  - abc@xyz.com
filter:
  - query:
      query_string:
        query: 'event_id:4740'
from_addr: abc@xyz.com
import: BaseRule.config
index: winlogbeat-*
is_enabled: true
name: EventID 4740 - Account Locked Out
num_events: 1
realert:
  minutes: 5
terms_size: 50
timeframe:
  minutes: 5
timestamp_field: '@timestamp'
timestamp_type: iso
type: frequency
use_strftime_index: false
```
