### ISSUE TITLE
Flatline does not work unless match count is above threshold to begin with

### ISSUE THREAD

**Issue by roubles** [Yelp/elastalert#2199]
We use flatlines to detect no data is being written to a particular index as follows:

```
name: MyIndexStatus
type: flatline
index: "foo-metrics-*"
realert:
  minutes: 5
threshold: 1
timeframe:
  minutes: 5
query_key: host
doc_type: doc
```

Now this works, if there are some (greater than threshold) documents in the index prior to elastalert starting. And when the we fall below the threshold (of 1) document in the index, elastalert fires normally.

However, lets say we start off with 0 documents in the index. elastalert will **not** fire. We need a mechanism to reliably fire if there are no documents in an index. If there is a better way to do this, other than a flatline, please let us know.
