### ISSUE TITLE
Elastalert AWS SNS Template

### ISSUE THREAD

**Issue by brucekk248** [Yelp/elastalert#2205]
Hello Team, 
I was planning to implement sns alerting mode. I would like to have a template on how to do so. 

template  example:
alert:
 - "sns"
 - "arn" 
Where should I be giving username and password for this arn?

**Comment by nsano-rururu** [comment]
```
alert:
  - sns:
      sns_topic_arn: "arn:aws:sns:~aws region name~:~id~:~topic name~"
      # Example  aws_region: "ap-northeast-1"
      aws_region: "~aws region name~"
      aws_access_key_id: "~my access key~"
      aws_secret_access_key: "~my secret key~"
```

sns_topic_arn, aws_access_key, aws_secret_key, aws_region, profile are written,
Currently, sns_topic_arn, aws_access_key_id, aws_secret_access_key, aws_profile.
I think I forgot to update the documentation.
https://elastalert.readthedocs.io/en/latest/ruletypes.html#sns
>sns_topic_arn: The SNS topic’s ARN. For example, arn:aws:sns:us-east-1:123456789:somesnstopic
>
>Optional:
>
>aws_access_key: An access key to connect to SNS with.
>
>aws_secret_key: The secret key associated with the access key.
>
>aws_region: The AWS region in which the SNS resource is located. Default is us-east-1
>
>profile: The AWS profile to use. If none specified, the default will be used.

I confirmed by looking at the line 936-942 of the source code
https://github.com/Yelp/elastalert/blob/master/elastalert/alerts.py

```
        super(SnsAlerter, self).__init__(*args)
        self.sns_topic_arn = self.rule.get('sns_topic_arn', '')
        self.aws_access_key_id = self.rule.get('aws_access_key_id')
        self.aws_secret_access_key = self.rule.get('aws_secret_access_key')
        self.aws_region = self.rule.get('aws_region', 'us-east-1')
        self.profile = self.rule.get('boto_profile', None)  # Deprecated
        self.profile = self.rule.get('aws_profile', None)
````
