### ISSUE TITLE
Include does not work in cardinality rule

### ISSUE THREAD

**Issue by Lindmin** [Yelp/elastalert#2210]
Hello,

I have a problem with cardinality rule. My include list field does not work.

rule : 
```

name: Controle de la remontée d informations des serveurs
type: cardinality
index: metricbeat-*
cardinality_field: beat.hostname

timestamp_field: "@timestamp"

min_cardinality: 1
query_key: "beat.hostname"

filter:
- terms:
    metricset.name: ["memory"]

timeframe:
  minutes: 10

realert:
  minutes: 120

include:
  - fields.domain

alert:
  - command

new_style_string_format: true
command: ["/product/ELASTALERT/script/test_bvk.sh", "SERVER_INFO",  "%(beat.hostname)s", "%(fields.domain)s" ,"{@timestamp}"]

```

the elastic  query run : 

```
GET /metricbeat-*/_search?pretty&_source_include=fields.domain,beat.hostname,timestamp&ignore_unavailable=true&scroll=30s&size=10000
{
  "query": {
    "bool": {
      "filter": {
        "bool": {
          "must": [
            {
              "range": {
                "@timestamp": {
                  "gt": "2019-04-16T14:00:00+02:00",
                  "lte": "2019-04-16T14:15:00+02:00"
                }
              }
            },
            {
              "terms": {
                "metricset.name": [
                  "memory"
                ]
              }
            }
          ]
        }
      }
    }
  },
  "sort": [
    {
      "@timestamp": {
        "order": "asc"
      }
    }
  ]
}
```
here an extract of the data returned : 

```
  "took" : 58,
  "timed_out" : false,
  "_shards" : {
    "total" : 18,
    "successful" : 18,
    "skipped" : 0,
    "failed" : 0
  },
  "hits" : {
    "total" : 2924,
    "max_score" : null,
    "hits" : [
      {
        "_index" : "metricbeat-2019.s16",
        "_type" : "doc",
        "_id" : "bD0EJmoBUrRG94mArk29",
        "_score" : null,
        "_source" : {
          "beat" : {
            "hostname" : "lnvfr99720542"
          },
          "fields" : {
            "domain" : "DOM2"
          }
        },
        "sort" : [
          1555416001220
        ]
      },
      {
        "_index" : "metricbeat-2019.s16",
        "_type" : "doc",
        "_id" : "Fx8EJmoBtP-AeIIgr3ma",
        "_score" : null,
        "_source" : {
          "beat" : {
            "hostname" : "lnvfr99720444"
          },
          "fields" : {
            "domain" : "TRANSVERSE"
          }
        },
        "sort" : [
          1555416001429
        ]
      },

```

as you see, the fields.domain is in the response.

But in the alert, the beat.hostname is returned, but not the fields.domain field : 

```
[elastalert@lnxfrp099700489 ~]$ elastalert --config conf/config.yaml --rule rules/server_info.yaml.bvk --start  "2019-04-16 14:00 CEST" --end "2019-04-16 14:15 CEST" --verbose --es_debug_trace ES_DEBUG_TRACE
INFO:elastalert:Starting up
INFO:elastalert:Queried rule Controle de la remontée d informations des serveurs from 2019-04-16 14:00 CEST to 2019-04-16 14:15 CEST: 2924 / 2924 hits
SERVER_INFO lnvfr99720533 <MISSING VALUE> 2019-04-16T14:15:00+02:00
SERVER_INFO lnvfr99720534 <MISSING VALUE> 2019-04-16T14:15:00+02:00
SERVER_INFO lnvfr99720537 <MISSING VALUE> 2019-04-16T14:15:00+02:00
SERVER_INFO lnvfr99720034 <MISSING VALUE> 2019-04-16T14:15:00+02:00
SERVER_INFO lnvfr99720549 <MISSING VALUE> 2019-04-16T14:15:00+02:00
SERVER_INFO lnvfr99720578 <MISSING VALUE> 2019-04-16T14:15:00+02:00
SERVER_INFO lnvfr99720573 <MISSING VALUE> 2019-04-16T14:15:00+02:00
INFO:elastalert:Ran Controle de la remontée d informations des serveurs from 2019-04-16 14:00 CEST to 2019-04-16 14:15 CEST: 2924 query hits (0 already seen), 7 matches, 7 alerts sent

```

my alerter is a simple echo $@ for test purpose.

Is it normal that the include list is not returned ?

**Comment by Qmando** [comment]
Thanks for the excellent bug report. I'll investigate this, it doesn't seem normal.

**Comment by Lindmin** [comment]
Thanks for your reply.

I by passed the problem by specifying a compound query key : 

```
name: Controle de la remontée d informations des serveurs
type: cardinality
index: metricbeat-*
cardinality_field: beat.hostname

timestamp_field: "@timestamp"

min_cardinality: 1
query_key: [beat.hostname,fields.domain]

filter:
- terms:
    metricset.name: ["memory"]

timeframe:
  minutes: 10

realert:
  minutes: 120

alert:
  - command

new_style_string_format: true
command: ["/product/ELASTALERT/script/send_alert.sh", "SERVER_INFO",  "%(beat.hostname,fields.domain)s", "{@timestamp}"]

```
But i think it is a bit dirty to use the field beat.hostname,fields.domain ...

Plus, I have to use the formatting old style , because with the fields with dot it's not working : 
ex : {beat.hostname,fields.domain} dont work
{beat[hostname],fields[domain] don't work too...

So, why with compound query key is working, but not with include ?

For me, elastalert use a larger time frame (in the past) to check  if the actual timeframe does not contain the specify domain.


Waiting for your reply.
