### ISSUE TITLE
Timestamp Format Error

### ISSUE THREAD

**Issue by yakult1995** [Yelp/elastalert#2242]
I'm trying to run an alert on elastalert(v.0.2.0b) with elasticsearch7.0, and here is config file.
I'm using custom timestamp format as below.

```
es_host: ******
es_port: ******

rules_folder: rules

run_every:
  seconds: 5

buffer_time:
  minutes: 1

highlight=send_get_body_as#transport

writeback_index: elastalert_status

alert_time_limit:
  days: 2

timestamp_type: custom
timestamp_format: "%Y-%m-%dT%H:%M:%SZ"
```

Then, I run a elastalert and got this error.
```
elastalert_container | 22:57:40.254Z ERROR elastalert-server:
elastalert_container |     ProcessController:  ERROR:root:Error running query: RequestError(400, u'search_phase_execution_exception', u"failed to parse date field [2019-05-12T22:56:40Z] with format [yyyy-MM-dd HH:mm:ss Z]: [Text '2019-05-12T22:56:40Z' could not be parsed at index 10]")
```

It seems like elastalert server does not catch config file...
