### ISSUE TITLE
Working with two fields

### ISSUE THREAD

**Issue by nikhilgangrade** [Yelp/elastalert#2260]
@Qmando just wondering is there any option that we can work with two fields and in jira throw value in two different comments.
Let say if the filter is something like this-
```
filter:
- range:
    system.memory.used.pct:
      gt: 0.40
- range:
    system.cpu.total.norm.pct:
      gt: 0.50
```
 in jira We get MEMORY: 60% in one comment and CPU:67% in another using alert text.

And also we can comment when the value is above the given range can we throw an alert when it goes below that value?

**Comment by Qmando** [comment]
You can create two different alerts with the same `alert_summary` to get them to comment on the same ticket.

You can do the same for different conditions, though, it's probably going to be spamming comments on the ticket unless you are managing state via ticket status and using `jira_bump_not_in_status` etc.

**Comment by nikhilgangrade** [comment]
Correct me if i am wrong.
You are saying to create two different rules file i.e. yaml files and run together?

**Comment by Qmando** [comment]
yes

**Comment by nikhilgangrade** [comment]
And can we use two range in filter.
`filter:
- range:
    system.cpu.total.norm.pct:
      from: 0.1
      to: 0.7

- range:
    system.cpu.total.norm.pct:
      from: 0.7
      to: 0.9`

Or simply,
`filter:
- range:
    system.cpu.total.norm.pct:
      from: 0.1
      to: 0.9`
First i was just checking the value through gt: 0.7, but my requirement is to get a comment when the value is in range below 70% and above 70%.

**Comment by Qmando** [comment]
In your first example, that's the same as doing .1 to .9. You don't get any hits because they are ANDed together, so they contradict each other.

Here's an example of how I'd set this up using two rules where one opens a ticket and one closes it

Rule 1
```
name: "High CPU alert"
filter:
- range:
    system.cpu.total.norm.pct:
      from: 0.8
alert_subject: "Host {} has high CPU usage"
alert_subject_args: [hostname]
jira_bump_in_statuses: [Open]
realert:
  hours: 1
```

Rule 2:
```
name: "Low CPU ticket closer"
filter:
- range:
    system.cpu.total.norm.pct:
      to: 0.8
alert_subject: "Host {} has high CPU usage"
alert_subject_args: [hostname]
jira_bump_only: true
jira_transition_to: Closed
jira_bump_in_statuses: [Open]
alert_text: "Closing ticket because CPU is now below 80%"
```

Obviously I left a bunch of things out, but this should give you a rough idea.
