### ISSUE TITLE
Flatline Rule does not work.

### ISSUE THREAD

**Issue by aimtsou** [Yelp/elastalert#2313]
Hi,

I am trying to create a flatline rule where I want alerts to be sent where in a specific index there is no documents for the last 15 minutes. I have written this but I cannot match it

```
name: Index_empty

type: flatline

index: mine-*

threshold: 1

timeframe:
  minutes: 15

query_key: "_index"
doc_type: "doc"

use_terms_query: true

filter:
- query:
    query_string:
      query: "*"`
```

The thing is an alert is never triggered and I get a warning about doc_type and elasticsearch 6.x. Am i doing something wrong?

Can I make it without query ie to use term?
