### ISSUE TITLE
Any alert just won't trigger - v0.1.38

### ISSUE THREAD

**Issue by runtman** [Yelp/elastalert#2320]
I am a bit lost with this rule, it's a really basic rule.

I have logs in elasticsearch with a field "package.status: installed", so I want to alert on when a new package is installed, these logs are in system-logs-{DATE}

Here is my rule:

```
name: DPKG new package installed
filter:
  - term:
      package.status: "installed"

type: any
query_key: host

#This option allows you to ignore repeating alerts for a period of time.
#If the rule uses a query_key, this option will be applied on a per key basis.
realert:
  minutes: 5

# (Required)
# Index to search, wildcard supported
index: system-logs-*

# (Required)
# The alert is use when a match is found
alert:
- "email"
- "slack"

alert_subject: "New Installed Pacakge Detected"

# Alert Content Settings
alert_text: "We have detected a new package being installed on {0} \n\n
  Message: {1}\n
  Package: {2}\n\n"
alert_text_type: alert_text_only
alert_text_args: ["beat.hostname", "message", "package.name"]
include: ["@timestamp", "beat.hostname", "message", "package.name"]

# Email Settings
email:
- "devops@x"
email_reply_to: "alerts"
from_addr: "alerts"

# Slack Settings
slack_webhook_url: "x"
slack_username_override: "Elastic-Search Alerts"
slack_emoji_override: ':eyes:'
slack_msg_color: 'warning'

```

I see Elastalert accepts the rule but it just won't trigger:

```
Jul  3 10:58:49 elk-elastalert-node-1 elastalert[24654]: INFO:elastalert:Queried rule DPKG new package installed from 2019-07-03 10:45 UTC to 2019-07-03 10:58 UTC: 0 / 0 hits
Jul  3 10:58:49 elk-elastalert-node-1 elastalert[24654]: INFO:elastalert:Ran DPKG new package installed from 2019-07-03 10:45 UTC to 2019-07-03 10:58 UTC: 0 query hits (0 already seen), 0 matches, 0 alerts sent

```

And here is a elasticsearch doc for proof it's there.

```
{
  "_index": "system-logs-2019.07.03",
  "_type": "log",
  "_id": "WPZ4t2sBY_vaJUobT3ub",
  "_score": 1,
  "_source": {
    "package": {
      "name": "mime-support",
      "version": "3.54ubuntu1.1",
      "architecture": "all",
      "status": "installed"
    },
    "offset": 375165,
    "input_type": "log",
    "source": "/var/log/dpkg.log",
    "message": "status installed mime-support:all 3.54ubuntu1.1",
    "type": "log",
    "tags": [
      "dpkg_log",
      "beats_input_codec_plain_applied"
    ],
    "@timestamp": "2019-07-03T09:53:59.000Z",
    "@version": "1",
    "beat": {
      "hostname": "dev-app-1.x",
      "name": "dev-app-1.x",
      "version": "5.6.16"
    },
    "host": "dev-app-1.x",
    "fields": {
      "log_type": "dpkg_log",
      "environment": "dev",
      "alert_email": "dev-alerts",
      "source": "dev",
      "environment_type": "development"
    }
  },
  "fields": {
    "@timestamp": [
      "2019-07-03T09:53:59.000Z"
    ]
  }
}
```

Thanks again.
