### ISSUE TITLE
Helm-Slack-Elastalert

### ISSUE THREAD

**Issue by prvnmali2017** [Yelp/elastalert#2323]
Hi Team,
I am trying to get alerts notified to my slack. 
I am applying filter which is same as what I put in Kibana Dashboard.
I can view the filters work properly on kibana dashboard, but via helm based elastalert, I do not get all the alerts or messages to slack. In direct sense filters dont work when I used helm based elastalert approach.
**Dashboard -** 
![image](https://user-images.githubusercontent.com/25573531/60701440-1f654f80-9f3f-11e9-9660-8255525257b0.png)

Works Well 

**On Slack -**
I get proper error messages, if I specify the filter as `"log: error"` and run it via helm.
```rules:
  service: |-
    ---
    name: service
    type: any
    index: logstash*
    use_strftime_index: True
    num_events: 1
    timeframe:
        hours: 24
    filter:
      - query:
          query_string:
            query: "log: error"

    alert:
      - "slack"
    alert_text: |
      At `{0}` the following error occurred:
```
if I specify this filter `query: "kubernetes.namespace_name: tolmach and log: error"`, **I do not get any alerts at all.**
```
rules:
  zoe_services: |-
    ---
    name: Zoe Dev Services
    type: any
    index: logstash*
    use_strftime_index: True
    num_events: 1
    timeframe:
        hours: 24
    filter:
      - query:
          query_string:
            query: "kubernetes.namespace_name: tolmach and log: error"
```
My question is, Am I doing some filtering wrong?
Or namespace based filter not working in elastalert?

![image](https://user-images.githubusercontent.com/25573531/60701631-bcc08380-9f3f-11e9-8782-337966439f7e.png)

**Comment by naseemkullah** [comment]
try using `term` rather than `query_string` in this case
```
[...]
    filter:
    - term:
        kubernetes.namespace_name: "tolmach"
```
