### ISSUE TITLE
2 post alert in the same alert

### ISSUE THREAD

**Issue by xwing22** [Yelp/elastalert#2334]
Is there any way to define 2 post alerts on the same alert with different http_post_url and different payloads? 

ex:

...

alert: 
- "post"

http_post_url: "https://webhook1" 
http_post_payload: 
exception: exception 
message: message 
date: date 
id: _id 
http_post_static_payload: 
source: ElastAlert 
alerte: TEST-WEBHOOK1

http_post_url: "https://webhook2" 
http_post_payload: 
exception: exception 
message: message
 http_post_static_payload: 
source: ElastAlert
 alerte: TEST-WEBHOOK2

**Comment by Qmando** [comment]
Yeah
```
alerts:
 - post:
      http_post_url: "webhook1"
      http_whatever: something
 - post:
      http_post_url: "webhook2"
      http_whatever: somethingelse
```
