### ISSUE TITLE
Unable to send HTTP POST alert to New Relic Event API

### ISSUE THREAD

**Issue by ocofaigh** [Yelp/elastalert#2351]
According to the New Relic documentation (https://docs.newrelic.com/docs/insights/insights-data-sources/custom-data/send-custom-events-event-api) it is possible to send custom events to the Event API.

According to the ElastAlert documentation (https://elastalert.readthedocs.io/en/latest/ruletypes.html?highlight=timestamp_type#http-post), the HTTP POST alert type will send results to a JSON endpoint using HTTP POST. The key names are configurable so this is compatible with almost any endpoint.

So I am trying to use the ElastAlert HTTP POST alert type to send data to New Relic, but I can't seem to get it working. Here is what I am trying:

```
alert: post
http_post_url: "https://insights-collector.newrelic.com/v1/accounts/XXXXXXX/events"
http_post_payload:
  eventType: "auto-update-check"
  cluster: cluster_name
  autoUpdate: autoUpdateEnabled
http_post_static_payload:
  X-Insert-Key: "XXXXXXXXXXXXXXXXXXXXXXX"
  Content-Type: "application/json"
```
Here is an example of a typical JSON data set to send to New Relic Insights:
```
[
  {
    "eventType":"auto-update-check",
    "cluster":"MyCluster",
    "autoUpdate":"True"
  }
]
```
And here is the expected format of the POST event:

```
curl -X POST -H "Content-Type: application/json" 
-H "X-Insert-Key: YOUR_KEY_HERE" -H "Content-Type: application/json" 
https://insights-collector.newrelic.com/v1/accounts/YOUR_ACCOUNT_ID/events -d @newrelic.json
```

This works fine when trying manually with a `curl` command. But when I try to use ElastAlert with the syntax above, I get:

```
ERROR:root:Error while running alert http_post: Error posting HTTP Post alert: 400 Client Error: Bad Request for url: https://insights-collector.newrelic.com/v1/accounts/XXXXXXX/events
```

Any ideas? Or any idea how I can actually see the JSON payload that Elastalert is trying to send?
