### ISSUE TITLE
attach_related does not display every events

### ISSUE THREAD

**Issue by Theoooooo** [Yelp/elastalert#2352]
Hello everyone,
i'm currently testing elastalert for, well, alterting purpose, and i ran into this issue.
While using the frequency type, i set attach_related to "true"  but not every matches are displaying in the alert send.

In my case i'm using telegram for the alerting platform.
rule file :

```
name: "Connexion refusée Mikrotik Labo"
type: frequency
index: mktk_labo*

num_events: 1
timeframe:
  minutes: 1

attach_related: true

filter:
- query:
    query_string:
      query: "denied OR failure"

alert:
- "telegram"
telegram_bot_token: "my token"
telegram_room_id: "my room id"
```

i'm doing a 1 num_events just to see if i can display every log i'm getting in my ES instance.

Output of the alert :
![image](https://user-images.githubusercontent.com/33425208/61635805-a4b56780-ac94-11e9-8735-75f735906a77.png)

If you know a better way other than top_count_keys because my logs for this machine only got 1 field, i'm taking it ^^

**Comment by Qmando** [comment]
IF you set num_events to 1, it always sends the alert immediately after the very first event, so you wont ever get related events. You'd need to set that higher, or use something like aggregation.

For example
```
name: "Connexion refusée Mikrotik Labo"
type: any
index: mktk_labo*

aggregation:
  minutes: 10
realert:
  minutes: 0

filter:
- query:
    query_string:
      query: "denied OR failure"

alert:
- "telegram"
telegram_bot_token: "my token"
telegram_room_id: "my room id"
```

What this will do is after it sees a matching events, it will wait up to 10 minutes and then send all the alerts together. One issue with this is that it doesn't look super pretty because it just concatenates the alerts together rather than making a nice JSON blob.
