### ISSUE TITLE
Elast Alert Percentage Match Issue

### ISSUE THREAD

**Issue by MaxPhilippot** [Yelp/elastalert#2370]
Hello,

I want to create an alert on business action (Error or Success) if the error rate reach a certain point i want to raise an alert.

I am sure that i have hits on Kibana explorer for the last 15min (so my buffer_time is more than enough)

My rules looks like that: 

```
name: PercentageTest
index: xxxx-*
type: percentage_match
query_key:
 -ActionResult
 -ActionName
filter:
- term:
   ActionName: Authentication
doc_type: "string"
match_bucket_filter:
- term:
   ActionResult: AUTHENTICATION_SUCCESS
max_percentage: 10
buffer_time:
 hours: 1
realert:
 minutes: 20
alert:
- "email"
email: 
- "xxxx"
```

I am quite sure that my filter & match filter are good (according to few examples that are available on web). I also checked the mandatory options on the documentation, however I have a doubt on 

```doc_type: "string" ```
 is that the "type" that we have on index? 

The Test function does not return error on format but i have 0 hits...
Do you have any ideas of what am i doing wrong please?

Thanks in advance
Regards
Max
