### ISSUE TITLE
Match on chronological events

### ISSUE THREAD

**Issue by jtabet010** [Yelp/elastalert#2386]
Hello, 
would it be possible to trigger an alert for a chronology of events happening. 
Suppose am trying to create an event that has the following topology
if event id = 1 and within 1m you see event id =2 o 3 , generate an alert and send the data of event id 2.

**Comment by LaZyDK** [comment]
I am currently trying to solve the same issue with the "percentage_match" rule. 
I just want to "cancel" sending an alert if I see another event type as defined below. 

```
filter:
- terms:
    event.type: ["Quarantine Failure", "Threat Quarantined"]

buffer_time:
  minutes: 2

query_key: host.hostname.keyword

match_bucket_filter:
- terms:
    event.type: ["Threat Quarantined"]

min_percentage: 50

bucket_interval:
  minutes: 1

realert:
  minutes: 0
```

If we get an Quarantine Failure event we want an alert. 
If we get an Quarantine Failure event and afterward see more than 50% of Threat Quarantined, we don't want the alert anyhow.
