### ISSUE TITLE
Flatline hits no matches threshold under 1

### ISSUE THREAD

**Issue by dotdate** [Yelp/elastalert#2400]
Hello, I'm trying to configure elastalert for our environment and need a rule to detect missing logs within a period of time.

- Period is 24h
- Number of logs in period 1

`name: RULENAME
type: flatline
index: INDEXNAME-*
threshold: 2
run_every:
  minutes: 1
buffer_time:
  minutes: 15
num_events: 0
timeframe:
    hours: 23
filter:
- query:
    query_string:
      query: 'message: "STRING IN ONE DAY"'
alert:
- "email"
email:
- example@mail.com
smtp_host: "example.mail.com"
smtp_port: "26"`

Testrule output:

`elastalert_status - {'hits': 1, 'matches': 0, '@timestamp': datetime.datetime(2019, 8, 14, 8, 54, 23, 156222, tzinfo=tzutc()), 'rule_name': 'RULENAME', 'starttime': datetime.datetime(2019, 8, 13, 9, 40, 34, 21174, tzinfo=tzutc()), 'endtime': datetime.datetime(2019, 8, 14, 8, 54, 22, 21174, tzinfo=tzutc()), 'time_taken': 1.1245999336242676}`

As I understand, the rule has a hit within 24 hours, but threshold is set to 2. So the overall score was below 2. Shouldn't the rule have a match?

In the end i want to reduce threshold to 1, so when there is no hit the rule fires.

Did I misunderstand the whole concept with Flatline?
How do you monitor for "no logs"?

I have read through the following issues:
#1548 
#1380 
#1279
#1270 
#972
#832

**Comment by dotdate** [comment]
I'm still looking for a solution.

It **sometimes** works with Threshold set to 2 and score below 2 but never with threshold 1 and no data.
Is there another way to get an alert if no data appears for a search pattern in a specific amount of time?

**Comment by dotdate** [comment]
This is my config:

`
name: testrule
type: flatline
index: frontend-*
threshold: 1
use_count_query: true
doc_type: doc
timeframe:
  hours: 18
filter:
- query:
    query_string:
      query: 'message: "not existing message"'
alert:
- "email"
email:
- test@test.com
smtp_host: "mail.test.local"
smtp_port: "26"
`

**elastalert-test-rule points out:**
`
elastalert_status - {'rule_name': 'testrule', 'endtime': datetime.datetime(2019, 9, 17, 12, 46, 18, 770354, tzinfo=tzutc()), 'starttime': datetime.datetime(2019, 9, 16, 18, 35, 30, 770354, tzinfo=tzutc()), 'matches': 22, 'hits': 0, '@timestamp': datetime.datetime(2019, 9, 17, 12, 46, 27, 364698, tzinfo=tzutc()), 'time_taken': 8.562491655349731}
`

Why do i have 22 hits?
conf.yaml got default buffer_time and run_every but it shouldn't be the problem since i use_count_query: true

**Comment by dotdate** [comment]
Much more interesting..

```
type: flatline
index: frontend--*
threshold: 1

run_every:
  minutes: 60
buffer_time:
  minutes: 15
num_events: 0
timeframe:
    hours: 25
filter:
- query:
    query_string:
      query: 'message: "not existing message"'
alert:
- "email"
email:
- test@test.com
smtp_host: "mail.test.local"
smtp_port: "26"
```
This gives me one match as expected while it can't find any hits.
When i change timeframe to below 25h elastalert gives me 0 hits and 0 matches. 

@Qmando do i misunderstand?
