### ISSUE TITLE
Access result of `top_count_keys` in `alert_text` ?

### ISSUE THREAD

**Issue by sherifabdlnaby** [Yelp/elastalert#2420]
I want to send a formatted alert to slack, the query uses `use_count_query` in conjunction with `top_count_keys`.

I want to access the result of `top_count_keys` via python formatting.

The results are only shown when using the default alert text (unformatted).

How can I pass the results to `alert_text_args` and hence access it in `alert_text`?

**Comment by sherifabdlnaby** [comment]
`top_events_<key>.keyword`

**Comment by lonfme** [comment]
``` YAML
top_count_keys: ["module-name", "alertTag"]
raw_count_keys: false

alert_text: |
  topEventsModuleName: {}
  topEventsAlertTag: {}

alert_text_args:
- top_events_module-name
- top_events_alertTag
```
