### ISSUE TITLE
SIEM alerts

### ISSUE THREAD

**Issue by tmihaldinec** [Yelp/elastalert#2443]
Hi,

Can you be so kind and tell me if elastalert works with SIEM module?

many thanks
tomislav

**Comment by architect00** [comment]
Hi tomislav!

If you mean compatibility between the _Elastic_ SIEM module and elastalert; **yes it works**.

The SIEM module saves its alerts to the index `.siem-signals-default-*`. You can query `.siem-signals-default-*` with elastalert. The following elastalert rule to sens the SIEM alerts to TheHive:

```yaml
name: elastic-siem-signals
type: any
index: .siem-signals-default-*
alert: hivealerter
filter:
  - query_string:
      query: "signal.status:open"
realert:
  minutes: 0
[...OMITTED...]
```
