### ISSUE TITLE
Issue with frequency alert

### ISSUE THREAD

**Issue by alvarolmedo** [Yelp/elastalert#2487]
Hi @Qmando,

Yesterday we have an issue with a elastalert's rule (type frequency). The rule is very simple:
```
name: "whatever_seguridad-alto_volumen_login_whatever_alerta_seguridad-prod"
type: frequency
use_count_query: true
doc_type: doc
num_events: 250
timeframe:
  minutes: 1
index: whatever*-%Y.%m.%d
use_strftime_index: True
filter:
- query:
    query_string:
      query: 'endpoint:"accounts.login"'
realert:
  minutes: 0
alert:
  - email:
      email:
        - blabla@whatever.com
```
The "endpoint accounts login" indicate us a login try in our web, this query is used to detect attacks to out login system: more than 250 tries in a minute indicate that an attack is possible.

Yesterday morning we receive an email with the alert (6am UTC = 8 GMT+1 in summer time), but, surprise, the email indicate us that the match number is 211. :open_mouth: 
![email](https://user-images.githubusercontent.com/3691730/65622362-d4029080-dfc5-11e9-8fc9-b33af83e4cff.png)

Checking in the metadata indexes, we only can confirm the 211 alarm, the last status of the rule indicates a result of 198 hits:
![metainfo_elatalert_status](https://user-images.githubusercontent.com/3691730/65622390-dc5acb80-dfc5-11e9-9fa1-34326231d202.png)

So, in kibana, go to the index to check and query by endpoint accounts login in an amplied timeframe and we observe more volume of login's actions at the end of 56 minute:
![amplied](https://user-images.githubusercontent.com/3691730/65622427-eed50500-dfc5-11e9-84f1-2141848c338d.png)

But, in detail, if we run queries with a exact minute of timeframe during any second (from 6:56:XXUTC to 6:57:XXUTC or from 6:56:XX+1UTC to 6:57:XX+1UTC or ...) the result is the same, the 250 threshold is not violated in a exact 1 minute timeframe. For example i've attached from 6:56:49UTC to 6:57:49UTC:
![exact-time](https://user-images.githubusercontent.com/3691730/65622456-fa283080-dfc5-11e9-8af1-e517b352b7c9.png)

Do you any idea that what happen with the elastalert and the count of matches for this rule?

Thanks in advance for your help.

We are running a v0.1.38.
