### ISSUE TITLE
Frequency rule matches incorrectly

### ISSUE THREAD

**Issue by kkoppel** [Yelp/elastalert#251]
I have the following rule defined:
```
name: Events frequency
type: frequency
index: sw-prod-*
num_events: 200000
timeframe:
  minutes: 5
timestamp_field: "asctime"
use_count_query: true
doc_type: "events"
filter:
- query:
    query_string:
      query: "*"
```
With the --verbose option I can see the following output from elastalert:
```
Queried rule Events frequency from 9-15 15:55 UTC to 9-15 16:00 UTC: 124955 hits
Sent email to ['x@y.z']
Ran Events frequency from 9-15 15:55 UTC to 9-15 16:00 UTC: 124955 query hits, 1 matches, 1 alerts sent
```
So, I'm getting an alert although the number of events is considerably lower than the threshold set with num_events. I would have expected an alert only when the query gets **at least** num_events hits. Or am I misunderstand how the frequency rule is supposed to work?

Just in case, I checked the actual Elasticsearch query using the --es_debug_trace option and verified that ES does actually give out roughly 125000 hits.

I haven't verified 100%, but it seems like the frequency rule is matching when the number of hits reaches half of num_events.
