### ISSUE TITLE
Whitelist does not work.

### ISSUE THREAD

**Issue by negi700** [Yelp/elastalert#2521]
Even if you write kubelet in whitelist, it will be detected as alert.
Is the setting method bad?

setting
---
rule.yamll
``` yaml

    type: whitelist
    compare_key: "message"
    ignore_null: true
    whitelist:
        - "kubelet"

    type: blacklist
    compare_key: "message"
    blacklist:
        - "testtest

    type: frequency
    num_events: 1
    timeframe:
        seconds: 1

    aggregation:
      schedule: '*/30 * * * * *'
        
    realert:
      minutes: 0

**Comment by daichi703n** [comment]
Hi, @negi700 
Your YAML form seems to be broken.
Try this:

```
    type: whitelist
    compare_key: "message"
    ignore_null: true
    whitelist:
      - "kubelet"

    type: blacklist
    compare_key: "message"
    blacklist:
      - "testtest

    type: frequency
    num_events: 1
    timeframe:
      seconds: 1

    aggregation:
      schedule: '*/30 * * * * *'
        
    realert:
      minutes: 0
```
