### ISSUE TITLE
victorops error "404 Client Error"

### ISSUE THREAD

**Issue by jusmitch** [Yelp/elastalert#2522]
Having trouble getting victorops integration to work. I'm getting the following error:

`Oct 17 13:18:29 ip-x-x-x-x.ec2.internal elastalert[19714]: ERROR:root:Error while running alert victorops: Error posting to VictorOps: 404 Client Error: Not Found for url: https://alert.victorops.com/integrations/generic/xxxxxx/alert/xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx/elastalert`

Config:

```
 alert:
 - "email"
 - "victorops"
 email: "x@x.com"
 from_addr: "x@x.com"
 
 victorops_api_key: xxxxxxxxxxxxxxxxxxxxxxxxxxxxx
 victorops_routing_key: elastalert
 victorops_message_type: INFO

```

Any idea what could be going on?
