### ISSUE TITLE
ElastAlert misses historic timestamp events

### ISSUE THREAD

**Issue by AkashKrDutta** [Yelp/elastalert#2534]
ElastAlert config:
```
is_enabled: true
environment: ####
use_ssl: true
name: ####
type: any
index: ####
run_every:
  minutes: 2
realert:
  minutes: 0
filter
- query:
    query_string:
        query: "alerts: disabled_user"
```
**Issue**: Some of the alerts are not fired, while in kibana we can see that `alerts` array has a value `disabled_user` in it.
**My 20 cents**: We might have a delay in receiving events in elasticsearch. When elastalert queries ES say at t1, and after that a new event is populated in ES with timestamp before t1. Now for the next time elastalert won't query this event since it's timestamp is <t1.

Note: Increasing `run_every` doesn't solves our problem. Problem occurs at boundaries, when `run_every` period just finishes and next starts.

We cannot change the timestamp definition. It depends on the time when the event was triggered from source and we don't want to change the name from `@timestamp`. Any way we get the alerts for events that are less than t1 (some kind of a buffer that it keeps -- given that we can assure it always has a delay less than a threshhold).

Thanks in advance!
