### ISSUE TITLE
alert_text_args are not substituted into alert_text

### ISSUE THREAD

**Issue by selivan** [Yelp/elastalert#2539]
Elastalert version: 0.2.1

I am trying to use alert_text and alert_text_args to get some fields into notification, but it does not work.

Rule file:

```yaml
name: wazuh alerts level >= 7
type: frequency
timeframe:
  seconds: 30
num_events: 1

filter:
- query:
    query_string:
      query: rule.level:>=7
index: wazuh-alerts-3.x-%Y.%m.%d
use_strftime_index: true

alert:
- telegram

alert_text: "agent.id: {0} agent.ip: {1} agent.name: {2} decoder.name: {3}\nfull_log:\n\n{4}"
alert_text_agrs: [  "agent.id", "agent.ip", "agent.name", "decoder.name", "full_log" ]
alert_text_type: alert_text_only
```

I get alerts without substitute fields like that:

```
agent.id: {0} agent.ip: {1} agent.name: {2} decoder.name: {3} 
full_log: {4}
```

When I comment out all `alert_text_*` setting, I see full alert with information:

```
⚠️ wazuh alerts level >= 7 ⚠️ 
wazuh alerts level >= 7

At least 1 events occurred between 2019-10-28 15:48 UTC and 2019-10-28 15:49 UTC

@timestamp: 2019-10-28T15:49:07.094Z
_id: rYJ1_m0BKDTqKG_aEbh_
_index: wazuh-alerts-3.x-2019.10.28
_type: _doc
agent: {
    "id": "010",
    "ip": "X.X.X.X",
    "name": "foobar"
}
decoder: {
    "name": "rootcheck"
}

data: {
    "file": "/usr/bin/mail",
    "title": "Trojaned version of file detected."
}

...

timestamp: 2019-10-28T15:49:05.561+0000
```

So it seems that information is available to elastalert.

How do I get that information into `alert_text` ? What is wrong with my configuration now?
