### ISSUE TITLE
query syntax

### ISSUE THREAD

**Issue by ltagliamonte** [Yelp/elastalert#255]
Hello! I'm trying to use elastalert to get alerts from elasticsearch with cloudtrail data (i'm using https://github.com/AppliedTrust/traildash).
The elastalert installation went fine, but i didn't understand how to properly write filters, for example i'd like to match:
EventName=AuthorizeSecurityGroupIngress and SourceIPAddress=0.0.0.0
i wrote the following filter
```
filter:
- query:
   query_string:
     query: "EventName=AuthorizeSecurityGroupIngress AND SourceIPAddress=0.0.0.0"
```
but when i run:
```
elastalert-test-rule example_rules/example_frequency.yaml 
```
i got:
```
elastalert_status - {'hits': 0, 'matches': 0, '@timestamp': datetime.datetime(2015, 9, 23, 12, 43, 11, 745594, tzinfo=tzutc()), 'rule_name': 'SecurityGroupAlert', 'starttime': datetime.datetime(2015, 9, 22, 12, 43, 11, 613524, tzinfo=tzutc()), 'endtime': datetime.datetime(2015, 9, 23, 12, 43, 11, 613524, tzinfo=tzutc()), 'time_taken': 0.13024282455444336}
```
0 matches even if in the Kibana console i get 3 matches.
Thanks for the support.
Regards
L.

**Comment by iamrudra** [comment]
I'd try:
```
filter:
- and:
    - term:
        field1: "value"
    - term:
        field2: "value"
```

**Comment by iamrudra** [comment]
It'll help if you could provide some more information on where and what kind of match you find on Kibana? I mean is it in the Discover? Or you are using some term/query filter in the visualization window?

**Comment by Qmando** [comment]
@ltagliamonte: elastalert-test-rule by default only looks 24 hours back, so maybe it's missing the documents? You can add ``--days 10``, etc, to look back further. The query_string query should return the exact same results as what you would get in Kibana. I've always used the format ``EventName: AuthorizeSecurityGroupIngress AND SourceIPAddress: 0.0.0.0``, but if your query works in Kibana it should work for ElastAlert.

**Comment by ltagliamonte** [comment]
thank guys, i was able to query, now i get 11 match:
```
Would have written the following documents to elastalert_status:

silence - {'rule_name': 'SecurityGroupAlert', '@timestamp': datetime.datetime(2015, 9, 24, 13, 49, 6, 171569, tzinfo=tzutc()), 'exponent': 0, 'until': datetime.datetime(2015, 9, 24, 13, 50, 6, 171561, tzinfo=tzutc())}

elastalert_status - {'hits': 11, 'matches': 11, '@timestamp': datetime.datetime(2015, 9, 24, 13, 49, 6, 173431, tzinfo=tzutc()), 'rule_name': 'SecurityGroupAlert', 'starttime': datetime.datetime(2015, 9, 23, 13, 49, 6, 8133, tzinfo=tzutc()), 'endtime': datetime.datetime(2015, 9, 24, 13, 49, 6, 8133, tzinfo=tzutc()), 'time_taken': 0.16359090805053711}
```
but not able to get the email notification:
```
python -m elastalert.elastalert --verbose --rule example_frequency.yaml 
Queried rule SecurityGroupAlert from 9-24 13:48 UTC to 9-24 13:49 UTC: 0 hits
INFO:elastalert:Queried rule SecurityGroupAlert from 9-24 13:48 UTC to 9-24 13:49 UTC: 0 hits
Ran SecurityGroupAlert from 9-24 13:48 UTC to 9-24 13:49 UTC: 0 query hits, 0 matches, 0 alerts sent
INFO:elastalert:Ran SecurityGroupAlert from 9-24 13:48 UTC to 9-24 13:49 UTC: 0 query hits, 0 matches, 0 alerts sent
Sleeping for 299 seconds
INFO:elastalert:Sleeping for 299 seconds
```
this is my configuration:
```
filter:
- query:
   query_string:
    query: "EventName=AuthorizeSecurityGroupIngress AND SourceIPAddress=94.34.229.65"
# (Required)
# The alert is use when a match is found
alert:
- "email"

# (required, email specific)
# a list of email addresses to send alerts to
email:
- "luigi@mydomain.com"
```
what is wrong?
