### ISSUE TITLE
Does Deadman Switch Slack works nicely? Thanks.

### ISSUE THREAD

**Issue by johnzheng1975** [Yelp/elastalert#2581]
I created a deadman as your example show, but did not got alert at all.  (My other normal rules works well)
I expected to get deadman alert if there is no other alerts in one period (let us say: 30 mins)
Is below configure correctly? How can I receive this for below configuration?
```
  deadman_slack: |-
    ---
    name: Deadman Switch Slack
    type: frequency
    index: newf1-*
    num_events: 3
    timeframe:
      minutes: 3
    filter:
    - term:
        message: "deadmanslack"
    alert:
    - "slack":
        slack_webhook_url: "https://hooks.slack.com/services/xxx/xxx/xxxxx"
        slack_username_override: "webhookbot"
        slack_channel_override: "#alert"
        slack_emoji_override: ":robot_face:"
        slack_msg_color: "danger"
    - "email":
        smtp_host: 'email-smtp.us-east-1.amazonaws.com'
        smtp_port: '587'
        from_addr: "xxxx-v21qause1b@xxx.com"
        email: "xxx@xx.com"
```

**Comment by daichi703n** [comment]
Hi, @johnzheng1975 
Try this

```
  deadman_slack: |-
    ---
    name: Deadman Switch Slack
    type: frequency
    index: newf1-*
    num_events: 3
    timeframe:
      minutes: 3
    filter:
    - term:
        message: "deadmanslack"
    alert:
    - slack
    - email
    slack_webhook_url: "https://hooks.slack.com/services/xxx/xxx/xxxxx"
    slack_username_override: "webhookbot"
    slack_channel_override: "#alert"
    slack_emoji_override: ":robot_face:"
    slack_msg_color: "danger"
    smtp_host: 'email-smtp.us-east-1.amazonaws.com'
    smtp_port: '587'
    from_addr: "xxxx-v21qause1b@xxx.com"
    email: "xxx@xx.com"
```
