### ISSUE TITLE
The filter don't work.

### ISSUE THREAD

**Issue by negi700** [Yelp/elastalert#2582]
An error is output when the following filter is processed.
Is the query description bad?
Is there any way to solve it?

 filter:
     - query:
          query_string:
           query: "(tags: messages) AND message: FATAL AND NOT message: DEBUG"

ERROR:root:Error running query: ['Failed to parse query [(tags: messages)... (301 characters removed)

**Comment by daichi703n** [comment]
Hi, @negi700 
Your YAML format(indent) is broken.
Try this: 

```
  filter:
    - query:
        query_string:
          query: "(tags: messages) AND message: FATAL AND NOT message: DEBUG"
```
