### ISSUE TITLE
Elastalet fails if alerter type zabbix is used: "ValueError: not enough values to unpack" [bug]

### ISSUE THREAD

**Issue by selivan** [Yelp/elastalert#2586]
Elastalert version: 2.1
Python version: 3.6 (Docker image based on python:3.6-alpine)

Error when trying to use rule with `zabbix` alerter:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/elastalert/util.py", line 26, in get_module
    module_path, module_class = module_name.rsplit('.', 1)
ValueError: not enough values to unpack (expected 2, got 1)

...
```

Full traceback here: https://gist.github.com/selivan/42c629cc331226f07bd4fb88e29b7caf

Rule file:

```yaml

alert:
- zabbix
buffer_time:
  seconds: 30
filter:
- query:
    query_string:
      query: tags:"balancer"
index: someindex-%Y.%m.%d
name: test rule alert command
num_events: 1
realert:
  seconds: 0
timeframe:
  seconds: 20
type: frequency
use_strftime_index: true

zbx_item: trapper_information["test_alert_command"]
zbx_sender_host: "172.20.113.14"
zbx_sender_port: 10051
zbx_host: "wazuh-server2-ire1"
```
