### ISSUE TITLE
I need some help

### ISSUE THREAD

**Issue by melema123** [Yelp/elastalert#2630]
I am trying to achieve this. 

Generate an alert when there is no event for the last five minutes. I have managed to do so with  metric_aggregation. However, I want to get last time the event was logged. Something like:

```
{
	"query": {
		"match_all": {}
	},
	"size": 1,
	"sort": [{
		"eventdatetime": {
			"order": "desc"
		}
	}]
}
```

So I would like to have an alert that says: No event detect within the last 5 minutes. Last event was at {eventdatetime}.

Do I achieve this?

My alert.yml looks :
```
name: Events Rule
type: metric_aggregation

index: events-*

buffer_time:
  hours: 1

metric_agg_key: id
metric_agg_type: value_count
doc_type: _doc
  
bucket_interval:
  minutes: 5
  
sync_bucket_interval: true
#allow_buffer_time_overlap: true
#use_run_every_query_size: true

min_threshold: 0.1

# (Required)
# The alert is use when a match is found
alert:
- "email"
```
