### ISSUE TITLE
Flatline rule issue on filtering docs

### ISSUE THREAD

**Issue by fberrez** [Yelp/elastalert#2638]
My logs are a summary of the activity of my IOT devices.

I have two kinds of IOT devices:

- IOT1 which should send me a data every x seconds
- IOT2 which does not do anything actually (but it is is still logged) 

**I would like to get an alert when an IOT1 device does not send in the last 5 minutes.**

Here is my flatline rule: 

```yml
name: IOT1 flatline
description: Sends alerts when a running IOT1 did not send data in the last 5 minutes.
index: myindex-*
type: flatline
timeframe:
  minutes: 5
threshold: 1
filter:
  - query:
      query_string:
        query: 'fields.metadata.code.keyword: DATA_RECEIVED and fields.metadata.entity.keyword: IOT1 and fields.metadata.details.status.keyword: Running'

# Groups alerts by mac address
query_key: 'fields.metadata.data.mac_address'

# Sets a time interval between two alerts of a same mac address
realert:
  minutes: 1

# Defines alert output
alert:
  - 'slack'

slack_webhook_url: my-slack-webhook
slack_username_override: elastalert

# Builds alert message
alert_subject: '[IOT1] {0} stopped to send data at {1}'
alert_subject_args:
  - key
  - '@timestamp'
```

I would like to apply this rule on the IOT1 but not on the IOT2 devices. 
Nonetheless, they both have a mac address in their logs. 
Therefore, they are caught by my rule.
I understand that by doing `query_key: 'fields.metadata.data.mac_address'`, it means that I'd get triggered if any one IOT device has no matching documents.

I would like to find something like a "preselection" to only apply my rule on the IOT1 devices but I do not find anything about it.
