### ISSUE TITLE
Strange results from spike_aggregation alert

### ISSUE THREAD

**Issue by thethomp** [Yelp/elastalert#2639]
I want to alert when the average build time (fields.duration) over the past 24 hours, is 20% or more larger than the average build time from the day before (48 hours ago - 24 hours ago). To do this I'm using the spike_aggregation rule. I tested it with elastalert-test-rule and it seems to work, but now that it's running in production I'm getting strange results. I got an email alert yesterday that told me the following:

>Mean Build Time Spike - Day over day
>An abnormal avg of fields.duration (716482623.0) occurred around 2020-01-11 14:02 PST.
>Preceding that time, there was a avg of fields.duration of (520382860.86) within 1 day, 0:00:00
>formatted_time: 2020-01-11T22:02:18.014445Z
>num_hits: 19
>num_matches: 2
>reference_count: 520382860.8595236
>spike_count: 716482622.999998
>tags.name.keyword: redacted

How can I validate this exactly? I went through Kibana and the actual averages during these timeframes are around 2 million, where these numbers are saying spike of 700 millioon, and the reference window average was 520 million. These numbers are WAY off and I have no idea where they're coming from.

This is my config.yaml:
```
rules_folder: rules
run_every:
  minutes: 5
buffer_time:
  days: 1
es_host: hostname
es_port: 9200
writeback_index: elastalert_status
writeback_alias: elastalert_alerts
alert_time_limit:
  days: 2
```

And my rule yaml:
```

es_host: hostname
es_port: 9200
name: Mean Build Time Spike - Day over day
type: spike_aggregation

index: telegraf-jenkins*
timestamp_field: formatted_time
timeframe:
    days: 1
buffer_time:
    days: 1

metric_agg_key: fields.duration
metric_agg_type: avg

query_key: tags.name.keyword

### Minimum 1 minute build time to rule out build log pipeline and fast running jobs
threshold_ref: 60000

min_doc_count: 1

spike_height: 1.20

spike_type: "up"

filter:
   - query_string:
       query: "_exists_:fields.duration"
```
Is there some problem with my configuration? Any help would be greatly appreciated!
