### ISSUE TITLE
Question regarding frequency monitoring on unique key-values

### ISSUE THREAD

**Issue by nhua6456** [Yelp/elastalert#2641]
I wish to track the frequency of login activity, but on a per-basis without creating a new rule for each user, as it is not very scalable and we have about a hundred users to keep track of.

Right now, my rule to track login activity looks like this:
```yaml
num_events: 10
timeframe:  
  minutes: 1
filter:
- query_string:
    query: "message: \"sshd\" AND \"Accepted\""
```
However, I do have a key called username that displays the user performing the login activity.
Is there a way to modify my filter parameters or are there elastalert parameters i can set to track the frequency of K-V pairs such as username?
