### ISSUE TITLE
Consecutive Rule Matches to Trigger Alert

### ISSUE THREAD

**Issue by crossan007** [Yelp/elastalert#2648]
Transposed from discussion on Freenode; #2257 

I'm attempting to write a rule which matches _any_ instance of a specific event but only if this rule has been matched for 5 consecutive timeframes (1 minute each).  In other words: It doesn't matter if there was 1, or 1,000 hits of this event; the rule should not trigger until the event has been happening for 5 minutes.

I could use the `Frequency` rule if a `Common Configuration Option` existed something like: ``consecutive_rule_hits: Number of consecutive hits on this rule before triggering alerts.`

This could be utilized something like:
```
#  Trigger an alert when one or more event has been written to the event log each minute for the last 5 consecutive minutes.
frequency:
  num_events: 1
  timeframe:
    minutes: 1
consecutive_rule_hits: 5
```

This is similar to #1582, but I don't have the benefit of a stable rate of incoming events (therefore "5 hits in the last 5 minutes" does not mean for me 5 "consecutive" events).
