### ISSUE TITLE
HTTP_POST alert and post data to Icinga

### ISSUE THREAD

**Issue by fgrelafmpl** [Yelp/elastalert#2669]
Trying to send an alert from elastalert to Icininga2 (nagios fork). The Icinga2 API requires authorization using basic auth. How can I transfer login data in ElastAlert?

```
alert: post
http_post_url: 'https://icinga.example:5665/v1/actions/process-check-result?service=host.example!HDFS%20servoice'
http_post_headers:
  Authorization: 'root:password'
  Content-Type: 'application/json'
  plugin_output: 'dupoa dupa dupa\n dupa nowa linia 1'
  check_source: 'host.example'
  exit_status: '2
```
Log with elastalert:
```
 ProcessController:  ERROR:root:Error while running alert http_post: Error posting HTTP Post alert: 400 Client Error: Bad Request for url: https://icinga.example:5665/v1/actions/process-check-result?service=host.example!HDFS%20servoice'
```
curl is working fine:
```
curl -k -s -u root:password -H 'Accept: application/json' -X POST 'https://icinga.example:5665/v1/actions/process-check-result?service=host.example!HDFS%20servoice' -d '{ "exit_status": 2, "plugin_output": "New malware detected: 1\n\nfdsfds", "check_source": "exampe" }' | python -m json.tool
```
Output:
```
{
    "results": [
        {
            "code": 200.0,
            "status": "Successfully processed check result for object 'host.example!HDFS servoice'."
        }
    ]
}
```
Anyone have any idea what the correct http_post query in elastalert should look like?
