### ISSUE TITLE
Issue with type:new_term and exceptions

### ISSUE THREAD

**Issue by WinterLily** [Yelp/elastalert#2689]
Hi there, my team have been experimenting with certain logs and ElastAlert for a bit now, and trying to see if integrating these will be a viable option for us, and we're trying to experiment with the "new_term" type in an effort to make the alerting a little bit cleaner, however, we've run into a weird issue with filtering on this. Unfortunately, I am not able to share many details due to confidentiality, but here's what we're seeing: 

In type:any rules or the like, we can use something like 

`filter:
- term:
    product.keyword: "productname"
- exists:
    field: "somefield"
- query:
    query_string:
      query: "severity:3 OR severity:4"
- query:
    query_string:
      query: "src: [10.0.0.0 TO 10.255.255.255] OR src: [172.16.0.0 TO 172.31.255.255]"`

And this will filter out anything non-matching. However, if we apply the exact same filters to a rule with type:new_term, the rule crashes with ElastAlert returning the following in the journalctl output:

`
WARNING:elasticsearch:GET https://localhost:9200/index*/_search?ignore_unavailable=true&timeout=50s [status:400 request:0.082s]
Feb 20 14:03:18 server python[30778]: ERROR:root:Could not load rule /etc/elastalert/rules/rulename-new.yaml: Error initializing rule somerule 14:03:18 server python[30778]: /usr/lib/python2.7/site-packages/urllib3/connectionpool.py:1004: InsecureRequestWarning: Unverified HTTPS request is being made. A
Feb 20 14:03:18 server python[30778]: InsecureRequestWarning,
Feb 20 14:03:18 server python[30778]: /usr/lib/python2.7/site-packages/elastalert/elastalert.py:1045: YAMLLoadWarning: calling yaml.load() without Loader=... is depreca
Feb 20 14:03:18 server python[30778]: rule_yaml = yaml.load(f)
Feb 20 14:03:18 server python[30778]: ERROR:root:Error connecting to SMTP host: `{}``

Can anyone please share if there's a way to filter this out appropriately or if a different tactic has to be used?

**Comment by daichi703n** [comment]
What is your ElastAlert, Elasticsearch version?

This page helps you to create filter query.
https://elastalert.readthedocs.io/en/latest/recipes/writing_filters.html#negation-and-or

**Comment by WinterLily** [comment]
> What is your ElastAlert, Elasticsearch version?
> 
> This page helps you to create filter query.
> https://elastalert.readthedocs.io/en/latest/recipes/writing_filters.html#negation-and-or

Sorry for taking some time to get back to you on this, 

The ElasticSearch version is 6.8.1, and according to `pip list`, our ElastAlert version is 0.1.39. 

Is this a known issue with either of these versions?

**Comment by WinterLily** [comment]
> > What is your ElastAlert, Elasticsearch version?
> > This page helps you to create filter query.
> > https://elastalert.readthedocs.io/en/latest/recipes/writing_filters.html#negation-and-or
> 
> Sorry for taking some time to get back to you on this,
> 
> The ElasticSearch version is 6.8.1, and according to `pip list`, our ElastAlert version is 0.1.39.
> 
> Is this a known issue with either of these versions?

If it helps, I can throw in an edited version of the rule with sensitive information omitted. 

I see there appears to have been a similar issue in an early elastalert version, but that this was patched in 0.1.35.

**Comment by daichi703n** [comment]
At a moment, I don’t have same versions, therefore I can’t reproduce.
Would you please post your rule? (Please quote the block with ``` and check preview your markdown format.)

Does your rule contain `fields: [“xxx”, “xxx”]`?
not required on `any`, but required on `new_term`.

Examples are not updated, but required options are written.
https://github.com/Yelp/elastalert/blob/master/example_rules/example_new_term.yaml

Also, options are written in docs.
https://elastalert.readthedocs.io/en/latest/ruletypes.html#new-term

**Comment by WinterLily** [comment]
Please see below rule:

```# Alert when the rate of events exceeds a threshold

# (Optional)
# Elasticsearch host
es_host: localhost

# (Optional)
# Elasticsearch port
es_port: 9200

# (OptionaL) Connect with SSL to Elasticsearch
#use_ssl: True

# (Optional) basic-auth username and password for Elasticsearch
#es_username: someusername
#es_password: somepassword

# (Required)
# Rule name, must be unique
name: somecustomer - someproduct security monitoring

# (Required)
# Type of alert.
# the frequency rule type alerts when num_events events occur with timeframe time
type: new_term

terms_window_size:
days: 7

# (Required)
# Index to search, wildcard supported
index: cp-somecustomer-*

# (Required, frequency specific)
# Alert when this many documents matching the query occur within a timeframe
#num_events: 5

# (Required, frequency specific)
# num_events must occur within this amount of time to trigger an alert
#timeframe:
#  hours: 4

# Send every alert - dsomeproviderble silencing of rule
#realert:
# minutes: 720

fields:
- src
- somefield

#query_key: "protection_name"
#query_key: [src, protection_name, resource]
query_key: [src, somefield]

# (Required)
# A list of Elasticsearch filters used for find events
# These filters are joined with AND and nested in a filtered query
# For more info: http://www.elasticsearch.org/guide/en/elasticsearch/reference/current/query-dsl.html
filter:
- term:
    product.keyword: "someproduct"
- exists:
    field: "somefield"
- term:
    severity: "4"

- query:
    query_string:
      query: "src: [10.0.0.0 TO 10.255.255.255] OR src: [172.16.0.0 TO 172.31.255.255]"

# Exclude DNS reputation alerts from known DNS servers
# somehost.somedomain 10.22.4.21
# somehost.somedomain 10.22.4.20
# somehost.somedomain 10.9.1.12
# somehost.somedomain 10.9.1.11 
# somehost.somedomain 10.22.4.37
#
- query:
    query_string:
      query: "NOT (protection_type: \"DNS reputation\" AND (src: 10.22.4.21 OR src: 10.22.4.20 OR src: 10.9.1.12 OR src: 10.9.1.11 OR src: 10.22.4.37))"

# (Required)
# The alert is use when a match is found
alert:
- "email"
#from_addr: "elastalert@someprovider.co.za"
from_addr: "secmon@somecustomer.mss.someprovider.co.za"
alert_subject: "IoC - Malware Bot - {0} - {1} - {2} - {3} - source {4} (newly observed)"

alert_subject_args:
- protection_type
- protection_name_root
#- resource_host
- action
- severity_label
- src

#alert_text: "IoC - {0} - {1} - {2} - {4} (severity {3}) - {5}"
alert_text: "Customer: {12}\n\rEvent type: IoC - Malware Bot\n\rProtection type: {0}\n\rProtection name: {1}\n\rAction: {2}\n\rSeverity: {4} ({3})\n\rResource: {7}\n\rDescription: {8}\n\rSource IP: {9}\n\rSource user DN: {10}\n\rSource user name: {11}\n\r-----"
alert_text_args:
- protection_type
- protection_name
- action
- severity
- severity_label
- confidence
- confidence_label
- resource
- description
- src
- src_user_dn
- src_user_name
- fields.cust_id

# (required, email specific)
# a list of email addresses to send alerts to
email:
- "someperson@someprovider.co.za"
- "someperson@someprovider.co.za"
#- "someperson@someprovider.co.za"
- "someperson@someprovider.co.za"

# SMTP host
smtp_host: "192.168.88.20"

```

I've read through the page you've linked, but I'm not sure if I'm just bricked, because I'm not seeing what the problem is if it's syntax or logic related. 

Thank you so much for your assistance on this

**Comment by daichi703n** [comment]
Thanks. Config has indent ploblem.

```
terms_window_size:
days: 7
```

to

```
terms_window_size:
  days: 7
```

But I don’t think only this cause error... Sorry I’m not very familiar with `new_term` rule...

**Comment by WinterLily** [comment]
Fixes the indent, didn't fix the alerting :/ it seems that whenever I unhash one of the ```-query``` lines, it cannot be read.

**Comment by daichi703n** [comment]
I figured out what happens.

Your filter list are not compatible with generated Elasticsearch Query.

This seems to work. Your `unhash` meant like this?

```
filter:
- term:
    product.keyword: "someproduct"
- exists:
    field: "somefield"
- term:
    severity: "4"
- query_string:
    query: "src: [10.0.0.0 TO 10.255.255.255] OR src: [172.16.0.0 TO 172.31.255.255]"
- query_string:
    query: "NOT (protection_type: \"DNS reputation\" AND (src: 10.22.4.21 OR src: 10.22.4.20 OR src: 10.9.1.12 OR src: 10.9.1.11 OR src: 10.22.4.37))"
```

`filter` query for `new_term` is generated as `bool` & `must` query.

https://www.elastic.co/guide/en/elasticsearch/reference/6.8/query-dsl-bool-query.html


---
### debug
trace ES query
```
/opt/elastalert # python -m elastalert.elastalert --es_debug_trace ./trace.log --rule ./rules/debug.yaml
```

run with curl to ES.
```
/opt/elastalert # cat ./trace.log
curl -H 'Content-Type: application/json' -XGET 'http://localhost:9200/praeco_elastalert_status_status/_search?pretty&_source_include=%40timestamp%2C%2A&ignore_unavailable=true&scroll=30s&size=10000' -d '{
  "query": {
    "bool": {
      "filter": {
        "bool": {
          "must": [
            {
              "range": {
                "@timestamp": {
                  "gt": "2020-02-25T14:03:43.215218Z",
                  "lte": "2020-02-25T14:04:06.949120Z"
                }
              }
            },
            {
              "term": {
                "product.keyword": "someproduct"
              }
            },
            {
              "exists": {
                "field": "somefield"
              }
            },
            {
              "term": {
                "severity": "4"
              }
            },
            {
              "query_string": {
                "query": "nule_name:test"
              }
            },
            {
              "query_string": {
                "query": "NOT (protection_type: \"DNS reputation\" AND (src: 10.22.4.21 OR src: 10.22.4.20 OR src: 10.9.1.12 OR src: 10.9.1.11 OR src: 10.22.4.37))"
              }
            }
          ]
        }
      }
    }
  },
  "sort": [
    {
      "@timestamp": {
        "order": "asc"
      }
    }
  ]
}'
```

**Comment by daichi703n** [comment]
Issued filter
```
filter:
- term:
    product.keyword: "someproduct"
- exists:
    field: "somefield"
- term:
    severity: "4"
- query:
    query_string:
      query: "src: [10.0.0.0 TO 10.255.255.255] OR src: [172.16.0.0 TO 172.31.255.255]"
- query:
    query_string:
      query: "NOT (protection_type: \"DNS reputation\" AND (src: 10.22.4.21 OR src: 10.22.4.20 OR src: 10.9.1.12 OR src: 10.9.1.11 OR src: 10.22.4.37))"
```

generates this query. When running the query, Elasticsearch respond error by query format error.

```
/opt/elastalert # curl -H 'Content-Type: application/json' -XGET 'http://elasticsearch:9200/index/_search?pretty&ignore_unavailable=true&timeout=50s' -d '{
>   "aggs": {
>     "filtered": {
>       "aggs": {
>         "values": {
>           "terms": {
>             "field": "test.keyword",
>             "size": 2147483647
>           }
>         }
>       },
>       "filter": {
>         "bool": {
>           "must": [
>             {
>               "range": {
>                 "@timestamp": {
>                   "gte": "2020-02-18T13:56:22.450441Z",
>                   "lt": "2020-02-19T13:56:22.450441Z"
>                 }
>               }
>             },
>             {
>               "query": {
>                 "query_string": {
>                   "query": "test:test"
>                 }
>               }
>             }
>           ]
>         }
>       }
>     }
>   }
> }'
{
  "error" : {
    "root_cause" : [
      {
        "type" : "parsing_exception",
        "reason" : "no [query] registered for [query]",
        "line" : 24,
        "col" : 24
      }
    ],
    "type" : "parsing_exception",
    "reason" : "no [query] registered for [query]",
    "line" : 24,
    "col" : 24
  },
  "status" : 400
}
```

**Comment by WinterLily** [comment]
Thanks so much for the responses, I've attempted the suggestion given by @daichi703n in #2688. 

I see the rule has now not broken (mind you its a very simple filter), but I guess I'll need to keep watching to see if it actually _alerts_ 

Thanks again for the help

**Comment by daichi703n** [comment]
Sure. You can test your rule like this.
https://elastalert.readthedocs.io/en/latest/ruletypes.html#testing

Don’t you have any more question? Please close this issue.

**Comment by WinterLily** [comment]
Thanks for the tip, 

The rule is still being rejected and I'm not sure why?

Please see rule below: 

```
# Alert when the rate of events exceeds a threshold

# (Optional)
# Elasticsearch host
es_host: localhost

# (Optional)
# Elasticsearch port
es_port: 9200

# (OptionaL) Connect with SSL to Elasticsearch
#use_ssl: True

# (Optional) basic-auth username and password for Elasticsearch
#es_username: someusername
#es_password: somepassword

# (Required)
# Rule name, must be unique
name: somecustomer - Someproduct IoC Malware Bot New EXCLUSIONTESTING

# (Required)
# Type of alert.
# the frequency rule type alerts when num_events events occur with timeframe time
type: new_term

terms_window_size:
#  hours: 24
   days: 7

# (Required)
# Index to search, wildcard supported
index: sp-somecustomer-*

# (Required, frequency specific)
# Alert when this many documents matching the query occur within a timeframe
#num_events: 5

# (Required, frequency specific)
# num_events must occur within this amount of time to trigger an alert
#timeframe:
#  hours: 4

# Send every alert - dsomeSPble silencing of rule
# realert:
#  minutes: 720

fields:
- src
- protection_name_root

query_key: [src, protection_name_root]

# (Required)
# A list of Elasticsearch filters used for find events
# These filters are joined with AND and nested in a filtered query
# For more info: http://www.elasticsearch.org/guide/en/elasticsearch/reference/current/query-dsl.html
filter:
- term:
    product.keyword: "Anti Malware"
- exists:
    field: "protection_type"
- term:
    severity: "4"
#
#Filtering only for internal ranges (192.168.x.x not included due to this range being assigned to open WiFi ranges)
#
filter:
    query_string:
      query: "src: [10.0.0.0 TO 10.255.255.255] OR src: [172.16.0.0 TO 172.31.255.255]"
#
#
# Exclude DNS reputation alerts from known DNS servers
#
#         somehost.somecustomer.internal 10.22.4.21
#         somehost.somecustomer.internal 10.22.4.20
#         somehost.somecustomer.internal 10.9.1.12
#         somehost.somecustomer.internal 10.9.1.11 
#         somehost.somecustomer.internal 10.22.4.37
#         somehost.somecustomer.internal 10.23.4.45
#         somehost.somecustomer.internal 10.23.4.65
#
#
filter:
    query_string:
      query: "NOT (protection_type: \"DNS reputation\" AND (src: 10.22.4.21 OR src: 10.22.4.20 OR src: 10.9.1.12 OR src: 10.9.1.11 OR src: 10.22.4.37 OR src: 10.23.4.45 OR src:10.23.4.65))"
#
#
# Proxy Exclusions
#
#         10.23.4.233 - somehost.somecustomer.internal - Permanent exclusion for somesite GFI Proxy
#         10.23.4.234 - somehost.somecustomer.internal - Permanent exclusion for somesite GFI Proxy
#         10.23.4.9 - somehost.somecustomer.internal	- Permanent exclusion for somesite GFI Proxy
filter:
    query_string:
      query:"NOT (src:10.23.4.233 OR src:10.23.4.234 OR src:10.23.4.9)"
#
#
# Mobile WiFi Exclusions
#
#         [10.23.170.0 TO 10.23.171.255] - Permanent exclusion for somesite Mobile WiFi Network
#         [10.17.160.0 TO 10.17.160.255] - Permanent exclusion for somesite Guest WiFi Network
#         [10.23.160.0 TO 10.23.160.255] - Permanent exclusion for somesite Guest WiFi Network
#         [10.31.160.0 TO 10.31.160.255] - Permanent exclusion for somesite Guest WiFi Network
filter:
    query_string:
      query:"NOT (src:[10.23.170.0 TO 10.23.171.255] OR src:[10.23.171.0 TO 10.23.171.255] OR src: [10.17.160.0 TO 10.17.160.255] OR src:[10.23.160.0 TO 10.23.160.255] OR src:[10.31.160.0 TO 10.31.160.255])"
#
#
# Temporary Exclusions for Hosts Undergoing Remediation
#
#         10.9.10.13 - somehost.somecustomer.internal - Currently awaiting remediation from the customer's side, cannot be remediated without networking change
#         10.9.10.75 - somehost.somecustomer.internal   - Currently awaiting remediation from the customer's side, cannot be remediated without networking change
#
filter:
    query_string:
      query:"NOT (src:10.9.10.13 OR src:10.9.10.75)"
#
#
# (Required)
# The alert is use when a match is found
alert:
- "email"
#from_addr: "elastalert@someSP.co.za"
from_addr: "secmon@somecustomer.mss.someSP.co.za"
alert_subject: "IoC - Malware Bot - {0} - {1} - {2} - {3} - source {4} - EXCLUSION"

alert_subject_args:
- protection_type
- protection_name_root
#- resource_host
- action
- severity_label
- src

#alert_text: "IoC - {0} - {1} - {2} - {4} (severity {3}) - {5}"
alert_text: "Customer: {12}\n\rEvent type: IoC - Malware Bot\n\rProtection type: {0}\n\rProtection name: {1}\n\rAction: {2}\n\rSeverity: {4} ({3})\n\rResource: {7}\n\rDescription: {8}\n\rSource IP: {9}\n\rSource user DN: {10}\n\rSource user name: {11}\n\r-----"
alert_text_args:
- protection_type
- protection_name
- action
- severity
- severity_label
- confidence
- confidence_label
- resource
- description
- src
- src_user_dn
- src_user_name
- fields.cust_id

# (required, email specific)
# a list of email addresses to send alerts to
email:
#- "philip@someSP.co.za"
- "jesse@someSP.co.za"
#- "timo@someSP.co.za"
#- "premiumsupport@someSP.co.za"

# SMTP host
smtp_host: "192.168.88.20"

```

Also here's output of the elastalert-test-rule:

```

elastalert-test-rule /etc/elastalert/rules/somecustomer-cp-ioc-malware-bot-exclusions.yaml
/usr/lib/python2.7/site-packages/elastalert/config.py:31: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  rule_schema = jsonschema.Draft4Validator(yaml.load(open(os.path.join(os.path.dirname(__file__), 'schema.yaml'))))
Traceback (most recent call last):
  File "/bin/elastalert-test-rule", line 11, in <module>
    load_entry_point('elastalert==0.1.39', 'console_scripts', 'elastalert-test-rule')()
  File "/usr/lib/python2.7/site-packages/elastalert/test_rule.py", line 463, in main
    test_instance.run_rule_test()
  File "/usr/lib/python2.7/site-packages/elastalert/test_rule.py", line 430, in run_rule_test
    rule_yaml = load_rule_yaml(args.file)
  File "/usr/lib/python2.7/site-packages/elastalert/config.py", line 145, in load_rule_yaml
    loaded = yaml_loader(filename)
  File "/usr/lib/python2.7/site-packages/staticconf/loader.py", line 168, in yaml_loader
    return yaml.load(fh, Loader=SafeLoader) or {}
  File "/usr/lib64/python2.7/site-packages/yaml/__init__.py", line 114, in load
    return loader.get_single_data()
  File "/usr/lib64/python2.7/site-packages/yaml/constructor.py", line 43, in get_single_data
    node = self.get_single_node()
  File "_yaml.pyx", line 707, in _yaml.CParser.get_single_node (ext/_yaml.c:8040)
  File "_yaml.pyx", line 725, in _yaml.CParser._compose_document (ext/_yaml.c:8295)
  File "_yaml.pyx", line 776, in _yaml.CParser._compose_node (ext/_yaml.c:8983)
  File "_yaml.pyx", line 890, in _yaml.CParser._compose_mapping_node (ext/_yaml.c:10513)
  File "_yaml.pyx", line 776, in _yaml.CParser._compose_node (ext/_yaml.c:8983)
  File "_yaml.pyx", line 890, in _yaml.CParser._compose_mapping_node (ext/_yaml.c:10513)
  File "_yaml.pyx", line 776, in _yaml.CParser._compose_node (ext/_yaml.c:8983)
  File "_yaml.pyx", line 892, in _yaml.CParser._compose_mapping_node (ext/_yaml.c:10544)
  File "_yaml.pyx", line 905, in _yaml.CParser._parse_next_event (ext/_yaml.c:10722)
yaml.parser.ParserError: while parsing a block mapping
  in "/etc/elastalert/rules/somecustomer-cp-ioc-malware-bot-exclusions.yaml", line 107, column 7
did not find expected key
  in "/etc/elastalert/rules/somecustomer-cp-ioc-malware-bot-exclusions.yaml", line 107, column 131

```

**Comment by daichi703n** [comment]
```
filter:
- term:
    key: "value"
- exists:
    key: "value"
- term:
    key: "value"
- query_string:
    query: "<QUERY>"
- query_string:
    query: "<QUERY>"
- query_string:
    query: "<QUERY>"
- query_string:
    query: "<QUERY>"
- query_string:
    query: "<QUERY>"
- query_string:
    query: "<QUERY>"
- query_string:
    query: "<QUERY>"
- query_string:
    query: "<QUERY>"
```
