### ISSUE TITLE
Error running your filter

### ISSUE THREAD

**Issue by kasramtm** [Yelp/elastalert#2694]
Hello all,
my rules for an index does not get hit and I have the following error for test-rule:
Error running your filter:
TypeError("search() got multiple values for argument 'body'",)
INFO:elastalert:Note: In debug mode, alerts will be logged to console but NOT actually sent.
                To send them but remain verbose, use --verbose instead.
1 rules loaded
INFO:apscheduler.scheduler:Adding job tentatively -- it will be properly scheduled when the scheduler starts

INFO:elastalert:Queried rule user deleted from cloud from 2020-01-25 07:22 UTC to 2020-01-26 23:22 UTC: 0 / 0 hits
INFO:elastalert:Queried rule user deleted from cloud from 2020-01-26 23:22 UTC to 2020-01-28 15:22 UTC: 0 / 0 hits
INFO:elastalert:Queried rule user deleted from cloud from 2020-01-28 15:22 UTC to 2020-01-30 07:22 UTC: 0 / 0 hits
INFO:elastalert:Queried rule user deleted from cloud from 2020-01-30 07:22 UTC to 2020-01-31 23:22 UTC: 0 / 0 hits
INFO:elastalert:Queried rule user deleted from cloud from 2020-01-31 23:22 UTC to 2020-02-02 15:22 UTC: 0 / 0 hits

and here is my rule
```
name: user deleted from cloud
type: any
index: cloud*
filter:
        - query:
            query_string:
                    query: "_type: doc"
```

**Comment by daichi703n** [comment]
quote your name

```
name: "user deleted from cloud"
type: any
index: cloud*
filter:
        - query:
            query_string:
                    query: "_type: doc" 
```
