### ISSUE TITLE
Flatline Alert not working without "logstash-" prefix

### ISSUE THREAD

**Issue by malteleek** [Yelp/elastalert#2696]
We have an index called firewall-00001 in elasticsearch 7.3.1 and elastalert 0.2.1.
We have a flatline alert which is not working if the index name does not start with "logstash-".

Our alert config:
```
name: "TEST: Monitor Data (Flatline): Firewall"
type: flatline
index: "firewall-*"
threshold: 1
timeframe:
  minutes: 10
scan_entire_timeframe: true
realert:
  minutes: 1
filter:
- query:
    query_string:
      query: "*"
alert:
- "telegram"
telegram_bot_token: "<TOKEN>"
telegram_room_id: "<ID>"
```
If we use  the index name "firewall-*" we get zero hits and false alerts. 
```
curl -H 'Content-Type: application/json' -XGET 'http://localhost:9200/firewall-*/_count?pretty&ignore_unavailable=true' -d '{
  "query": {
    "bool": {
      "filter": {
        "bool": {
          "must": [
            {
              "range": {
                "@timestamp": {
                  "gt": "2020-02-20T09:31:34.950227Z",
                  "lte": "2020-02-20T09:32:34.950227Z"
                }
              }
            },
            {
              "query_string": {
                "query": "*"
              }
            }
          ]
        }
      }
    }
  }
}'
curl -H 'Content-Type: application/json' -XPOST 'http://localhost:9200/elastalert_status/_doc?pretty' -d '{
  "@timestamp": "2020-02-20T09:32:34.986969Z",
  "endtime": "2020-02-20T09:32:34.950227Z",
  "hits": 0,
  "matches": 0,
  "rule_name": "TEST: Monitor Data (Flatline): Firewall",
  "starttime": "2020-02-20T09:22:34.950227Z",
  "time_taken": 0.03672599792480469
}'
```
After we set an alias "logstash-firewall-2020" on the index and changed our alert config to `index: logstash-firewall-*` we got hits and no alerts as expected.

```
curl -H 'Content-Type: application/json' -XGET 'http://localhost:9200/logstash-firewall-*/_search?pretty&_source_includes=%2A%2C%40timestamp&ignore_unavailable=true&scroll=30s&size=10000' -d '{
  "query": {
    "bool": {
      "filter": {
        "bool": {
          "must": [
            {
              "range": {
                "@timestamp": {
                  "gt": "2020-02-27T08:17:52.377012Z",
                  "lte": "2020-02-27T08:27:52.377012Z"
                }
              }
            },
            {
              "query_string": {
                "query": "*"
              }
            }
          ]
        }
      }
    }
  },
  "sort": [
    {
      "@timestamp": {
        "order": "asc"
      }
    }
  ]
}'
curl -H 'Content-Type: application/json' -XPOST 'http://localhost:9200/elastalert_status/_doc?pretty' -d '{
  "@timestamp": "2020-02-27T08:27:52.989337Z",
  "endtime": "2020-02-27T08:27:52.377012Z",
  "hits": 2646,
  "matches": 0,
  "rule_name": "TEST: Monitor Data (Flatline): Firewall",
  "starttime": "2020-02-27T08:17:52.377012Z",
  "time_taken": 0.612307071685791
}'
```
