### ISSUE TITLE
is it possible to use a frequency rule with both use_terms_query and timeframe?

### ISSUE THREAD

**Issue by jmcclelland** [Yelp/elastalert#2697]
I'm trying to get an alert if the same IP address shows up 10 or more times in a four hour window. If it does, I want to be alerted right away, so I'm checking every 60 seconds.

```
run_every:
  seconds: 60
name: ban ips with dovecot login failure
type: frequency
num_events: 10 
timeframe:
  hours: 4
doc_type: _doc
terms_size: 500
use_terms_query: true
query_key: dissect.client_ip
index: journalbeat-*
filter:
- query:
    query_string:
      query: 'host.hostname:mailcf-* and syslog.identifier:dovecot and dissect.auth_failed_attempts > 0'
```
If all 10 occurences happen within the 60 second `run_every` setting, it works.

But if 5 happen during one run and 5 happen during the next, it fails to trigger.

I [read](https://elastalert.readthedocs.io/en/latest/ruletypes.html#testing-your-rule) that:

> In addition, use_count_query and use_terms_query rely on run_every to determine their resolution.

Does that mean if I use `use_terms_query`, my timeframe can only be as large as my `run_every` setting? Or am I doing something else wrong that could be fixed?
