### ISSUE TITLE
Is Frequency in ElastAlert accurate?

### ISSUE THREAD

**Issue by arnavbose** [Yelp/elastalert#2706]
Hi,

I have an alert in place and it works fine when the log count is higher than the frequency set in the rule.

```
nextrulename: FrequentHostMoveEvents
type: frequency
index: logstash-*
num_events: 100
timeframe:
  minutes: 10
filter:
- query:
    query_string:
      query: 'log:HOST_MOVED* AND log:EventPublisherUtil*'
alert: my_alerts.AlertManager
labels:
  severity: critical
  slack: 'true'
  auto_resolve: 'false'
annotations:
  description: Frequent HOST MOVE events observed in the last 10 minutes.
```

But I recently found that even though in UI if I see the log count of the events is around 110-115 in 10 minutes, this alert does not trigger. So, I just want to know, how accurate is the frequency type elast alerts? Is there anyway I can make it more precise?

Thanks
