### ISSUE TITLE
 How to exclude some servers in a rule

### ISSUE THREAD

**Issue by premierpsp** [Yelp/elastalert#2714]
Hi

I want to exclude some servers in a rule. My rule is:

```
# Type of alert.
# the frequency rule type alerts when num_events events occur with timeframe time
type: frequency

# (Required, frequency specific)
# Alert when this many documents matching the query occur within a timeframe
num_events: 1

# Index to search, wildcard supported
index: logstash-*

# (Required, frequency specific)
# num_events must occur within this amount of time to trigger an alert
timeframe:
  hours: 1

# Rule
#realert: minutes: 0
alert_time_limit:
  minutes: 1

# (Required)
# A list of Elasticsearch filters used for find events
# These filters are joined with AND and nested in a filtered query
# For more info: http://www.elasticsearch.org/guide/en/elasticsearch/reference/current/query-dsl.html
filter:
- query_string:
    query: message:"foo"

```
And i need to exclude some hosts from that condition. these hosts exists in the index logstash-*
 
Thanks!
