### ISSUE TITLE
Problems with false alarms

### ISSUE THREAD

**Issue by qizai123** [Yelp/elastalert#2723]
I ran into some small problems and I hope to get help, thank you

We hope that each restart of elastalert will be evaluated with reference to the latest 1 minute, instead of referring to the data from the time when the elastalert was last closed to the current interval, I now make the following modifications

```yaml
About config.yaml

old_query_limit:
  minutes: 1
buffer_time:
  minutes: 1
```

After the modification, only the data of the last minute is searched for evaluation. But I encountered the problem of inaccurate data

```yaml
About my conf

es_host: mgt-elk-esmaster1
es_port: 9200
name: prod-nginx-error-5xx
type: frequency
index: prod-nginx-access-*
num_events: 200
timeframe:
    minutes: 1
filter:
- query:
    query_string:
      query: status>= 500 and status < 600
```

I got the following log:

```verilog
INFO:elastalert:Queried rule online-nginx-error-5xx from 2020-03-27 18:56 CST to 2020-03-27 18:56 CST: 3 / 3 hits
INFO:elastalert:Ran online-nginx-error-5xx from 2020-03-27 18:55 CST to 2020-03-27 18:56 CST: 3 query hits (0 already seen), 1 matches, 1 alerts sent
```

I don't understand why "3 query hits" and "1 matches" trigger an alarm
