### ISSUE TITLE
No alerts, 0 hits

### ISSUE THREAD

**Issue by cyberzlo** [Yelp/elastalert#2724]
Hi, I have some general problems with elastalert and trying do few things for many, many hours.

For example, I have simple query in Kibana, like:

mac:"00:11:22"

and it works, but this is KQL... why elastalert using DSL / Lucene? I don't even know how create query, can't just copy it from Kibana :(.

I know that is free project, but I just don't get it, why it can't be so simple to copy/paste queries from Kibana? this is debug from Kibana, it query elasticsearch same as elastalerts...

But I am trying:

```
type: any

filter:
- query:
    wildcard:
      mac: "00*"
```

This is only what works, but match too much...

```
mac: "00*11*22*" don't work
mac: "00\:11\:22\:*" don't work
mac: "00:11:22:*" don't work
mac_info: "OreoPoo*" don't work
```

when frields and values are following:

```
mac			00:11:22:33:44:55
mac_info		OrientPo_33:44:55
```

I just don't have idea how deal with it, people in comments are saying that don't have problems but I have a lot, and can't find any other free alternative :(.

What is wrong in my rules for elastalert?

This is whole rule:

```
name: ABC

type: any

filter:
- query:
    wildcard:
      mac: "00*"

index: test-*

realert:
  minutes: 1

#query_key:
#  - mac

alert_subject: "{} ABC"
alert_subject_args:
  - mac

alert_text: |-
  {} ABC
alert_text_args:
  - mac

alert_text_type: alert_text_only

alert:
  - slack

slack_webhook_url: "..."
slack_username_override: "..."
```
