### ISSUE TITLE
Alert for two different values in the same field at different time

### ISSUE THREAD

**Issue by syunusic** [Yelp/elastalert#2728]
Hi, 
Let's say I have this log:
```
time: 12.00, room_id:1, action:open
time: 12.10, room_id:2, action:open
time: 12.20, room_id:3, action:open
time: 12.30, room_id:1, action:close
time: 12.40, room_id:4, action:open
```
And my frequency rule is like this:
``` 
name: freq rule
type: frequency
index: rooms-*
num_events: 1
timeframe:
  hours: 2
filter:
- term:
    action: "open"
- term:
    action: "close"
query_key:
 - room
alert:
- "slack"
slack:
slack_webhook_url: "https://hooks.slack.com/services/blahaaaaaaaa"
```

I want to have one alert, not five.
What I want is "if there is an action 'open' and 'close' for a room in less than 2 hours, alert"
Is that possible? Because I've thinking on this a lot without success.
Help!
