### ISSUE TITLE
Issue related with frequency alert and related_events

### ISSUE THREAD

**Issue by alvarolmedo** [Yelp/elastalert#2749]
Hello @Qmando,

We've observed than num_events limit the size of related_events.
For example, when you obtain 10 documents in query execution during an interval and the threshold (num_events) is set to 5, only 5 documents are attached in the alert: 1 on the match and the other 4 in the related_events list attached inside the match.

In our opinion, 10 documents would be attached in the alert: 1 on the match and the other 9 in the related_events lists.

We are doing something wrong?
```
type: frequency
use_count_query: false
doc_type: doc
num_events: 3
timeframe:
  seconds: 300
index: kafka_cloudera-%Y.%m.%d
use_strftime_index: True
filter:
- query:
    query_string:
      query: 'VarName:"minutos_accepted" AND NumValue:>3'
query_key: "VarName"
attach_related: true
realert:
  minutes: 0
```
