### ISSUE TITLE
Getting No such file or directory: 'config.yaml' when running from elastalert-server

### ISSUE THREAD

**Issue by tbhaxor** [Yelp/elastalert#2761]
The complete log is here

```
12:38:19.029Z ERROR elastalert-server:
    ProcessController:  Traceback (most recent call last):
      File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
        "__main__", mod_spec)
      File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
        exec(code, run_globals)
      File "/usr/local/lib/python3.6/dist-packages/elastalert/create_index.py", line 268, in <module>
        main()
      File "/usr/local/lib/python3.6/dist-packages/elastalert/create_index.py", line 215, in main
        host = args.host if args.host else input('Enter Elasticsearch host: ')
    EOFError: EOF when reading a line
    
12:38:19.029Z ERROR elastalert-server: ProcessController:  Index create exited with code 1
12:38:19.029Z  WARN elastalert-server: ProcessController:  ElastAlert will start but might not be able to save its data!
12:38:19.030Z  INFO elastalert-server: ProcessController:  Starting elastalert with arguments [none]
12:38:19.042Z  INFO elastalert-server: ProcessController:  Started Elastalert (PID: 5656)
12:38:19.045Z  INFO elastalert-server: Server:  Server listening on port 3030
12:38:19.046Z  INFO elastalert-server: Server:  Websocket listening on port 3333
12:38:19.046Z  INFO elastalert-server: Server:  Server started
12:38:19.589Z ERROR elastalert-server:
    ProcessController:  Traceback (most recent call last):
      File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
        "__main__", mod_spec)
      File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
        exec(code, run_globals)
      File "/usr/local/lib/python3.6/dist-packages/elastalert/elastalert.py", line 2055, in <module>
        sys.exit(main(sys.argv[1:]))
      File "/usr/local/lib/python3.6/dist-packages/elastalert/elastalert.py", line 2049, in main
        client = ElastAlerter(args)
      File "/usr/local/lib/python3.6/dist-packages/elastalert/elastalert.py", line 138, in __init__
        self.conf = load_conf(self.args)
      File "/usr/local/lib/python3.6/dist-packages/elastalert/config.py", line 45, in load_conf
        conf = yaml_loader(filename)
      File "/usr/local/lib/python3.6/dist-packages/PyStaticConfiguration-0.10.4-py3.6.egg/staticconf/loader.py", line 167, in yaml_loader
        with open(filename) as fh:
    FileNotFoundError: [Errno 2] No such file or directory: 'config.yaml'
    
12:38:19.702Z ERROR elastalert-server: ProcessController:  ElastAlert exited with code 1
```

**Comment by tbhaxor** [comment]
It seems the issue with elastalert not elastaler-server

**Comment by nsano-rururu** [comment]
@tbhaxor 

I will answer on the assumption that it is started with Docker. If you made a mistake, please tell me the correct information.

■ Error "No such file or directory: 'config.yaml'"

It says that there is no config.yaml file.
It looks like the directory and files are not ready.

■ About Elast Alert Server

For Docker image "bitsensor/elastalert: 3.0.0-beta.0" or "servercentral/elastalert: latest",
It will have ElastAlert made in Python and ElastAlert Server made in Node.js installed.

ElastAlert Server is started at the last ENTRYPOINT ["npm", "start"] of Dockerfile of bitsensor/elastalert.
Connect to ElasticSearch of "es_host" in the configuration file, and if the Index used by ElastAlert has not been created yet,
Create 4 indexes in ElasticSearch.
https://github.com/bitsensor/elastalert/blob/master/Dockerfile

■ Directory configuration example for bitsensor/elastalert:3.0.0-beta.0

rule_templates and rules must be authorized with chmod 777
Download config.json, elastalert-test.yaml, elastalert.yaml from the following sites
"es_host" of 3 files is changed to service name when started with docker-compose
https://github.com/bitsensor/elastalert/tree/master/config

```
|--elastalert
|  |--config
|  |  |--config.json
|  |  |--elastalert-test.yaml
|  |  |--elastalert.yaml
|  |--rule_templates
|  |--rules
```

■Directory configuration example for servercentral/elastalert: latest

rule_templates and rules must be authorized with chmod 777
Download api.config.json and elastalert.yaml from the following sites
"es_host" of 2 files is changed to service name when started with docker-compose
https://github.com/ServerCentral/praeco/tree/master/config
```
|--elastalert
|  |--config
|  |  |--api.config.json
|  |  |--elastalert.yaml
|  |--rule_templates
|  |--rules
```

**Comment by nsano-rururu** [comment]
@tbhaxor 

Sample to launch Elasticsearch, Kibana, ElastAlert, Praeco with docker-compose

■Command execution

```
mkdir docker-work
cd docker-work
mkdir elastalert-docker
cd elastalert-docker
mkdir Dockerfiles
vi Dockerfiles/Dockerfile.elastalert
```

■Dockerfiles/Dockerfile.elastalert

```
FROM servercentral/elastalert:latest

USER root

RUN apk update && \
    apk add bash curl && \
    rm -rf /var/cache/apk/*

ADD praeco/bin/elastalert-start.sh /usr/local/bin/
ADD praeco/bin/elastic_search_status.sh /usr/local/bin/

RUN chmod +x /usr/local/bin/elastalert-start.sh 

USER node

ENTRYPOINT ["/usr/local/bin/elastalert-start.sh"]
```

■Command execution

```
mkdir -p elasticsearch/config
vi elasticsearch/config/elasticsearch.yml
```

■elasticsearch/config/elasticsearch.yml

```
cluster.name: "docker-cluster"
network.host: 0.0.0.0
discovery.zen.minimum_master_nodes: 1
```

■Command execution

```
mkdir -p elasticsearch/data
chmod 777 elasticsearch/data
mkdir -p kibana/config
vi kibana/config/kibana.yml
```

■kibana/config/kibana.yml

```
server.name: kibana
server.host: "0"
elasticsearch.hosts: http://elasticsearch:9200
xpack.monitoring.ui.container.elasticsearch.enabled: true
```
■Command execution

```
mkdir -p praeco/bin
vi praeco/bin/elastalert-start.sh
```

■praeco/bin/elastalert-start.sh

```
#!/bin/bash

set -e

echo "Giving Elasticsearch at $ELASTICSEARCH_URL time to start..."

elastic_search_status.sh

echo "Starting ElastAlert!"
npm start
```
■Command execution

```
vi praeco/bin/elastic_search_status.sh
```

■praeco/bin/elastic_search_status.sh

```
#!/bin/bash

set -e

if [ $# -gt 0 ]; then
  ES_URL="$1"
elif [[ -n $ELASTICSEARCH_URL ]]; then
  ES_URL="$ELASTICSEARCH_URL"
elif [[ -n $ES_HOST ]] && [[ -n $ES_PORT ]]; then
  ES_URL="http://$ES_HOST:$ES_PORT"
else
  ES_URL="http://elasticsearch:9200"
fi

until [[ "$(curl -fsSL "$ES_URL/_cat/health?h=status" | sed -r 's/^[[:space:]]+|[[:space:]]+$//g')" =~ ^(yellow|green)$ ]]; do
  # printf '+' >&2
  sleep 1
done

echo "Elasticsearch is up and healthy at "$ES_URL"" >&2
```

■Command execution

```
mkdir -p praeco/config
mkdir -p praeco/nginx_config
mkdir -p praeco/public
mkdir -p praeco/public/js
mkdir -p praeco/rule_templates
chmod 777 praeco/rule_templates
mkdir -p praeco/rules
chmod 777 praeco/rules
cd praeco/config
wget https://raw.githubusercontent.com/ServerCentral/praeco/master/config/api.config.json
wget https://raw.githubusercontent.com/ServerCentral/praeco/master/config/elastalert.yaml
cd ../
cd nginx_config
wget https://raw.githubusercontent.com/ServerCentral/praeco/master/nginx_config/default.conf
wget https://raw.githubusercontent.com/ServerCentral/praeco/master/nginx_config/nginx.conf
cd ../
cd public/js
wget https://raw.githubusercontent.com/ServerCentral/praeco/master/public/js/cron-ui.min.js
cd ../
wget https://github.com/ServerCentral/praeco/blob/master/public/favicon.ico
wget https://raw.githubusercontent.com/ServerCentral/praeco/master/public/index.html
wget https://raw.githubusercontent.com/ServerCentral/praeco/master/public/praeco.config.json
cd ../../

vi docker-compose.yml
```

■docker-compose.yml

```
version: "3.7"
services:
  elasticsearch:
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:7.5.2
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      - ES_JAVA_OPTS=-Xms128m -Xmx256m
      - discovery.type=single-node
    restart: always
    volumes:
      - ./elasticsearch/data:/usr/share/elasticsearch/data
      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    healthcheck:
        test: ["CMD-SHELL", "curl -f http://localhost:9200 || exit 1"]
        interval: 30s
        timeout: 15s
        retries: 3
        start_period: 180s

  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:7.5.2
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch
    restart: always
    volumes:
      - ./kibana/config/kibana.yml:/usr/share/kibana/config/kibana.yml
    healthcheck:
        test: ["CMD-SHELL", "curl -f http://localhost:5601/api/status || exit 1"]
        interval: 30s
        timeout: 15s
        retries: 3
        start_period: 200s

  elastalert:
    container_name: elastalert
    build:
      context: .
      dockerfile: Dockerfiles/Dockerfile.elastalert
    image: elastalert:0.2.1
    ports:
      - 3030:3030
      - 3333:3333
    depends_on:
      - elasticsearch
    restart: always
    volumes:
      - ./praeco/config/elastalert.yaml:/opt/elastalert/config.yaml
      - ./praeco/config/api.config.json:/opt/elastalert-server/config/config.json
      - ./praeco/rules:/opt/elastalert/rules
      - ./praeco/rule_templates:/opt/elastalert/rule_templates
    healthcheck:
        test: ["CMD-SHELL", "curl -f http://localhost:3030 || exit 1"]
        interval: 30s
        timeout: 15s
        retries: 3
        start_period: 200s

  praeco:
    container_name: praeco
    image: servercentral/praeco:latest
    ports:
      - 8080:8080
    depends_on:
      - elastalert
    restart: always
    volumes:
      - ./praeco/public/praeco.config.json:/var/www/html/praeco.config.json
      - ./praeco/nginx_config/nginx.conf:/etc/nginx/nginx.conf
      - ./praeco/nginx_config/default.conf:/etc/nginx/conf.d/default.conf    
    healthcheck:
        test: ["CMD-SHELL", "curl -f http://localhost:8080 || exit 1"]
        interval: 30s
        timeout: 15s
        retries: 3
        start_period: 200s
```

■Command execution

```
docker-compose up -d
```
