### ISSUE TITLE
Q: Silence based on a `match_body` field?

### ISSUE THREAD

**Issue by naseemkullah** [Yelp/elastalert#2777]
Hello,

we have been very happily using ElastAlert in our production kubernetes environment for almost two years.

We've been very basic with our approach, and have a catch all rule to alert whenever there is a structured log emitted with the `level: error` key value.

Recently an issue where noise emitted by a certain workload has led us to look into silencing alerts.

As per https://elastalert.readthedocs.io/en/latest/elastalert_status.html#silence it does not appear that `match_body.x.y.z` can be used as a parameter to target silences.

Could this please be confirmed? Would the approach then be to break up our catch all `level: error` alert into many granular alerts based on other fields of the emitted structured logs?

For reference our catch all error, which requires granular silencing (via `match_body` fields) is:

```
    name: "Error"
    type: any
    index: "*"
    filter:
    - term:
        level: "error"
    alert:
    - "slack"
```

An example of how an alert could (ideally, if possible) be targetted for silence:

![image](https://user-images.githubusercontent.com/24660299/80833139-f98af480-8bbb-11ea-8ab4-3757289e0a3f.png)

**Comment by JasperJuergensen** [comment]
When you have a query_key in the rule silencing can be done based on the values of this query_key. For example if you have the query_key `kubernetes.labels.app_kubernetes_io/component` you can silence the rule only for a specific value in this field. Thius happens for the realert timeframe. If you want to do this by hand, you have to add a document to the elasticsearch silence index manually because this is not supported by the --silence option. The silence_key (in the elasticsearch document saved in the rule_name field) is then `<rule_name>.<query_key_value>`.

**Comment by naseemkullah** [comment]
Thanks @JasperJuergensen!

With regards to this, I realized our logger does emit a field `name` for the instrumented service which I will leverage as follows:

```
    name: "Error"
    type: any
    index: "*"
    filter:
    - term:
        level: "error"
    query_key: name
    alert:
    - "slack"
```

I will then confirm that I can granularly silence alert depending on the value of their `name` field at which point I will resolve this issue.
