### ISSUE TITLE
How can I received alert for each hit?

### ISSUE THREAD

**Issue by BangShinChul** [Yelp/elastalert#2805]
Hello. 
I'm using elastalert to monitor service exceptions.

I set up to attach a unique message for each alerts, so I need to be notified for each hit.
but I found that my alert are sent overlapping look like below.

```
My Alert
Access Log Status 500 Check Alarm
@timestamp: 2020-05-12T17:00:47.572000+09:00
_id: NfXmB3IB5y4dyA0AnAdA
_index: access_log-2020.05.
_type: _doc
message: <my unique message>
num_hits: 34
num_matches: 9
status: 500
table: access_log
tag: access_log
txId: 043e6c21-c2fe-43c7-a9c7-85d2986e03ea
type: failed
userId: None
```

I want to be received alert for each hit.
Below is the contents of the config.yaml file I set.

```
rules_folder: /home/elastalert/rules
es_host: <my-ip>
es_port: <my-port>
run_every:
  seconds: 10
buffer_time:
  minutes: 5
use_ssl: False
disable_rules_on_error: false
writeback_index: elastalert_status
writeback_alias: elastalert_alerts
alert_time_limit:
  days: 1
```

How should I fix it so that it works for me?
Thank you.
