### ISSUE TITLE
Can't user alerter POST with username:password

### ISSUE THREAD

**Issue by Theoooooo** [Yelp/elastalert#2830]
I was trying to setup a post alerter to send data to another elasticsearch indice for a specific project, but it seems i can't make this plugin work with username/password authentication.

There is no option whatsoever about this apart using the authorization, which is not usefull if you never authenticate first to retreive your token or something else.

I didn't really wanted to create a new alerter to point to an elasticsearch cluster but it seems i will need to ...

Putting the username:password inside the URL with @ doesn't work in this case, because elasticsearch check the URL upon indexing and reject this type of authentication

My configuration file so far :
```
name: "Alerte HTTP JSON Loadout Agent Restart or Added"
type: any
index: json_wazuh-%Y-%m-%d
use_strftime_index: true

filter:
- query:
    query_string:
      query: 'rule.id: [501 TO 503]'

realert:
  minutes: 0

alert: post
http_post_url : "http://x.x.x.x:9200/json_alerting/_doc/"
http_post_static_payload:
  acknowledge: "false"
  type: "wazuh"
http_post_headers:
  Content-Type: application/json
```
