### ISSUE TITLE
How to use SSL encryption port 465 to configure email alerts in Elastalert?

### ISSUE THREAD

**Issue by BadboyXMP** [Yelp/elastalert#2833]
I use Elastalert as an alarm plug-in on Alibaba Cloud. How do I configure SSL alarms using SSL encryption port 465 in Elastalert? Alibaba Cloud does not support the 25 port email alert method

**Comment by nsano-rururu** [comment]
What kind of setting did you make?

**Comment by nsano-rururu** [comment]
For gmail, see below
https://github.com/Yelp/elastalert/issues/627#issuecomment-727515367

**Comment by nsano-rururu** [comment]
When using'smtp.mail.yahoo.co.jp' for smtp_host

```yaml
smtp_host: 'smtp.mail.yahoo.co.jp'
smtp_port: 465 
smtp_ssl: true
smtp_auth_file: '/opt/elastalert/pass/smtp_auth_user.yaml'
```

smtp_auth_user.yaml

```yaml
user: xxx@yahoo.co.jp
password: xxx
```
