### ISSUE TITLE
Setting PagerDuty severity not working

### ISSUE THREAD

**Issue by n8gard** [Yelp/elastalert#2834]
I have read the docs, googled, and experimented. Regardless of how I configure, I can only get alerts to PagerDuty that have "HIGH" severity set. The docs say you can set "critical", "warning", "info", etc. I have looked at PagerDuty's API doc and 'info' is a valid severity. But, invariably, my alerts hit PD and are set to 'HIGH'. I have tried `v1` and `v2` rule configurations.

My rule config is below:
```yaml
alert:
  - pagerduty

alert_subject: "a very silly rule"

pagerduty_api_version: v2
pagerduty_v2_payload_severity: info
pagerduty_client_name: elastalert_poc
pagerduty_service_key: xxxabc123xxx
```

EDIT:
1. added clarity to Issue subject
2. addd note about reviewing PD's API doc
