### ISSUE TITLE
Elastalert always use elastalert_status_silence with POST alerter

### ISSUE THREAD

**Issue by Theoooooo** [Yelp/elastalert#2837]
While using the POST alerter to a valid HTTP endpoint (which respond as well at the http request by Elastalert), Elastalert will always assume nothing happened after the alert triggered. It's like he assume no alert has been sent but the POST query was successful.

Configuration File :
 ```
name: "Alerte HTTP JSON Loadout Agent Restart or Added"
type: any
index: json_wazuh-%Y-%m-%d
use_strftime_index: true

filter:
- query:
    query_string:
      query: 'rule.id: [501 TO 503]'

realert:
  minutes: 0

alert: post
http_post_url : "http://172.31.27.19:15001/api/gateway_alerter"
http_post_static_payload:
  alerter: "rule_test_ajout_agent_http_loadout.yaml"
  type: "Wazuh"
  acknowledge: "false"
http_post_headers:
  Content-Type: application/json
```

Don't take in account the error of the index not being available. I was having issue creating only the silence index. But it's the only alerter configuration which behave like this. I got other alerts who send mail as alert and doesn't have to use the elastalert_status_silence for this.

ElastAlert output :

Jun 04 09:30:22 centos elastalert[22585]: INFO:elastalert:Sleeping for 19.999552 seconds
Jun 04 09:30:23 centos elastalert[22585]: INFO:elastalert:Queried rule Alerte HTTP JSON Loadout Agent Restart or Added from 2020-06-04 09:29 CEST to 2020-06-04 09:30 CEST: 1 / 1 hits
Jun 04 09:30:23 centos elastalert[22585]: WARNING:elasticsearch:GET http://172.31.27.7:9200/elastalert_status_silence/_search?_source_includes=until%2Cexponent&size=1 [status:404 request:0.011s]
Jun 04 09:30:23 centos elastalert[22585]: ERROR:root:Error while querying for alert silence status: NotFoundError(404, 'index_not_found_exception', 'no such index [elastalert_status_silence]', elastalert_s... index_or_alias)
Jun 04 09:30:23 centos elastalert[22585]: WARNING:elasticsearch:GET http://172.31.27.7:9200/elastalert_status_silence/_search?_source_includes=until%2Cexponent&size=1 [status:404 request:0.013s]
Jun 04 09:30:23 centos elastalert[22585]: ERROR:root:Error while querying for alert silence status: NotFoundError(404, 'index_not_found_exception', 'no such index [elastalert_status_silence]', elastalert_s... index_or_alias)
Jun 04 09:30:23 centos elastalert[22585]: INFO:elastalert:HTTP Post alert sent.
Jun 04 09:30:23 centos elastalert[22585]: INFO:elastalert:Ran Alerte HTTP JSON Loadout Agent Restart or Added from 2020-06-04 09:29 CEST to 2020-06-04 09:30 CEST: 1 query hits (0 already seen), 1 matches, 1 alerts sent
