### ISSUE TITLE
Error checking metric_aggregation rule

### ISSUE THREAD

**Issue by LazarenkoA** [Yelp/elastalert#2852]
What have I done wrong?

````yaml
/opt/elastalert/rules/excp_Aggregation.yaml                                                                                                                                 559/559               100%
name: "excp_aggregation"
type: metric_aggregation
index: log1c-*


buffer_time:
  hours: 1

metric_agg_key: "t:computerName"
metric_agg_type: value_count
doc_type: _doc
max_threshold: 5

filter:
- query:
    - query_string:
        query: "Descr: \"...................\""
- term:
    type: "log1c-excp"




alert:
  - "command"
....
````

`Error running your filter:
TypeError("search() got multiple values for argument 'body'",)
1 rules loaded
INFO:apscheduler.scheduler:Adding job tentatively -- it will be properly scheduled when the scheduler starts
Traceback (most recent call last):
  File "/usr/local/bin/elastalert-test-rule", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/site-packages/elastalert/test_rule.py", line 445, in main
    test_instance.run_rule_test()
  File "/usr/local/lib/python3.6/site-packages/elastalert/test_rule.py", line 437, in run_rule_test
    self.run_elastalert(rule_yaml, conf, args)
  File "/usr/local/lib/python3.6/site-packages/elastalert/test_rule.py", line 318, in run_elastalert
    client.run_rule(rule, endtime, starttime)
  File "/usr/local/lib/python3.6/site-packages/elastalert/elastalert.py", line 884, in run_rule
    if not self.run_query(rule, rule['starttime'], tmp_endtime):
  File "/usr/local/lib/python3.6/site-packages/elastalert/elastalert.py", line 631, in run_query
    data = self.get_hits_aggregation(rule, start, end, index, rule.get('query_key', None))
  File "/usr/local/lib/python3.6/site-packages/elastalert/elastalert.py", line 565, in get_hits_aggregation
    body=query, size=0, ignore_unavailable=True)
  File "/usr/local/lib/python3.6/site-packages/elasticsearch/client/utils.py", line 92, in _wrapped
    return func(*args, params=params, headers=headers, **kwargs)
TypeError: deprecated_search() got an unexpected keyword argument 'headers'`
