### ISSUE TITLE
How to push to relevant person in charge based on service name？

### ISSUE THREAD

**Issue by wajika** [Yelp/elastalert#2868]
```
filter:
- term:
    http.response.status_code: "500"
- term:
    service.name: "A or B or C"   

A: xx1
B: xx2
C: xx3

```
If the information found is A service, then send to xx1
If the information found is B service, then send to xx2
