### ISSUE TITLE
how to configure elastalerts rule for multiple hosts

### ISSUE THREAD

**Issue by appleajay** [Yelp/elastalert#2870]
I have multiple machines where beat are  running.
I want to get alert for login abuse of these machine, i have configure a rule(type=frequency) to check for login abuse for 3 in 5 minutes. following is the rule for the same.
```
filter:
- term:
    fields.application: "mysql_audit"
- term:
    log.operation: "FAILED_CONNECT"
- query:
    query_string:
      query: " NOT log.retcode: 1158"
```

It is working fine, but if i have login abuse at machine1 machine2 and then machine1 it generate an alert, which is not the use case of mine,
Is there any  way that i can distinguish between the above three events and only generate the alert if it comes from a single machine thrice in 5 minutes.
