### ISSUE TITLE
Trouble pulling the host name for a flatline check

### ISSUE THREAD

**Issue by CommanderTso** [Yelp/elastalert#2875]
Hi folks!

Thank you for this tool - it's been extremely helpful, and is a big improvement over Watcher.

I'm having trouble understanding exactly what data comes back from Elasticsearch to use in my flatline alert.  Here's the current alert:

```
name: "Lustre Node - No Data"
type: "flatline"
threshold: 1
timeframe:
  minutes: 1
realert:
  minutes: 0
doc_type: "doc"
query_key: host.name
forget_keys: false
index: "metricbeat-storage*"
timestamp_field: "@timestamp"
alert_subject: "No data from Lustre node {} for pattern {}"
alert_subject_args:
- key
- "index"
alert:
  - pagerduty
pagerduty_service_key: XXXXXXXXXXXXXXXXXXXXXXXXXX
pagerduty_client_name: "ElastAlert"
pagerduty_event_type: "trigger"
pagerduty_incident_key: hostname
pagerduty_api_version: "v2"
pagerduty_v2_payload_class: "lustre flatline failure"
pagerduty_v2_payload_severity: "critical"
pagerduty_v2_payload_source: hostname
```

My issue has been in trying to pull in the flatlined host's name to use in the alert, both as a dedup key and in order to add that data to the subject line.

I can't get things like `beat.name` and `host.name` (which I'd expect to be present in a metricbeat record of the kind it's checking) to show up.  I managed to get `key` to work for adding this data to the alert subject, but still can't get anything to work for adding to the `pagerduty_v2_payload_source` or `pagerduty_incident_key`.  I've reviewed the documentation, but if it's there, I'm missing it.

My question then is, how can I know what fields and field names are available to me in building out the data I send to PagerDuty from a flatline check?

Thanks!
