### ISSUE TITLE
percentage_match rule is sending false alert rules

### ISSUE THREAD

**Issue by bperel** [Yelp/elastalert#2882]
I would like to trigger an alert when Nginx logs have more than 3% of HTTP 500. However, I receive the notification even when, according to my filter, the threshold is not reached. Here is my rule:

```yaml
name: Too many HTTP 500
type: percentage_match

index: journalbeat-*
description: "No more than 3% of all http requests should respond HTTP 500"

filter:
- query:
    query_string:
      query: "not http.request_url: '/v1/test' AND container.name: *nginx"

buffer_time:
  minutes: 3

realert:
  minutes: 0

doc_type: _doc

match_bucket_filter:
- query_string:
    query: "http.status_code: 500"

max_percentage: 3

alert:
  - "googlechat"

alert_text: |
  There were more than 3% of HTTP 500 responses in this period ({0}% of all {1} HTTP requests).
alert_text_args:
  - percentage
  - denominator
alert_text_type: alert_text_only
```

I receive this false alert at each of the 3-minute interval, for instance:
`There were more than 3% of HTTP 500 responses in this period (5.555555555555555% of all 108 HTTP requests).`

However, when I run the query in Kibana, I don't have any results, even during the last 30 minutes.
![image](https://user-images.githubusercontent.com/1484692/87135154-f423e780-c299-11ea-9d83-90678db84824.png)
