### ISSUE TITLE
Paths in a blacklist file don't work

### ISSUE THREAD

**Issue by ty-sop** [Yelp/elastalert#2887]
Hi,

I have a blacklist rule that performs detection on Windows scheduled task paths. I have several paths stored in a file, and I want an alert to be raised when a log containing this path appears.

Currently my rule looks like this:
```
name: windowsTaskExample

type: blacklist

index: index-*

compare_key: TaskName

blacklist:
- "!file /path/to/blacklist/file"

filter:
- query:
    query_string:
        query: "EventID: 4702"

alert: debug
```

My blacklist file looks like this :
```
- "\\Microsoft\\Windows\\WS\\Licence Validation"
- "\\Microsoft\\Windows\\..."
[...]
```
I can't get any matches with that, but when I set a path as a value for the blacklist field as below. The rule works and I got matches.
```
blacklist:
- "\\Microsoft\\Windows\\WS\\Licence Validation"
- "!file /path/to/blacklist/file"
```

The paths contained in the file must have a specific format to work? 
I tried several formats, without the `-`, without the quotes, without escaping the backslashes, but nothing worked.

Any ideas why it works when the paths are specified as a value for the blacklist field and it doesn't work when the paths are in a file ?
