### ISSUE TITLE
Is it possible to don't repeat alerts with the same query but potentially different error content?

### ISSUE THREAD

**Issue by denisgranha** [Yelp/elastalert#2927]
Hi!

I tried to figure this out by reading the documentation and past issues but couldn't figure out the answer, it seems to not be possible at the moment.

We have a rule with the following definition:
```
# (Required)
# Type of alert.
# the frequency rule type alerts when num_events events occur with timeframe time
type: any

# (Required)
# Index to search, wildcard supported
index: logstash-*
include: ["kubernetes.labels.app", "log"]

# (Required)
# A list of Elasticsearch filters used for find events
# These filters are joined with AND and nested in a filtered query
# For more info: http://www.elasticsearch.org/guide/en/elasticsearch/reference/current/query-dsl.html
filter:
- query:
    query_string:
      query: 'kubernetes.labels.app:"dev-safe-transaction-service" AND log:"ERROR"'
```

It's a general rule for all messages with ERROR level. Would it be possible to don't repeat errors with the same error content during a certain timeframe but show errors with the same query but different error content?

for example. "ERROR issue 1" and "ERROR issue2"

By looking at realert, having the same query if error 1 it's triggered, error 2 would be shadowed and that's not desirable

Thank you very much!
