### ISSUE TITLE
Rule works in debug mode but not in production  

### ISSUE THREAD

**Issue by saurabhPV** [Yelp/elastalert#2928]
config file -
```
.
.
run_every:
  minutes: 1

buffer_time:
  minutes: 10

alert_time_limit:
  days: 2
.
.
```

Rule file - 

```
alert:
- alerta
alert_missing_value: '-'
alerta_api_url: my-server-url
alerta_attributes_keys:
- d-event_timestamp
alerta_attributes_values:
- '%(@timestamp)s'
alerta_correlate: []
alerta_environment: Prod
alerta_event:  is_winter_coming?
alerta_group: BS
alerta_origin: '41'
alerta_resource: elastalert
alerta_service:
- elastalert
alerta_severity: minor
alerta_tags: []
alerta_text: winter is coming
alerta_type: frequency
es_host: some-ip
es_port: 9200
filter:
- query:
    query_string:
      query: 'a simple filter'
index: stark-*
name: winterfell
num_events: 1
realert:
  minutes: 120
timeframe:
  minutes: 2
type: frequency
```
> Yeah I know, it doesn't make sense to use frequency for one event, but I have tested it with `Any` type too 

In kibana I can see there is a data for this period - 

![data](https://user-images.githubusercontent.com/15213067/90547156-af4c7400-e1a8-11ea-9fcd-25294ac17851.png)

However there was no alert , and as expected on Kiban rule status was -
 
![elastalert status](https://user-images.githubusercontent.com/15213067/90547298-ecb10180-e1a8-11ea-9eb2-5867b4625a8f.png)

So when I tested it for the same duration with `elastalert-test-rule` I got hits and match! 

```
Would have written the following documents to writeback index (default is elastalert_status):

silence - {'exponent': 0, 'rule_name': 'is_winter_coming?', '@timestamp': datetime.datetime(2020, 8, 18, 17, 43, 30, 835490, tzinfo=tzutc()), 'until': datetime.datetime(2020, 8, 18, 19, 43, 30, 835477, tzinfo=tzutc())}

elastalert_status - {'rule_name': 'is_winter_coming?', 'endtime': datetime.datetime(2020, 8, 18, 4, 4, 22, tzinfo=<UTC>), 'starttime': datetime.datetime(2020, 8, 18, 4, 3, 22, tzinfo=<UTC>), 'matches': 5, 'hits': 5, '@timestamp': datetime.datetime(2020, 8, 18, 17, 43, 30, 838319, tzinfo=tzutc()), 'time_taken': 0.01810431480407715}

```

I have observed such behavior in other rules as well. 
I have around 200 rules. have I touched some limit here ? 
Earlier I used to run these in single docker container but for now I am running these in 3 different containers on same host and they all write to different index on es.
