### ISSUE TITLE
metric_aggregation rule type doesn't hit any log.

### ISSUE THREAD

**Issue by GuidoCantalupo** [Yelp/elastalert#2932]
Hello, i'm trying to write a rule which alert if :
- CPU usage is at 100% during a period of 5 minutes and keep constant.

This is my rule: 
```
name: CPU Usage
type: metric_aggregation
index: metricbeat*

buffer_time:
  minutes: 5

metric_agg_key: system.cpu.total.pct
metric_agg_type: avg
query_key: cloud.instance.id.keyboard
doc_type: doc

bucket_interval:
  minutes: 5

sync_bucket_interval: true
max_threshold: 0.999

filter:
- term:
    metricset.name: cpu

alert:
- "email"
```

My approach is to get the AVG of system.cpu.total.pct during a period of 5 minutes and check if it is higher than 0.999

The issue that i'm having is that this rule doesn't hit any log and i don't know why.
Appreciate if someone can help me to identify the issue of my rule and give me an advice.
Thanks y'all!!
