### ISSUE TITLE
Problem with Flatline

### ISSUE THREAD

**Issue by vennca** [Yelp/elastalert#2939]
Hello,
I have problem with Flatline rule. Rules is triggered but it shouldn't.

I run Elastalert with debug mode:

`/usr/bin/python3.6 -m elastalert.elastalert --es_debug --es_debug_trace trace.log --config /opt/elastalert/config.yaml --rule /opt/elastalert/rules/application-flatline-per-app-6.yml`

There is my **main config**:
`/opt/elastalert/config.yaml`

```
run_every:
  seconds: 30
buffer_time:
  minutes: 5
rules_folder: rules
use_ssl: true
es_host: ********
es_port: 9200
es_username: elastalert
es_password: *********
es_send_get_body_as: GET
writeback_index: elastalert_audit
```
**Rule**

`/opt/elastalert/rules/application-flatline-per-app-6.yml`
```

---
es_host: ********
es_port: 9200
es_username: elastalert
es_password: ******
name: "APP.flatline.momas - ***** - momas"
type: flatline
index: a-app
use_count_query: true
doc_type: "_doc"
scan_entire_timeframe: true
threshold: 1
timeframe:
  minutes: 15
filter:
- term:
    event.category: "app"
- query:
    query_string:
      query: "( app:\"momas\" OR event.provider:\"momas\")"    
alert:
- "command"
  
command: ["*****.",]
raw_count_keys: false
```

I found out that Elastalert is issuing these queres to Elasticsearch:
```

curl -H 'Content-Type: application/json' -XPOST 'http://localhost:9200/a-app/_doc/_count?pretty&ignore_unavailable=true' -d '{
  "query": {
    "bool": {
      "filter": {
        "bool": {
          "must": [
            {
              "range": {
                "@timestamp": {
                  "gt": "2020-08-25T08:58:25.304650Z",
                  "lte": "2020-08-25T08:58:50.716761Z"
                }
              }
            },
            {
              "term": {
                "event.category": "app"
              }
            },
            {
              "query_string": {
                "query": "( app:\"momas\" OR event.provider:\"momas\")"
              }
            }
          ]
        }
      }
    }
  }
}'



curl -H 'Content-Type: application/json' -XPOST 'http://localhost:9200/a-app/_doc/_count?pretty&ignore_unavailable=true' -d '{
  "query": {
    "bool": {
      "filter": {
        "bool": {
          "must": [
            {
              "range": {
                "@timestamp": {
                  "gt": "2020-08-25T08:58:50.716761Z",
                  "lte": "2020-08-25T08:59:20.605087Z"
                }
              }
            },
            {
              "term": {
                "event.category": "app"
              }
            },
            {
              "query_string": {
                "query": "( app:\"momas\" OR event.provider:\"momas\")"
              }
            }
          ]
        }
      }
    }
  }
}'


curl -H 'Content-Type: application/json' -XPOST 'http://localhost:9200/a-app/_doc/_count?pretty&ignore_unavailable=true' -d '{
  "query": {
    "bool": {
      "filter": {
        "bool": {
          "must": [
            {
              "range": {
                "@timestamp": {
                  "gt": "2020-08-25T08:59:20.605087Z",
                  "lte": "2020-08-25T08:59:45.758124Z"
                }
              }
            },
            {
              "term": {
                "event.category": "app"
              }
            },
            {
              "query_string": {
                "query": "( app:\"momas\" OR event.provider:\"momas\")"
              }
            }
          ]
        }
      }
    }
  }
}'
```

Can anyone help me what am I doing wrong or whether is it bug?

**Software:**
Elastalert 0.2.0 and 0.2.4
ES 7.8.0
