### ISSUE TITLE
num_hits - Number of hits is not displayed correctly

### ISSUE THREAD

**Issue by vennca** [Yelp/elastalert#2941]
Hello,
my rule configuration is:

```
es_host: ********
es_port: 9200
es_username: elastalert
es_password: *********
name: "a-web - lorem ipsum - WEB.5xx-detection"
type: frequency
use_count_query: true
doc_type: "_doc"
index: a-web
scan_entire_timeframe: true
num_events: 200
timeframe:
  minutes: 15
filter:
- term:
    event.category: "web"
- term:
    env: "prod"
- query:
    query_string:
      query: "http.response.status_code:>=500 AND http.response.status_code:<=599"

alert:
- "command"
command: ["/opt/elastalert/scripts/alert-warning.sh", "lorem-prisum;More than 200 (%(num_hits)s) hit(s) / last 15 min",]
raw_count_keys: false

```

**Output is:**
More than 200 (14) hit(s) / last 15 min

But if I issue query in Kibana or via curl tool I got more than 200 hits. 

Could anyone help me how to print number of hits correctly? Thank you.

**Software:**
Elastalert 0.2.0 and 0.2.4
ES 7.8.0
