### ISSUE TITLE
Logging to the file

### ISSUE THREAD

**Issue by vennca** [Yelp/elastalert#2942]
Hello,
can anyone help me with setting logging to file **/var/log/elastalert/elastalert.log**?

I have this configuration but it doesn't work:

**/opt/elastalert/config.yaml**

run_every:
  seconds: 30
buffer_time:
  minutes: 5
rules_folder: rules
use_ssl: true
es_host: ********
es_port: 9200
es_username: elastalert
es_password: **********
es_send_get_body_as: GET
writeback_index: elastalert_audit
```

logging:
  version: 1
  incremental: false
  disable_existing_loggers: false
  formatters:
    logline:
      format: '%(asctime)s %(levelname)+8s %(name)+20s %(message)s'

    handlers:
      console:
        class: logging.StreamHandler
        formatter: logline
        level: DEBUG
        stream: ext://sys.stderr

      file:
        class : logging.FileHandler
        formatter: logline
        level: DEBUG
        filename: /var/log/elastalert/elastalert.log

    loggers:
      elastalert:
        level: DEBUG
        handlers: []
        propagate: true

      elasticsearch:
        level: DEBUG
        handlers: []
        propagate: true

      elasticsearch.trace:
        level: DEBUG
        handlers: []
        propagate: true

      '':  # root logger
        level: DEBUG
        handlers:
          - console
          - file
        propagate: false
```

```
[root@alerter-as1 elastalert]# systemctl status elastalert
● elastalert.service - Elastalert
   Loaded: loaded (/etc/systemd/system/elastalert.service; enabled; vendor preset: disabled)
   Active: active (running) since St 2020-08-26 09:39:47 CEST; 13min ago
 Main PID: 26064 (python3.6)
   CGroup: /system.slice/elastalert.service
           └─26064 /usr/bin/python3.6 -m elastalert.elastalert --config /opt/elastalert/config.yaml
```
