### ISSUE TITLE
Email alerts are not arriving when I add field "from_addr:"

### ISSUE THREAD

**Issue by ManuelFFF** [Yelp/elastalert#2953]
Hi,

First of all, thank the maintainers for this wonderful tool, which is a better option than the integrated alert tool that comes with ELK, much more extensive and flexible, and also free.

I just started exploring ElastAlert and I am testing the `email` alerts. Using the following config for a `frequency` alert, I am able to receive email alerts, but I'm trying to customize the content of the email as much as possible. The problem comes when I add the `from_addr:` field, then I don't get any errors in the console and apparently the mail is sent, but it is never received.

I think the problem may be where I am putting the field or that it is not being nested properly.

```
type: frequency
index: logstash-*
num_events: 5
timeframe:
  hours: 1
filter:
- term:
    alert.category.keyword: "Targeted Malicious Activity was Detected"
alert:
- "email"
     from_addr: "email address"
     alert_subject: "Alert: Malicious Activity was Detected"
email:
- "email address 1"
- "email address 2"
```

Please help.

Thank you

**Comment by nsano-rururu** [comment]
look

https://elastalert.readthedocs.io/en/latest/ruletypes.html#alerts

```
Options for each alerter can either defined at the top level of the YAML file, or nested within the alert name, allowing for different settings for multiple of the same alerter. For example, consider sending multiple emails, but with different ‘To’ and ‘From’ fields:

alert:
 - email
from_addr: "no-reply@example.com"
email: "customer@example.com"
versus

alert:
 - email:
     from_addr: "no-reply@example.com"
     email: "customer@example.com"
 - email:
     from_addr: "elastalert@example.com""
     email: "devs@example.com"
If multiple of the same alerter type are used, top level settings will be used as the default and inline settings will override those for each alerter.
```

**Comment by ManuelFFF** [comment]
Hi @nsano-rururu ,

Thank you for the link, which I tried and still I'm not receiving emails when define the "from address" field in the rule file. Any idea about what could be failing here?

Thank you

```
name: TEST frequency rule
type: frequency
index: logstash-*
num_events: 5
timeframe:
  hours: 1
filter:
- term:
    alert.category.keyword: "Targeted Malicious Activity was Detected"
alert_subject: "Alert: Malicious Activity was Detected"
alert:
 - email:
     from_addr: "alerts@example.com"
     email: "email address 1"
 - email:
     from_addr: "alerts@example.com"
     email: "email address 2"
```
