### ISSUE TITLE
Trigger alert when no query is empty

### ISSUE THREAD

**Issue by pbn4** [Yelp/elastalert#2963]
Hello I'm trying to create an alert for a case when ES does not contain any documents for a given query. Here's my initial approach:

```
    name: Logs missing rule
    index: logstash-*
    type: flatline
    query_key: ["kubernetes.labels.app"]
    threshold: 1
    timeframe:
      minutes: 5
    realert:
      minutes: 0
    use_count_query: true
    doc_type: _doc
    filter:
    - query:
        query_string:
          query: "kubernetes.labels.app: mylabel"
```
but unfortunately it does not work.

I have seen https://github.com/Yelp/elastalert/issues/2687 comments about flatline not working with ES7.8, so still searching for solution to this.
