### ISSUE TITLE
Getting <MISSING VALUE> in frequency type rule

### ISSUE THREAD

**Issue by justrishabh** [Yelp/elastalert#2966]
I'm getting missing value for the following configuration. Not sure if I'm missing anything or is not configured.

**# The alert looks like**
```
name: Account balance threshold is close
description: "Triggers when Account balance threshold is close"
type: frequency
use_strftime_index: true
index: logstash-*

filter:
- query:
    query_string:
      query: (sixt4.State.Result.AccountDetail.password:* OR sixt4.State.Result.AccountDetail.username*))) OR sixt4.State.Result.BookingStatus:'pending')"

num_events: 1

timeframe:
  minutes: 10

buffer_time:
  minutes: 5

query_key: [airline]

alert_text: |
    The account balance threshold have reached. The remaining balance is {0}
alert_text_args: ["Funds.Balance"]
alert_text_type: alert_text_only


alert: 
- "email"

email:

- "elastalert@example.com"
```

**And the email looks like**
```
The account balance threshold has reached. The remaining balance is <MISSING VALUE>
```
