### ISSUE TITLE
my rule can alertd at 'elastalert-test-rule' with '--alert',but not alert at 'elastalert'

### ISSUE THREAD

**Issue by watara** [Yelp/elastalert#2972]
Hello,I write a rule to watch nginx logs,the rule workd at 'elastalert-test-rule' mode with  '--alert', it send email success, but when I run it in 'elastalert',It is bad,I don't know why ,please help me.Thinks .

here is my  `config.yaml`:
```
rules_folder: /etc/elastalert/rules
run_every:
  minutes: 1
buffer_time:
  minutes: 15
es_host: 127.0.0.1
es_port: 9200
writeback_index: elastalert_status
writeback_alias: elastalert_alerts
alert_time_limit:
  days: 2
```
and here is my `rule.yaml`:
```
es_host: 127.0.0.1
es_port: 9200
name: 502 error
type: frequency
index: access-*
num_events: 10
timeframe:
  minutes: 1
filter:
- term:
    status: "502"
alert_text: "Nginx has {0} 502 now!"
alert_text_args:
  - num_hits
smtp_host: smtp.XXX.com
smtp_port: 25
smtp_auth_file: /etc/elastaler/smtp_auth_file.yaml
email_reply_to: XXX@XXX.com
from_addr: XXX@XXX.com
alert:
- email

email:
- "XXX@XXX.com"
```

when I run it with
