### ISSUE TITLE
elastalert not sending all the hits

### ISSUE THREAD

**Issue by antoniopafundi-yv** [Yelp/elastalert#2973]
Hi,
elastalert send only some alert, but it doesn't send all the hits. 
If I run `elastalert-test-rule --config config/elastalert_config.yaml rules/slack_alert_f1_sniff.yaml` I get instead all the hits.

This is my rule:
```
name: my_name

type: any

realert:
  minutes: 0

# (Required)
# Index to search, wildcard supported
index: my_index

filter:
- term:
    report_tags.keyword: "my_tag"
- term:
    fail: 1

# (Required)
# The alert is use when a match is found
alert:
- "slack"

slack:
# prod slack
slack_webhook_url: "mywebhook"

slack_emoji_override: ':warning:'
slack_parse_override: full

alert_subject: "Dashboard link: mylink"
alert_text: |
    Failure test: {0}
    @timestamp: {1}
    Box: {2} {3} {4} {5}
    Failure reason: {6}
    Slot: myslot
    Report tags: {8}

alert_text_type: alert_text_only
alert_text_args: ["test_name","@timestamp", "box_oem", "box_type", "box_model","box_ps_version", "failure_reason","slot","report_tags"]
```
