### ISSUE TITLE
Example for MS Teams notification

### ISSUE THREAD

**Issue by knightian** [Yelp/elastalert#3020]
I don't think MS Teams notifications worked.

I've tried every combination of config I can think of and elastalert just breaks completely.

Can you at least put an example config for us to try and start with?

**Comment by nsano-rururu** [comment]
I was able to notify MS Teams of an alert without any problems.
ElastAlert 0.2.4

```
alert:
  - ms_teams
ms_teams_alert_summary: Alert
ms_teams_theme_color: '#ff0000'
ms_teams_webhook_url: 'https://outlook.office.com/webhook/xxx'
```

![キャプチャ](https://user-images.githubusercontent.com/22293449/97795210-ea5a3180-1c46-11eb-91c8-9f56d117c68a.PNG)

**Comment by nsano-rururu** [comment]
[Webhook URL取得方法（Microsoft Teams）](https://faq.form.run/microsoftteams-webhook)

**Comment by nsano-rururu** [comment]
The rule was set and generated on the [Praeco](https://github.com/johnsusek/praeco) screen

```
 __praeco_full_path: a
__praeco_query_builder: >-
  {"query":{"logicalOperator":"all","children":[{"type":"query-builder-rule","query":{"rule":"message","selectedOperator":"contains","selectedOperand":"message","value":"Quit"}}]}}
alert:
  - ms_teams
alert_subject: a
alert_subject_args: []
alert_text: b
alert_text_args: []
filter:
  - query:
      query_string:
        query: 'message:Quit'
import: BaseRule.config
index: mariadblog-*
is_enabled: true
ms_teams_alert_summary: Alert
ms_teams_theme_color: '#ff0000'
ms_teams_webhook_url: >-
  https://outlook.office.com/webhook/xxx
name: a
num_events: 1
realert:
  minutes: 1
terms_size: 50
timeframe:
  minutes: 1
timestamp_field: '@timestamp'
timestamp_type: iso
type: frequency
use_strftime_index: false
```
