### ISSUE TITLE
Using nested field for timestamp_field

### ISSUE THREAD

**Issue by GrzegorzCzm** [Yelp/elastalert#3023]
Hi, 

I am trying to use nested timestamp_field, as base [Add support for nested timestamp fields #507](https://github.com/Yelp/elastalert/pull/507) it should works. I have spent two days with not success.

elastalert==0.2.4 

My mapping for elastalert messages
```
{
  "dynamic-elastalert" : {
    "aliases" : { },
    "mappings" : {
      "properties" : {
        "ip" : {
          "type" : "text"
        },
        "test" : {
          "type" : "date"
        },
        "user" : {
          "type" : "nested",
          "properties" : {
            "test" : {
              "type" : "date"
            },
            "username" : {
              "type" : "text"
            }
          }
        }
      }
    },
  (...)
        "provided_name" : "dynamic-elastalert"
      }
    }
  }
}

```
So I have field test with type date, and nested field user.test with type date. 

My rule is more or less like:
```
type: any # type of alert
index: dynamic-elastalert
timestamp_field: "user.test"                     <--  (1) not working, but using not nested field like 'timestamp_field: test' works fine
alert:
  - xxx_elastalert.alerters.IncidentAlerter
xxx_incident:
  title: "Nested alert: {ip}"
  type: "IPDEC"
  instance_id: " IPDEC:{ip}"
  description: "New IP login detected for {ip} ip detected."
  severity: "Critical"
 (...)
  timestamp_field: "user.test"
  category: ["Attack"]
  context:
  - name: "username"
    value: "user.username"
    type: "string"
    aggregation: append
  - name: "ip"
    value: "ip"
    type: "string"
```

Elastalert settings: 
```
run_every:
  seconds: 15
buffer_time:
  minutes: 15
writeback_index: elastalert_metadata
alert_time_limit:
  minutes: 2880
disable_rules_on_error: true
```

In general my rule should put new documents  to xxx_incident ES index when there is a match. It is run every 15sec. 

So when I put in my config (1): 
```timestamp_field: "user.test" ``` 
or without quotes then alert will not be generated. But when I do something like: 
```timestamp_field: test```
then not nested 'test' field is taken and alert is generated. 

Base on logs I can see that there is not hits when nested field is used. E.g. 
```
{"version": "1.0", "type": "log", "systemid": "xxx-elastalert", "system": "xxx-elastalert", "log": {"message": "GET https:/XXX/dynamic-elastalert/_search?_source_includes=user.test%2C%2A&ignore_unavailable=true&scroll=30s&size=10000 [status:200 request:0.022s]"}, "level": "INFO", "time": "2020-11-03T16:42:51.542Z"}
{"version": "1.0", "type": "log", "systemid": "xxx-elastalert", "system": "xxx-elastalert", "log": {"message": "> {\"query\":{\"bool\":{\"filter\":{\"bool\":{\"must\":[{\"range\":{\"user.test\":{\"gt\":\"2020-11-03T16:27:51.514308Z\",\"lte\":\"2020-11-03T16:42:51.514308Z\"}}}]}}}},\"sort\":[{\"user.test\":{\"order\":\"asc\"}}]}"}, "level": "DEBUG", "time": "2020-11-03T16:42:51.542Z"}

```
From logs it looks like elastalert is trying to filter base on range for user.test field. I am not sure if this can work. 
But when I change timestamp_field to definition like: 
```timestamp_field: test``` 
then it works fine and alert is generated. 

I have tried to dig into elastalert code to find any solution for my issue. Looks like query visible in logs above (I am guessing that this is the problematic one) is build by method get_query from https://github.com/Yelp/elastalert/blob/master/elastalert/elastalert.py . Unfortunately I could not find any solution base on code analyse to make my alerts working with nested timestamp_field. 

Could you advice what should I change to make nested  timestamp_field working?
Thanks in advance, 
Grzegorz
