### ISSUE TITLE
Alert thehive when thehive is behind reverse proxy

### ISSUE THREAD

**Issue by V1D1AN** [Yelp/elastalert#3033]
Hi the community,

ElastAlert has problem when thehive is behind a reverse proxy.
My Thehive has url https://host.com/thehive

I have set 
hive_host: host.com/thehive
hive_port: 443

In my elastalert logs, i have 
A client error occurred on POST /thehive:443/api/alert

If a delete the hive_port ... i have another error
ERROR:root:Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/elastalert/elastalert.py", line 1450, in alert
    return self.send_alert(matches, rule, alert_time=alert_time, retried=retried)
  File "/usr/local/lib/python3.7/dist-packages/elastalert/elastalert.py", line 1544, in send_alert
    alert.alert(matches)
  File "/usr/local/lib/python3.7/dist-packages/elastalert/alerts.py", line 2170, in alert
    req = '{}:{}/api/alert'.format(connection_details['hive_host'], connection_details['hive_port'])
KeyError: 'hive_port'

ERROR:root:Uncaught exception running rule Detection_d0c5aa2e-7d2b-44e6-a27a-3e18f234bb06: 'hive_port'

**Comment by nsano-rururu** [comment]
https://elastalert.readthedocs.io/en/latest/ruletypes.html#thehive

```
 hive_connection:
   hive_host: http://localhost
   hive_port: <hive_port>
   hive_apikey: <hive_apikey>
   hive_proxies:
     http: ''
     https: ''

  hive_alert_config:
    title: 'Title'  ## This will default to {rule[index]_rule[name]} if not provided
    type: 'external'
    source: 'elastalert'
    description: '{match[field1]} {rule[name]} Sample description'
    severity: 2
    tags: ['tag1', 'tag2 {rule[name]}']
    tlp: 3
    status: 'New'
    follow: True

hive_observable_data_mapping:
    - domain: "{match[field1]}_{rule[name]}"
    - domain: "{match[field]}"
    - ip: "{match[ip_field]}"
```
