### ISSUE TITLE
Aggregation Schedule time always interpreted as UTC

### ISSUE THREAD

**Issue by remoteexception** [Yelp/elastalert#3055]
Hi all,
is there a way to tell ElastAlert to interpret the configured schedule time as the local timezone? We run our ElastAlert-Container with a specific timezone (TZ=Europe/Berlin). The schedule time is configured as follows:
```
    import-warnings: |-
      name: Import Warnings
      aggregation:
        schedule: '2 7 * * *'
        ...
```
I expect the rule to trigger at 7:02 am local time (Europe/Berlin). That is, it should trigger at 5:02 UTC in DST or else at 6:02 UTC. However, the trigger appears to be ignoring the specified time zone and fires at 7:02 UTC.
I hope the problem is clear and someone can help.
