### ISSUE TITLE
How to configure the best practice alarm rules for most services?

### ISSUE THREAD

**Issue by wajika** [Yelp/elastalert#3058]
At the beginning, my idea was to obtain the status code of the service request and check it every minute. If it is 401, 403, 404, 500 or the like, as long as there is at least one, an alarm message will be generated. But in this way, a service needs to create at least 4 rule files. The more services there are, the more rule files there are. Will this affect the query performance of elastalert? Is there a best practice configuration scheme?

```
name: ABC-http400-alert
type: frequency
index: index-*
query_key:
  - service.name
realert:
  minutes: 15
exponential_realert:
  hours: 1

num_events: 1
timeframe:
    minutes: 1
filter:
- term:
    http.response.status_code: "400"
- term:
    service.name: "ABC"

```
