### ISSUE TITLE
alert formatting duration from ns to milliseconds or seconds

### ISSUE THREAD

**Issue by lucmichalski** [Yelp/elastalert#3071]
Hi guys,

Hope you are all well !

I have activated the filebeat mysql module and wanted to get slack alerts on slow logs. For that part, it is all fine and working perfectly but I cannot format in alert_text the duration from ns to ms.

Is there a parameter that can allow me to format the output of my alert message ?

Please find my rule below:
```yaml
# Alert when the rate of events exceeds a threshold

# (Required)
# Rule name, must be unique
name: mysql-slowlog frequency rule

# (Required)
# Type of alert.
# the frequency rule type alerts when num_events events occur with timeframe time
type: frequency

#aggregation:
#  "* * * * *" means: run as the "run_every" in config.yaml
#  schedule: "* * * * *"
# aggregate_by_match_time: true

# (Required)
# Index to search, wildcard supported
index: filebeat-*

# (Required, frequency specific)
# Alert when this many documents matching the query occur within a timeframe
num_events: 1

# (Required, frequency specific)
# num_events must occur within this amount of time to trigger an alert
timeframe:
  #hours: 4
  minutes: 2

# (Required)
# A list of Elasticsearch filters used for find events
# These filters are joined with AND and nested in a filtered query
# For more info: http://www.elasticsearch.org/guide/en/elasticsearch/reference/current/query-dsl.html
filter:
- bool:
    must:
      - match_phrase:
          event.module:
             query: "mysql"
      - match_phrase:
          fileset.name:
             query: "slowlog"             
    #must_not:
      #- match:
      #    message: "SQL_NO_CACHE"
      #- match:    
      #    message: "[SUCCESS]"

alert:
- "slack"

import: BaseRule.config

alert_subject: "MySQL slow query occurred at {0} on {1}"

alert_subject_args:
- "@timestamp"
- agent.hostname

alert_text: |-
  timestamp: {0}
  user: {1}
  duration: {2}
  query: {3}

alert_text_args:
- "@timestamp"
- user.name
- event.duration
- mysql.slowlog.query

alert_text_type: alert_text_only
realert:
  minutes: 1

aggregation:
  minutes: 2

```

Thanks for any inputs or insights on that question :-)

Cheers,
Luc Michalski
