### ISSUE TITLE
exclude filter not working.

### ISSUE THREAD

**Issue by rishi360** [Yelp/elastalert#3072]
Hi All, I am facing an issue when I am making elastalert rule. In that rule I want to exclude term, tags. Here is my code filter:
"- query:
not:
term:
tags: ["hadoop-storage"]";

Where tags "hadoop-storage" that I want to exclude. I have tried but not working. Getting error 
.....................................................................................................................
 "elasticsearch.exceptions.RequestError: RequestError(400, 'x_content_parse_exception', 'unknown query [not]')"]
.........................................................................................................................

**Comment by nsano-rururu** [comment]
https://github.com/Yelp/elastalert/issues/790

**Comment by rishi360** [comment]
> #790

Please let know if my if these lines added in alert rule are correct or not!
"- query:
not:
term:
tags: ["hadoop-storage"]";

**Comment by nsano-rururu** [comment]
@rishi360 

It seems that the writing method does not work unless it is Elasticsearch 2.X

https://elastalert.readthedocs.io/en/latest/recipes/writing_filters.html#negation-and-or

Negation, and, or
For Elasticsearch 2.X, any of the filters can be embedded in not, and, and or:

```
filter:
- or:
    - term:
        field: "value"
    - wildcard:
        field: "foo*bar"
    - and:
        - not:
            term:
              field: "value"
        - not:
            term:
              _type: "something"
```

For Elasticsearch 5.x, this will not work and to implement boolean logic use query strings:

```
filter:
 - query:
      query_string:
        query: "somefield: somevalue OR foo: bar"
```
