### ISSUE TITLE
metric_aggregation configuration problem

### ISSUE THREAD

**Issue by dmanbu** [Yelp/elastalert#3079]
elastalert version: 0.2.4

This is my rule:
```
name: nginx-upstream_gt_500ms
index: nginx-*
type: metric_aggregation

num_events: 1

metric_agg_key: upstream_response_time
metric_agg_type: avg
query_key: domain
max_threshold: 0.5

alert_subject: "upstream_response_time > 500 ms"
alert_text: |
  alert_name: "upstream_response_time > 500 ms"
  domain: {0}
alert_text_type: alert_text_only
alert_text_args:
  - domain

alert:
- email
```

I have a domain name: user-center.test.com
But I got two alert emails
email body:
```
alert_name: "upstream_response_time > 500 ms"
domain: user
```
and
```
alert_name: "upstream_response_time > 500 ms"
domain: center.test.com
```

What is wrong with my configuration？
I need help, thank you
