### ISSUE TITLE
percentage_match false positive: linked to the way the queries are scrolled through?

### ISSUE THREAD

**Issue by NanoPish** [Yelp/elastalert#3086]
I have a percentage_match rule defined this way, that triggers even when the corresponding kibana dashboard doesn't show the conditions required:

```
type: percentage_match
index: my_index

doc_type: "_doc"

bucket_interval:
 minutes: 5

realert:
  minutes: 20

exponential_realert:
  hours: 2

filter:
- query:
    query_string:
      query: "http_request_type: my_http_request_type"

match_bucket_filter:
 - query_string:
      query: "response_time > 200"

max_percentage: 70
```
My config is mostly defaults:

```
rules_folder: myrules

run_every:
  minutes: 1

buffer_time:
  minutes: 15

realert:
  minutes: 10

es_host: my_host

es_port: 9200

es_username: myuser
es_password: mypassword

writeback_index: elastalert_status
writeback_alias: elastalert_alerts

alert_time_limit:
  days: 2

use_ssl: True
client_cert: /opt/elastalert/mycer.cer
client_key: /opt/elastalert/mykey.key
ca_certs: False
verify_certs: False
```

False positives appear at random times, not very frequently. When I look my data with kibana, I don't see high response_time at the moment the alert triggers. The data shows that I am really far from having > 80% my_http_request_type requests that have more than 200 ms response_time.

I am wondering if this can be linked to the way the data is scrolled through, as explained in the [documentation](https://elastalert.readthedocs.io/en/latest/elastalert.html) for scrolling.

Is it possible that the different buckets of size max_query_size scrolled by elastalert randomly contain all the requests that have high response_time and trigger an alert because of this one specific bucket ?

Thank you
