### ISSUE TITLE
Alerts not being sent, even if alerting condition is maintained

### ISSUE THREAD

**Issue by amitrmishra** [Yelp/elastalert#3096]
Hi,

I'm working with the **frequency** rule type of ElastAlert and observe that even if alerting condition is
maintained, the **matches** is 0 even if **hits** is non-zero.

I'm sharing the yaml file for the rules. I'm checking that at least **1 document** arrives in the index in the **last 2 mins**, I should be alerted. My elastic search is **7.x** and elastalert uses **buffer time** as **5 mins**.

When the rule runs, the **elastalert_status_status** contains
**endtime**: the time when rule ran
**starttime**: endtime - 5 mins (buffer time)
**hits**: number of documents matching the rule between starttime and the endtime
**matches**: 1 (only for the first occurence of the alert)

```
name: elastalert-test
type: frequency
index: alert-test
buffer_time:
  minutes: 5
num_events: 1
timeframe:
  minutes: 2
realert:
  seconds: 0
run_every:
  seconds: 5
filter: []
alert:
- "victorops"

victorops:
victorops_api_key: "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx"
victorops_routing_key: "elastalert"
victorops_message_type: "CRITICAL"
victorops_entity_display_name: "Test Alert"
```

I'm sharing my observation and the difference from the expectation.

1. When I index a doc in the index **alert-test**, I get an alert. This is expected.
2. Since, I'm not **aggregating** or **silencing** the alert (**realert** is set to 0), I expect an alert to be sent every **5 seconds** (run_every is set to 5s) for the next 2 mins (the **timeframe** of frequency rule type). This is because there will be at least one doc in the index in the last 2 mins. But I don't get any further alert. On checking the metadata index **elastalert_status_status**, the hits is 1 for the next 5 mins (buffer_time is 5m), but matches is 0

I observe that alert is sent only when 1 document is indexed since the last run of the rule checker.

My motivation is to know when does an alert gets resolved and I was trying to get this info from `len(rule['type'].matches)` in elastalert.py

I'll appreciate any pointer or suggestion.
