### ISSUE TITLE
Frequency rule with use_terms_query and query_key does't recived fields data from searches.

### ISSUE THREAD

**Issue by Lelik13a** [Yelp/elastalert#3100]
elastalert: 0.2.4
elasticsaerch: 7.10

Configuration like:
```
use_terms_query: true
query_key: "app.keyword"
doc_type: "_doc"

filter:
- query:
    query_string:
      query: "level: Fatal"

# this options don't affect query 
max_query_size: 5
```

Generated http query (in logs):
```
GET /index-*/_doc/_search?ignore_unavailable=true&size=0 HTTP/1.1" 200 269 "" "" "" "{"query":{"bool":{"filter":{"bool":{"must":[{"range":{"@timestamp":{"gt":"2021-01-17T22:37:09.792097Z","lte":"2021-01-17T22:42:09.792097Z"}}},{"query_string":{"query":"level: Fatal"}}]}}}},"aggs":{"counts":{"terms":{"field":"app.keyword","size":50,"min_doc_count":1}}}}"
```
with option `size=0` index data don't returned. And index fields cant be used in alert  text.
