### ISSUE TITLE
Is the project still in active development

### ISSUE THREAD

**Issue by badsector3** [Yelp/elastalert#3106]
Hi.

   Just wanted to  confirm that the project is still in active developement. Last relase was in April 2020. The kibana plugin last docker image  uploaded 2 or 3 years ago. Thanks

**Comment by nsano-rururu** [comment]
not active

look
[Please don't let this die. ElastAlert usecase is very strong.](https://github.com/Yelp/elastalert/issues/2947)
[Should someone else maintain this?](https://github.com/Yelp/elastalert/issues/2946)
[Status of the elastalert project](https://github.com/Yelp/elastalert/issues/2911)

**Comment by nsano-rururu** [comment]
>The kibana plugin last docker image uploaded 2 or 3 years ago

kibana plugin project? .. It's not this repository and I think the company is different. That has already been developed.

**Comment by nsano-rururu** [comment]
I answered. Please close

**Comment by nsano-rururu** [comment]
ping

**Comment by nsano-rururu** [comment]
| Python |〇 or ✖ |remark|
| :-------------: | :-------------: |-|
| 3.6| 〇  ||
| 3.7| 〇  ||
| 3.8| 〇  ||
| 3.9| ✖  |Change Library blist to sortedcontainers|

**Alerts**

| Alerts|〇 or ✖ |remark|
| :-------------: | :-------------: |-|
|Command|〇|
|Email|△|There is a bug(gmail, Office365 etc)|
|Jira|△|There is a bug(Custom Filed Support etc)|
|OpsGenie|？||
AWS SNS|△|It doesn't work due to a bug. There is a pull request|
MS Teams|〇||
Slack|〇||
Mattermost|〇||
Telegram|〇||
GoogleChat|？||
PagerDuty|？||
PagerTree|✖|It doesn't work due to a bug. There is a pull request|
Exotel|？||
Twilio|〇||
VictorOps|〇||
Gitter|〇||
ServiceNow|？||
Debug|〇||
Stomp|✖|It doesn't work due to a bug. There is a pull request|
Alerta|？||
HTTP POST|？||
Line Notify|✖|It doesn't work due to a bug. There is a pull request|
TheHive|？||
Zabbix|✖|It doesn't work due to a bug. There is a pull request|

**Comment by nsano-rururu** [comment]
>The kibana plugin last docker image uploaded 2 or 3 years ago. Thanks

Another project. The place to ask is different. It seems that the development of ElastAlert Server and elastalert-kibana-plugin has been completed.

https://github.com/bitsensor/elastalert
https://github.com/bitsensor/elastalert-kibana-plugin

| Docker image name    | tag| ElastAlert |Elasticsearch 7 Support|   Remarks    |
|:-------------------|:----:|:----------:|:----------:|:-----------|
|[bitsensor/elastalert](https://hub.docker.com/r/bitsensor/elastalert/)|2.0.1 |0.1.39|×||
|[bitsensor/elastalert](https://hub.docker.com/r/bitsensor/elastalert/)|lastet|0.1.39|×||
|[bitsensor/elastalert](https://hub.docker.com/r/bitsensor/elastalert/)|3.0.0-beta.0|0.2.0b2|〇||
|[bitsensor/elastalert](https://hub.docker.com/r/bitsensor/elastalert/)|3.0.0-beta.1|0.2.0b2|〇||

**Comment by nsano-rururu** [comment]
@badsector3

The elastalert server is dead. The elastalert-kibana-plugin is also dead.

**Comment by nsano-rururu** [comment]
@badsector3

bitsensor/elastalert:3.0.0-beta.0
docker.elastic.co/kibana/kibana:7.7.0
docker.elastic.co/elasticsearch/elasticsearch:7.7.0

```
/home/sano/docker-wk2
|--Dockerfiles
|  |--Dockerfile-elastalert
|  |--Dockerfile-kibana
|--docker-compose.yml
|--elastalert
|  |--bin
|  |  |--elastalert-start.sh
|  |  |--elastic_search_status.sh
|  |--config
|  |  |--config.json
|  |  |--elastalert-test.yaml
|  |  |--elastalert.yaml
|  |--rule_templates
|  |--rules
|--es
|  |--config
|  |  |--elasticsearch.yml
|  |--data
|--kibana
|  |--config
|  |  |--kibana.yml

```

**Dockerfiles/Dockerfile-elastalert**

```
FROM bitsensor/elastalert:3.0.0-beta.0

USER root

RUN apk update && \
    apk add bash curl && \
    rm -rf /var/cache/apk/*

ADD elastalert/bin/elastalert-start.sh /usr/local/bin/
ADD elastalert/bin/elastic_search_status.sh /usr/local/bin/

RUN chmod +x /usr/local/bin/elastalert-start.sh & \
    chmod +x /usr/local/bin/elastic_search_status.sh

USER node

ENTRYPOINT ["/usr/local/bin/elastalert-start.sh"]
```

**Dockerfiles/Dockerfile-kibana**

```
FROM docker.elastic.co/kibana/kibana:7.7.0

USER root

RUN /usr/share/kibana/bin/kibana-plugin install https://github.com/nsano-rururu/elastalert-kibana-plugin/releases/download/1.2.0/elastalert-kibana-plugin-1.2.0-7.7.0.zip --allow-root

USER kibana
```

**docker-compose.yml**


```
version: "3.7"
services:
  elasticsearch:
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:7.7.0
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      - ES_JAVA_OPTS=-Xms256m -Xmx256m
      - discovery.type=single-node
    restart: always
    volumes:
      - ./es/data:/usr/share/elasticsearch/data
      - ./es/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    healthcheck:
        test: ["CMD-SHELL", "curl -f http://localhost:9200 || exit 1"]
        interval: 30s
        timeout: 15s
        retries: 3
        start_period: 180s

  kibana:
    container_name: kibana
    image: kibana:7.7.0
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch
    restart: always
    volumes:
      - ./kibana/config/kibana.yml:/usr/share/kibana/config/kibana.yml
      #- ./kibana/plugin:/usr/share/kibana/work
    healthcheck:
        test: ["CMD-SHELL", "curl -f http://localhost:5601/api/status || exit 1"]
        interval: 30s
        timeout: 15s
        retries: 3
        start_period: 200s

  elastalert:
    container_name: elastalert
    build:
      context: .
      dockerfile: Dockerfiles/Dockerfile-elastalert
    image: elastalert:3.0.0-beta.0
    ports:
      - 3030:3030
      - 3333:3333
    depends_on:
      - elasticsearch
      - kibana
    restart: always
    volumes:
      - ./elastalert/config/elastalert.yaml:/opt/elastalert/config.yaml
      - ./elastalert/config/elastalert-test.yaml:/opt/elastalert/config-test.yaml
      - ./elastalert/config/config.json:/opt/elastalert-server/config/config.json
      - ./elastalert/rules:/opt/elastalert/rules
      - ./elastalert/rule_templates:/opt/elastalert/rule_templates
    healthcheck:
        test: ["CMD-SHELL", "curl -f http://localhost:3030 || exit 1"]
        interval: 30s
        timeout: 15s
        retries: 3
        start_period: 200s
```

**elastalert/bin/elastalert-start.sh**

```
#!/bin/bash

set -e

echo "Giving Elasticsearch at $ELASTICSEARCH_URL time to start..."

elastic_search_status.sh

echo "Starting ElastAlert!"
npm start
```


**elastalert/bin/elastic_search_status.sh**

```
#!/bin/bash

set -e

if [ $# -gt 0 ]; then
  ES_URL="$1"
elif [[ -n $ELASTICSEARCH_URL ]]; then
  ES_URL="$ELASTICSEARCH_URL"
elif [[ -n $ES_HOST ]] && [[ -n $ES_PORT ]]; then
  ES_URL="http://$ES_HOST:$ES_PORT"
else
  ES_URL="http://elasticsearch:9200"
fi

until [[ "$(curl -fsSL "$ES_URL/_cat/health?h=status" | sed -r 's/^[[:space:]]+|[[:space:]]+$//g')" =~ ^(yellow|green)$ ]]; do
  # printf '+' >&2
  sleep 1
done

echo "Elasticsearch is up and healthy at "$ES_URL"" >&2
```

**elastalert/config/config.json**

```
{
    "appName": "elastalert-server",
    "port": 3030,
    "wsport": 3333,
    "elastalertPath": "/opt/elastalert",
    "verbose": false,
    "es_debug": false,
    "debug": false,
    "rulesPath": {
      "relative": true,
      "path": "/rules"
    },
    "templatesPath": {
      "relative": true,
      "path": "/rule_templates"
    },
    "es_host": "elasticsearch",
    "es_port": 9200,
    "writeback_index": "elastalert_status"
  }
```

**elastalert/config/elastalert-test.yaml**

```
{
    "appName": "elastalert-server",
    "port": 3030,
    "wsport": 3333,
    "elastalertPath": "/opt/elastalert",
    "verbose": false,
    "es_debug": false,
    "debug": false,
    "rulesPath": {
      "relative": true,
      "path": "/rules"
    },
    "templatesPath": {
      "relative": true,
      "path": "/rule_templates"
    },
    "es_host": "elasticsearch",
    "es_port": 9200,
    "writeback_index": "elastalert_status"
  }
```


**elastalert/config/elastalert.yaml**

```
# NOTE: This config is used when testing a rule

# The elasticsearch hostname for metadata writeback
# Note that every rule can have its own elasticsearch host
es_host: elasticsearch

# The elasticsearch port
es_port: 9200

# This is the folder that contains the rule yaml files
# Any .yaml file will be loaded as a rule
rules_folder: rules

# How often ElastAlert will query elasticsearch
# The unit can be anything from weeks to seconds
run_every:
  seconds: 5

# ElastAlert will buffer results from the most recent
# period of time, in case some log sources are not in real time
buffer_time:
  minutes: 1

# Optional URL prefix for elasticsearch
#es_url_prefix: elasticsearch

# Connect with TLS to elasticsearch
#use_ssl: True

# Verify TLS certificates
#verify_certs: True

# GET request with body is the default option for Elasticsearch.
# If it fails for some reason, you can pass 'GET', 'POST' or 'source'.
# See http://elasticsearch-py.readthedocs.io/en/master/connection.html?highlight=send_get_body_as#transport
# for details
#es_send_get_body_as: GET

# Option basic-auth username and password for elasticsearch
#es_username: someusername
#es_password: somepassword

# The index on es_host which is used for metadata storage
# This can be a unmapped index, but it is recommended that you run
# elastalert-create-index to set a mapping
writeback_index: elastalert_status

# If an alert fails for some reason, ElastAlert will retry
# sending the alert until this time period has elapsed
alert_time_limit:
  days: 2
```

**es/config/elasticsearch.yml**

```
cluster.name: "docker-cluster"
network.host: 0.0.0.0
discovery.zen.minimum_master_nodes: 1
```

**kibana/config/kibana.yml**

```
server.name: kibana
server.host: "0"
elasticsearch.hosts: http://elasticsearch:9200
xpack.monitoring.ui.container.elasticsearch.enabled: true

# elastalert-kibana-plugin
elastalert-kibana-plugin.serverHost: elastalert
elastalert-kibana-plugin.serverPort: 3030
```

**execute**

```
mkdir -p es/data
chmod 777 es/data
cd Dockerfiles/
docker build -t kibana:7.7.0 -f Dockerfile-kibana .
cd ..
docker-compose up -d
```
![1](https://user-images.githubusercontent.com/22293449/87555352-4b89e380-c6f0-11ea-8e1e-cdac3d4773af.PNG)
![2](https://user-images.githubusercontent.com/22293449/87555402-5a709600-c6f0-11ea-964f-316a8bdd205e.PNG)
![3](https://user-images.githubusercontent.com/22293449/87555415-60667700-c6f0-11ea-8f61-5ebf81e908dc.PNG)
