### ISSUE TITLE
Flatline doesn't work as expected

### ISSUE THREAD

**Issue by vennca** [Yelp/elastalert#3117]
Hello, could anyone help me with simple FLATLINE rule?
I would like to detect if no documents in elasticsearch appears during last 3 hours.

```
---
es_host: ******
es_port: 9200
es_username: elastalert
es_password: *****
name: "APP.flatline.liferay - ***** - liferay"
type: flatline
index: aplikace
use_count_query: true
doc_type: "_doc"
threshold: 1
run_every:
  minutes: 5
scan_entire_timeframe: true
timeframe:
  hours: 3
filter:
- term:
    event.category: "app"
- query:
    query_string:
      query: "( app:\"liferay\" OR event.provider:\"liferay\")"
alert:
- "command"
command: [".....",]
raw_count_keys: false
```
