### ISSUE TITLE
SNS alerter Typographical errors in the document

### ISSUE THREAD

**Issue by nsano-rururu** [Yelp/elastalert#3136]
aws_access_key
　↓
aws_access_key_id

aws_secret_key
　↓
aws_secret_access_key

profile
　↓
aws_profile

Since I use the key aws_region elsewhere, I have to write it as follows, so I need to either change the key name or just modify the document.

```
    alert:
      - sns:
          aws_region: 'us-east-1' # You must nest aws_region within your alert configuration so it is not used to sign AWS requests.
    sns_topic_arn: 'arn:aws:sns:us-east-1:123456789:somesnstopic'
    aws_access_key_id: 'XXXXXXXXXXXXXXXXXX''
    aws_secret_access_key: 'YYYYYYYYYYYYYYYYYYYY'
```

Also, the profile implementation is incorrect. I think it was implemented by a stranger.

the current

```
        session = boto3.Session(
            aws_access_key_id=self.aws_access_key_id,
            aws_secret_access_key=self.aws_secret_access_key,
            region_name=self.aws_region,
            profile_name=self.profile
        )
```

Fix

```
        if self.profile is None:
            session = boto3.Session(
                aws_access_key_id=self.aws_access_key_id,
                aws_secret_access_key=self.aws_secret_access_key,
                region_name=self.aws_region
            )
        else:
            session = boto3.Session(profile_name=self.profile)
```
