### ISSUE TITLE
Rule query is not accurate

### ISSUE THREAD

**Issue by ktpktr0** [Yelp/elastalert#3228]
I use the following expression to query the log error, but it will alarm as long as it meets one of the keywords. Using "and" or "at the same time does not take effect

```
name: for test
type: frequency
index: test-*
num_events: 10
timeframe:
  minutes: 2
realert:
  minutes: 5
filter:
- query:
    query_string:
      query: "DB ERROR"
```
use and

```
name: for test
type: frequency
index: test-*
num_events: 10
timeframe:
  minutes: 2
realert:
  minutes: 5
filter:
- query:
    query_string:
#      query: "message: DB ERROR"
      query: "message: DB ERROR AND Error Content = query time out"
```

When "dB / DB" or "error / error" appears in the log, an alarm will be given
