### ISSUE TITLE
@timestamp is UTC-0 how do i change it?

### ISSUE THREAD

**Issue by annastudio** [Yelp/elastalert#3268]
Нello!
In kibana the time is displayed correctly (UTC + 3). 
But the email sent from elastalert its still in UTC-0 is there anyway to force it to show up as UTC +3?
I've already done:
elastalert_modules\time_enhancement.py
```
from elastalert.util import pretty_ts
from elastalert.enhancements import BaseEnhancement


class TimeEnhancement(BaseEnhancement):
    '''
    Add local @timestamp (server time)
    '''

    def process(self, match):
        if '@timestamp' in match:
            ts = match['@timestamp']
            if isinstance(ts, str) and ts.endswith('Z'):
                match['@timestamp_local'] = pretty_ts(ts)
```
rules\rule1.yaml
```
name: "alert for email notification about create or block user"

type: any

realert:
  minutes: 0

index: winlogbeat-*
use_local_time: true
timestamp_field: "@timestamp"
match_enhancements:
- elastalert_modules.my_enhancements.TimeEnhancement

filter:
- terms:
    event.code: ["4740", "4720"]

include:
  - event.code
  - event.action
  - "@timestamp"
  - user.id
  - winlog.event_data.SubjectUserName
  - winlog.event_data.SubjectDomainName
  - winlog.logon.id
  - winlog.event_data.TargetSid
  - winlog.event_data.TargetUserName
  - winlog.event_data.TargetDomainName

alert_text: "<h2>A monitored security event has occurred</h2><p>{0} - Event Action: {1}</p><p>Timestamp Alert: {2}</p><h4>Performer:</h4><p>SID: {3}<br>Account Name: {4}<br>Account Domain: {5}<br>Logon ID: {6}</p><h4>User:</h4>Security ID:$
alert_text_args:
  - event.code
  - event.action
  - "@timestamp_local"
  - user.id
  - winlog.event_data.SubjectUserName
  - winlog.event_data.SubjectDomainName
  - winlog.logon.id
  - winlog.event_data.TargetSid
  - winlog.event_data.TargetUserName
  - winlog.event_data.TargetDomainName

alert_text_type: alert_text_only

alert:
- "email"
email_format: html
email:
- "someone@somewhere.com"
from_addr: "someone@somewhere.com"

smtp_host: "smtp.somewhere.com"
smtp_port: 25
```
The rule works when I run `elastalert --config config.yaml --verbose --rule rules\rule1.yaml` and alerts are sent.
But in normal mode, nothing comes to the mail.
Help me please!
