### ISSUE TITLE
Slow searches - why not use filtered queries by default?

### ISSUE THREAD

**Issue by jraby** [Yelp/elastalert#327]
I was trying to understand why the search were so slow for simple rules like this one:
```
name: HTTP 500
type: frequency
index: logstash-*
num_events: 1
timeframe:
  hours: 1
aggregation:
  hours: 1
realert:
  minutes: 0

filter:
- query:
    query_string:
      query: 'http_response_code:500'

[...]
```

For this rule, it seems that elastalert will generate elasticsearch queries similar to this:
```
{"filter": {"bool": {"must": [{"range": {"@timestamp": {"gt": "2015-12-02T22:40:29.757603Z", "lte": "2015-12-02T22:41:29.757603Z"}}}, {"query": {"query_string": {"query": "http_response_code:500"}}} ]}}, "sort": [{"@timestamp": {"order": "asc"}}]}
```

This is *really* slow,  it takes 15s+ to run on our machine.

Using a filtered query would be much more efficient, something like the following takes ~150ms to run here:
```
{"sort": [{"@timestamp": {"order": "asc"}}], "query": {"filtered": {"filter": {"bool": {"must": [{"range": {"@timestamp": {"gt": "2015-12-03T00:49:00Z", "lte": "2015-12-03T00:50:00Z"}}}, {"query": {"query_string": {"query": "http_response_code:400"}}}]}}}}}
```

From my perspective, it seems that elastalert should be using filtered queries by default for such rules. Am I missing something or is there a reason why it should not do so?

I'll hack up a proof of concept today.
