### ISSUE TITLE
Empty message text in zoom (MAC OS) via incoming webhook

### ISSUE THREAD

**Issue by kga676** [Yelp/elastalert#3291]
I am trying to send elastalerts to zoom via http_post to incoming webhook app
on Windows in works just OK
on Mac OS there is empty message text.
BUT if I copy message to clipboard and paste it - text is OK
![image](https://github.com/Yelp/elastalert/assets/45682640/1d4b06ce-43c0-4d8f-bfcb-b0d475c38e7e)

My alert rule
```
alert: post
http_post_url: "https://inbots.zoom.us/incoming/hook/My_chat_id_here?format=fields"
http_post_payload:
  message: message
http_post_headers:
  authorization: Bearer My token is here
http_post_proxy:
  http://my_proxy_is_here:and_port
```

adding   Content-Type: "application/json" does NOT work :(
