### ISSUE TITLE
Type frequency

### ISSUE THREAD

**Issue by nguyenling** [Yelp/elastalert#333]
I write rule detect web attack by ElastAlert.How to write rule detect incoming request abnormalities with 8 request /120s of the same source IP address --> alert attack

**Comment by Qmando** [comment]
Perhaps something like
```
type: frequency
num_events: 8
timeframe:
  minutes: 2
filter:
  - range:
      response_code:
        from: 400
        to: 599
alert: email
email: foo@example.com
```
