### ISSUE TITLE
nested object queries

### ISSUE THREAD

**Issue by nitinlkoin1984** [Yelp/elastalert#349]
Is there a way to write filters that can query nested objects?

Also, is there a way to write custom elastic search queries that elast alert can execute as filters?

**Comment by Qmando** [comment]
Sure. You can do something like
```
filter:
 - term:
     apache.request.method: "post"
```
You should be able to use any Elasticsearch query you want. It is passed as a filtered query. For example, with query_string query type
```
filter:
  - query:
      query_string:
        query: "foo AND bar"
        default_field: "baz"
        analyzer: "my_analyzer"
```
