### ISSUE TITLE
Help Creating Rule

### ISSUE THREAD

**Issue by ninjada** [Yelp/elastalert#360]
hello, testing elastalert and having a bit of trouble with syntax for negate/and/or rule filters.

i'm attempting to run a rule based on the following kibana 4 search:

```
{
  "index": "logstash-*",
  "filter": [
    {
      "meta": {
        "negate": true,
        "index": "logstash-*",
        "key": "verb",
        "value": "GET",
        "disabled": false
      },
      "query": {
        "match": {
          "verb": {
            "query": "GET",
            "type": "phrase"
          }
        }
      }
    },
    {
      "meta": {
        "negate": false,
        "index": "logstash-*",
        "key": "verb",
        "value": "POST",
        "disabled": false
      },
      "query": {
        "match": {
          "verb": {
            "query": "POST",
            "type": "phrase"
          }
        }
      }
    }
  ],
  "query": {
    "query_string": {
      "query": "message:*imgpost*",
      "analyze_wildcard": true
    }
  }
}
```

eg. message: *imgpost* with filters for AND verb: POST NOT verb: GET 

everything i'm trying in the rule yaml is resulting in search errors

Additionally, the docs show option for elastalert-rule-from-kibana but for kibana 3.. is this compatible with the latest kibana 4.x?

**Comment by Qmando** [comment]
Try
```
filter:
- query:
    query_string:
      query: "message:*imgpost*"
      analyze_wildcard: true
- term:
    verb: post
- not:
    term:
      verb: get
```
Although seems the NOT verb: post part is unnecessary.
