### ISSUE TITLE
Elastalert not alerting

### ISSUE THREAD

**Issue by patrick-bark** [Yelp/elastalert#417]
I am trying to utilize a simple rule using Elastalert, and it seems to not be functioning properly. My rule is:

```
    # Elasticsearch host
    es_host: elastic search
    
    # The elastic search port
    es_port: 9200
    
    name: dzd_count_zero
    
    type: any
    
    index: logstash-*
    
    filter:
    - term:
        project: "drop_zone_double"
    - terms:
        name: ["s3_count", "dzd_nas_pcount"]
    
    alert:
    - "email"
    
    email:
    - "myemail@m.com"

```
and when I put debug on i get:

`    elastalert:Ran dzd_count_zero from 2016-03-02 13:59 UTC to 2016-03-02 17:59 UTC: 16 query hits, 0 matches, 0 alerts sent`

If the rule is 'any' then any query hits should be alerted on, but as you can see it is not. Any ideas?
