### ISSUE TITLE
Could not generate kibana dash for Test rule match: Could not parse filter

### ISSUE THREAD

**Issue by jurgenhaas** [Yelp/elastalert#437]
My rule is working just fine but I can't generate Kibana links. The rule is this:

```
es_host: "localhost"
es_port: 9200
index: "logstash-*"
name: "Test rule"
type: "frequency"
alert:
  - "slack"
description: "This is just a test"

generate_kibana_link: true
use_kibana4_dashboard: "http://crcmon1/app/kibana#/dashboard/Default"
kibana_url: "http://crcmon1/app/kibana"

slack_webhook_url: 'removed'

num_events: 1
timeframe:
  minutes: 5
filter:
  - query_string:
      query: ident:drupal* AND (@log_name:"syslog.local0.err" OR @log_name:"syslog.local0.emerg")
      analyze_wildcard: true
```

The full error message:

```
elastalert_error - {'message': 'Could not generate kibana dash for Test rule match: Could not parse filter {\'query_string\': {\'query\': \'ident:drupal* AND (@log_name:"syslog.local0.err" OR @log_name:"syslog.local0.emerg")\', \'analyze_wildcard\': True}} for Kibana', 'traceback': ['Traceback (most recent call last):', '  File "/usr/local/lib/python2.7/dist-packages/elastalert-0.0.75-py2.7.egg/elastalert/elastalert.py", line 909, in send_alert', '    kb_link = self.generate_kibana_db(rule, matches[0])', '  File "/usr/local/lib/python2.7/dist-packages/elastalert-0.0.75-py2.7.egg/elastalert/elastalert.py", line 783, in generate_kibana_db', '    kibana.add_filter(db, filter)', '  File "/usr/local/lib/python2.7/dist-packages/elastalert-0.0.75-py2.7.egg/elastalert/kibana.py", line 221, in add_filter', '    raise EAException("Could not parse filter %s for Kibana" % (es_filter))', 'EAException: Could not parse filter {\'query_string\': {\'query\': \'ident:drupal* AND (@log_name:"syslog.local0.err" OR @log_name:"syslog.local0.emerg")\', \'analyze_wildcard\': True}} for Kibana']}
```

Looks like we are having trouble with that filter?
