### ISSUE TITLE
My DSL Query not working in elastalert

### ISSUE THREAD

**Issue by selvamvasu** [Yelp/elastalert#462]
When I have tried the below elasticsearch query through curl, it is working fine. How can i implement the same in elastalert rule.

{ 
  "query": { 
    "filtered": { 
       "query": { 
         "match": { "plugin": "tcpconns" } 
        },
       "query": {
         "match": { "plugin_instance": "9200-local" }
       },
       "query": {
         "match": { "type_instance": "ESTABLISHED" }
       },
       "filter": {
         "bool": { 
           "must": { "range": { "value": { "gt": 0 } } },
           "must_not": { "term": { "host": "localhost" } }
         }
       }
    } 
  }
}

$ curl -XPOST 'http://127.0.0.1:9200/systemcollectd-2016.04.06/_search?pretty' -d '
> { 
>   "query": { 
>     "filtered": { 
>        "query": { 
>          "match": { "plugin": "tcpconns" } 
>         },
>        "query": {
>          "match": { "plugin_instance": "9200-local" }
>        },
>        "query": {
>          "match": { "type_instance": "ESTABLISHED" }
>        },
>        "filter": {
>          "bool": { 
>            "must": { "range": { "value": { "gt": 0 } } },
>            "must_not": { "term": { "host": "localhost" } }
>          }
>        }
>     } 
>   }
> }'
{
  "took" : 28,
  "timed_out" : false,
  "_shards" : {
    "total" : 5,
    "successful" : 5,
    "failed" : 0
  },
  "hits" : {
    "total" : 0,
    "max_score" : null,
    "hits" : [ ]
  }
}

I added the below one in elastalert rule file. But it is sending alert for my localhost. it doesn't not filter correctly.

query:
- filtered:
   - query:
      match: "plugin: tcpconns"
   - query:
      match: "plugin_instance: 9200-local"
   - query:
      match: "type_instance: ESTABLISHED"
   - filter:
      bool:
       - must:
          range:
           value: "gt: 0"
       - must_not:
          term: "host: localhost"

Let me know how can i get it.

**Comment by Qmando** [comment]
I think you want
```
filter:
- query:
    match:
      plugin: tcpconns
- query:
    match:
      plugin_instance: 9200-local
- query:
    match:
      type_instance: ESTABLISHED
- range:
    value:
     gt: 0
- not:
    term:
      host: localhost
```
