### ISSUE TITLE
Hits but 0 matches

### ISSUE THREAD

**Issue by yuan0122** [Yelp/elastalert#503]
We are using ElastAlert to track the health of our Hadoop tables, like the count of records for each hour. 

Here is how my filter looks like:

```
filter:
- query:
    query_string:
      query: "_type: my_type"
- range:
    count:
      from: 0
      to: 300000
```

After testing this rule, it will give me 4 hits (which is the correct amount of hours that have 0 ~ 300000 records) but 0 matches. So I am wondering what "hits" and "matches" really tell us. And if my need email alerting, will alerts be sent based on hits or matches? Thanks!

Sorry if this is not the right place to ask questions. If I'm at the wrong place, can anyone drop me a link to where I should post my questions?
