### ISSUE TITLE
Flatline rules did not fire during logging outage

### ISSUE THREAD

**Issue by tlamay** [Yelp/elastalert#520]
None of my alerts fired when logs were unavailable yesterday for a period of 5 hours. I do not have elastalert logs from the event window but I am going to try and reproduce today. I expected flatline alerts to at least fire during this period.

Example rule:
```
name: Flatline - Registrations Total
index: logstash-%Y.%m.%d
use_strftime_index: true

alert:
- "email"
email:
- "redacted"

filter:
- query:
    query_string:
      query: "recordType: REGISTRATION"

type: flatline
threshold: 800

timeframe:
  minutes: 30

use_count_query: true
doc_type: logs

query_delay:
  minutes: 10
```
