### ISSUE TITLE
`new_term` doesn't work with `fields` containing `.raw`

### ISSUE THREAD

**Issue by pgaubatz** [Yelp/elastalert#528]
Hi!

I've got a simple `new_term` rule that contains the following:
```yaml
fields:
- err.name.raw
- err.stack.raw
```

Using `elastalert-test-rule` I found that my rule never matches because `lookup_es_key(document, field)` in https://github.com/Yelp/elastalert/blob/master/elastalert/ruletypes.py#L702 wants to retrieve e.g. `err.name.raw` from `document` which doesn't exist. At least in my setup `document` doesn't contain any `*.raw` properties.

A quick-and-dirty workaround that makes the rule work for me is to change `lookup_es_key(document, field)` to `lookup_es_key(document, field.replace(".raw", ""))` but I doubt that this is the cleanest solution... :smile: 

Maybe `lookup_es_key()` should be changed to strip the `.raw` from field names?

Cheers,
Patrick

**Comment by Qmando** [comment]
It should work if you add
```
use_terms_query: true
doc_type: foo
```
though, that has slightly different behavior.

Either your solution, or having the get_all_terms function automatically add '.raw', similar to https://github.com/Yelp/elastalert/blob/master/elastalert/elastalert.py#L354 would work.

**Comment by phermann1988** [comment]
@pgaubatz could you maybe post your whole new_term.yaml-config? I want to try similar things with a new term config but my config won't work in test-rule. what did i miss?


# Rule name, must be unique
name: my_new_term

# Type of alert.
type: new_term

# Index to search, wildcard supported
index: logstash-*

# (Required, new_term specific)
fields:
 - "rid"

# (Optional, new_term specific)
terms_window_size:
  days: 90

# (Required)
# A list of elasticsearch filters used for find events
filter:
- query:
    query_string:
      query: "rop: GetMediaPreview"


use_local_time: false

smtp_host: 192.168.220.133

smtp_port: 25

alert:
- "email"

# (required, email specific)
email:
- "elastalert@example.com"

**Comment by pgaubatz** [comment]
My rule looks like this:

```yaml
name: client errors
index: logstash-*

es_host: elasticsearch_host
es_port: 9200

type: new_term

filter:
- term:
    name.raw: "client-log-collector"
- term:
    level: "error"

fields:
- err.name
- err.stack

alert: slack
slack_webhook_url: ...
```
