### ISSUE TITLE
Query using range on numeric field

### ISSUE THREAD

**Issue by vikas8190** [Yelp/elastalert#550]
I am trying to use below filter in one of the custom rules I am creating. However it throws error saying malformed query.

```
filter:
- range:
  mem.used_p:
    from: 0.85
    to: 1
```

Any idea what is the problem?

**Comment by Qmando** [comment]
```
filter:
- range:
    mem.used_p:
      from: .85
      to: 1
```
