### ISSUE TITLE
Flatline alert with filter

### ISSUE THREAD

**Issue by evusik** [Yelp/elastalert#562]
Hello, 

I'd appreciate advice on using filter with flatline alert type.

My goal is: trigger alert when there is less than 1 summary document type incoming for ToolName: Tool1, per different TeamName.

An example of data is
TeamName: TeamX uploads 1 summary file per hour with ToolName: Tool1
TeamName: TeamY uploads 1 summary file per hour with ToolName: Tool1

If any of those teams fails to upload the summary file in an hour, I want to get an alert.

My yaml with the rule looks as follows:
```
es_host: localhost
es_port: 9200

name: Tool1 Report per Team Frequency

type: flatline

index: indexname_*

threshold: 1

timeframe:
  hours: 1

use_terms_query: true

query_key: TeamName

doc_type: summary

terms_size: 9999

filter:
- query:
    query_string:
      query: "ToolName: Tool1"

alert:
- "email"

email:
- "x@y.com"
```

This currently doesn't have any hits, although I can see that there are clearly gaps in the data (i.e. TeamName: TeamX did not upload a summary file every hour).

Any ideas what I am doing wrong?

Thanks,
Eva
