### ISSUE TITLE
alert via mail {'from_addr': 'no-reply@some-mail-host.tld'} is not of type 'string'

### ISSUE THREAD

**Issue by Deshke** [Yelp/elastalert#601]
trying to figure out what i'm doing wrong, but the yaml is valid, and the from_addr is a string value.

whole thing is running in a docker container with branch master from yesterday(https://github.com/Yelp/elastalert/commit/245fa7d247ac140c0ce93632046491ff0c253fab) 

any idea? 

```yaml
alert:
- email
email:
- foo@bar.tld
- {from_addr: 'no-reply@some-mail-host.tld'}
- {smtp_host: email-smtp.eu-west-1.amazonaws.com}
- {smtp_auth_file: /opt/rules/aws-smtpauth}
filter:
- query:
    query_string: {query: 'logger_name: monitoring.DefaultErrorHandler AND tags: live'}
index: logstash-*
name: server error
timeframe: {minutes: 5}
type: any

```

```bash
alerting_1  | Traceback (most recent call last):
alerting_1  |   File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
alerting_1  |     "__main__", fname, loader, pkg_name)
alerting_1  |   File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
alerting_1  |     exec code in run_globals
alerting_1  |   File "/opt/elastalert/elastalert/elastalert.py", line 1407, in <module>
alerting_1  |     sys.exit(main(sys.argv[1:]))
alerting_1  |   File "/opt/elastalert/elastalert/elastalert.py", line 1402, in main
alerting_1  |     client = ElastAlerter(args)
alerting_1  |   File "/opt/elastalert/elastalert/elastalert.py", line 94, in __init__
alerting_1  |     self.conf = load_rules(self.args)
alerting_1  |   File "elastalert/config.py", line 399, in load_rules
alerting_1  |     raise EAException('Error loading file %s: %s' % (rule_file, e))
alerting_1  | elastalert.util.EAException: Error loading file /opt/rules/server-error-handler.yaml: Invalid Rule: server error
alerting_1  | {'from_addr': 'no-reply@some-mail-host.tld'} is not of type 'string'
alerting_1  | 
alerting_1  | Failed validating 'type' in schema['properties']['email']['items']:
alerting_1  |     {'type': 'string'}
alerting_1  | 
alerting_1  | On instance['email'][1]:
alerting_1  |     {'from_addr': 'no-reply@some-mail-host.tld'}
```

**Comment by Deshke** [comment]
fixit myself the email settings had to go under the alert type and not with in the email list
```yaml
alert:
  - email:
      from_addr: "no-reply@some-domain.tld"
      smtp_host: email-smtp.eu-west-1.amazonaws.com
      smtp_auth_file: /opt/rules/aws-smtpauth

```
