### ISSUE TITLE
Topbeat Alerts with Elastalert? Like 90% HDD used or Process stopped

### ISSUE THREAD

**Issue by phermann1988** [Yelp/elastalert#609]
I would like to get an alarm when for example the field fs.used_p is greater (<= 90) 90%. the rule should send one mail per day with this status + hostname. Another idea ist to get an mail when a spefic process isn't running anymore. Does anybody know if this is possible with elastalert? thank you for your answer. pat.

**Comment by Qmando** [comment]
Both should be possible.

```
name: "90% used_p"
type: any # alert on a single event

filter: # Only alert on >90
- range:
     fs.used_p:
       gt: 90

include: ["fs.used_p", "hostname"] # include these fields in alert

alert: email
email: "foo@bar.com"

# Send a maximum of 1 alert per day
realert:
  days: 1
```

```
name: "some program stopped"
type: flatline # Alert when something stops
threshold: 1 # Alert when there are less than 1 (0 events)
query_key: "program" # Alert for each value of the "program" field
timeframe: # alert when it stopped for a whole hour
  hours: 1
```
