### ISSUE TITLE
Arithmetic operations in filters of Rule

### ISSUE THREAD

**Issue by Pransh20** [Yelp/elastalert#629]
Hi i am editing the frequency rule and in the filter sectioni wanted to define something like this

filter:
  -filed_name > or < value

Is it possible?

Thanks & Regards
Pransh

**Comment by Qmando** [comment]
https://www.elastic.co/guide/en/elasticsearch/reference/2.1/query-dsl-range-query.html

```
filter:
- range:
     field_name:
       from: 10
       to: 20
```
