### ISSUE TITLE
Can not use different aws account/region for es and sns

### ISSUE THREAD

**Issue by leonhartX** [Yelp/elastalert#630]
since they are using the same config items: `aws_region`, `aws_access_key`, `aws_secret_access_key `, there is no way to using es with sns which are not in the same region or from differen account.

maybe it's better to use separated config items for aws es and sns.

**Comment by Qmando** [comment]
You should be able to set different values like this
```
aws_region: us-east-1
aws_access_key: XXXXX
alert:
  - sns:
       aws_region: us-west-1
       aws_access_key: XXXX
```
