### ISSUE TITLE
minimum_should_match not working with terms

### ISSUE THREAD

**Issue by JazminGonzalez-Rivero** [Yelp/elastalert#633]
I was following the filter examples and I got to terms. 

when i try anything along the lines of 
`- terms:
    fieldX: ["value1", "value2"]
    fieldY: ["something", "something_else"]
    fieldZ: ["foo", "bar", "baz"]
    minimum_should_match: 2`

I get 

`u'[terms] query does not support [minimum_should_match]'`

I kow in elasticsearch this has been replaced by the bool query's should cause but how is this done in elastalert

thanks!

**Comment by Qmando** [comment]
Terms + minimum_should_match was deprecated in 2.0 apparently. I'm not actually sure what can be used instead. Elastalert is hardcoded to put everything into a bool MUST clause. The new place to recreate this behavior in 2.0 is bool SHOULD.

You could recreate this in boolean logic, though it would look very ugly.

```
filter:
- or:
     - and:
          - fieldX: ["value1", "value2"]
          - fieldY: ["foo", "bar"]
     - and:
          - fieldZ: ["value1", "value2"]
          - fieldY: ["foo", "bar"]
     - and:
          - fieldX: ["value1", "value2"]
          - fieldZ: ["value1", "value2"]
```
but there has got to be a better way.

I should probably add an additional option, ``filter_should`` or something, so that you can use this feature. Perhaps there IS a way to use it with the current version, but I'm not sure.
