### ISSUE TITLE
Unable to send hipchat room notifications

### ISSUE THREAD

**Issue by geertvanheusden** [Yelp/elastalert#636]
Hi,

I have the following rule with a Hipchat alert:

```
name: ErrorRule
type: frequency
index: logstash-*
num_events: 10
timeframe:
    minutes: 5
filter:
- query:
    query_string:
      query: "level: ERROR"
alert:
- "hipchat"
hipchat_auth_token: my_token
hipchat_room_id: my_id
```

but when the filter matches I always get the following exception:

```
ERROR:root:Error while running alert hipchat: Error posting to HipChat: 400 Client Error: Bad Request for url: https://api.hipchat.com/v2/room/my_id/notification?auth_token=my_token
```

I am sure the token and room_id are valid because I tried to send a POST request with **message**, **notify** and **color** in the payload, from within a REST tool, and it works perfectly.

Only thing I could think of is that an empty message is used in the payload...
Is there any way I could control this message?

Regards,

Geert
