### ISSUE TITLE
I have some problem ( configure : utf-8 )

### ISSUE THREAD

**Issue by sg-studio** [Yelp/elastalert#643]
Hi,
While I was in inputting some condition and executing the elastalert test, I encountered some unknown problem. 
The outcome should have matched the item but it didn't.  
So, I wanted to find solutions to this problem by using tcpdump program.  

----------Condition ---------
example_frequncy.yaml

``` yaml
es_host: my_elasticsearch_ip
es_port: 9200
name: Example test
type: frequency
index: test-index-*
num_events: 1
timeframe:
    hours: 1
filter:
- term:
    type: "자유"
alert:
- "email"
email:
- "secret@domain.com"
```

----------Result ---------

tcpdump_log.txt

```
{"sort": [{"@timestamp": {"order": "asc"}}], "query": {"filtered": {"filter": {"bool": {"must": [{"range": {"@timestamp": {"gt": "2016-07-20T00:40:01.114361Z", "lte": "2016-07-20T01:25:01.114361Z"}}}, {"term": {"type": "\uc790\uc720"}}]}}}}}
```

--------Problem-------
A word '자유' meaning freedome in Korean, is translated into "unicode hexadecimal" which connotates completely different meaning. 

Can anyone help me? ;))
