### ISSUE TITLE
Slack and Kibana_link

### ISSUE THREAD

**Issue by remotesyssupport** [Yelp/elastalert#660]
We predominantly use slack as our alert notifications. I wanted to know if it is possible to include the kibana4 dashboard link in the slack alerts 

My check with including it in alert_text_args (as shown below) doesnt seem to work. Although if I use alert_text_type as default, I can see the kibana_link in the fields of the slack notification

```
# Kibana Link
use_kibana4_dashboard: "https://kibana.internal/app/kibana#/dashboard/applog"
kibana4_start_timedelta:
  minutes: 10
kibana4_end_timedelta:
  minutes: 10

# Alert Config
alert:
- "slack"

alert_text_type: exclude_fields
alert_text_args:
- kibana_link
```
