### ISSUE TITLE
Matches found on test but nothing on production

### ISSUE THREAD

**Issue by xbogdan** [Yelp/elastalert#668]
Hello, 

I can't make elastalert work. When I test my rule config I get matches but when it gets started 
properly it is not finding anything.

I'm using this docker: https://github.com/krizsan/elastalert-docker

Rule:
```
# Elasticsearch port
# es_port: 14900

# (OptionaL) Connect with SSL to elasticsearch
#use_ssl: True

# (Optional) basic-auth username and password for elasticsearch
#es_username: someusername
#es_password: somepassword

# (Required)
# Rule name, must be unique
name: DJANGO SUCCESS

# (Required)
# Type of alert.
# the frequency rule type alerts when num_events events occur with timeframe time
type: frequency

# (Required)
# Index to search, wildcard supported
index: logstash-django-*

# (Required, frequency specific)
# Alert when this many documents matching the query occur within a timeframe
num_events: 1

# (Required, frequency specific)
# num_events must occur within this amount of time to trigger an alert
timeframe:
    hours: 4

realert:
    minutes: 0

# (Required)
# A list of elasticsearch filters used for find events
# These filters are joined with AND and nested in a filtered query
# For more info: http://www.elasticsearch.org/guide/en/elasticsearch/reference/current/query-dsl.html
filter:
- query:
    query_string:
        query: "task_state: SUCCESS"

# (Required)
# The alert is use when a match is found
alert:
- "email"

email:
- "email@email.com"
smtp_host: "send.one.com"
smtp_port: 587
smtp_ssl: true
smtp_auth_file: "/opt/smtp_auth.yaml"
```

Config:
```
# This is the folder that contains the rule yaml files
# Any .yaml file will be loaded as a rule
rules_folder: /opt/rules

# How often ElastAlert will query elasticsearch
# The unit can be anything from weeks to seconds
run_every:
  minutes: 1

# ElastAlert will buffer results from the most recent
# period of time, in case some log sources are not in real time
buffer_time:
  minutes: 15

# The elasticsearch hostname for metadata writeback
# Note that every rule can have its own elasticsearch host
es_host: 172.17.0.4 #elasticsearch_host

# The elasticsearch port
es_port: 9200

# Optional URL prefix for elasticsearch
#es_url_prefix: elasticsearch

# Connect with SSL to elasticsearch
#use_ssl: True

# GET request with body is the default option for Elasticsearch.
# If it fails for some reason, you can pass 'GET', 'POST' or 'source'.
# See http://elasticsearch-py.readthedocs.io/en/master/connection.html?highlight=send_get_body_as#transport
# for details
#es_send_get_body_as: GET

# Option basic-auth username and password for elasticsearch
#es_username: someusername
#es_password: somepassword

# The index on es_host which is used for metadata storage
# This can be a unmapped index, but it is recommended that you run
# elastalert-create-index to set a mapping
writeback_index: elastalert_status

# If an alert fails for some reason, ElastAlert will retry
# sending the alert until this time period has elapsed
alert_time_limit:
  days: 2
```
Test Log:

```
Successfully loaded DJANGO SUCCESS

INFO:requests.packages.urllib3.connectionpool:Starting new HTTP connection (1): 172.17.0.4
Got 54114 hits from the last 1 day

Available terms in first hit:
	exception
	task_id
	tags
	@version
	@timestamp
	level
	stack_info
	task_retval
	host
	logger_name
	task_name
	path
	message
	task_state
	type
	port

INFO:elastalert:Note: In debug mode, alerts will be logged to console but NOT actually sent. To send them, use --verbose.
INFO:requests.packages.urllib3.connectionpool:Starting new HTTP connection (1): 172.17.0.4
INFO:elastalert:Queried rule DJANGO SUCCESS from 2016-08-08 10:35 UTC to 2016-08-08 10:50 UTC: 546 / 546 hits
INFO:elastalert:Queried rule DJANGO SUCCESS from 2016-08-08 10:50 UTC to 2016-08-08 11:05 UTC: 1210 / 664 hits
.......
INFO:elastalert:Alert for DJANGO SUCCESS at 2016-08-08T10:35:25.547Z:
INFO:elastalert:DJANGO SUCCESS

@timestamp: 2016-08-08T10:38:37.375Z
@version: 1
_id: AVZqCdCArJELOfvTUtam
_index: logstash-django-2016.08.08
_type: %{[@metadata][type]}
exception: None
host: localhost
level: WARNING
logger_name: shorthosters.tasks
message: None
path: /var/www/lb/app/utils.py
port: 46212
stack_info: None
tags: []
task_id: 31c468c3-0e8e-4f9a-b29d-331ba175a7fc
task_name: shorthosters.tasks.ExtractUrlTask
task_retval: None
task_state: SUCCESS
type: django

INFO:elastalert:Alert for DJANGO SUCCESS at 2016-08-08T10:38:54.090Z:
INFO:elastalert:DJANGO SUCCESS

....

INFO:elastalert:Ignoring match for silenced rule DJANGO SUCCESS

Would have written the following documents to elastalert_status:

silence - {'rule_name': 'DJANGO SUCCESS', '@timestamp': datetime.datetime(2016, 8, 9, 10, 38, 36, 567278, tzinfo=tzutc()), 'exponent': 0, 'until': datetime.datetime(2016, 8, 9, 10, 39, 36, 567262, tzinfo=tzutc())}

elastalert_status - {'hits': 54092, 'matches': 54092, '@timestamp': datetime.datetime(2016, 8, 9, 10, 38, 42, 333260, tzinfo=tzutc()), 'rule_name': 'DJANGO SUCCESS', 'starttime': datetime.datetime(2016, 8, 8, 10, 38, 17, 511125, tzinfo=tzutc()), 'endtime': datetime.datetime(2016, 8, 9, 10, 38, 17, 511125, tzinfo=tzutc()), 'time_taken': 24.818827867507935}
```

Production log:
```
INFO:elastalert:Queried rule DJANGO SUCCESS from 2016-08-09 10:26 UTC to 2016-08-09 10:41 UTC: 0 / 0 hits
INFO:elastalert:Ran DJANGO SUCCESS from 2016-08-09 10:26 UTC to 2016-08-09 10:41 UTC: 0 query hits, 0 matches, 0 alerts sent
INFO:elastalert:Sleeping for 59 seconds
```
