### ISSUE TITLE
@channel alerts in slack

### ISSUE THREAD

**Issue by 326TimesBetter** [Yelp/elastalert#680]
This may be a question for slack, but can you send @channel alerts in elastalerts slack alerts?? I have tried including the lines "@channel", "@channel:", "@channel: " in my alerts but thus far they have only printed those lines as text, and do not trigger the slack @channel alerts that notify people in the channel.

Thank you!

**Comment by henb** [comment]
@326TimesBetter try using the **[alert_subject](https://elastalert.readthedocs.io/en/latest/ruletypes.html#alert-content)**.
For example
```yaml
alert_text_type: alert_text_only
alert_subject: "<!channel> DON'T WORRY"
type: new_term
index: logstash-*
query_key: message
fields:
 - "message"
terms_window_size:
  days: 30
filter:
- query:
    query_string:
      query: "severity:debug"
alert:
  - "slack"
```
