### ISSUE TITLE
 u'search_phase_execution_exception', u"Can't get text on a START_ARRAY 

### ISSUE THREAD

**Issue by stefansaye** [Yelp/elastalert#695]
hi ,

I have set a rule part of as below,it's will alert when id is 1.5.3 and user is bobo or user is guestBobo , 
but when run the rule ,got the error 

         u'search_phase_execution_exception', u"Can't get text on a START_ARRAY 
 it's looks like the array for wildcard , can't use array for wildcard ?

    filter:
     - and:
       - term:
            id: "1.5.3"
       - query:
           wildcard:
              user: ["*bo*","*guest*"]

**Comment by Qmando** [comment]
```
filter:
- term:
     id: "1.5.3"
- or:
    - query:
         wildcard:
           user: "*bo*"
    - query:
         wildcard:
           user: "*guest*"
```
