### ISSUE TITLE
 email  alert content parameters show '< VALUE > MISSING'?

### ISSUE THREAD

**Issue by Canon88** [Yelp/elastalert#697]
Hi, guy:
I met a problem, when I used the email alert, adjust the alarm template. But the email content parameters show `'< VALUE > MISSING'` is this why?
Example: my configuration:
```
name: elk-flatline-test
type: flatline
es_host: x.x.x.x
es_port: 9200
index: logstash-test_log-*
threshold: 3
timeframe: 
    minutes: 1
filter:
- query:
    query_string:
        query: "status:ERROR"
use_count_query: true
doc_type: logstash-test_log
alert:
- "email"
email:
- "my@email.com"
alert_subject: "Alert {0} at {1}"
alert_subject_args:
- status
- date
include: ['alert_text']
alert_text: 
    date is {0} 
    status is {1}
alert_text_args:
- date
- status
```

**Comment by Qmando** [comment]
remove ``include: ['alert_text']``, that is for including fields from elasticsearch data. You can't use that with ``use_count_query`` AND flatline alert gets trigger on the lack of events, so there is no field data.

The only fields you can use in alert_subject_args and alert_text_args are ``count`` and ``@timestamp``.

Are you trying to make an alert when there ARE error messages?

**Comment by Canon88** [comment]
Yeah, I want to try when flatline alarm,
Send mail to custom alert_text_args, alert_subject_args parameter error message.

**Comment by Qmando** [comment]
You know that flatline means when there are LESS than 3 events? That's what you want to do?

**Comment by Canon88** [comment]
I want to express meaning. I want to know. How can let ` alert_text_args, alert_subject_args ` work. At the moment, I received an email in ` < VALUE > MISSING `. I don't know what is going on. I hope you can help me, thank you.
I'm sorry, my English is not very good.

**Comment by Canon88** [comment]
```
type: flatline
threshold: 3
timeframe: 
    minutes: 1
filter:
- query:
    query_string:
        query: "status:ERROR"
```
For this configuration, when 1 minutes, ` status: ERROR ` less than 3. The alarm will occur. This is my understanding.

**Comment by Canon88** [comment]
@Qmando Thank you for your answer. I think I've found the problem, because ` use_count_query = true `, I disable ` use_count_query ` normal. Thank you again!

**Comment by bean5** [comment]
I ran into this as well. So the solution is to set use_count_query: false explicitly or to not set it at all?

**Comment by bean5** [comment]
@Canon88 feel free to close this when you feel it is complete.

**Comment by bean5** [comment]
Hmm, I specified 'use_count_query: false' and I still get `<MISSING VALUE>` coming through.

**Comment by Qmando** [comment]
If you use the default alert text with ``--debug``, the match dictionary will get dumped, so you will see exactly which fields you can use. It prints them out line by line as "Key: Value".

If you are using flatline alert, the alert can be generated on ZERO documents, which means no fields would be available.

**Comment by bean5** [comment]
So query_key grouping is done by ES? For some reason I though ElastAlert was caching the set of query_key values and using those to detect when flatline threshold is met _when query_key is set_. I was using the query_key as a value in alert_text_args.

**Comment by Qmando** [comment]
Ah! Elastalert does the grouping. This one is not very intuitive but that value can be accessed with "key" and not whatever query_key is set to. 

https://github.com/Yelp/elastalert/blob/master/elastalert/ruletypes.py#L476

Several people have run into this exact issue several times recently, so I'll add some code to use the actual field name.

**Comment by bean5** [comment]
That would be awesome.

You might want to consider being backwards compatible if you think many are using "key" instead of the actual key's name.

**Comment by cfbao** [comment]
Just to confirm, when using flatline rule with `query_key`, I should put the literal word "key" in `alert_text_args`? like this:

```yaml
query_key: Instance
alert_text: |
  Instance {0} flatlined
alert_text_args:
  - key
```

and it's still not possible to use the actual key name?
