### ISSUE TITLE
How to get "all" match alerts ?

### ISSUE THREAD

**Issue by stefansaye** [Yelp/elastalert#701]
hi all
I want to receive alert for each hit of query. I use rule with "any" type.  and set 

     relert:
        minutes: 0

but when I run elastalert ,it 2 matches, but only  1 alerts sent

            # python -m elastalert.elastalert --config ./config.yaml --rule ./rules/Test.yaml --verbose --es_debug_trace alert.log
        INFO:elastalert:Starting up
        INFO:elastalert:Queried rule Test rule from 2016-09-08 16:00 CST to 2016-09-08 16:04 CST: 2 hits
        INFO:elastalert:Ignoring match for silenced rule Test rule
        INFO:elastalert:Ran Test rule from 2016-09-08 16:00 CST to 2016-09-08 16:04 CST: 2 query hits, 2     matches, 1 alerts sent
      
        INFO:elastalert:Sleeping for 59 seconds
        INFO:elastalert:Queried rule Test rule from 2016-09-08 16:00 CST to 2016-09-08 16:09 CST: 8 hits
        INFO:elastalert:Ignoring match for silenced rule Test rule
        INFO:elastalert:Ignoring match for silenced rule Test rule
        INFO:elastalert:Ignoring match for silenced rule Test rule
        INFO:elastalert:Ignoring match for silenced rule Test rule
        INFO:elastalert:Ran Test rule from 2016-09-08 16:00 CST to 2016-09-08 16:09 CST: 8 query hits, 4 matches, 0 alerts sent

my test rule,

     name: Test rule
     type: any
     index: logstash-log-*
     relert:
        minutes: 0
     filter:
      - term:
           id: "1.3.6"
      - query:
           query_string:
             query: "user:*bobo*"
    alert:
      - command
      command: ["/bin/send_alert.sh", "--user", "%(user)s"]

How can I  receive all alert that each match hit of query ?

 What else could be wrong?

**Comment by Qmando** [comment]
reAlert not relert

**Comment by RanaBhagathChand** [comment]
@stefansaye , @Qmando 

Same problem here did you guys have a solution?

`ProcessController:  INFO:elastalert:Ran ssl_certification_expiry from 2020-08-31 11:37 UTC to 2020-08-31 11:38 UTC: 2 query hits (0 already seen), 2 matches, 1 alerts sent`

I have mentioned 

```
realert:
    minutes: 0
```
in the rule but still no use.

**Comment by Qmando** [comment]
Post your rule if you want help

**Comment by RanaBhagathChand** [comment]
@Qmando  Thanks for the reply 

restart of the elastalert server  solved the issue after adding the realert: minutes: 0 in the rule

Here is the working rule:

```
name: a subject with fewer marks
type: any
index: subjects

alert_subject: "An issue with index:{0} doc:{1}"
alert_subject_args:
- "_index"
- "_id"

alert_text: "You got less marks in {0} subject marks: {1} "
alert_text_args:
- "subject"
- "marks"

realert:
  minutes: 0

filter:
 - range:
      marks:
        lt: 35

alert:
- "email"

email:
 - "sendto@gmail.com"
```
