### ISSUE TITLE
Missing Value coming from frequency alert

### ISSUE THREAD

**Issue by bean5** [Yelp/elastalert#763]
I get messages with "Missing Value" a lot coming from frequency alerts. I am not sure if there is a bug, something is misconfigured, or I am using a unique rule name that was previously used by a different rule type. @Qmando I was hoping you would be able to spot what is wrong in the config file.

I have my rule configured to send a HipChat message, which looks like this when it is generated:
```
Failure: Registered too many events in the past ~1 hour for <MISSING VALUE>. See https://kibana/goto/4d3875ff3761fec17f7a8d6d1cc6805d?_g=%28refreshInterval%3A%28dis... or https://kibana/goto/99e14b9795d81248bb8d9733abab5838.

At least 5 events occurred between 2016-10-12 16:51 UTC and 2016-10-12 18:11 UTC

@timestamp: 2016-10-12T18:11:35.622505Z
kibana_link: https://kibana/goto/4d3875ff3761fec17f7a8d6d1cc6805d?_g=%28refreshInterval%3A%28dis...
```

That "Missing Value" thing doesn't makes sense. When the events occur, they definitely have a value that should appear there. Following is the rule:
```
name: restore-fails-per-host
type: frequency

index: srv:backup*
num_events: 5
timeframe:
    minutes: 80
run_every:
    minutes: 5
realert:
    minutes: 140

filter:
- query:
    query_string:
        query: "status:fail"

use_kibana4_dashboard: https://kibana/goto/4d3875ff3761fec17f7a8d6d1cc6805d
kibana_url: https://kibana/
generate_kibana_link: true

use_count_query: true
doc_type: "restore"
query_key: "host"
owner: "me"

alert:
- "hipchat"

# Obtained at https://hipchat/rooms/tokens/707
hipchat_auth_token: "insert_token_here"
hipchat_room_id: "707"
hipchat_msg_color: "red"
hipchat_domain: "hipchat"
hipchat_ignore_ssl_errors: false
hipchat_notify: true
hipchat_from: "restore"
# hipchat_proxy: By default Elastalert will not use a network proxy to send notifications to HipChat. Set this option using hostname:port if you need to use a proxy.
hipchat_message_format: text

alert_text: "Failure: Registered too many events in the past ~1 hour for {0}. See {1} or https://kibana/goto/99e14b9795d81248bb8d9733abab5838."
alert_text_args:
- host
- kibana_link
```
