### ISSUE TITLE
Request: Better example of how to use negation with query_string

### ISSUE THREAD

**Issue by rodriguezsergio** [Yelp/elastalert#779]
I've been trying to write a filter where I negate a large portion of the potential results AND match the remaining results by looking for a particular string, but I can't seem to get it to work unless I do this all within a query_string. This is fine for now, but I would like to use more complicated queries in the future and avoid using a 100 character plus long query for readability.

I did notice that none of the examples in the docs seem to combine the two, so is this just not supported at all?

The latest iteration of my attempt at getting this to work is this:

``` yaml
filter:
- and:
  - query:
      query_string:
        query: "fooBarBaz"
  - not:
    - term:
        someField: "badValue"
```

**Comment by Qmando** [comment]
That example is correct. You can change together as much boolean logic as you like. The examples are pretty bad right now and haven't been updated in forever, so I will gave that a look.

**Comment by rodriguezsergio** [comment]
I was saying the above did _NOT_ work.

**Comment by Qmando** [comment]
Hm, it should. 

The first and is superfluous, since all the top levels filters are joined together in a ``must: [ ... ]``.  It's equivalent to 
```
filter:
- query:
    query_string:
      query: "fooBarBaz"
- not:
  - term:
      someField: "badValue"
```

Was there an error? Or you just didn't get the results you expect? You must be careful with using term on analyzed fields.

**Comment by rodriguezsergio** [comment]
I keep getting null_pointer_exception when I do that. 

The rule that is returning these errors is the following:
```yaml
filter:
- query:
    query_string:
      query: "\"stringToSearchFor\""
- not:
  - term:
      integerField: 0
```

The working version that I have been using looks like this:
```yaml
filter:
- query:
    query_string:
      query: "\"stringToSearchFor\" AND NOT (integerField: 0)"
```

Here's the error output:

> INFO:requests.packages.urllib3.connectionpool:Starting new HTTP connection (1): $ESHOST
> WARNING:elasticsearch:GET http://$ESHOST:9200/IndexName/_search?ignore_unavailable=true&size=1 [status:500 request:0.026s]
> Error running your filter:
> TransportError(500, {u'failed_shards': [{u'node': u'gRitU6veThC5GDbWMT4p8A', u'index': u'IndexName', u'reason': {u'reason': None, u'type': u'null_pointer_exception'}, u'shard': 0}], u'root_cause': [{u'reason': None, u'type': u'null_pointer_exception'}], u'grouped': True, u'reason': u'all shards failed', u'phase': u'query', u'type': u'search_phase_execution_exception'}, {u'status': 500, u'error': {u'failed_shards': [{u'node': u'gRitU6veThC5GDbWMT4p8A', u'index': u'IndexName', u'reason': {u'reason': None, u'type': u'null_pointer_exception'}, u'shard': 0}], u'root_cause': [{u'reason': None, u'type': u'null_pointer_exception'}], u'grouped': True, u'reason': u'all shards failed', u'phase': u'query', u'type': u'search_phase_execution_exception'}})
> INFO:elastalert:Note: In debug mode, alerts will be logged to console but NOT actually sent. To send them, use --verbose.
> INFO:requests.packages.urllib3.connectionpool:Starting new HTTP connection (1): $ESHOST
> WARNING:elasticsearch:GET http://$ESHOST:9200/IndexName/FooBar/_search?search_type=count&ignore_unavailable=true [status:500 request:0.009s]
> ERROR:root:Error running query: TransportError(500, {u'failed_shards': [{u'node': u'3OCyXSQER1i22El4zMEsug', u'index': u'IndexName', u'reason': {u'reason': None, u'type': u'null_pointer_exception'}, u'shard': 0}], u'root_cause': [{u'reason': None, u'type': u'null_pointer_exception'}], u'grouped': True, u'reason': u'all shards failed', u'phase': u'query', u'type': u'search_phase_execution_exception'})
> 
> Would have written the following documents to writeback index (default is elastalert_status):
> 
> elastalert_error - {'message': "Error running query: TransportError(500, {u'failed_shards': [{u'node': u'3OCyXSQER1i22El4zMEsug', u'index': u'IndexName', u'reason': {u'reason': None, u'type': u'null_pointer_exception'}, u'shard': 0}], u'root_cause': [{u'reason': None, u'type': u'null_pointer_exception'}], u'grouped': True, u'reason': u'all shards failed', u'phase': u'query', u'type': u'search_phase_execution_exception'})", 'traceback': ['Traceback (most recent call last):', '  File "/home/sergio/yelp-elastalert/lib/python2.6/site-packages/elastalert-0.1.2-py2.6.egg/elastalert/elastalert.py", line 318, in get_hits_terms', "    res = self.current_es.search(index=index, doc_type=rule['doc_type'], body=query, search_type='count', ignore_unavailable=True)", '  File "/home/sergio/yelp-elastalert/lib/python2.6/site-packages/elasticsearch/client/utils.py", line 68, in _wrapped', '    return func(*args, params=params, **kwargs)', '  File "/home/sergio/yelp-elastalert/lib/python2.6/site-packages/elasticsearch/client/__init__.py", line 498, in search', '    params=params, body=body)', '  File "/home/sergio/yelp-elastalert/lib/python2.6/site-packages/elasticsearch/transport.py", line 301, in perform_request', '    status, headers, data = connection.perform_request(method, url, params, body, ignore=ignore, timeout=timeout)', '  File "/home/sergio/yelp-elastalert/lib/python2.6/site-packages/elasticsearch/connection/http_requests.py", line 72, in perform_request', '    self._raise_error(response.status_code, raw_data)', '  File "/home/sergio/yelp-elastalert/lib/python2.6/site-packages/elasticsearch/connection/base.py", line 102, in _raise_error', '    raise HTTP_EXCEPTIONS.get(status_code, TransportError)(status_code, error_message, additional_info)', "TransportError: TransportError(500, {u'failed_shards': [{u'node': u'3OCyXSQER1i22El4zMEsug', u'index': u'IndexName', u'reason': {u'reason': None, u'type': u'null_pointer_exception'}, u'shard': 0}], u'root_cause': [{u'reason': None, u'type': u'null_pointer_exception'}], u'grouped': True, u'reason': u'all shards failed', u'phase': u'query', u'type': u'search_phase_execution_exception'})"], 'data': {'rule': 'rule name'}}
>

**Comment by Qmando** [comment]
Oops, I made a mistake. Try this instead (remove - from term)

```yaml
filter:
- query:
    query_string:
      query: "\"stringToSearchFor\""
- not:
     term:
       integerField: 0
```

**Comment by amolkekan** [comment]
> Oops, I made a mistake and didn't catch this before. Try this instead (remove - from term)
> 
> ```yaml
> filter:
> - query:
>     query_string:
>       query: "\"stringToSearchFor\""
> - not:
>      term:
>        integerField: 0
> ```

how to use multiple comparision in single line

**Comment by Qmando** [comment]
```
filter:
 - query:
      query_string:
        query: "\"stringToSearchFor\" AND NOT integerField: 0"
```
