### ISSUE TITLE
Inline alert configurations 

### ISSUE THREAD

**Issue by Qmando** [Yelp/elastalert#78]
Instead of alerts reading their configuration from the top level of the configuration file, they should have inline configuration which would allow multiple alerts of the same type. For example:

```
alert:
- email:
    recipient: foo@bar.baz
- email:
    recipient: baz@foo.bar
```
