### ISSUE TITLE
Using script fields

### ISSUE THREAD

**Issue by AlmogBaku** [Yelp/elastalert#784]
Is it possible to use script fields with elastalert?

**Comment by mza97** [comment]
I tried too but failed, there is no docs :/

**Comment by fabMrc** [comment]
I works , foe example

You juste need to enable it on your ES configuration

```yaml
filter:
- term:
    name: mem.physical.free
- script:
    script:
      inline: doc['value'].value > 1

```
