### ISSUE TITLE
elasticsearch ignores set range(?)

### ISSUE THREAD

**Issue by Thermi** [Yelp/elastalert#791]
Hello,

I'm trying to use the following rule, but the filter returns also documents where the range is below the set minimum. I also tried `from` and `to` in the `range` filter, but to no avail.

```
name: CPU usage for master node ip-10-0-0-50.eu-west-1.compute.internal
type: frequency
index: heapster-cpu-*
timestamp_field: CpuMetricsTimestamp
num_events: 1
timeframe:
    minutes: 15

filter:
- and:
   - term:
       "MetricsTags.type" : "node"
   - term:
       "MetricsTags.hostname.raw": "ip-10-0-0-50.eu-west-1.compute.internal"
   - range:
       "Metrics.cpu/node_utilization.value":
         gte: 0.800
         lte: 1.000
```

[es_trace.txt](https://github.com/Yelp/elastalert/files/567382/es_trace.txt)
