### ISSUE TITLE
[_na] query malformed, no field after start_object  for  or query in filter ?

### ISSUE THREAD

**Issue by stefansaye** [Yelp/elastalert#804]
hi all,
I want to set  a rule when match (user:admin and query_string : exe  ) or (user:"boss") then alert 
I have try to set as below,

     filter:
      - or:
        - bool:
            must:
               term: "user:admin "
               query:
                   query_string:
                   query: "saction:exe"
        - term:
           user: "boss"

but get the error as below

    ERROR:root:Error running query: TransportError(400, u'search_phase_execution_exception', u'[term] query does not support different field names, use [bool] query instead')

**Comment by Qmando** [comment]
Why did you add bool must? That's already built in.
```
filter:
- or:
    - term:
         user: boss
    - and:
         - term:
              user: admin
         - query:
              query_string:
                query: "saction: exe"
```
