### ISSUE TITLE
options in query string not supported

### ISSUE THREAD

**Issue by treasurer** [Yelp/elastalert#811]
I am getting this error while adding options field in query string in rule file.
"Error running query: TransportError(400, 'search_phase_execution_exception', '[query_string] query does not support [options]'

Can anyone help me

**Comment by Qmando** [comment]
Could you post your query? Or link to the documentation for ``options``? The normal format I've used is something like
```
filter:
- query:
     query_string:
        query: "foo: bar AND _exists_: baz"
```
