### ISSUE TITLE
alert from the past

### ISSUE THREAD

**Issue by s0rc3r3r01** [Yelp/elastalert#817]
Hello,  I have a script that starts Elastalert at 8 o' clock UTC.
python -m elastalert.elastalert --verbose

This is the  rule : 
```

type: flatline

index: logstash-*

threshold: 1

timeframe:
  minutes: 10

filter:
- term:
    channel: "XXXXX"
- query:
    query_string:
      query: "*"


```
When started at 8.00 I've received an alert with the contents : 

> 
> An abnormally low number of events occurred around 2016-11-19 05:29 UTC.
> Between 2016-11-19 05:19 UTC and 2016-11-19 05:29 UTC, there were less than 1 events.
> 

Any idea why Elastalert is alerting about an event hours in the past and out of scope ?

Thanks
