### ISSUE TITLE
0 match with Flatline

### ISSUE THREAD

**Issue by mza97** [Yelp/elastalert#832]
```
type: flatline
threshold: 3000
use_count_query: true
doc_type: 'msg'
timeframe:
  minutes: 5
query_delay:
  minutes: 1
filter:
- query:
    query_string:
      query: 'type: bsm'
```
and conf:

```
run_every:
  minutes: 5
buffer_time:
  minutes: 5
old_query_limit:
   seconds: 5
```
 I got:
INFO:elastalert:Found expired previous run for bobAlert at 2016-11-29 15:23:13.112199+00:00
INFO:elastalert:Queried rule bobAlert from 2016-11-29 15:18 UTC to 2016-11-29 15:23 UTC: 2240 / 2240 hits
INFO:elastalert:Ran bobAlert from 2016-11-29 15:18 UTC to 2016-11-29 15:23 UTC: 2240 query hits, 0 matches, 0 alerts sent

**Comment by mza97** [comment]
Okey thank you for your help, since I don't need to download my documents I can use "use_count_query" and buffer_time is ignored (by default 45min ?).
I can't set 'run_every" at 10sec I have to request every 5min and look if there are no logs during 5min.
I have a last question, I want to apply this rule on two types of docs, I should use "use_count_query" + "query_key" or "use_terms_query" + "query_key"?

**Comment by Qmando** [comment]
Use ``doc_type: type1,type2``. You cannot use query_key + use_count_query together.

**Comment by mza97** [comment]
No, sorry it was not very clear, my keys have the same _type but I need to count for each value of a field called "msg_type" and see witch one is equal to zero. I will try "use_terms_query".

**Comment by mza97** [comment]
Hi, 
I create two flatline rules which have the same options (so request the same index) but not the same query.
This morning I should have receive alerts from the two rules but I received only from one, the other one doesn't the match event if it was 0 hits.

**Comment by Qmando** [comment]
Can you post the rule yaml and show the logs where it got 0 hits?

**Comment by mza97** [comment]
```
Bob alert which didn't alert:
name: bobAlert
type: flatline
threshold: 1
timeframe:
  minutes: 5
use_terms_query: true
doc_type: 'bob_msg'
query_key: msg_type
query_delay:
  minutes: 1
realert:
   minutes: 0
filter:
- query:
    query_string:
      query: 'msg_type: BSM AND msg_type: BPM'
```

```
Bob2 alert which alert:
name: bob2Alert
type: flatline
threshold: 1
timeframe:
  minutes: 5
use_terms_query: true
doc_type: 'bob_msg'
query_key: logsource
query_delay:
  minutes: 1
realert:
   minutes: 0
filter:
- query:
    query_string:
      query: 'logsource: bob01 OR logsource: bob02'
```

in Kibana:

elastalert_status	bobAlert	        0      0	2016-12-05T09:28:46.889268Z
elastalert_status	bob2Alert	0	4	2016-12-05T09:28:48.026677Z

**Comment by Qmando** [comment]
Ah! I think I see what the issue is. You are using ``use_terms_query: true`` with ``query_key``. Using flatline with that means "Alert for any term that falls below the threshold", but if there are never ANY hits, we don't know of any terms to alert on.

From http://elastalert.readthedocs.io/en/latest/ruletypes.html, under the flatline section, ``query_key: With flatline rule, query_key means that an alert will be triggered if any value of query_key has been seen at least once and then falls below the threshold.`` The key phrase there being "seen at least once".

**Comment by mza97** [comment]
Ah ok, thank you! Since the result of the request is passed to the rule, for 0 hits we can't create a new type rule and have to modify the code to alert for 0 hits  ?

**Comment by mza97** [comment]
I created a rule type based on add_terms_data in the frequency rule, but I don't understand how the timeframe works, my rule depends on the run_every. Can you explain me where in the code we check every timeframe the number of docs?
With add_terms_data we only add one data (dict: bucket[key], count) per request to the windows so the duration is always 00:00 per key ?

**Comment by Qmando** [comment]
``With add_terms_data we only add one data (dict: bucket[key], count) per request to the windows so the duration is always 00:00 per key ?`` 

No... The format of data is {timestamp: {term: count, term2:count}}. These terms are added into EventWindows, which are automatically resized based on the timeframe. Any events in the EventWindow that are ``timeframe`` older than the most recent event will be dropped.

``run_every`` determines the granularity of the data added. Imagine  following scenario:

```
run_every: 
  minutes: 3
timeframe:
  minutes: 10
```
Data added:
```
{'12:00': {'foo': 2}}
{'12:03': {'foo': 3}}
{'12:06': {'foo': 5}}
{'12:09': {'foo': 1}}
```
The current count is 11, and there is 9 minutes of data currently stored. If we add one more data point
```
{'12:12': {'foo': '1}}
```
The data from '12:00' will be evicted because it's more than 10 minutes away from 12:12. The count will now be 10.

The count is checked against ``num_every`` after every piece of data is added.

**Comment by Qmando** [comment]
In your code, you are limiting the valid keys to ["bsm", "bpm"] which you could just do by adding a filter to the query. You are also adding 0 count events, which can never increase the running count, so why add them at all? You will only ever need to check the count AFTER adding a non-zero data point.

**Comment by Qmando** [comment]
I added several comments but deleted them because I realize what you are trying to do. You are probably running into this check https://github.com/Yelp/elastalert/blob/master/elastalert/ruletypes.py#L475. You could try deleting that line and your code would probably work.

**Comment by Qmando** [comment]
I think you could achieve that with this change as well
```
qlo@dev33-devc:~/elastalert (master) $ git diff
diff --git a/elastalert/ruletypes.py b/elastalert/ruletypes.py
index f53d2f4..35ccac3 100644
--- a/elastalert/ruletypes.py
+++ b/elastalert/ruletypes.py
@@ -503,7 +503,7 @@ class FlatlineRule(FrequencyRule):
     def garbage_collect(self, ts):
         # We add an event with a count of zero to the EventWindow for each key. This will cause the EventWindow
         # to remove events that occurred more than one `timeframe` ago, and call onRemoved on them.
-        default = ['all'] if 'query_key' not in self.rules else []
+        default = ['all'] if 'query_key' not in self.rules else self.rules['buckets']
         for key in self.occurrences.keys() or default:
             self.occurrences.setdefault(key, EventWindow(self.rules['timeframe'], getTimestamp=self.get_ts)).append(({self.ts_field: ts}, 0))
             self.first_event.setdefault(key, ts)
```

**Comment by mza97** [comment]
Thank you for you help, it's working but not for the timeframe, I think I don't well understand the timeframe. If I want to look every 2min (timeframe) in 5min of request (run_every) if there are no docs, I can't do this with use_terms_query since it's just counting the whole 5min.
I think I should not use `use_terms_query` but create buckets per timeframe and key and counting.

**Comment by mza97** [comment]
In a rule.yaml: `except_data_null: true`

in elastalert.py run_query:
``` 
        # There was an exception while querying
        if data is None and rule.get('except_data_null'):
            rule_inst.add_data(data)
        elif data is None:
            return False
``` 

Is this can provoke problemes ?

**Comment by Qmando** [comment]
Yes, that will cause problems.

**Comment by mza97** [comment]
Ok, thank you for your answer :)

**Comment by PMDubuc** [comment]
I'm trying to do something similar with flatline, but I'm not having much luck.  I have multiple doc_types which represent log message types.  Each message type can be sent from one or more hosts.  So I want to know if any [_type, host] combination has not been seen within the timeframe.  Can I do it with a single rule like this one, or do I need a separate rule for each specific logtype and host?  What am I missing?

```
name: "4 Minute Heartbeat"
type: flatline

index: logstash-%Y.%m.%d
use_strftime_index: true

doc_type: logtype1,logtype2,logtype3

alert_text: "Absence of {0} events detected for time period"
alert_text_args: ["doc_type"]

threshold: 1

timeframe:
    minutes: 4

query_key: [_type, host]

use_terms_query: true
term_size: 500

alert:
- email

email:
- me@host.com
```

**Comment by Qmando** [comment]
I'm not actually sure what the behavior is with multiple doc_types with ``use_terms_query``. You can achieve this, although slower, by removing use_terms_query, doc_type, and using a filter instead

```
filter:
- terms:
     _type: ["logtype1", "logtype2"]
```

**Comment by PMDubuc** [comment]
Thanks!  That seems to work well.  It seems like, once it sends an alert, the number of messages needs to go back above the threshold again, then drop below it for another alert to be sent.  Is that true?

Thanks again.

**Comment by mza97** [comment]
I change my code of the type rule:
[thresholdZ.txt](https://github.com/Yelp/elastalert/files/764189/thresholdZ.txt)

```
threshold: 1
buckets: ["bsm", "bpm"]
query_delay:
  minutes: 10
realert:
   minutes: 1

```



I still request every 5min with ``` use term query ```
But Sometimes I get false alerts telling me that there are no events for some fields
I figured out that sometimes elastalert requests 2 times for the same rule

```
Threshold: 1
// result of request
{u'key': u'bsm', u'doc_count': 2270}
{u'key': u'bpm', u'doc_count': 2240}

// Buckets that do not match the condition to alert: 
key non Alert: bsm count: 2270 
key non Alert: bpm count: 2240
ts: 2017-02-09T15:15:57.192250Z  ||  2017-02-09T15:20:57.192250Z

key Alert:  // List of buckets which are empty or count is bellow the threshold 
Threshold: 1

// SECOND REQUEST
// result of request
{u'key': u'bpm', u'doc_count': 36}
{u'key': u'bsm', u'doc_count': 8}

// Buckets that do not match the condition to alert: 
key non Alert: bpm count: 36
key non Alert: bsm count: 8

**ts: 2017-02-09T15:15:59.918696Z  ||  2017-02-09T15:20:59.918696Z**
key Alert:  // List of buckets which are empty or count is bellow the threshold 
```
