### ISSUE TITLE
Aggregation re-alert time is fixated on a past time

### ISSUE THREAD

**Issue by j4nu5** [Yelp/elastalert#836]
I have a multi-tenant system on which I want alerting. I do not want to create individual rules for individual tenants (identified by the field `app` in my logs). I wrote the following rule:

```
name: APP_ERROR_NOTIFICATIONS
type: any
index: logs-*
timestamp_field: timestamp

query_key: app
filter:
  - query:
      query_string:
        query: "level:ERROR"

aggregation:
  schedule: '*/5 * * * *'
realert:
  minutes: 0
aggregation_key: app

alert_text: "{0} is producing errors"

alert_text_args: ["app"]

alert_text_type: alert_text_only

alert:
- email

email: ["myemail@mydomain"]
```

Running this rule alerts after the first 5 minutes of startup but never again. Here is a sample log from ElastAlert:

```
INFO:elastalert:Adding alert for APP_ERROR_NOTIFICATIONS to aggregation(id: AVjYoGbd2Sp-VHc21gBW, aggregation_key: proteus), next alert at 2016-12-07 09:35:00+00:00
```

I had run ElastAlert before 09:30 UTC and I got some alert emails immediately. I kept it running for 1/2 hour at least but from the logs, it seems it is fixated on the alert time 09:35.

This happens after a restart of ElastAlert too. It gets fixated on the next multiple of 5 time and never sends any alert after that time has passed.
