### ISSUE TITLE
Querying multiple indices

### ISSUE THREAD

**Issue by AviralSri** [Yelp/elastalert#843]
I am using elasticsearch, topbeat and packetbeat.
I need to query topbeat-* and packetbeat-* in the same rule file.
How the filters will be separated by index??
OR
The filters will be queried against both indexes??

**Comment by Qmando** [comment]
Just comma separate them

index: topbeat*,packetbeat*

**Comment by AviralSri** [comment]
Hi,

I already tried with as you replied.
My rule file is as follows:-
es_port: 9200
index: topbeat-*,packetbeat-*
smtp_host: ismtp.corp.company.com
es_host: xx.xx.xx.xx
realert:
  minutes: 5
alert: email
timeframe:
  minutes: 30
type: frequency
from_addr: abc@email.com
num_events: 1
email: ["kpr@email.com"]
name: multiple_indices
filter:
 - range:
    fs.used_p:
      from: 0.50
      to: 1
 - term:
    beat.hostname: server1
 - term:
    http.code: 200
 - term:
    beat.hostname: server2
My question is how the elastalert will know fs.used_p and beat.hostname: server1 will be queries against topbeat-* AND http.code:200 and beat.hostname: server2 will be queries against packetbeat-*

**Comment by Qmando** [comment]
How about
```
filter:
 - or:
    - and:
      - range:
          fs.used_p:
            from: 0.50
             to: 1
      - term:
           beat.hostname: server1
    - and 
      - term:
           http.code: 200
      - term:
           beat.hostname: server2
```
