### ISSUE TITLE
ERROR when using query_string

### ISSUE THREAD

**Issue by levylll** [Yelp/elastalert#858]
When I use query like this in my rule yaml
```
filter:
- query:
    query_string:
      query: "host:127.0.0.1 AND status:500"
``` 

I get the response
`TransportError(400, u'parsing_exception', u'no [query] registered for [query]')"]`
When I use term, everything is OK.
But I still want to know how to use query_string.
Thank you very much.

**Comment by Qmando** [comment]
Instead of
```
filter:
 - query:
      query_string:
        query: "blah blah"
```
use 
```
filter:
 - query_string:
      query: "blah blah"
```
