### ISSUE TITLE
@timestamp is UTC-0 how do i change it?

### ISSUE THREAD

**Issue by AnderssonPeter** [Yelp/elastalert#861]
I currently live in sweden and we have UTC +1 as timezone and when i browse events in kibana they show up correct.

But the email sent from elastalert its still in UTC-0 is there anyway to force it to show up as UTC +1?

```
@timestamp: 2017-01-11T14:15:00.003Z
@version: 1
Exception: {}
Thread: {}
_id: AVmN4qp564hcKyDm5kTG
_index: logs-kajsa-2017.01.11
_type: anteo
...
received_at: 2017-01-11T14:15:07.279Z
received_from: kajsa
tags: [
    "beats_input_codec_plain_applied"
]
thread: {
    "id": 21, 
}
type: anteo
```
Kibana:
```
  @timestamp	   	January 11th 2017, 15:15:00.003
t @version	   	1
t _id	   	AVmN4qp564hcKyDm5kTG
t _index	   	logs-kajsa-2017.01.11
...
  received_at	   	January 11th 2017, 15:15:07.279
t received_from	   	kajsa
t tags	   	beats_input_codec_plain_applied
# thread.id	   	21
t thread.name	   	Autogiro_Worker-1
t type	   	anteo
```

Iv been thinking the whole time there is one hour delay from that we receiver the events until i get a alert but after looking at the id i figured its just a timezone error.

**Comment by AnderssonPeter** [comment]
To solve this issue i tried to write a `enhancement` module.
so my directory structure is
```
/etc/elastalert
 * rules
   * rule1.yaml
 * elastalert_modules
   * __init__.py (emtpy file)
   * time_enhancement.py
 * config.yaml
```
config.yaml
```
rules_folder: /etc/elastalert/rules
run_every:
  minutes: 5

buffer_time:
  minutes: 6

es_host: localhost
es_port: 9200
writeback_index: elastalert_status
alert_time_limit:
  days: 2

smtp_host: "smtp.somewhere.com"
from_addr: "someone@somewhere.com"
email:
- "someone@somewhere.com"

notify_email:
- "someone@somewhere.com"
```

modules\time_enhancement.py
```
from datetime import datetime, timedelta
from elastalert.enhancements import BaseEnhancement


class TimeEnhancement(BaseEnhancement):
    hoursToAdd = 1

    def process(self, match):
        offset = timedelta(hours=self.hoursToAdd)
        for attribute in dir(match):
            # skip system attributes
            if not attribute.startswith('__'):
                value = getattr(match, attribute)
                # skip callable attributes and attributes that arent datetimes
                if not callable(value) and type(value) is datetime:
                    # add offset to datetime
                    setattr(match, attribute, value + offset)

```

rules\rule1.yaml
```
...snip...
match_enhancements:
- "elastalert_modules.time_enhancement.TimeEnhancement"
```

The rule seems to be running but the dates aren't modified what am i missing? (i have never written python code before so i might be doing things totally wrong!!!)
