### ISSUE TITLE
ES5 ignore certain time range?

### ISSUE THREAD

**Issue by AnderssonPeter** [Yelp/elastalert#868]
The ES5 branch does not support the yaml query format instead you are forced to use the query_string if you want more then one filter.

Now i have the following:
```
# Alert when page_life_expectancy is under 1000
name: page_life_expectancy_under_1000
type: any
index: logs-*
doc_type: sql_server_statistics
filter:
- query_string:
    query: "received_from: production AND page_life_expectancy: [* TO 999]"

alert:
- "email"

alert_subject_args:
- issue.name
- "@timestamp"

email:
- "someone@somewhere.com"
```

Now i would like to ignore this if it happens between `14:30 - 14:45` or `02:30 - 02:45` as we are running backups then and they always cause a drop in `page_life_expectancy`.

Now if i could use the yaml syntax i could have written some thing like:
```
filter:
- and:
  - range:
    page_life_expectancy:
      from: 0
      to: 999
  - not:
    - or:
      - range:
        timestamp:
          format: "HH:mm:ss"
          from: "02:30"
          to: "02:45"
      - range:
        timestamp:
          format: "HH:mm:ss"
          from: "14:30"
          to: "14:45"
```

How do i express this in the query_string format?

Edit: or do i misunderstand the `format` part is it only there to help the query parser to parse a string?
