### ISSUE TITLE
alert on elastAlert status

### ISSUE THREAD

**Issue by mza97** [Yelp/elastalert#873]
Hi,
I need to alert in the elastAlert index for each rule name when a elastAlert_status has matches > 0,
I use frequency and use_term_query but I don't get the excepted result.
Here's my conf:

```
es_host: localhost
es_port: 9200
name: elastAlertTest2
index: elastalert_status
buffer_time:
   hours 6
type: frequency
num_events: 1
query_key: ["rule_name"]
use_terms_query: true
doc_type: elastalert_status
timeframe:
   hours: 6
realert:
   minutes: 0
filter:
- range:
    matches:
      from: 1
alert:
- "email"
...
```
