### ISSUE TITLE
How to have alert when the count exceed the threshold that match a query?

### ISSUE THREAD

**Issue by stefansaye** [Yelp/elastalert#888]
I need to write an ElastAlert rule that aggregates the values of events. 
The thresholds are 5 matching conditions within 2 minutes when match a filter (user is bob and message contain "login fail" and event_type  is login)

Example document:

    {
        type: "log",
        user: "bob",
        event_type :"login",
        message:"login fail and blablablablablablablabla"
        timestamp : "2016-09-20T00:05:00"
    }
    {
        type: "log",
        user: "amy",
        event_type :"something",
        message:"send mail blablablablablablablabla"
        timestamp : "2016-09-21T00:05:00"
    }

Example rule in english:

     alert : The sum of all documents when user= 'bob' and message contain "fail" and event_type  is login over the past 2 minutes exceeds 4

I'm new to elastalert so was wondering if there are examples for such rules anywhere.

**Comment by Qmando** [comment]
Here's an example https://github.com/Yelp/elastalert/blob/master/example_rules/example_frequency.yaml
```
type: frequency
num_events: 5
timeframe:
  minutes: 2
filter:
- query:
     query_string:
       query: "message: \"login fail\" AND event_type: login"
```
