### ISSUE TITLE
Two requests for the same rule

### ISSUE THREAD

**Issue by mza97** [Yelp/elastalert#895]
Hi,
For some rules, ElastAlert requests two times Elasticsearch, the second request trigger some times false alerts.
It's not depending on the type of rule because it's doing this with a simple `any`.

The first request:
```
curl -XGET 'http://localhost:9200/bob/bob/_search?pretty&search_type=count&ignore_unavailable=true' -d '{
  "aggs": {
    "filtered": {
      "aggs": {
        "counts": {
          "terms": {
            "field": "msg_type",
            "size": 50
          }
        }
      },
      "filter": {
        "bool": {
          "must": [
            {
              "range": {
                "@timestamp": {
                  "gt": "2017-02-10T16:05:05.333615Z",
                  "lte": "2017-02-10T16:10:05.333615Z"
                }
              }
            },
...
}'
```
The second request:

```
curl -XGET 'http://localhost:9200/bob/bob/_search?pretty&search_type=count&ignore_unavailable=true' -d '{
  "aggs": {
    "filtered": {
      "aggs": {
        "counts": {
          "terms": {
            "field": "msg_type",
            "size": 50
          }
        }
      },
      "filter": {
        "bool": {
          "must": [
            {
              "range": {
                "@timestamp": {
                  "gt": "2017-02-10T16:10:05.333615Z",
                  "lte": "2017-02-10T16:10:05.785115Z"
                }
              }
            },
...
}'
```

Here my principal config:
```
run_every:
  minutes: 5
buffer_time:
  minutes: 15
old_query_limit:
  seconds: 30
```
If someone can help me.

**Comment by Qmando** [comment]
You have ``use_terms_query: true`` in your rule, correct?

If that is set, ``buffer_time`` is ignored, and instead, each query will ``run_every`` sized. 

You didn't post the command you used to run this. Nor did you post what you expected to happen. It won't trigger a false alert unless Elasticsearch returns hits. I don't understand what the issue here is.

**Comment by mza97** [comment]
Ah ok sorry for the lack of informations.
I know that buffer_time is ignored but it's mandatory to put it in the ElastAlert config.

My probleme is that sometimes I get two requests in a row, and the second causes false alerts.

I use a script that I found here to make a service:
```
case $1 in
   start)
      echo -n $"Starting $NAME: "
      cd $ELASTALERT_DIR
      daemon --user="$ELASTALERT_USER" --pidfile="$PIDFILE" "$ELASTALERT --config $CONFIG_FILE --es_debug_trace ESBobLog.log &"
      RETVAL=$?
      pid=`ps -ef | grep python | grep elastalert | awk '{print $2}'`
      if [ -n "$pid" ]; then
        echo $pid > "$PIDFILE"
      fi
   ;;
```

my ElastAlert config:
```
rules_folder: rules
run_every:
  minutes: 5
buffer_time:
  minutes: 15
old_query_limit:
  seconds: 30
es_host: *****
es_port: *****
writeback_index: ********
alert_time_limit:
  days: 2
```
An exemple of rule that get two requests in a row
```
index: index
name: osirisAlert
buffer_time:
  minutes: 5
type: frequency
num_events: 1
timeframe:
  minutes: 1
aggregation:
  schedule: '0 0 * * * * '
```

Other Rule that get double requests in a row 
[thresholdZ.txt](https://github.com/Yelp/elastalert/files/782676/thresholdZ.txt)

```
index: index2
name: bobAlert
type: "elastalert_modules.thresholdZ.TresholdBucketZ"
threshold: 1
use_terms_query: true
use_count_query: false
doc_type: 'bob_msg'
query_key: msg_type
buckets: ["bsm", "bpm"]
query_delay:
  minutes: 10
realert:
   minutes: 1
filter:
- query:
    query_string:
      query: 'msg_type: BSM OR msg_type: BPM'
```

For the bobAlert rule:

```
The first request time's range:
"gt": "2017-02-10T16:05:05.333615Z",
"lte": "2017-02-10T16:10:05.333615Z"

The Second request time's range:
"gt": "2017-02-10T**16:10:05.333615Z**",
"lte": "2017-02-10T**16:10:05.785115Z**"
```

For BobAlert since I want to alert when there are no logs, I don't want the second request
