### ISSUE TITLE
apparently random alerts with flatline rule

### ISSUE THREAD

**Issue by s0rc3r3r01** [Yelp/elastalert#967]
Hello, I have a job that creates a log event every hour and I want to check that this even has been  created ( aka the count is not zero in that timeframe). I've used a flatline rule and it work well for hours, but randomly I get an alert that reports 0 events even if I can the events in Kibana.
I've also noticed that the Slack alert for this is quite peculiar
```
An abnormally low number of events occurred around 2017-03-25 22:43 UTC.
Between 2017-03-25 19:43 UTC and 2017-03-25 22:43 UTC, there were less than 1 events.

@timestamp: 2017-03-25XXX
count: 0
key: all
num_hits: 0
num_matches: 2
```
How come it has count 0 and num_matches 2 ? In fact in that timeframe there are two events of this type in Elasticsearch and the alert should not have been fired.

This is the rule :
```
type: flatline
index: XXXXX-*
threshold: 1
timeframe:
  hours: 3

use_count_query: true
doc_type: app
filter:
- query:
    query_string:
      query: "\"DDDDD\" AND \"BBBBBB\""
```
```
run_every:
  minutes: 5

buffer_time:
  minutes: 15
```

Any idea what is going on ?
