### ISSUE TITLE
verbose mode start time always the same 

### ISSUE THREAD

**Issue by tkumark** [Yelp/elastalert#988]
Hi
Just getting started on elastalert. Below is my rules yaml file
```
name: frequencytest
type: frequency
index: logstash-*

num_events: 60

timeframe:
  minutes: 1
filter:
- query:
    query_string:
      query: "response: \"200\""

alert:
- "email"

email:
- "myemail@gmail.com"
```

I used python -m elastalert.elastalert --verbose --rule ./myrules/myrule_frequency.yaml
the verbose mode gave the the following output
Each time elastalert runs it star with 2017-04-05 14:14 UTC. even though I have kept timeframe as 1min. Is it considering all events from the time I stared elastalert?
2017-04-05 14:14 UTC to 2017-04-05 14:15 UTC
2017-04-05 14:14 UTC to 2017-04-05 14:16 UTC
2017-04-05 14:14 UTC to 2017-04-05 14:17 UTC
2017-04-05 14:14 UTC to 2017-04-05 14:18 UTC

what does 995 / 53 hits mean 

> INFO:elastalert:Queried rule frequencytest from 2017-04-05 14:14 UTC to 2017-04-05 14:15 UTC: 995 / 53 hits
INFO:elastalert:Queried rule frequencytest from 2017-04-05 14:14 UTC to 2017-04-05 14:16 UTC: 125 / 125 hits
