### ISSUE TITLE
How to send alert with frequency rule?

### ISSUE THREAD

**Issue by ZillaG** [Yelp/elastalert#999]
How do I set up the filter on a frequency rule to look for "PooledConnection init failure" in the "msgbody" field of my logstash-* index. I have this filter, but I'm getting a LOT of hits (in the hundreds), though I only see a few error logs with this text. How can I improve my filter?

```
doc_type: error-log
filter:
- query:
     query_string:
       query: "msgbody: PooledConnection init failure"

```

**Comment by Qmando** [comment]
You need to add quotation marks
```
filter:
- query:
     query_string:
       query: "msgbody: \"PooledConnection init failure\""
```
